Repository root-project/root, pull requests merged in 2018-11, with the labels that each got.

#2893 v6 14 Fix runtime_modules compilation failure
  core/metacling/src/TCling.cxx
Labels: backport, bugfix

#2931 [DF] Optimise runtime of RSlotStack by removing useless duplicated map lookup
  tree/dataframe/src/RSlotStack.cxx
Labels: performance optimisation

#2939 Fix RooArgSets for windows.
  roofit/roofitcore/src/MemPoolForRooSets.h
Labels: ready to merge

#2936 [RooFit] Fix race condition when running tutorial tests.
  tutorials/CMakeLists.txt
Labels: ready to merge

#2942 Work around to silent a compiler error on Windows
  core/imt/inc/ROOT/TThreadExecutor.hxx
Labels: do not merge

#2886 [DOC] Update release notes for RDF+TTreeProcessorMT
  README/ReleaseNotes/v616/index.md
Labels: docs

#2941 [RooFit] [ROOT-9571] Fix range check for RooArgSet arenas
  roofit/roofitcore/inc/RooArgSet.h
  roofit/roofitcore/inc/RooDataSet.h
  roofit/roofitcore/src/MemPoolForRooSets.h
Labels: ready to merge

#2950 [ROOT-9665] Fix processing in RooCmdArg
  roofit/roofitcore/src/RooCmdConfig.cxx
Labels: bugfix, ready to merge

#2945 jsroot: several fixes from dev
  etc/http/scripts/JSRootCore.js
  etc/http/scripts/JSRootPainter.js
  etc/http/scripts/JSRootPainter.v6.js
  etc/http/scripts/JSRootPainter.v7.js
Labels: ready to merge

#2919 [DF] Set axes titles of histos and graphs obtained w/o models
  tree/dataframe/inc/ROOT/RDF/RInterface.hxx
  tree/dataframe/test/dataframe_simple.cxx
Labels: new feature

#2943 [RooFit] [ROOT-9571] Replace RooArgSet and RooDataSet mempools with single templated mempool.
  roofit/roofitcore/inc/RooArgSet.h
  roofit/roofitcore/inc/RooDataSet.h
  roofit/roofitcore/src/MemPoolForRooSets.h
  roofit/roofitcore/src/RooArgSet.cxx
  roofit/roofitcore/src/RooDataSet.cxx
  roofit/roofitcore/src/RooSentinel.cxx
Labels: backport, bugfix, do not merge

#2964 jsroot: for ROOT 6.16
  etc/http/changes.md
  etc/http/scripts/JSRootCore.js
  etc/http/scripts/JSRootPainter.hist.js
  etc/http/scripts/JSRootPainter.hist3d.js
  etc/http/scripts/JSRootPainter.openui5.js
  etc/http/scripts/JSRootPainter.v6.js
  etc/http/scripts/JSRootPainter.v7.js
Labels: bugfix

#2965 jsroot: for ROOT 6.16
  etc/http/changes.md
  etc/http/scripts/JSRootCore.js
  etc/http/scripts/JSRootPainter.hist.js
  etc/http/scripts/JSRootPainter.hist3d.js
  etc/http/scripts/JSRootPainter.openui5.js
  etc/http/scripts/JSRootPainter.v6.js
  etc/http/scripts/JSRootPainter.v7.js
Labels: bugfix

#2974 [DF][NFC] Mention conversion to RNode in user guide
  tree/dataframe/src/RDataFrame.cxx
Labels: docs

#2966 [CMake][ROOT-9739] Upgrade VDT built-in version from 0.4.1 to 0.4.2
  cmake/modules/SearchInstalledSoftware.cmake
Labels: bugfix

#2979 [Dictgen] ROOT-9635 ROOT-9615: filter out unwanted rootcling args.
  core/dictgen/src/rootcling_impl.cxx
Labels: backport

#2988 Revert "[TTreeProcMT] Fix COV-98763: large variable passed by value"
  tree/treeplayer/inc/ROOT/TTreeProcessorMT.hxx
Labels: bugfix

#2990 [CMake][ROOT-9637] Adopt c++14 flag in root-config
  cmake/modules/RootConfiguration.cmake
  config/root-config.in
Labels: bugfix

#3001 [DF] Use LoadTree(0), not GetEntry(0), to reset TChain state
  tree/dataframe/src/RLoopManager.cxx
Labels: performance optimisation

#3015 Fix TTreeCache issue related to learning from ROOT-9773.
  io/io/inc/TFileCacheRead.h
  tree/tree/inc/TTreeCache.h
  tree/tree/src/TBranch.cxx
  tree/tree/src/TTreeCache.cxx
Labels: backport

#3014 Fix TTreeCache issue related to learning from ROOT-9773.
  io/io/inc/TFileCacheRead.h
  tree/tree/inc/TTreeCache.h
  tree/tree/src/TBranch.cxx
  tree/tree/src/TTreeCache.cxx
Labels: backport

#3023 [DF] Let SaveGraph return a string rather than print to stdout
  tree/dataframe/inc/ROOT/RDFHelpers.hxx
  tree/dataframe/test/dataframe_helpers.cxx
Labels: backport

#3033 [TCling][ROOT-9660] Do not fwd declare on library load enums Cling kows already
  core/metacling/src/TCling.cxx
Labels: Work in progress do not merge

#3002 Support systems with no `manpath` nor `man` in thisroot.sh
  config/thisroot.sh
Labels: bugfix

#3057 [Geo][ROOT-9837] Avoid name clashes
  geom/geocad/inc/TGeoToOCC.h
  geom/geocad/inc/TOCCToStep.h
  geom/geocad/src/TGeoToOCC.cxx
  geom/geocad/src/TGeoToStep.cxx
Labels: bugfix
