Repository root-project/root, pull requests merged in 2018-07, with the labels that each got.

#2279 [DOCS] Update RDF release notes
  README/ReleaseNotes/v616/index.md
Labels: docs

#2283 [DOCS] Add me and Massimo to contributor list
  README/ReleaseNotes/v616/index.md
Labels: docs

#2291 updated doxygen list
  tree/dataframe/inc/ROOT/RDataSource.hxx
Labels: docs

#2201 [cxxmodules] Evaluate code with interpreter in pretty print
  bindings/pyroot/src/Pythonize.cxx
  core/meta/inc/TInterpreterValue.h
  core/metacling/src/TClingValue.cxx
  core/metacling/src/TClingValue.h
Labels: bugfix

#2304 [DF] Fix warnings relative to PassAsVecHelper
  tree/dataframe/inc/ROOT/RDFHelpers.hxx
Labels: bugfix

#2299 [DF] Add tutorial on RDF helpers
  tutorials/dataframe/df020_helpers.C
Labels: docs

#2303 [DF] Fix RResultPtr copy-assignment, move-ctor
  tree/dataframe/inc/ROOT/RResultPtr.hxx
  tree/dataframe/test/dataframe_resptr.cxx
Labels: bugfix

#2312 [DF] Fix resultptr
  tree/dataframe/inc/ROOT/RResultPtr.hxx
  tree/dataframe/test/dataframe_resptr.cxx
Labels: backport, bugfix

#2311 Fix Wsign-compare warning in master
  core/metacling/src/TClingValue.cxx
Labels: bugfix

#2368 [DF][Doc] Graph action documented
  tree/dataframe/src/RDataFrame.cxx
Labels: docs

#2355 [DF] Improved snapshot doc
  tree/dataframe/src/RDataFrame.cxx
Labels: docs

#2390 [DF][NFC] Fix some misspelled doxygen data member docs
  tree/dataframe/inc/ROOT/RDFNodes.hxx
  tree/dataframe/inc/ROOT/RSnapshotOptions.hxx
Labels: docs
