Repository root-project/root, pull requests merged in 2018-06, with the labels that each got.

#2127 [cxxmodules] Don't generate rootmap files with cxxmodules
  core/dictgen/src/rootcling_impl.cxx
Labels: ready to merge

#2140 [DOC] Minor fixes to RVec docs
  math/vecops/inc/ROOT/RVec.hxx
Labels: docs

#2135 [cxxmodules] Fix failing fedora build (ROOT-9445)
  core/metacling/src/TCling.cxx
Labels: bugfix

#2145 [DF] Use human readable type names in error message
  tree/dataframe/inc/ROOT/RDFNodes.hxx
Labels: backport

#2149 [DF] No need for shared_from_this anymore
  tree/dataframe/inc/ROOT/RDFInterface.hxx
  tree/dataframe/inc/ROOT/RDFNodes.hxx
Labels: bugfix

#2159 [TREEPROCMT] Do not build test if not an imt build
  tree/treeplayer/test/CMakeLists.txt
Labels: bugfix

#2158 Fix RDF interpreted snapshot, ROOT-9236
  tree/dataframe/inc/ROOT/RDFInterface.hxx
Labels: bugfix

#2160 Revert "Add the cwg to the prebuilt module cache path."
  interpreter/cling/lib/Interpreter/CIFactory.cpp
Labels: bugfix, urgent

#2152 [TREE] Only trigger parallel GetEntry if number of branches > 1
  tree/tree/src/TTree.cxx
Labels: bugfix, needs review

#2151 [DF] No need for shared_from_this anymore
  tree/dataframe/inc/ROOT/RDFInterface.hxx
  tree/dataframe/inc/ROOT/RDFNodes.hxx
Labels: backport, bugfix

#2163 Fix RDF interpreted snapshot, ROOT-9236
  tree/dataframe/inc/ROOT/RDFInterface.hxx
Labels: backport, bugfix

#2164 [TREE] Only trigger parallel GetEntry if number of branches > 1
  tree/tree/src/TTree.cxx
Labels: backport, bugfix

#2168 [TREEPROCMT] Do not rebuild chain if the processed file is the same
  tree/treeplayer/inc/ROOT/TTreeProcessorMT.hxx
Labels: bugfix

#2169 [TREEPROCMT] Avoid useless construction of thread-local chains
  tree/treeplayer/inc/ROOT/TTreeProcessorMT.hxx
Labels: backport, bugfix

#2174 [TREEPROCMT] Explicitly initialize fFriendInfo in ctors
  tree/treeplayer/src/TTreeProcessorMT.cxx
Labels: bugfix

#2177 [DF] Use different filenames in python and C tutorials
  tutorials/dataframe/df003_profiles.py
  tutorials/dataframe/df008_createDataSetFromScratch.py
  tutorials/dataframe/df017_vecOpsHEP.py
Labels: bugfix

#2178 [DF] Fix df017_vecOpsHEP.root
  tutorials/dataframe/df017_vecOpsHEP.py
Labels: bugfix

#2113 [VecOps] Do not invoke vdt functions if vdt is disabled
  tutorials/vecops/vo002_VectorCalculations.C
Labels: bugfix

#2167 Fix TROOT::LoadClass for C++runtime modules
  core/base/src/TROOT.cxx
Labels: bugfix

#2187 Revert "[cxxmodules] Don't generate rootmap files with cxxmodules"
  core/dictgen/src/rootcling_impl.cxx
Labels: trying multiplatform tests

#2199 [DOC] Uniform doxygen doc for TTree::Write overloads
  tree/tree/src/TTree.cxx
Labels: docs

#2131 [cxxmodules] Implement Bloom Filter
  core/metacling/src/TCling.cxx
Labels: needs review

#2203 [cxxmodules] Fix bloom filter without .gnu.hash
  core/metacling/src/TCling.cxx
Labels: bugfix, urgent

#2137 [cxxmodules] Respect LD_LIBRARY_PATH order and save memory
  core/metacling/src/TCling.cxx
Labels: needs review

#2204 [cxxmodules] Support both sysv and gnu hash for bloom filter
  cmake/modules/SetUpLinux.cmake
Labels: bugfix

#2227 [DF] Fix ROOT-9456, "[Jenkins][DF] Sporadic failures in test_snapshotNFiles"
  tree/dataframe/inc/ROOT/RDFActionHelpers.hxx
Labels: bugfix

#2228 [DF] Use stacks rather than single output files in Snapshot MT
  tree/dataframe/inc/ROOT/RDFActionHelpers.hxx
Labels: backport, bugfix

#2234 [DF] Avoid TChain::AddClone in Snapshot when unnecessary
  tree/dataframe/inc/ROOT/RDFActionHelpers.hxx
Labels: bugfix

#2242 [DF] Avoid TChain::AddClone in Snapshot when unnecessary
  tree/dataframe/inc/ROOT/RDFActionHelpers.hxx
Labels: backport, bugfix

#2258 [DF] Remove obsolete part from error message
  tree/dataframe/inc/ROOT/RDFNodes.hxx
Labels: backport
