Repository root-project/root, pull requests merged in 2018-10, with the labels that each got.

#2743 [DF] Help windows with namespaces
  tree/dataframe/src/RCustomColumnBase.cxx
  tree/dataframe/src/RJittedAction.cxx
  tree/dataframe/src/RRangeBase.cxx
Labels: bugfix

#2744 [DF][NFC] Improve doc, use aliases for return types
  tree/dataframe/inc/ROOT/RDF/RInterface.hxx
Labels: docs

#2758 [DOCS] Fix typo
  tree/treeplayer/src/TBranchProxy.cxx
Labels: docs

#2768 [TreePlayer] Remove leftover debug output
  tree/treeplayer/src/TTreeReaderValue.cxx
Labels: bugfix

#2620 [VecOps] Add Nonzero and Intersect helpers
  math/vecops/inc/ROOT/RVec.hxx
  math/vecops/test/vecops_rvec.cxx
  tutorials/vecops/vo006_IndexManipulation.C
Labels: needs review

#2625 [VecOps] Add Where helper
  math/vecops/inc/ROOT/RVec.hxx
  math/vecops/test/vecops_rvec.cxx
  tutorials/vecops/vo003_LogicalOperations.C
Labels: needs review

#2871 webgui: correctly check if browser executable was found
  gui/webdisplay/inc/ROOT/RWebDisplayHandle.hxx
  gui/webdisplay/src/RWebDisplayHandle.cxx
Labels: bugfix
