Repository root-project/root, pull requests merged in 2018-12, with the labels that each got.

#3076 [RF] Improve doxygen for several RooFit classes.
  documentation/doxygen/images/RF_Landau.png
  roofit/roofit/src/RooLandau.cxx
  roofit/roofitcore/inc/RooAbsReal.h
  roofit/roofitcore/inc/RooMCStudy.h
  roofit/roofitcore/src/RooAbsPdf.cxx
  roofit/roofitcore/src/RooAbsReal.cxx
  roofit/roofitcore/src/RooAbsRealLValue.cxx
  roofit/roofitcore/src/RooAddPdf.cxx
  roofit/roofitcore/src/RooAddition.cxx
  roofit/roofitcore/src/RooArgSet.cxx
  roofit/roofitcore/src/RooExtendPdf.cxx
  roofit/roofitcore/src/RooFitResult.cxx
  roofit/roofitcore/src/RooMCStudy.cxx
  roofit/roofitcore/src/RooRealIntegral.cxx
  roofit/roostats/inc/RooStats/HypoTestInverterPlot.h
  roofit/roostats/src/HypoTestInverterPlot.cxx
Labels: docs

#3098 [DF] Fix compilation error on mac1012, XCode9
  tree/dataframe/src/RDataFrame.cxx
Labels: bugfix

#3112 [Tutorials] Modernise FITSIO tutorials
  tutorials/fitsio/FITS_tutorial1.C
  tutorials/fitsio/FITS_tutorial2.C
  tutorials/fitsio/FITS_tutorial3.C
  tutorials/fitsio/FITS_tutorial4.C
  tutorials/fitsio/FITS_tutorial5.C
  tutorials/fitsio/FITS_tutorial6.C
  tutorials/fitsio/FITS_tutorial7.C
Labels: docs

#3153 [DF][ROOT-9865][ROOT-9860] Handle snapshot of C arrays drastically changing ther size
  tree/dataframe/inc/ROOT/RDF/ActionHelpers.hxx
  tree/dataframe/test/dataframe_snapshot.cxx
Labels: bugfix

#3162 eve7: fix in GL view update
  etc/eve7/GL.controller.js
Labels: backport, bugfix

#3159 eve7: fix in GL view update
  etc/eve7/GL.controller.js
Labels: bugfix

#3166 [DF][ROOT-9860][ROOT-9865] Fix
  tree/dataframe/inc/ROOT/RDF/ActionHelpers.hxx
  tree/dataframe/test/dataframe_snapshot.cxx
Labels: backport, bugfix

#3164 [RF][ROOT-9826] Fix generation of Asimov data.
  roofit/roostats/src/AsymptoticCalculator.cxx
Labels: backport

#3165 [RF][ROOT-9826] Fix generation of Asimov data.
  roofit/roostats/src/AsymptoticCalculator.cxx
Labels: backport, bugfix

#3173 [TTreeCacheUnzip] [ROOT-9870] Uncompress the cache in parallel only if ImplicitMT is enabled
  tree/tree/src/TTreeCacheUnzip.cxx
Labels: bugfix

#3188 [ROOT-9876] Fix crash introduced by the lazy array interface if cppyy…
  bindings/pyroot/src/Pythonize.cxx
Labels: bugfix

#3186 [ROOT-9872] Enable nested namespace when loading enum fwdDecls
  core/metacling/src/TCling.cxx
Labels: bugfix

#3189 [DF] Use spin mutex in RSlotStack instead of rw-spin lock
  tree/dataframe/inc/ROOT/RDF/RSlotStack.hxx
  tree/dataframe/src/RSlotStack.cxx
Labels: performance optimisation

#3185 [RF] Improve RooFit documentation.
  documentation/doxygen/images/RooArgusBG.png
  roofit/histfactory/doc/index.md
  roofit/histfactory/src/Measurement.cxx
  roofit/roofit/doc/index.md
  roofit/roofit/src/RooArgusBG.cxx
  roofit/roofit/src/RooBernstein.cxx
  roofit/roofit/src/RooBukinPdf.cxx
  roofit/roofitcore/src/RooAbsPdf.cxx
  roofit/roofitcore/src/RooArgList.cxx
  roofit/roofitcore/src/RooCustomizer.cxx
  roofit/roofitcore/src/RooDataSet.cxx
  roofit/roofitcore/src/RooPolyVar.cxx
  roofit/roostats/doc/index.md
  roofit/roostats/inc/RooStats/AsymptoticCalculator.h
  roofit/roostats/src/AsymptoticCalculator.cxx
  tutorials/histfactory/index.md
  tutorials/roofit/index.md
Labels: docs

#3187 Fix ROOT-7487, make TObject::Clone always proceed. Backport v616
  core/base/src/TObject.cxx
Labels: backport

#3206 [VecOps] Allow to emplace_back on RVec<bool> on all platforms
  math/vecops/inc/ROOT/RVec.hxx
  math/vecops/test/vecops_rvec.cxx
Labels: bugfix
