Repository root-project/root, pull requests merged in 2018-04, with the labels that each got.

#1823 [Core] Backport std::integer_sequence & co. from libstdc++
  cmake/modules/RootConfiguration.cmake
  config/RConfigure.in
  core/foundation/inc/ROOT/RIntegerSequence.hxx
Labels: ready to merge

#1827 [VecOps] Refactor code and move to core/foundation and math/vecops
  core/foundation/test/CMakeLists.txt
  math/CMakeLists.txt
  math/vecops/CMakeLists.txt
  math/vecops/inc/LinkDef.h
  math/vecops/inc/ROOT/TAdoptAllocator.hxx
  math/vecops/inc/ROOT/TVec.hxx
  math/vecops/src/TVec.cxx
  math/vecops/test/CMakeLists.txt
  math/vecops/test/vecops_tadoptallocator.cxx
  math/vecops/test/vecops_tvec.cxx
  tree/treeplayer/inc/LinkDef.h
  tree/treeplayer/test/CMakeLists.txt
Labels: needs review

#1903 [TDF] Do not keep dot-less branch name if it was part of a longer one
  tree/treeplayer/src/TDFInterfaceUtils.cxx
Labels: bugfix

#1938 [TDF] Avoid accessing zero-length TTreeReaderArray
  tree/treeplayer/inc/ROOT/TDFNodes.hxx
Labels: bugfix

#1936 [Math] Avoid std::string in signature of template class method
  math/mathcore/inc/Math/MixMaxEngine.h
  math/mathcore/inc/Math/MixMaxEngine.icc
  math/mathcore/inc/TRandomGen.h
Labels: bugfix
