Repository root-project/root, pull requests merged in 2018-08, with the labels that each got.

#2362 Fix memory leak in TTreeReaderArray
  tree/treeplayer/inc/TTreeReaderArray.h
  tree/treeplayer/src/TTreeReaderArray.cxx
Labels: bugfix

#2393 [DF] Add GetColumnType utility to RInterface
  tree/dataframe/inc/ROOT/RDFInterface.hxx
  tree/dataframe/test/dataframe_interface.cxx
Labels: new feature

#2400 Add TGraph2D::GetPoint
  hist/hist/inc/TGraph2D.h
  hist/hist/src/TGraph2D.cxx
Labels: needs review, new feature

#2413 Extended return value of operator* to TGeoHMatrix. Added Multiply tak…
  geom/geom/inc/TGeoMatrix.h
  geom/geom/src/TGeoMatrix.cxx
  geom/geom/test/TestMatrix.C
Labels: backport

#2414 Extended return value of operator* to TGeoHMatrix. Added Multiply tak…
  geom/geom/inc/TGeoMatrix.h
  geom/geom/src/TGeoMatrix.cxx
  geom/geom/test/TestMatrix.C
Labels: backport

#2415 Extended return value of operator* to TGeoHMatrix. Added Multiply tak…
  geom/geom/inc/TGeoMatrix.h
  geom/geom/src/TGeoMatrix.cxx
  geom/geom/test/TestMatrix.C
Labels: backport

#2361 Fix memory leak in GetStreamInfoListImpl
  io/io/src/TFile.cxx
Labels: bugfix

#2416 Fix dataframe_snapshot test on Windows
  tree/dataframe/test/dataframe_snapshot.cxx
Labels: bugfix

#2419 [DOC] Comment on windows' behavior for TSystem::Unlink
  core/base/src/TSystem.cxx
  core/winnt/src/TWinNTSystem.cxx
Labels: docs

#2394 [DF] [ROOT-9457] Introduced GetFilterNames
  tree/dataframe/inc/ROOT/RDFInterface.hxx
  tree/dataframe/inc/ROOT/RDFInterfaceUtils.hxx
  tree/dataframe/inc/ROOT/RDFNodes.hxx
  tree/dataframe/src/RDFInterfaceUtils.cxx
  tree/dataframe/src/RDFNodes.cxx
  tree/dataframe/test/dataframe_interface.cxx
Labels: new feature

#2450 [DF] Store RJittedAction on the heap to avoid use after delete
  tree/dataframe/inc/ROOT/RDFInterface.hxx
  tree/dataframe/inc/ROOT/RDFInterfaceUtils.hxx
  tree/dataframe/inc/ROOT/RResultPtr.hxx
  tree/dataframe/src/RDFInterfaceUtils.cxx
Labels: bugfix

#2456 Consistency for copy constructors and assignment.
  geom/geom/inc/TGeoMatrix.h
  geom/geom/src/TGeoMatrix.cxx
  geom/geom/test/TestMatrix.C
Labels: backport

#2458 Consistency for copy constructors and assignment.
  geom/geom/inc/TGeoMatrix.h
  geom/geom/src/TGeoMatrix.cxx
  geom/geom/test/TestMatrix.C
Labels: backport

#2457 Consistency for copy constructors and assignment.
  geom/geom/inc/TGeoMatrix.h
  geom/geom/src/TGeoMatrix.cxx
  geom/geom/test/TestMatrix.C
Labels: backport

#2477 [VecOps] Add helpers to compute combinations of collections
  math/vecops/inc/ROOT/RVec.hxx
  math/vecops/test/vecops_rvec.cxx
  tutorials/vecops/vo005_Combinations.C
  tutorials/vecops/vo005_Combinations.py
Labels: do not merge, needs review

#2515 [DF] Fixed ambiguous calls to Cache and Display
  tree/dataframe/inc/ROOT/RDFInterface.hxx
  tree/dataframe/test/dataframe_cache.cxx
  tree/dataframe/test/dataframe_simple.cxx
Labels: bugfix

#2128 Use IsLibraryLoaded when you already know that file is a library
  core/base/src/TSystem.cxx
  core/meta/inc/TInterpreter.h
  core/metacling/src/TCling.cxx
  core/metacling/src/TCling.h
Labels: needs review

#2524 [DF][Doc] Updated the release notes
  README/ReleaseNotes/v616/index.md
Labels: docs

#2537 [DF][NFC] Improve Cache documentation
  tree/dataframe/inc/ROOT/RDFInterface.hxx
Labels: docs

#2550 [DF] More docs
  tree/dataframe/src/RDataFrame.cxx
Labels: docs

#2552 [DF] Fix jitted RResultPtr lifetimes
  tree/dataframe/inc/ROOT/RDFInterface.hxx
Labels: bugfix

#2569 [DF] Fix clang9 warnings
  tree/dataframe/test/RStreamingDS.hxx
Labels: bugfix
