Repository root-project/root, pull requests merged in 2019-05, with the labels that each got.

#3777 [Graphics][ROOT-7647] Properly delete the return of `colormap_asimage`
  graf2d/asimage/src/TASImage.cxx
Labels: bugfix

#3786 Fix for ROOT-9993
  geom/geom/src/TGeoCache.cxx
Labels: bugfix

#3775 RooChebychev: scalable implementation
  roofit/roofit/inc/RooChebychev.h
  roofit/roofit/src/RooChebychev.cxx
Labels: ready to merge

#3791 Fix fot ROOT-9938.
  geom/geom/src/TGeoPgon.cxx
Labels: bugfix

#3776 RooAbsAnaConvPdf: allow different time acceptance for different categories
  roofit/roofitcore/src/RooAbsAnaConvPdf.cxx
Labels: ready to merge

#3802 [tcling] In some cases the path to the dyLibName can be relative.
  core/metacling/src/TCling.cxx
Labels: bugfix

#3808 [cling] Do not copy the FrontendOpts, we want to modify the object.
  interpreter/cling/lib/Interpreter/CIFactory.cpp
Labels: bugfix

#3812 [forest] Convert to string stringview w/o using the to_string method
  tree/forest/v7/inc/ROOT/RField.hxx
  tree/forest/v7/inc/ROOT/RForestView.hxx
  tree/forest/v7/src/RField.cxx
  tree/forest/v7/src/RForest.cxx
  tree/forest/v7/src/RForestDescriptor.cxx
  tree/forest/v7/src/RPageStorageRoot.cxx
Labels: bugfix

#3813 [tcling] Use the right interface to make a path absolute.
  core/metacling/src/TCling.cxx
Labels: bugfix

#3824 [Doc][ROOT-10124] Close code example for ROOT::VecOps::Construct
  math/vecops/inc/ROOT/RVec.hxx
Labels: bugfix

#3836 [TTree][NFC] Refurbish a bit the documentation of TTree
  tree/tree/src/TTree.cxx
Labels: docs

#3845 [RVec] Revert SBO implementation for now
  math/vecops/inc/ROOT/RAdoptAllocator.hxx
  math/vecops/inc/ROOT/RVec.hxx
  tree/dataframe/inc/ROOT/RDF/ActionHelpers.hxx
Labels: performance optimisation
