Repository root-project/root, pull requests merged in 2019-06, with the labels that each got.

#3639 [RF] Reduce global statics
  roofit/roofitcore/inc/RooExpensiveObjectCache.h
  roofit/roofitcore/inc/RooMsgService.h
  roofit/roofitcore/inc/RooNameReg.h
  roofit/roofitcore/inc/RooNumGenConfig.h
  roofit/roofitcore/inc/RooNumGenFactory.h
  roofit/roofitcore/inc/RooNumIntConfig.h
  roofit/roofitcore/inc/RooNumIntFactory.h
  roofit/roofitcore/inc/RooRealConstant.h
  roofit/roofitcore/inc/RooResolutionModel.h
  roofit/roofitcore/src/RooExpensiveObjectCache.cxx
  roofit/roofitcore/src/RooMsgService.cxx
  roofit/roofitcore/src/RooNameReg.cxx
  roofit/roofitcore/src/RooNumGenConfig.cxx
  roofit/roofitcore/src/RooNumGenFactory.cxx
  roofit/roofitcore/src/RooNumIntConfig.cxx
  roofit/roofitcore/src/RooNumIntFactory.cxx
  roofit/roofitcore/src/RooRealConstant.cxx
  roofit/roofitcore/src/RooResolutionModel.cxx
  roofit/roofitcore/src/RooSentinel.cxx
Labels: ready to merge, squash on merge

#3859 [RF] Trigger collection of histograms in HistFactory.
  roofit/histfactory/src/HistoToWorkspaceFactoryFast.cxx
Labels: bugfix

#3899 [RF] Trigger collection of histograms in HistFactory.
  roofit/histfactory/src/HistoToWorkspaceFactoryFast.cxx
Labels: backport, bugfix

#3908 [RF] Disable forceful component selection in RooRealIntegral.
  roofit/roofitcore/inc/RooAbsReal.h
  roofit/roofitcore/src/RooRealIntegral.cxx
Labels: bugfix

#3941 [RF] Improve documentation for projecting Data.
  roofit/roofitcore/src/RooAbsData.cxx
  roofit/roofitcore/src/RooHist.cxx
Labels: docs

#3934 [Doc] More concise TClass class documentation
  core/meta/src/TClass.cxx
Labels: docs

#3948 [RF] Disable forceful component selection in RooRealIntegral.
  roofit/roofitcore/inc/RooAbsReal.h
  roofit/roofitcore/src/RooRealIntegral.cxx
Labels: backport, bugfix

#3993 [PyROOT] Move some tutorials to legacy category
  tutorials/legacy/pyroot/fildir.py
  tutorials/legacy/pyroot/file.py
  tutorials/legacy/pyroot/first.py
  tutorials/legacy/pyroot/framework.py
  tutorials/legacy/pyroot/test.py
  tutorials/legacy/pyroot/tree.py
Labels: docs

#4009 [RF][Docs] Documentation updates / fixes collected througout june.
  math/minuit2/inc/Minuit2/Minuit2Minimizer.h
  roofit/roofit/doc/index.md
  roofit/roofit/src/RooChi2MCSModule.cxx
  roofit/roofitcore/doc/index.md
  roofit/roofitcore/inc/RooConstVar.h
  roofit/roofitcore/inc/RooCustomizer.h
  roofit/roofitcore/inc/RooGlobalFunc.h
  roofit/roofitcore/inc/RooRealConstant.h
  roofit/roofitcore/src/RooAbsReal.cxx
  roofit/roofitcore/src/RooCustomizer.cxx
  roofit/roofitcore/src/RooDataHist.cxx
  roofit/roofitcore/src/RooMCStudy.cxx
  roofit/roofitcore/src/RooMsgService.cxx
  roofit/roofitcore/src/RooSTLRefCountList.cxx
  roofit/roofitcore/src/RooSimPdfBuilder.cxx
  roofit/roofitcore/src/RooSimWSTool.cxx
  roofit/roostats/doc/index.md
  roofit/roostats/inc/RooStats/HypoTestInverter.h
  roofit/roostats/inc/RooStats/ModelConfig.h
  roofit/roostats/src/HypoTestInverter.cxx
  roofit/roostats/src/ModelConfig.cxx
  roofit/roostats/src/SPlot.cxx
  roofit/roostats/src/ToyMCSampler.cxx
  tutorials/roofit/rf514_RooCustomizer.C
Labels: docs
