Repository root-project/root, pull requests merged in 2019-08, with the labels that each got.

#4145 [Math] Fix crash in TFoam when sampling a flat function.
  math/foam/src/TFoam.cxx
Labels: bugfix

#4153 [VecOps] Avoid allocating temporaries on heap in InvariantMass[es]
  math/vecops/inc/ROOT/RVec.hxx
Labels: performance optimisation

#4197 [PyROOT][ROOT-10268] Enable pickling of arrays returned by AsNumpy
  bindings/pyroot/_rdf_utils.py
  bindings/pyroot/test/rdataframe_asnumpy.py
  bindings/pyroot_experimental/PyROOT/python/ROOT/pythonization/_rdf_utils.py
  bindings/pyroot_experimental/PyROOT/test/rdataframe_asnumpy.py
Labels: bugfix, needs review

#4218 [RF] Fix stressRooStats failure on 32 bit.
  roofit/roofitcore/src/RooDataSet.cxx
Labels: backport

#4221 [RDF] Do not let Snapshot'ed TTrees spawn nested TBB tasks (v6.18)
  tree/dataframe/inc/ROOT/RDF/ActionHelpers.hxx
Labels: backport

#4213 [cling] Fix SIGSEGV after executing the `.stats decl' metacommand (ROOT-9934)
  interpreter/cling/lib/Interpreter/Interpreter.cpp
Labels: bugfix

#4244 [Cling] Improve help message for .x, allow macros with main.
  interpreter/cling/lib/MetaProcessor/MetaSema.cpp
Labels: squash on merge

#4308 [RF] Fix a crash in RooDataHist::sum().
  roofit/roofitcore/src/RooDataHist.cxx
Labels: bugfix
