Repository root-project/root, pull requests merged in 2019-02, with the labels that each got.

#3244 [RF] Remove fixed-length char buffers from RooWorkspace
  roofit/roofitcore/CMakeLists.txt
  roofit/roofitcore/inc/RooHelpers.h
  roofit/roofitcore/src/RooHelpers.cxx
  roofit/roofitcore/src/RooWorkspace.cxx
  roofit/roofitcore/test/testWorkspace.cxx
Labels: bugfix

#3261 [RF] Fix spurious binning warning in RooDataHist
  roofit/roofitcore/inc/RooDataHist.h
  roofit/roofitcore/inc/RooHelpers.h
  roofit/roofitcore/src/RooDataHist.cxx
  roofit/roofitcore/src/RooHelpers.cxx
  roofit/roofitcore/test/CMakeLists.txt
  roofit/roofitcore/test/testRooDataHist.cxx
Labels: bugfix

#3364 [DF][ROOT-9933] Add GetNSlots method to RInterface
  tree/dataframe/inc/ROOT/RDF/RInterface.hxx
  tree/dataframe/test/dataframe_interface.cxx
Labels: new feature

#3326 [RF][ROOT-9518][ROOT-5333] Fix analytical integral of RooPoisson
  roofit/roofit/src/RooPoisson.cxx
  roofit/roofit/test/CMakeLists.txt
  roofit/roofit/test/testRooPoisson.cxx
  test/stressRooStats_ref.root
Labels: bugfix

#3366 [TBufferMerger] Initialize TBufferFile with the right size in Write
  io/io/src/TBufferMergerFile.cxx
Labels: needs testing

#3345 [RF][ROOT-9816] Improve RooAbsCollection
  README/ReleaseNotes/v618/index.md
  roofit/roofitcore/CMakeLists.txt
  roofit/roofitcore/inc/LinkDef1.h
  roofit/roofitcore/inc/LinkDef2.h
  roofit/roofitcore/inc/RooAbsAnaConvPdf.h
  roofit/roofitcore/inc/RooAbsCollection.h
  roofit/roofitcore/inc/RooAddGenContext.h
  roofit/roofitcore/inc/RooAddPdf.h
  roofit/roofitcore/inc/RooArgList.h
  roofit/roofitcore/inc/RooArgSet.h
  roofit/roofitcore/inc/RooConstVar.h
  roofit/roofitcore/inc/RooLinkedList.h
  roofit/roofitcore/inc/RooLinkedListElem.h
  roofit/roofitcore/inc/RooLinkedListIter.h
  roofit/roofitcore/inc/RooNameReg.h
  roofit/roofitcore/inc/RooProdPdf.h
  roofit/roofitcore/inc/RooRealConstant.h
  roofit/roofitcore/src/RooAbsAnaConvPdf.cxx
  roofit/roofitcore/src/RooAbsArg.cxx
  roofit/roofitcore/src/RooAbsCollection.cxx
  roofit/roofitcore/src/RooAbsOptTestStatistic.cxx
  roofit/roofitcore/src/RooAddGenContext.cxx
  roofit/roofitcore/src/RooAddPdf.cxx
  roofit/roofitcore/src/RooArgList.cxx
  roofit/roofitcore/src/RooArgSet.cxx
  roofit/roofitcore/src/RooLinkedList.cxx
  roofit/roofitcore/src/RooLinkedListIter.cxx
  roofit/roofitcore/src/RooNameReg.cxx
  roofit/roofitcore/src/RooProdPdf.cxx
  roofit/roofitcore/src/RooProduct.cxx
  roofit/roofitcore/src/RooRealConstant.cxx
  roofit/roofitcore/src/RooRealIntegral.cxx
  roofit/roofitcore/src/RooRealSumPdf.cxx
Labels: performance optimisation

#3383 [Core] 1MB less RSS at root startup with simple optimisations
  core/base/CMakeLists.txt
  core/thread/CMakeLists.txt
  io/io/CMakeLists.txt
Labels: performance optimisation

#3256 [NFC][TMVA] Users guide -- update instructions for randomised trees
  documentation/tmva/UsersGuide/BDTs.tex
Labels: needs review

#3253 [TMVA] Fix GUI can't find all trained BDT's for plots
  tmva/tmva/src/MethodBase.cxx
  tmva/tmva/test/envelope/testClassification.cxx
Labels: needs review

#3412 [DOC][NFC] Mention that EnableThreadSafety does not make graphics thread-safe
  core/base/src/TROOT.cxx
Labels: docs

#3402 Fix the exclusion of underflow bin (and include the last bin) when computing the shortest interval in the BayesianCalculator
  roofit/roostats/inc/RooStats/BayesianCalculator.h
  roofit/roostats/src/BayesianCalculator.cxx
  test/stressRooStats_tests.cxx
Labels: bugfix

#3450 [DF][NFC] Small cleanups
  tree/dataframe/inc/ROOT/RDF/RInterface.hxx
Labels: ready to merge

#3453 [DOC][skip ci] Update RDF release notes
  README/ReleaseNotes/v618/index.md
Labels: docs
