Repository root-project/root, pull requests merged in 2019-01, with the labels that each got.

#3218 [PyROOT Exp] Use cppyy directly instead of TPython interface
  bindings/pyroot_experimental/PyROOT/src/TFilePyz.cxx
Labels: backport

#3224 [IMT][ROOT-9892] Impose work isolation to TTaskGroup
  core/imt/inc/ROOT/TTaskGroup.hxx
  core/imt/src/TTaskGroup.cxx
Labels: bugfix

#3241 [TreeReader] Do not warn about missing TEntryLists if you have one
  tree/treeplayer/src/TTreeReader.cxx
Labels: needs review

#3248 [RDF] Fix ROOT-9898
  tree/dataframe/inc/ROOT/RDF/RAction.hxx
  tree/dataframe/inc/ROOT/RDF/RActionBase.hxx
  tree/dataframe/inc/ROOT/RDF/RFilter.hxx
  tree/dataframe/inc/ROOT/RDF/RRange.hxx
  tree/dataframe/src/RActionBase.cxx
  tree/dataframe/src/RFilterBase.cxx
  tree/dataframe/src/RRangeBase.cxx
Labels: bugfix

#3251 [CMake] Disable all tmva related options if tmva is OFF
  cmake/modules/RootBuildOptions.cmake
Labels: bugfix

#3262 [PyROOT][ROOT-9903] Do not invoke TPython::Exec upon ROOT import from ipython
  bindings/pyroot/ROOT.py
Labels: bugfix

#3250 [RDF] Fix ROOT-9898
  tree/dataframe/inc/ROOT/RDF/RAction.hxx
  tree/dataframe/inc/ROOT/RDF/RActionBase.hxx
  tree/dataframe/inc/ROOT/RDF/RFilter.hxx
  tree/dataframe/inc/ROOT/RDF/RJittedAction.hxx
  tree/dataframe/inc/ROOT/RDF/RJittedFilter.hxx
  tree/dataframe/inc/ROOT/RDF/RRange.hxx
  tree/dataframe/src/RActionBase.cxx
  tree/dataframe/src/RFilterBase.cxx
  tree/dataframe/src/RRangeBase.cxx
Labels: backport, bugfix

#3334 [RF] Speed up hist2workspace
  README/ReleaseNotes/v618/index.md
  roofit/histfactory/inc/LinkDef.h
  roofit/histfactory/inc/RooStats/HistFactory/EstimateSummary.h
  roofit/histfactory/inc/RooStats/HistFactory/HistoToWorkspaceFactoryFast.h
  roofit/histfactory/inc/RooStats/HistFactory/Sample.h
  roofit/histfactory/inc/RooStats/HistFactory/Systematics.h
  roofit/histfactory/src/HistoToWorkspaceFactoryFast.cxx
  roofit/histfactory/src/Systematics.cxx
  roofit/histfactory/src/hist2workspace.cxx
Labels: performance optimisation

#3100 Add macros to flag legacy functions/classes.
  core/base/inc/ROOT/RConfig.h
Labels: needs review, new feature

#3340 geom: create TGeoCone with name in TGeoBuilder
  geom/geom/src/TGeoBuilder.cxx
Labels: bugfix

#3347 geom: 6.14 create TGeoCone with name in TGeoBuilder
  geom/geom/src/TGeoBuilder.cxx
Labels: bugfix

#3346 geom: 6.16 create TGeoCone with name in TGeoBuilder
  geom/geom/src/TGeoBuilder.cxx
Labels: bugfix

#3353 [DF][ROOT-9929] Extract branches names which are nested from jitted
  tree/dataframe/src/RDFInterfaceUtils.cxx
  tree/dataframe/test/dataframe_colnames.cxx
Labels: bugfix

#3350 [RF][ROOT-9777] Replay "Fix cloning workspaces"
  roofit/roofitcore/CMakeLists.txt
  roofit/roofitcore/inc/LinkDef3.h
  roofit/roofitcore/inc/RooWorkspaceHandle.h
  roofit/roofitcore/src/RooWorkspace.cxx
  roofit/roofitcore/test/CMakeLists.txt
  roofit/roofitcore/test/testWorkspace.cxx
  roofit/roostats/inc/RooStats/ModelConfig.h
  roofit/roostats/src/ModelConfig.cxx
Labels: bugfix

#3359 [DF][NFC] Minor fixes to OnPartialResult doc
  tree/dataframe/inc/ROOT/RResultPtr.hxx
Labels: docs
