Repository root-project/root, pull requests merged in 2019-04, with the labels that each got.

#3645 [DictGen][ROOT-10015] Remove remnants when dict generation fails
  core/dictgen/src/rootcling_impl.cxx
Labels: backport

#3557 cmake: enforce c++14 when enabling root7
  cmake/modules/RootBuildOptions.cmake
Labels: ready to merge

#3670 [PyROOT exp] Add 64bit long types to array interface
  bindings/pyroot_experimental/PyROOT/python/ROOT/pythonization/_rvec.py
  bindings/pyroot_experimental/PyROOT/test/array_interface.py
Labels: needs review

#3488 [No CI][PyROOT exp] Add feature to invoke Python callables from C++
  bindings/pyroot_experimental/PyROOT/CMakeLists.txt
  bindings/pyroot_experimental/PyROOT/python/ROOT/pythonization/_generic.py
  bindings/pyroot_experimental/PyROOT/src/CppCallablePyz.cxx
  bindings/pyroot_experimental/PyROOT/src/GenericPyz.cxx
  bindings/pyroot_experimental/PyROOT/src/PyROOTModule.cxx
  bindings/pyroot_experimental/PyROOT/src/PyROOTPythonize.h
  bindings/pyroot_experimental/PyROOT/test/CMakeLists.txt
  bindings/pyroot_experimental/PyROOT/test/cppcallable.py
Labels: needs review

#3669 [PyROOT exp] Introduce MakeNumpyDataFrame to read numpy arrays with RDF
  bindings/pyroot_experimental/PyROOT/CMakeLists.txt
  bindings/pyroot_experimental/PyROOT/inc/ROOT/RNumpyDS.hxx
  bindings/pyroot_experimental/PyROOT/python/ROOT/pythonization/_rdataframe.py
  bindings/pyroot_experimental/PyROOT/src/PyROOTModule.cxx
  bindings/pyroot_experimental/PyROOT/src/PyROOTPythonize.h
  bindings/pyroot_experimental/PyROOT/src/RDataFramePyz.cxx
  bindings/pyroot_experimental/PyROOT/test/CMakeLists.txt
  bindings/pyroot_experimental/PyROOT/test/rdataframe_makenumpy.py
Labels: needs review

#3633 Add alpha version of gdb pretty printers.
  build/CMakeLists.txt
  build/gdbPrinters/libCore.so-gdb.py
  build/gdbPrinters/libRooFitCore.so-gdb.py
Labels: needs review

#3739 [RF] Make sure that categories in multi-layer SimPdfs get updated.
  roofit/roofitcore/src/RooSimGenContext.cxx
Labels: backport, bugfix

#3748 [Core][ROOT-9959] Stop early manipulation of commandline args
  core/base/src/TApplication.cxx
Labels: bugfix
