Repository root-project/root, pull requests merged in 2019-03, with the labels that each got.

#3503 [RF] RooProdPdf leaks memory
  roofit/histfactory/src/HistoToWorkspaceFactoryFast.cxx
  roofit/roofitcore/inc/RooProdPdf.h
  roofit/roofitcore/src/RooProdPdf.cxx
  roofit/roostats/src/AsymptoticCalculator.cxx
Labels: bugfix

#3508 [RF] Fix memory leaks in RooFit/Stats.
  roofit/histfactory/src/HistoToWorkspaceFactoryFast.cxx
  roofit/roofitcore/inc/RooProdPdf.h
  roofit/roofitcore/src/RooProdPdf.cxx
  roofit/roostats/src/AsymptoticCalculator.cxx
Labels: backport, bugfix

#3510 [RF] Improve RooFit documentation.
  roofit/histfactory/src/FlexibleInterpVar.cxx
  roofit/roofit/src/RooKeysPdf.cxx
  roofit/roofit/src/RooPoisson.cxx
  roofit/roofitcore/inc/RooAbsReal.h
  roofit/roofitcore/src/RooAbsPdf.cxx
  roofit/roofitcore/src/RooAbsReal.cxx
  roofit/roofitcore/src/RooAddPdf.cxx
  roofit/roofitcore/src/RooCachedPdf.cxx
  roofit/roofitcore/src/RooCurve.cxx
  roofit/roofitcore/src/RooExtendPdf.cxx
  roofit/roofitcore/src/RooGenProdProj.cxx
  roofit/roofitcore/src/RooNLLVar.cxx
  roofit/roofitcore/src/RooProdPdf.cxx
  roofit/roofitcore/src/RooSimultaneous.cxx
  roofit/roofitcore/src/RooWorkspace.cxx
  tutorials/roofit/rf205_compplot.C
Labels: docs

#3509 [RF] Fix memory leaks in RooFit/Stats.
  roofit/histfactory/src/HistoToWorkspaceFactoryFast.cxx
  roofit/roofitcore/inc/RooProdPdf.h
  roofit/roofitcore/src/RooProdPdf.cxx
  roofit/roostats/src/AsymptoticCalculator.cxx
Labels: backport, bugfix

#3009 Generalization of RooArgusBG pdf
  roofit/roofit/src/RooArgusBG.cxx
Labels: new feature

#3559 [DF] Fix custom actions depending on RDF+RDataSource
  tree/dataframe/inc/ROOT/RDF/RInterface.hxx
Labels: bugfix

#3506 [DF][ROOT-10022]Add support for TBranchObject
  tree/dataframe/src/RLoopManager.cxx
Labels: bugfix, needs testing

#3565 [DF][ROOT-10045] Fix custom actions depending on RDF+RDataSource
  tree/dataframe/inc/ROOT/RDF/RInterface.hxx
Labels: backport

#3572 Fix interpretation of RooAddPdf coefficients for convolutions.
  roofit/roofitcore/src/RooFFTConvPdf.cxx
Labels: bugfix

#3601 [TTree] Avoid getting the number of branches twice
  tree/tree/src/TTree.cxx
Labels: bugfix, performance optimisation

#3611 [RF] Documentation updates.
  roofit/roofitcore/inc/RooAbsArg.h
  roofit/roofitcore/src/RooAbsArg.cxx
  roofit/roofitcore/src/RooAbsPdf.cxx
  roofit/roofitcore/src/RooAbsReal.cxx
  roofit/roofitcore/src/RooAbsTestStatistic.cxx
  roofit/roofitcore/src/RooChi2Var.cxx
  roofit/roofitcore/src/RooCustomizer.cxx
  roofit/roofitcore/src/RooFFTConvPdf.cxx
  roofit/roofitcore/src/RooLinearVar.cxx
Labels: docs
