Repository root-project/root, pull requests merged in 2019-10, with the labels that each got.

#4514 [RF] Fix ROOT-10331.
  roofit/roofitcore/inc/RooAbsReal.h
  roofit/roofitcore/inc/RooHelpers.h
  roofit/roofitcore/src/RooAbsReal.cxx
  roofit/roofitcore/src/RooNLLVar.cxx
Labels: bugfix

#4549 [Tree][Docs] Document TTree::Branch().
  tree/tree/inc/TTree.h
Labels: docs

#4586 [ROOT-10375] V523 The 'then' is equivalent to the 'else' case
  tmva/tmva/src/MethodMLP.cxx
Labels: needs review
