Repository root-project/root, pull requests merged in 2020-12, with the labels that each got.

#6912 [v7] RAxisBase() is noexcept only if std::string() is.
  hist/histv7/inc/ROOT/RAxis.hxx
Labels: bug

#6922 [http] provide MIME type when downloading file, support woff
  net/http/src/TCivetweb.cxx
  net/http/src/THttpServer.cxx
Labels: improvement

#6923 [cmake] Fix builds of clad with external LLVM (v6.22)
  interpreter/CMakeLists.txt
Labels: pr:backport

#6929 [net] Fixes a memory leak in TSocket::SendProcessIDs (ROOT-6892)
  net/net/src/TSocket.cxx
Labels: in:Other

#6938 [cling] DynamicLookup: avoid printing internal expression representation for non-debug builds
  interpreter/cling/lib/Interpreter/DynamicLookup.cpp
Labels: improvement, in:Cling

#6928 [cling] New interface to export Cling run-time configuration bits.
  core/clingutils/CMakeLists.txt
  core/metacling/src/TCling.cxx
  interpreter/cling/include/cling/Interpreter/Interpreter.h
  interpreter/cling/include/cling/Interpreter/RuntimeOptions.h
  interpreter/cling/include/cling/Interpreter/RuntimeUniverse.h
  interpreter/cling/include/cling/module.modulemap
  interpreter/cling/include/cling/module.modulemap.build
  interpreter/cling/lib/Interpreter/Interpreter.cpp
  interpreter/cling/test/CodeUnloading/DeclShadowing.C
Labels: improvement, in:Cling

#6943 [foundation] Work around spurious GCC 4.8 warning:
  core/foundation/inc/ROOT/RLogger.hxx
Labels: pr:squash on merge
