Repository root-project/root, pull requests merged in 2020-04, with the labels that each got.

#5272 [CmdLineUtils] Fix handling TObjects with multiple cycles.
  main/python/cmdLineUtils.py
Labels: bugfix

#5281 [DF] Disable splitcoll_arrayview test if runtime modules are on
  tree/dataframe/test/CMakeLists.txt
Labels: backport

#5286 [skip-ci] Update v6.22 release notes
  README/ReleaseNotes/v622/index.md
Labels: docs

#5292 [DF] Throw if thread pool size changed after RDF construction
  tree/dataframe/src/RLoopManager.cxx
  tree/dataframe/test/dataframe_concurrency.cxx
Labels: bugfix

#5306 [DF] Move test_splitcoll_arrayview to gtests from roottest (backport for v6.16)
  tree/dataframe/test/CMakeLists.txt
  tree/dataframe/test/TwoFloats.h
  tree/dataframe/test/TwoFloatsLinkDef.h
  tree/dataframe/test/dataframe_splitcoll_arrayview.cxx
Labels: backport

#5320 [math] Do not warn if len is unused.
  math/smatrix/inc/Math/SVector.icc
Labels: urgent

#5323 [genvector] Do not warn if end is unused.
  math/genvector/inc/Math/GenVector/LorentzVector.h
  math/genvector/inc/Math/GenVector/PositionVector3D.h
Labels: urgent

#5349 Fix compilation error due to a change merged before.
  core/dictgen/src/rootcling_impl.cxx
Labels: urgent

#5341 [RF] Fix ROOT-10670.
  roofit/roofitcore/src/RooMinimizer.cxx
Labels: backport

#5382 [DF] Veto SQlite tutorials if sqlite is not present
  tutorials/CMakeLists.txt
Labels: bugfix

#5237 [CMake] Add build option "asan" for address sanitizer builds.
  CMakeLists.txt
  README/ReleaseNotes/v622/index.md
  build/ASan_blacklist.txt
  cmake/modules/RootBuildOptions.cmake
  cmake/modules/RootMacros.cmake
  cmake/modules/RootTestDriver.cmake
  cmake/modules/SetUpLinux.cmake
  cmake/modules/SetUpMacOS.cmake
  core/CMakeLists.txt
  core/sanitizer/CMakeLists.txt
  core/sanitizer/README.md
  core/sanitizer/SanitizerSetup.cxx
  etc/lsan-root.supp
Labels: needs review

#5393 Add support for arrow 0.15.0+
  tree/dataframe/src/RArrowDS.cxx
Labels: bugfix

#5403 [webgui] provide fallback solution when chrome not run with files from tmp
  gui/webdisplay/src/RWebDisplayHandle.cxx
Labels: bugfix

#5360 [RF] Fix ROOT-10676.
  roofit/roofitcore/inc/RooDataSet.h
  roofit/roofitcore/src/RooDataSet.cxx
  roofit/roofitcore/src/RooFormulaVar.cxx
  roofit/roofitcore/src/RooTreeDataStore.cxx
  roofit/roofitcore/test/CMakeLists.txt
  roofit/roofitcore/test/testRooDataSet.cxx
Labels: bugfix

#5424 [ROOT-10677][cxxmodules] Support libcxx with glibc on unix.
  core/CMakeLists.txt
  interpreter/cling/include/cling/libc.modulemap
Labels: backport

#5422 [cxxmodules] Keep the pending rdict files to be re-read on reload.
  core/metacling/src/TCling.cxx
Labels: urgent

#5181 [cmake] use only source dirs as include paths when building ROOT
  CMakeLists.txt
  cmake/modules/RootConfiguration.cmake
  cmake/modules/RootMacros.cmake
  cmake/modules/SearchInstalledSoftware.cmake
  core/CMakeLists.txt
  core/base/CMakeLists.txt
  core/base/inc/LinkDef.h
  core/clib/CMakeLists.txt
  core/clingutils/CMakeLists.txt
  core/cont/CMakeLists.txt
  core/dictgen/CMakeLists.txt
  core/foundation/CMakeLists.txt
  core/gui/CMakeLists.txt
  core/imt/CMakeLists.txt
  core/lz4/CMakeLists.txt
  core/lzma/CMakeLists.txt
  core/macosx/CMakeLists.txt
  core/meta/CMakeLists.txt
  core/metacling/src/CMakeLists.txt
  core/newdelete/CMakeLists.txt
  core/rootcling_stage1/CMakeLists.txt
  core/textinput/CMakeLists.txt
  core/thread/CMakeLists.txt
  core/unix/CMakeLists.txt
  core/winnt/CMakeLists.txt
  core/zip/CMakeLists.txt
  core/zstd/CMakeLists.txt
  graf2d/cocoa/CMakeLists.txt
  graf2d/win32gdk/CMakeLists.txt
  graf3d/ftgl/CMakeLists.txt
  io/mpi/CMakeLists.txt
  io/rootpcm/CMakeLists.txt
  main/CMakeLists.txt
  math/mathcore/CMakeLists.txt
  math/mathmore/CMakeLists.txt
  net/rpdutils/CMakeLists.txt
  roofit/roofitcore/CMakeLists.txt
  roofit/roofitmore/CMakeLists.txt
  tmva/tmva/CMakeLists.txt
Labels: new feature

#5425 [RF] Fix ROOT-10676.
  roofit/roofitcore/inc/RooDataSet.h
  roofit/roofitcore/src/RooDataSet.cxx
  roofit/roofitcore/src/RooFormulaVar.cxx
  roofit/roofitcore/src/RooTreeDataStore.cxx
  roofit/roofitcore/test/CMakeLists.txt
  roofit/roofitcore/test/testRooDataSet.cxx
Labels: backport, bugfix

#5398 [dyld] Ignore ELF libraries which contain no symbols.
  core/metacling/src/TClingCallbacks.cxx
Labels: urgent

#5444 [dyld-v620] Ignore ELF libraries which contain no symbols.
  core/metacling/src/TClingCallbacks.cxx
Labels: backport

#5467 [DOCS][NFC] Add Renato Quagliani to v6.22 contributors
  README/ReleaseNotes/v622/index.md
Labels: docs

#5454 [NFC][Doc][RDF] Add "Efficient analysis in Python" section
  tree/dataframe/src/RDataFrame.cxx
Labels: docs

#5365 Move changes to TTreeCache data members in apparently better positions
  tree/tree/src/TTreeCache.cxx
  tree/treeplayer/src/TTreeReader.cxx
Labels: bugfix

#5489 [TChain] Do not try to retrieve the cache of a nullptr fTree
  tree/tree/src/TChain.cxx
Labels: bugfix

#5340 [Tree] Fix GetReadCache when called from a TChain
  tree/tree/src/TTree.cxx
Labels: bugfix, needs review
