Repository root-project/root, pull requests merged in 2020-03, with the labels that each got.

#5070 [Docs] Remove link to non-closed bug from release notes.
  README/ReleaseNotes/v620/index.md
Labels: docs

#4003 correct jobname in TMVACrossValidationApplication
  tutorials/tmva/TMVACrossValidationApplication.C
Labels: stale

#5125 [RF] Fix plotting slices of RooSimultaneous
  roofit/roofitcore/src/RooSimultaneous.cxx
Labels: bugfix

#5134 [RF] Fix plotting slices of RooSimultaneous.
  roofit/roofitcore/src/RooSimultaneous.cxx
Labels: backport, bugfix, needs review, ready to merge

#5164 [ntuple, tutorial] fix bad assert expression
  tutorials/v7/ntuple/ntpl004_dimuon.C
Labels: backport, bugfix

#5163 [ntuple, tutorial] fix bad assert expression
  tutorials/v7/ntuple/ntpl004_dimuon.C
Labels: backport, bugfix

#5166 [DF] Move test_splitcoll_arrayview to gtests from roottest
  tree/dataframe/test/CMakeLists.txt
  tree/dataframe/test/TwoFloats.h
  tree/dataframe/test/TwoFloatsLinkDef.h
  tree/dataframe/test/dataframe_splitcoll_arrayview.cxx
Labels: bugfix

#5180 [DF] Move test_splitcoll_arrayview to gtests from roottest
  tree/dataframe/test/CMakeLists.txt
  tree/dataframe/test/TwoFloats.h
  tree/dataframe/test/TwoFloatsLinkDef.h
  tree/dataframe/test/dataframe_splitcoll_arrayview.cxx
Labels: backport

#5188 [DF] Move test_splitcoll_arrayview to gtests from roottest
  tree/dataframe/test/CMakeLists.txt
  tree/dataframe/test/TwoFloats.h
  tree/dataframe/test/TwoFloatsLinkDef.h
  tree/dataframe/test/dataframe_splitcoll_arrayview.cxx
Labels: backport

#5086 Update clingUtils/CMakeLists.txt to copy module.modulemap in cling includes for Windows
  core/clingutils/CMakeLists.txt
Labels: gsoc

#5199 add missing GL includes in FTGL v6.20 [ROOT-10631]
  graf3d/ftgl/CMakeLists.txt
Labels: bugfix

#5214 [DF] Call CleanUpTask even if event loop throws
  tree/dataframe/src/RLoopManager.cxx
Labels: ready to merge

#5236 [notebook] add custom colors and gStyle in JSROOT drawings v6.20 [ROOT-10624][skip-ci]
  bindings/jupyroot/python/JupyROOT/helpers/utils.py
Labels: backport

#5234 Fix in TEntryList - check fCurrent memeber before access
  tree/tree/src/TEntryList.cxx
Labels: bugfix

#5220 [CMAKE] Make CXX_FLAGS on Mac cache variables.
  cmake/modules/SetUpMacOS.cmake
Labels: needs review

#5251 [RF] Pay attention to all arguments of RooArgSet::writeToStream().
  roofit/roofitcore/src/RooArgSet.cxx
Labels: backport, bugfix

#5253 [tree] avoid dependency from TreePlayer
  tree/tree/inc/TVirtualIndex.h
  tree/tree/src/TTree.cxx
  tree/treeplayer/inc/TChainIndex.h
  tree/treeplayer/inc/TTreeIndex.h
  tree/treeplayer/src/TChainIndex.cxx
  tree/treeplayer/src/TTreeIndex.cxx
Labels: backport, bugfix

#5262 Apply fixes in MethodPyKeras for Python3 (backport in 6.20)
  tmva/pymva/src/MethodPyKeras.cxx
Labels: backport
