Repository root-project/root, pull requests merged in 2020-02, with the labels that each got.

#4907 [RF] Fix crash in RooLinTransBinning due to uninitialised pointer.
  roofit/roofitcore/inc/RooLinTransBinning.h
  roofit/roofitcore/src/RooLinTransBinning.cxx
Labels: backport, bugfix

#4904 [ROOT-10534] Add GetNRuns feature to RDataFrame
  tree/dataframe/inc/ROOT/RDF/RInterface.hxx
  tree/dataframe/inc/ROOT/RDF/RLoopManager.hxx
  tree/dataframe/src/RLoopManager.cxx
  tree/dataframe/test/dataframe_simple.cxx
Labels: new feature

#4973 [Docs] Add paragraph about shared resources to RDF documentation.
  tree/dataframe/src/RDataFrame.cxx
Labels: docs

#4960 [RHist] Don't duplicate RHistBufferedFillBase members in RHistBufferedFill
  hist/histv7/inc/ROOT/RHistBufferedFill.hxx
Labels: bugfix, needs review

#4999 Fix mem leak in sqlitetest.cxx
  test/sqlitetest.cxx
Labels: bugfix

#4996 Fix memory leak in nbmain
  main/src/nbmain.cxx
Labels: bugfix, needs review

#5011 Return rootcling default to -v2.
  core/dictgen/src/rootcling_impl.cxx
Labels: bugfix, urgent

#4995 meta: Prevent CheckClassInfo from autoloading if it is globally disab…
  core/metacling/src/TCling.cxx
Labels: bugfix, urgent

#4994 properly handle scalar index variable. Fix ROOT-10557. v620
  tree/treeplayer/src/TTreeFormula.cxx
Labels: bugfix, urgent

#5017 [RF] Add line about SPlot to release notes.
  README/ReleaseNotes/v620/index.md
Labels: docs

#5006 [math] fix memory leak in TSPlot::SetTreeSelection
  math/splot/src/TSPlot.cxx
Labels: bugfix, needs review

#5021 [cling] Capture/reset expression eval context (ROOT-10511):
  interpreter/cling/include/cling/Utils/ParserStateRAII.h
  interpreter/cling/lib/Utils/ParserStateRAII.cpp
Labels: bugfix, needs review, urgent

#5027 properly handle scalar index variable. Fix ROOT-10557 v618
  tree/treeplayer/src/TTreeFormula.cxx
Labels: bugfix

#4979 [Core] Add 6.24/6.26 deprecation macros.
  core/base/inc/ROOT/RConfig.hxx
Labels: needs review

#5028 Fix ROOT-10552 incorrect StreamerInfoList update.
  io/io/src/TFile.cxx
  io/io/src/TStreamerInfo.cxx
  io/io/src/TStreamerInfoActions.cxx
Labels: bugfix, urgent

#5033 Fix ROOT-10574, ResolveTypedef was stripping 2 char from name prefixed with ::
  core/foundation/src/TClassEdit.cxx
Labels: bugfix

#4998 [mutiproc] fix memory leak with use of fMon.GetListOfActivities()
  core/multiproc/src/TMPClient.cxx
Labels: bugfix, needs review

#5023 [RHist] Generalize GetBinIndexForLowEdge to irregular axes
  hist/histv7/inc/ROOT/RAxis.hxx
  hist/histv7/src/RAxis.cxx
  hist/histv7/test/axis.cxx
Labels: needs review, new feature
