Repository root-project/root, pull requests merged in 2020-06, with the labels that each got.

#5769 [RF][ROOT-10810] Fix pickling of RooTreeDataStore.
  roofit/roofitcore/src/RooTreeDataStore.cxx
Labels: bugfix

#5777 [RF] Fix pickling of RooTreeDataStore.
  roofit/roofitcore/src/RooTreeDataStore.cxx
Labels: backport, bugfix

#5780 Fix circular includes Rtypes.h/TGenericClassInfo.h [ROOT-10820]
  core/meta/inc/TGenericClassInfo.h
Labels: bugfix

#5781 [RF] Fix pickling of RooTreeDataStore.
  roofit/roofitcore/src/RooTreeDataStore.cxx
Labels: backport, bugfix

#5792 Fix circular includes Rtypes.h/TGenericClassInfo.h [ROOT-10820] v6.22
  core/meta/inc/TGenericClassInfo.h
Labels: backport

#5787 [DF] Fix diagnostic of sparse/contiguous storage in TTreeReaderArray
  tree/dataframe/inc/ROOT/RDF/RColumnValue.hxx
Labels: bugfix

#5789 [DF] Fix diagnostic of sparse/contiguous storage in TTreeReaderArray (v6.22)
  tree/dataframe/inc/ROOT/RDF/RColumnValue.hxx
Labels: backport, bugfix

#5788 [DF] Fix diagnostic of sparse/contiguous storage in TTreeReaderArray (v6.20)
  tree/dataframe/inc/ROOT/RDF/RColumnValue.hxx
Labels: backport, bugfix

#5811 [DF] Fix contiguousness check, take #2
  tree/dataframe/inc/ROOT/RDF/RColumnValue.hxx
Labels: bugfix

#5810 [DF] Fix contiguousness check, take #2 (v6.20)
  tree/dataframe/inc/ROOT/RDF/RColumnValue.hxx
Labels: backport, bugfix

#5809 [DF] Fix contiguousness check, take #2 (v6.22)
  tree/dataframe/inc/ROOT/RDF/RColumnValue.hxx
Labels: backport, bugfix

#5813 Allow empty comments in TXMLEngine parser
  io/xml/src/TXMLEngine.cxx
Labels: bugfix

#5839 [DF][NFC] Fix typos in RLoopManager.cxx
  tree/dataframe/src/RLoopManager.cxx
Labels: backport

#5837 [DF] Fix memleak in helper function
  tree/dataframe/src/RDFInterfaceUtils.cxx
Labels: bugfix

#5552 [ROOT-9869] RMergeableValue: store RDF results and know how to merge them
  tree/dataframe/CMakeLists.txt
  tree/dataframe/inc/LinkDef.h
  tree/dataframe/inc/ROOT/RDF/ActionHelpers.hxx
  tree/dataframe/inc/ROOT/RDF/RAction.hxx
  tree/dataframe/inc/ROOT/RDF/RActionBase.hxx
  tree/dataframe/inc/ROOT/RDF/RJittedAction.hxx
  tree/dataframe/inc/ROOT/RDF/RMergeableValue.hxx
  tree/dataframe/inc/ROOT/RResultPtr.hxx
  tree/dataframe/src/RJittedAction.cxx
  tree/dataframe/test/CMakeLists.txt
  tree/dataframe/test/dataframe_merge_results.cxx
  tree/dataframe/test/dataframe_merge_results.py
Labels: needs review, new feature

#5846 [DF] Do not call SetBranchAddress when not needed
  tree/dataframe/inc/ROOT/RDF/ActionHelpers.hxx
Labels: backport, bugfix

#5875 [RF] Tweak release notes.
  README/ReleaseNotes/v622/index.md
Labels: docs

#5865 [RF][ROOT-10845] Correct IsOnHeap() for RooFit objects.
  roofit/roofitcore/src/MemPoolForRooSets.h
  roofit/roofitcore/test/CMakeLists.txt
  roofit/roofitcore/test/testRooAbsCollection.cxx
  roofit/roofitcore/test/testRooDataSet.cxx
Labels: bugfix

#5866 [RF][ROOT-10845] Correct IsOnHeap() for RooFit objects.
  roofit/roofitcore/src/MemPoolForRooSets.h
  roofit/roofitcore/test/CMakeLists.txt
  roofit/roofitcore/test/testRooAbsCollection.cxx
  roofit/roofitcore/test/testRooDataSet.cxx
Labels: backport, bugfix

#5876 [RF] Release notes.
  README/ReleaseNotes/v622/index.md
Labels: docs

#5880 [skip-ci][DOC] Clarify how we want to be cited in README.md
  README.md
Labels: docs

#5881 [thstack] fix error in options decoding, fix gcc10 warnings
  hist/hist/src/THStack.cxx
Labels: bugfix

#5898 [thstack] fix error in options decoding, v6.22
  hist/hist/src/THStack.cxx
Labels: backport

#5905 From Guilherme: Add missing include in XProofProtUtils.cxx (v6.22 backport)
  proof/proofd/src/XProofProtUtils.cxx
Labels: backport

#5946 [Tutorials] Veto df103_NanoAODHiggsAnalysis on Mac 10.13
  tutorials/CMakeLists.txt
Labels: backport

#5941 [cling] External llvm does not have config.h
  interpreter/cling/lib/Interpreter/DynamicLibraryManagerSymbol.cpp
Labels: backport
