Repository root-project/root, pull requests merged in 2021-01, with the labels that each got.

#6976 [README] Fix "Getting started with Root" link
  README.md
Labels: affects:master, in:Other

#6980 [JupyROOT][6974] Fixes for IPython
  bindings/jupyroot/python/JupyROOT/__init__.py
Labels: in:PyROOT

#6989 [http] disable auth domain check when domain not configured
  net/http/src/TCivetweb.cxx
Labels: improvement

#6990 [http] disable auth domain check when domain not configured 6.22
  net/http/src/TCivetweb.cxx
Labels: affects:6.22, improvement, pr:backport

#7006 [NFC] v6-22: Try to prevent anti-virus false positive detection on Wi…
  main/src/hadd.cxx
Labels: pr:backport

#7007 [NFC] v6-20: Try to prevent anti-virus false positive detection on Wi…
  main/src/hadd.cxx
Labels: pr:backport

#7020 [cmake] Patch tbb for Apple M1 (issue #6903).
  builtins/tbb/patches/apple-m1.patch
  cmake/modules/SearchInstalledSoftware.cmake
Labels: pr:squash on merge

#7049 [github] Update code owners. [skip-ci]
  .github/CODEOWNERS
Labels: pr:squash on merge

#7073 core: Do not rely on rootpcm for libMultiProc.
  core/metacling/src/TCling.cxx
  core/multiproc/CMakeLists.txt
Labels: in:Core Libraries
