Repository root-project/root, pull requests merged in 2021-02, with the labels that each got.

#7114 TH1::Scale() documentation typos
  hist/hist/src/TH1.cxx
Labels: in:Documentation

#7120 [http] add ROOT/MakeUnique.hxx to fastcgi
  net/http/src/TFastCgi.cxx
Labels: bug

#7130 [tree] adjust TBranchBrowsable code formatting
  tree/tree/inc/TBranchBrowsable.h
  tree/tree/src/TBranchBrowsable.cxx
Labels: improvement

#7145 Fix possible typo in TKDE.cxx
  hist/hist/src/TKDE.cxx
Labels: affects:master

#7119 In TBranchElement init offset avoid stripping part of the name.
  tree/tree/src/TBranchElement.cxx
Labels: bug, in:TTree

#7170 Add a circular buffer to compute the mean value (fix issue #7164)
  gui/gui/inc/TGSpeedo.h
  gui/gui/src/TGSpeedo.cxx
Labels: in:GUI

#7221 Fix TPad::WaitPrimitive() when canvas is closing
  graf2d/gpad/inc/TCanvas.h
  graf2d/gpad/inc/TPad.h
  graf2d/gpad/src/TPad.cxx
Labels: bug

#7224 Fix TPad::WaitPrimitive() when canvas is closing, v6.22
  graf2d/gpad/src/TPad.cxx
Labels: bug, pr:backport

#7219 [treereader] extend fgEntryStatusText array
  tree/treeplayer/inc/TTreeReader.h
  tree/treeplayer/src/TTreeReader.cxx
Labels: bug

#7188 [RF] RooFormula::processForumla: escape { and } in variable names.
  roofit/roofitcore/src/RooFormula.cxx
Labels: pr:backport

#7189 [RF] RooFormula::processForumla: escape { and } in variable names.
  roofit/roofitcore/src/RooFormula.cxx
Labels: pr:backport

#7139 Introduce ROOT.RDF.Distributed
  bindings/CMakeLists.txt
  bindings/experimental/distrdf/.gitignore
  bindings/experimental/distrdf/CMakeLists.txt
  bindings/experimental/distrdf/python/DistRDF/Backends/Base.py
  bindings/experimental/distrdf/python/DistRDF/Backends/Spark/Backend.py
  bindings/experimental/distrdf/python/DistRDF/Backends/Spark/__init__.py
  bindings/experimental/distrdf/python/DistRDF/Backends/Utils.py
  bindings/experimental/distrdf/python/DistRDF/Backends/__init__.py
  bindings/experimental/distrdf/python/DistRDF/ComputationGraphGenerator.py
  bindings/experimental/distrdf/python/DistRDF/DataFrame.py
  bindings/experimental/distrdf/python/DistRDF/Node.py
  bindings/experimental/distrdf/python/DistRDF/Operation.py
  bindings/experimental/distrdf/python/DistRDF/Proxy.py
  bindings/experimental/distrdf/python/DistRDF/__init__.py
  bindings/experimental/distrdf/test/CMakeLists.txt
  bindings/experimental/distrdf/test/__init__.py
  bindings/experimental/distrdf/test/backend/1000clusters.root
  bindings/experimental/distrdf/test/backend/2clusters.root
  bindings/experimental/distrdf/test/backend/4clusters.root
  bindings/experimental/distrdf/test/backend/CMakeLists.txt
  bindings/experimental/distrdf/test/backend/Slimmed_ntuple.root
  bindings/experimental/distrdf/test/backend/emptytree.root
  bindings/experimental/distrdf/test/backend/test_common.py
  bindings/experimental/distrdf/test/backend/test_dist.py
  bindings/experimental/distrdf/test/backend/test_headers/header1.hxx
  bindings/experimental/distrdf/test/backend/test_headers/header2.hxx
  bindings/experimental/distrdf/test/backend/test_headers/header3.hxx
  bindings/experimental/distrdf/test/backend/test_headers/header4.hxx
  bindings/experimental/distrdf/test/backend/test_spark.py
  bindings/experimental/distrdf/test/test_buildranges.py
  bindings/experimental/distrdf/test/test_callable_generator.py
  bindings/experimental/distrdf/test/test_friendinfo.py
  bindings/experimental/distrdf/test/test_headnode.py
  bindings/experimental/distrdf/test/test_node.py
  bindings/experimental/distrdf/test/test_operation.py
  bindings/experimental/distrdf/test/test_proxy.py
  bindings/pyroot/pythonizations/python/ROOT/_facade.py
Labels: new feature

#7251 TGSpeedo: enable retrieval of odometer value
  gui/gui/inc/TGSpeedo.h
Labels: improvement, in:GUI

#7220 Add up and down arrow keys handling (resolves #7180)
  gui/gui/inc/TGCommandPlugin.h
  gui/gui/src/TGCommandPlugin.cxx
Labels: affects:master, improvement, in:GUI

#7265 Fix CoreBaseTests failure on Windows
  core/base/test/CMakeLists.txt
Labels: affects:master, bug, in:Testing

#7262 add Modified() signal for TGNumberEntry
  gui/gui/inc/TGNumberEntry.h
  gui/gui/src/TGNumberEntry.cxx
Labels: improvement, in:GUI

#7094 Fix #7093: race condition tripping TEnum::GetEnum
  core/meta/src/TEnum.cxx
  core/metacling/src/TCling.cxx
Labels: affects:master, bug, priority:critical

#7237 TGFileDialog new option to open / save to a folder, instead of a file
  gui/gui/inc/TGFileDialog.h
  gui/gui/src/TGFileDialog.cxx
Labels: affects:master, improvement, in:GUI

#7288 Add `ACLiC.LinkLibs: 1` in the `.rootrc` file for Windows
  tutorials/CMakeLists.txt
Labels: affects:master, in:Testing

#7287 Fix for Apple Silicon M1 - gfortran does not accept -m64
  cmake/modules/SetUpMacOS.cmake
Labels: affects:master, in:Build System
