Repository root-project/root, pull requests merged in 2021-09, with the labels that each got.

#8943 [skip-ci] Mark TGeoTrack as deprecated
  geom/geompainter/src/TGeoTrack.cxx
Labels: in:Documentation

#8938 [DF] Suppress spurious ResourceWarning in distrdf-pyspark tests
  bindings/experimental/distrdf/test/backend/test_spark.py
Labels: in:RDataFrame

#8945 [skip-ci] TGeoTrack deprecation
  geom/geompainter/src/TGeoTrack.cxx
Labels: in:Documentation

#8934 [core] WriteObject overload for TObject-derived classes
  core/base/inc/TDirectory.h
  io/io/test/TFileTests.cxx
Labels: in:Core Libraries

#8630 Add several improvements to use Unuran with the DistSampler interface
  math/mathcore/inc/Math/DistSampler.h
  math/mathcore/inc/Math/DistSamplerOptions.h
  math/mathcore/inc/Math/GenAlgoOptions.h
  math/mathcore/src/DistSampler.cxx
  math/mathcore/src/DistSamplerOptions.cxx
  math/unuran/inc/TUnuran.h
  math/unuran/inc/TUnuranSampler.h
  math/unuran/src/TUnuran.cxx
  math/unuran/src/TUnuranContDist.cxx
  math/unuran/src/TUnuranSampler.cxx
  math/unuran/test/CMakeLists.txt
  math/unuran/test/unuranSampler.cxx
Labels: improvement, in:Math Libraries

#8967 Demoting change of TGeo units from Warning to Info.
  geom/geom/src/TGeoManager.cxx
Labels: improvement, in:Geometry

#8969 Fix relative links for PyROOT on macOS
  bindings/pyroot/cppyy/CPyCppyy/CMakeLists.txt
  bindings/pyroot/cppyy/cppyy-backend/CMakeLists.txt
  bindings/pyroot_legacy/CMakeLists.txt
Labels: pr:backport

#8975 Fix invalid pointer error in TRintTests.cxx
  core/rint/test/TRintTests.cxx
Labels: in:Core Libraries

#8772 [Rint] Correctly handle line continuation after '\'
  core/rint/inc/TRint.h
  core/rint/src/TRint.cxx
Labels: bug, affects:master, in:Core Libraries

#8986 [RF] Change RooNLLVar constructors to be backwards compatible
  roofit/roofitcore/inc/RooNLLVar.h
  roofit/roofitcore/src/RooAbsPdf.cxx
  roofit/roofitcore/src/RooNLLVar.cxx
  roofit/roofitcore/test/TestStatistics/testLikelihoodSerial.cxx
Labels: in:RooFit/RooStats

#8997 [RF] Avoid using forward-declared class as default template arguments
  roofit/roofitcore/inc/RooMinimizer.h
  roofit/roofitcore/inc/TestStatistics/MinuitFcnGrad.h
Labels: in:RooFit/RooStats

#8993 [TMVA][SOFIE] Fix problem with broadcasting bias tensor in the Conv operator.
  tmva/sofie/inc/TMVA/ROperator_Conv.hxx
  tmva/sofie/inc/TMVA/SOFIE_common.hxx
  tmva/sofie/src/SOFIE_common.cxx
Labels: in:TMVA

#9021 Prevent Access of deleted object during hadd tear down
  tree/tree/src/TTree.cxx
Labels: priority:critical, in:I/O

#9027 v622 Prevent Access of deleted object during hadd tear down
  tree/tree/src/TTree.cxx
Labels: in:I/O

#9026 v624 Prevent Access of deleted object during hadd tear down
  tree/tree/src/TTree.cxx
Labels: in:I/O

#9025 [cmake] Clone the corresponding `roottest` branch, if `latest-stable` has been checked out for `root`
  CMakeLists.txt
Labels: bug, affects:master, in:Build System

#9033 [ntuple,daos] `RNTupleWriter::Recreate()` now overwrites old ntuple
  tree/ntuple/v7/inc/ROOT/libdaos_mock/daos.h
  tree/ntuple/v7/src/RDaos.cxx
Labels: bug, affects:master, in:RNTuple

#9054 [ntuple] Remove warning `Warning: Unused class rule: PackedContainer`
  tree/ntuple/v7/test/CustomStructLinkDef.h
Labels: bug
