Repository root-project/root, pull requests merged in 2021-05, with the labels that each got.

#8056 HistFactory: Fix typo and add spacing in warning string
  roofit/histfactory/src/HistoToWorkspaceFactoryFast.cxx
Labels: improvement, in:RooFit/RooStats

#8025 fix opening reference guide with .help Class
  core/base/src/TApplication.cxx
Labels: improvement, in:Documentation

#8068 Fix multicore tests when running on machines with few cores
  tree/dataframe/test/dataframe_concurrency.cxx
  tree/dataframe/test/dataframe_interface.cxx
  tree/dataframe/test/dataframe_simple.cxx
  tree/dataframe/test/dataframe_snapshot.cxx
  tree/treeplayer/test/treeprocmt/treeprocessormt.cxx
Labels: improvement, in:RDataFrame

#8066 [LLVM] Replace "&" printing patch with LLVM commit
  interpreter/llvm/src/tools/clang/lib/AST/TemplateBase.cpp
Labels: improvement, in:Cling

#7878 Print key cycle information in rootls -l
  main/python/cmdLineUtils.py
Labels: improvement, in:Other

#8069 Fix ppc64le compilation with gcc 10
  interpreter/llvm/src/tools/clang/lib/Lex/Lexer.cpp
Labels: improvement, in:Cling

#8090 [RF] Test schema evolution of RooDataHist from version 5 and 6
  roofit/roofitcore/test/CMakeLists.txt
  roofit/roofitcore/test/dataHistv5_ref.root
  roofit/roofitcore/test/dataHistv6_ref.root
  roofit/roofitcore/test/testRooDataHist.cxx
Labels: in:RooFit/RooStats

#8089 Bump cling version to 1.0~dev.
  interpreter/cling/VERSION
  interpreter/cling/docs/ReleaseNotes.md
Labels: affects:master, in:Cling

#8045 [core/base] clang-tidy modernize nullptr
  core/base/src/Match.cxx
  core/base/src/Stringio.cxx
  core/base/src/TApplication.cxx
  core/base/src/TAttBBox.cxx
  core/base/src/TBenchmark.cxx
  core/base/src/TBuffer.cxx
  core/base/src/TBuffer3D.cxx
  core/base/src/TColor.cxx
  core/base/src/TColorGradient.cxx
  core/base/src/TDatime.cxx
  core/base/src/TDirectory.cxx
  core/base/src/TEnv.cxx
  core/base/src/TErrorDefaultHandler.cxx
  core/base/src/TFileCollection.cxx
  core/base/src/TFileInfo.cxx
  core/base/src/TFolder.cxx
  core/base/src/TMD5.cxx
  core/base/src/TMacro.cxx
  core/base/src/TMessageHandler.cxx
  core/base/src/TObject.cxx
  core/base/src/TPRegexp.cxx
  core/base/src/TPluginManager.cxx
  core/base/src/TProcessID.cxx
  core/base/src/TProcessUUID.cxx
  core/base/src/TQCommand.cxx
  core/base/src/TQConnection.cxx
  core/base/src/TQObject.cxx
  core/base/src/TROOT.cxx
  core/base/src/TRef.cxx
  core/base/src/TStorage.cxx
  core/base/src/TString.cxx
  core/base/src/TStyle.cxx
  core/base/src/TSystem.cxx
  core/base/src/TSystemDirectory.cxx
  core/base/src/TTask.cxx
  core/base/src/TTimeStamp.cxx
  core/base/src/TTimer.cxx
  core/base/src/TUUID.cxx
  core/base/src/TUrl.cxx
  core/base/src/TVirtualFFT.cxx
  core/base/src/TVirtualMonitoring.cxx
  core/base/src/TVirtualMutex.cxx
  core/base/src/TVirtualPad.cxx
  core/base/src/TVirtualPadEditor.cxx
  core/base/src/TVirtualPadPainter.cxx
  core/base/src/TVirtualPerfStats.cxx
  core/base/src/TVirtualViewer3D.cxx
  core/base/src/TVirtualX.cxx
Labels: improvement, in:Core Libraries

#8107 [core] Missing include in string_view header
  core/foundation/inc/ROOT/libcpp_string_view.h
Labels: affects:6.24, affects:master, bug, in:Core Libraries

#8093 [ntuple, daos] Defer `daos_init()` call until needed
  tree/ntuple/v7/src/RDaos.cxx
Labels: improvement, in:RNTuple

#8102 Fix #8033: string array StreamerElement not recorded properly
  core/meta/src/TStreamerElement.cxx
Labels: in:I/O

#8117 v624: Fix #8033: string array StreamerElement not recorded properly
  core/meta/src/TStreamerElement.cxx
Labels: affects:6.24, bug, in:I/O

#8116 v620: Fix #8033: string array StreamerElement not recorded properly
  core/meta/src/TStreamerElement.cxx
Labels: affects:6.20, bug, in:I/O

#8115 v622: Fix #8033: string array StreamerElement not recorded properly
  core/meta/src/TStreamerElement.cxx
Labels: affects:6.22, bug, in:I/O

#8138 [RF] Fix typo in RooMsgService
  roofit/roofitcore/src/RooMsgService.cxx
Labels: in:RooFit/RooStats

#8130 Use latest JSROOT as fallback in JupyROOT
  bindings/jupyroot/python/JupyROOT/helpers/utils.py
Labels: affects:master, in:Notebooks

#8114 Eve-7 Use server threads
  graf3d/eve7/inc/LinkDef.h
  graf3d/eve7/inc/ROOT/REveDataCollection.hxx
  graf3d/eve7/inc/ROOT/REveDataSimpleProxyBuilder.hxx
  graf3d/eve7/inc/ROOT/REveDataTable.hxx
  graf3d/eve7/inc/ROOT/REveManager.hxx
  graf3d/eve7/inc/ROOT/REveScene.hxx
  graf3d/eve7/inc/ROOT/REveSelection.hxx
  graf3d/eve7/inc/ROOT/REveTableInfo.hxx
  graf3d/eve7/inc/ROOT/REveTypes.hxx
  graf3d/eve7/src/REveDataCollection.cxx
  graf3d/eve7/src/REveDataProxyBuilderBase.cxx
  graf3d/eve7/src/REveDataSimpleProxyBuilder.cxx
  graf3d/eve7/src/REveDataTable.cxx
  graf3d/eve7/src/REveElement.cxx
  graf3d/eve7/src/REveGeoShape.cxx
  graf3d/eve7/src/REveManager.cxx
  graf3d/eve7/src/REveScene.cxx
  graf3d/eve7/src/REveSelection.cxx
  graf3d/eve7/src/REveTableInfo.cxx
  graf3d/eve7/src/REveTableProxyBuilder.cxx
  graf3d/eve7/src/REveTypes.cxx
  tutorials/eve7/collection_proxies.C
  tutorials/eve7/event_demo.C
  ui5/eve7/controller/Main.controller.js
  ui5/eve7/controller/Summary.controller.js
  ui5/eve7/lib/EveElements.js
  ui5/eve7/lib/EveManager.js
  ui5/eve7/lib/EveScene.js
  ui5/eve7/lib/GlViewerThree.js
Labels: affects:master, in:Other

#8164 Fix errors in documentation about dictionary generations [skip-ci]
  documentation/users-guide/AddingaClass.md
Labels: affects:master, in:Documentation

#8163 [VecOps] Remove deprecation warnings from RAdoptAllocator
  math/vecops/inc/ROOT/RAdoptAllocator.hxx
Labels: pr:backport

#8162 [VecOps] Remove deprecation warnings from RAdoptAllocator
  math/vecops/inc/ROOT/RAdoptAllocator.hxx
Labels: pr:backport

#4465 [cling] MetaSema code cleanup; add support in `.x` for a list of functions that will be called, in order (fallback)
  interpreter/cling/include/cling/MetaProcessor/MetaSema.h
  interpreter/cling/lib/MetaProcessor/MetaSema.cpp
Labels: improvement, in:Cling

#7885 [sql] provide TSQLServer::HasTransactionInFlight() method
  net/net/inc/TSQLServer.h
  net/net/src/TSQLServer.cxx
  sql/sqlite/inc/TSQLiteServer.h
  sql/sqlite/src/TSQLiteServer.cxx
Labels: affects:master, improvement

#8177 FindObject for rooabscollection
  roofit/roofitcore/inc/RooAbsCollection.h
Labels: in:RooFit/RooStats

#8091 [RF] Import more RooFit Python examples translated by Clemens Lange
  tutorials/roofit/rf105_funcbinding.py
  tutorials/roofit/rf208_convolution.py
  tutorials/roofit/rf210_angularconv.py
  tutorials/roofit/rf211_paramconv.py
  tutorials/roofit/rf401_importttreethx.py
  tutorials/roofit/rf403_weightedevts.png
  tutorials/roofit/rf510_wsnamedsets.py
  tutorials/roofit/rf512_wsfactory_oper.py
  tutorials/roofit/rf601_intminuit.py
  tutorials/roofit/rf605_profilell.py
  tutorials/roofit/rf606_nllerrorhandling.py
  tutorials/roofit/rf705_linearmorph.py
Labels: in:RooFit/RooStats

#8206 Use legend.DrawClone() in tutorial [skip-ci]
  tutorials/dataframe/df103_NanoAODHiggsAnalysis.C
Labels: affects:master, bug

#8223 [cling] Silence GCC 4.8 / CentOS7 warnings: [v624]
  interpreter/cling/include/cling/Interpreter/LookupHelper.h
  interpreter/cling/lib/Interpreter/LookupHelper.cpp
  interpreter/cling/lib/Utils/PlatformPosix.cpp
Labels: pr:backport

#8228 TFileMerger _actually_ delete directory only if we induced its creation/loading
  io/io/src/TFileMerger.cxx
Labels: affects:master, in:TTree

#8229 v624: TFileMerger _actually_ delete directory only if we induced its creation/loading
  io/io/src/TFileMerger.cxx
Labels: affects:6.24, in:I/O

#8230 Actually request the use of the large code model for ppc64/ppc64le
  interpreter/cling/lib/Interpreter/IncrementalExecutor.cpp
Labels: in:Cling

#8255 Fix invalid use of incomplete class in RWebBrowserImp
  gui/browserv7/src/RWebBrowserImp.cxx
Labels: affects:master, in:WebGui

#8111 Avoid self comparison when sorting RooAbsArg
  roofit/roofitcore/src/RooVectorDataStore.cxx
Labels: in:RooFit/RooStats

#8278 [DF] Do not store references to callables in PassAsVec (6.24)
  tree/dataframe/inc/ROOT/RDFHelpers.hxx
Labels: pr:backport

#8287 [core][6.24] Missing include in string_view header
  core/foundation/inc/ROOT/libcpp_string_view.h
Labels: pr:backport

#8289 [core][6.22][skip-ci] Missing include in string_view header
  core/foundation/inc/ROOT/libcpp_string_view.h
Labels: pr:backport

#8290 [core][6.20][skip-ci] Missing include in string_view header
  core/foundation/inc/ROOT/libcpp_string_view.h
Labels: pr:backport

#8291 [core][6.18][skip-ci] Missing include in string_view header
  core/foundation/inc/ROOT/libcpp_string_view.h
Labels: pr:backport
