Repository root-project/root, pull requests merged in 2021-03, with the labels that each got.

#7310 Fix TGraph copy constructor and assign operator (#7302) [6.22]
  hist/hist/src/TGraph.cxx
Labels: affects:6.22, bug, pr:backport

#7316 Fix build time on Windows when nothing changed in the code
  core/imt/CMakeLists.txt
Labels: in:Build System

#7324 Set pyroot_legacy=OFF by default on Windows
  cmake/modules/RootBuildOptions.cmake
Labels: in:Build System, in:PyROOT

#7330 [eve7] repair logic of mouseup handler [skip-ci]
  ui5/eve7/controller/GL.controller.js
  ui5/eve7/lib/GlViewerThree.js
Labels: bug

#7326 Fix assertion failure on Windows
  core/metacling/src/TCling.cxx
Labels: affects:master, bug, in:Cling

#7307 [doc] Link GitHub as issue tracker (NFC) [skip-ci] (skip-ci)
  documentation/doxygen/mainpage.md
Labels: in:Documentation

#7337 [gui] fix leak in TGFSComboBox, avoid usage of static variable
  gui/gui/inc/TGFSComboBox.h
  gui/gui/src/TGFSComboBox.cxx
Labels: in:GUI

#7342 Remove the __type_info_node symbol from the exports list
  core/metacling/src/CMakeLists.txt
Labels: in:Cling

#7353 [webgui] let reassign main thread id [6.22]
  gui/webdisplay/inc/ROOT/RWebWindowsManager.hxx
  gui/webdisplay/src/RWebWindowsManager.cxx
Labels: in:GUI, pr:backport

#7365 [modules] Fix crash in call to `FunctionDecl::setPure()`
  interpreter/llvm/src/tools/clang/lib/Serialization/ASTReaderDecl.cpp
Labels: affects:master, in:Cling

#7357 [asimage] set screen gamma to SCREEN_GAMMA
  graf2d/asimage/src/TASImage.cxx
Labels: affects:master, bug, in:Graphics

#7359 [asimage] set screen gamma to SCREEN_GAMMA, backport to 6.24
  graf2d/asimage/src/TASImage.cxx
Labels: bug, in:Graphics, pr:backport, priority:high

#7363 [webgui] mark TASImage as supported class in RBrowser, backport 6.24
  gui/browsable/src/TObjectElement.cxx
Labels: pr:backport

#7346 Fix libAfterImage building
  graf2d/asimage/src/libAfterImage/Makefile.in
Labels: in:Build System, priority:critical

#7360 Fix libAfterImage building, backport to 6.24
  graf2d/asimage/src/libAfterImage/Makefile.in
Labels: bug, pr:backport

#7328 [builtins] Update xxhash to latest version: 0.8.0
  builtins/xxhash/CMakeLists.txt
  builtins/xxhash/xxhash.c
  builtins/xxhash/xxhash.h
Labels: in:Other

#7356 Add deprecated flag on PROOF
  proof/proof/src/TProof.cxx
Labels: in:Math Libraries

#7364 [TChain] Do not try to look up index when loading non-existing entries
  tree/tree/src/TChain.cxx
Labels: in:I/O

#7367 [TChain] Do not try to look up index when loading non-existing entries (v6.24)
  tree/tree/src/TChain.cxx
Labels: pr:backport

#7355 [DF] Veto tutorials depending on davix when it is not present
  tutorials/CMakeLists.txt
Labels: in:RDataFrame

#7376 [Cling][cpt]Update cpt shebang to reflect Python 3 requirement [skip-ci]
  interpreter/cling/tools/packaging/cpt.py
Labels: improvement, in:Cling

#7331 [builtins] Update Davix to latest available version: 0.7.6
  builtins/davix/CMakeLists.txt
Labels: in:Other

#7380 Update xrootd to v4.12.8 (it contains critical patch fixing compilati…
  cmake/modules/SearchInstalledSoftware.cmake
Labels: affects:master, in:Build System, in:Other

#7378 [rootcling] add extra check for MathCore dependency from Vc
  core/dictgen/src/rootcling_impl.cxx
Labels: affects:master, in:Cling

#7379 [rootcling] add extra check for MathCore dependency from Vc, backport to 6.24
  core/dictgen/src/rootcling_impl.cxx
Labels: in:Cling, pr:backport

#7374 Fix libAfterImage building, backport 6.22
  graf2d/asimage/src/libAfterImage/Makefile.in
Labels: affects:6.22, pr:backport

#7387 Update xrootd to v4.12.8 (it contains critical patch fixing compilati…
  cmake/modules/SearchInstalledSoftware.cmake
Labels: in:Build System

#7392 Fix bug in cling's diagnostic engine, if CUDA mode is enable
  interpreter/cling/lib/Interpreter/CIFactory.cpp
Labels: in:Cling

#7386 Update xrootd to v4.12.8 (it contains critical patch fixing compilati…
  cmake/modules/SearchInstalledSoftware.cmake
Labels: in:Build System

#7397 Fix incrementals
  interpreter/llvm/src/tools/clang/lib/Serialization/ASTReader.cpp
Labels: in:Cling

#7371 Add distributed RDataFrame pyspark build option
  bindings/CMakeLists.txt
  bindings/experimental/distrdf/CMakeLists.txt
  bindings/experimental/distrdf/test/backend/CMakeLists.txt
  cmake/modules/FindPySpark.cmake
  cmake/modules/RootBuildOptions.cmake
  cmake/modules/SearchInstalledSoftware.cmake
Labels: in:Build System, in:RDataFrame, in:Testing

#7405 [RF] Assume uniform weights in computeBatched if weights vector is empty
  roofit/roofitcore/src/RooNLLVar.cxx
Labels: in:RooFit/RooStats

#7404 [RF] Assume uniform weights in computeBatched if weights vector is empty
  roofit/roofitcore/src/RooNLLVar.cxx
Labels: in:RooFit/RooStats, pr:backport

#7402 [dictgen] Do not create stray temp files:
  core/dictgen/src/TModuleGenerator.cxx
Labels: pr:backport

#7413 Build option for distributed RDF tests that use pyspark
  bindings/experimental/distrdf/CMakeLists.txt
  bindings/experimental/distrdf/test/backend/CMakeLists.txt
  cmake/modules/FindPySpark.cmake
  cmake/modules/RootBuildOptions.cmake
  cmake/modules/SearchInstalledSoftware.cmake
Labels: affects:master, in:Testing

#7416 backport for v6.24: Build option for distributed RDF tests that use pyspark
  bindings/experimental/distrdf/CMakeLists.txt
  bindings/experimental/distrdf/test/backend/CMakeLists.txt
  cmake/modules/FindPySpark.cmake
  cmake/modules/RootBuildOptions.cmake
  cmake/modules/SearchInstalledSoftware.cmake
Labels: pr:backport

#7419 [cling] Disable GlobalISel on AArch64
  interpreter/cling/lib/Interpreter/IncrementalExecutor.cpp
Labels: affects:6.24, affects:master, in:Cling, priority:high

#7314 [RF] Add keyword pythonization of fitTo to RooAbsPdf
  bindings/pyroot/pythonizations/python/ROOT/pythonization/_roofit/__init__.py
  bindings/pyroot/pythonizations/python/ROOT/pythonization/_roofit/_rooabspdf.py
  bindings/pyroot/pythonizations/test/roofit/rooabspdf_fitto.py
Labels: in:PyROOT

#7415 Pin the Roofit batch computation library to be used.
  roofit/batchcompute/src/Initialisation.cxx
Labels: new feature, priority:critical

#7463 [clingutils] simplify TMetaUtils::GetCppName
  core/clingutils/src/TClingUtils.cxx
Labels: improvement

#7475 Fix memory leak in TQCommand
  core/base/src/TQCommand.cxx
Labels: affects:6.24, affects:master, bug

#7474 [roofit] [memleak] Wrong delete operator for array in RooSegmentedIntegrator1D
  roofit/roofitcore/src/RooSegmentedIntegrator1D.cxx
Labels: affects:6.24, affects:master, bug, in:RooFit/RooStats

#7347 [RF] Do not import data in a RooDataSet if some branches are missing.
  roofit/roofitcore/src/RooTreeDataStore.cxx
Labels: in:RooFit/RooStats

#7473 Fix memory leak in TGraphEdge
  graf2d/gviz/src/TGraphEdge.cxx
Labels: affects:master, bug, in:Graphics

#7272 TGTab: support tab scrolling with mouse wheel
  gui/gui/inc/TGTab.h
  gui/gui/src/TGTab.cxx
Labels: improvement, in:GUI

#7490 Remove fName member from TPaletteAxis class
  hist/histpainter/inc/TPaletteAxis.h
  hist/histpainter/src/TPaletteAxis.cxx
Labels: improvement, in:Graphics

#7487 [DF][NFC] Simplify BoolArray helper class
  tree/dataframe/inc/ROOT/RDF/ActionHelpers.hxx
Labels: pr:backport

#7486 [DF] Remove RResultPtr::Release (an unreleased feature)
  tree/dataframe/inc/ROOT/RResultPtr.hxx
  tree/dataframe/test/dataframe_resptr.cxx
Labels: pr:backport

#7512 [jsroot] 6.24 branch [skip-ci]
  js/scripts/JSRoot.base3d.js
  js/scripts/JSRoot.core.js
  js/scripts/JSRoot.csg.js
  js/scripts/JSRoot.hierarchy.js
  js/scripts/JSRoot.hist3d.js
  js/scripts/JSRoot.interactive.js
  js/scripts/JSRoot.io.js
  js/scripts/JSRoot.jq2d.js
  js/scripts/JSRoot.menu.js
  js/scripts/JSRoot.v7hist3d.js
  js/scripts/JSRoot.webwindow.js
Labels: affects:6.24

#7478 [RF] Fix the integration of a cloned RooParamHistFunc with range
  roofit/roofit/src/RooParamHistFunc.cxx
Labels: bug, in:RooFit/RooStats

#7479 [RF] Fix the integration of a cloned RooParamHistFunc with range
  roofit/roofit/src/RooParamHistFunc.cxx
Labels: bug, in:RooFit/RooStats, pr:backport

#7516 Fix #7435 Canvas in gui_ex.py tutorial does not scale with window size
  tutorials/pyroot/gui_ex.py
Labels: affects:master

#7495 Add context menu to save the page content
  gui/guihtml/inc/TGHtml.h
  gui/guihtml/src/TGHtml.cxx
Labels: improvement, in:GUI

#7511 Add pyspark to requirements.txt, ignore in dependency_versions.py
  bindings/pyroot/pythonizations/test/dependency_versions.py
  requirements.txt
Labels: in:Build System, in:Testing

#7535 Fix TCreatePrimitives::Ellipse for logarithmic axes
  graf2d/gpad/src/TCanvas.cxx
  graf2d/gpad/src/TCreatePrimitives.cxx
  graf2d/gpad/src/TPad.cxx
Labels: affects:master, bug, in:Graphics

#7524 When injecting symbols, do not rely on the last Module:
  interpreter/cling/lib/Interpreter/Interpreter.cpp
Labels: pr:backport

#7551 [jsroot] dev 16/03/2021 [skip-ci]
  js/scripts/JSRoot.base3d.js
  js/scripts/JSRoot.core.js
  js/scripts/JSRoot.geobase.js
  js/scripts/JSRoot.geom.js
  js/scripts/JSRoot.gpad.js
  js/scripts/JSRoot.hierarchy.js
  js/scripts/JSRoot.hist.js
  js/scripts/JSRoot.hist3d.js
  js/scripts/JSRoot.io.js
  js/scripts/JSRoot.jq2d.js
  js/scripts/JSRoot.latex.js
  js/scripts/JSRoot.math.js
  js/scripts/JSRoot.menu.js
  js/scripts/JSRoot.more.js
  js/scripts/JSRoot.openui5.js
  js/scripts/JSRoot.painter.js
  js/scripts/JSRoot.tree.js
  js/scripts/JSRoot.v7gpad.js
  js/scripts/JSRoot.v7hist.js
  js/scripts/JSRoot.v7hist3d.js
  js/scripts/JSRoot.webwindow.js
Labels: bug, improvement

#7546 [DF][skip-ci] Update v6.24 release notes
  README/ReleaseNotes/v624/index.md
Labels: pr:backport

#7549 [relnotes] Updated v6.24 release notes for Cling
  README/ReleaseNotes/v624/index.md
Labels: pr:backport

#7557 Fix TLeaf::GetLeafCounter function
  tree/tree/src/TLeaf.cxx
Labels: affects:6.22, affects:6.24, affects:master, bug, in:TTree

#7574 Fix TLeaf::GetLeafCounter function, 6.22
  tree/tree/src/TLeaf.cxx
Labels: affects:6.22, bug, in:TTree, pr:backport

#7573 Fix TLeaf::GetLeafCounter function, 6.24
  tree/tree/src/TLeaf.cxx
Labels: affects:6.24, bug, in:TTree, pr:backport

#7587 [DF][NFC][skip-ci] Backport major doc improvements to 6.24
  tree/dataframe/src/RDataFrame.cxx
Labels: pr:backport

#7578 [mathcore] Fix memory leak in GausIntegrator
  math/mathcore/src/GaussIntegrator.cxx
Labels: affects:master, bug, in:Math Libraries

#7579 [cmake] Add ROOTVecOps to ROOT_LIBRARIES
  cmake/scripts/ROOTConfig.cmake.in
Labels: pr:backport

#7580 [cmake] Add ROOTVecOps to ROOT_LIBRARIES
  cmake/scripts/ROOTConfig.cmake.in
Labels: pr:backport

#7581 [cmake] Add ROOTVecOps to ROOT_LIBRARIES
  cmake/scripts/ROOTConfig.cmake.in
Labels: pr:backport

#7588 [mathcore] Fix memory leak in GausIntegrator, 6.22
  math/mathcore/src/GaussIntegrator.cxx
Labels: affects:6.22, bug, in:Math Libraries, pr:backport

#7589 [mathcore] Fix memory leak in GausIntegrator, 6.24
  math/mathcore/src/GaussIntegrator.cxx
Labels: affects:6.24, bug, in:Math Libraries, pr:backport

#7577 [gui] fix several clang-tidy issues
  gui/fitpanel/src/TTreeInput.cxx
  gui/ged/src/TAttLineEditor.cxx
  gui/ged/src/TH1Editor.cxx
  gui/ged/src/TStyleManager.cxx
  gui/gui/src/TGApplication.cxx
  gui/gui/src/TGCanvas.cxx
  gui/gui/src/TGFileBrowser.cxx
  gui/gui/src/TGFont.cxx
  gui/gui/src/TGFontDialog.cxx
  gui/gui/src/TGInputDialog.cxx
  gui/gui/src/TGLayout.cxx
  gui/gui/src/TGListBox.cxx
  gui/gui/src/TGListTree.cxx
  gui/gui/src/TGListView.cxx
  gui/gui/src/TGPack.cxx
  gui/gui/src/TGShapedFrame.cxx
  gui/gui/src/TGTable.cxx
  gui/gui/src/TGTextEdit.cxx
  gui/gui/src/TGTextEntry.cxx
  gui/gui/src/TGTextView.cxx
  gui/gui/src/TRootApplication.cxx
  gui/gui/src/TRootBrowserLite.cxx
  gui/gui/src/TRootContextMenu.cxx
  gui/guibuilder/src/TGuiBldDragManager.cxx
  gui/guihtml/src/TGHtmlDraw.cxx
  gui/guihtml/src/TGHtmlIndex.cxx
  gui/guihtml/src/TGHtmlLayout.cxx
  gui/guihtml/src/TGHtmlParse.cxx
  gui/guihtml/src/TGHtmlSizer.cxx
  gui/guihtml/src/TGHtmlTable.cxx
  gui/guihtml/src/TGHtmlUri.cxx
  gui/sessionviewer/src/TProofProgressDialog.cxx
Labels: in:GUI

#7594 [eve7] fix memory leak in REveCalo
  graf3d/eve7/src/REveCalo.cxx
Labels: affects:6.24, affects:master, bug, in:Graphics

#7597 [eve7] fix memory leak in REveCalo, 6.24
  graf3d/eve7/src/REveCalo.cxx
Labels: affects:6.24, bug, in:Graphics, pr:backport

#7600 [cling] Skip non-regular files to find dylibs: [v6.24]
  interpreter/cling/lib/Interpreter/DynamicLibraryManager.cpp
Labels: pr:backport

#7612 [guihtml] add missing strlcpy.h include
  gui/guihtml/src/TGHtmlUri.cxx
Labels: affects:master, bug, improvement

#7606 Fix unwind info relocation with large code model on AArch64 [v6.24]
  interpreter/llvm/src/lib/MC/MCObjectFileInfo.cpp
Labels: pr:backport

#7607 Fix unwind info relocation with large code model on PowerPC and AArch64 [v6.22]
  interpreter/llvm/src/lib/MC/MCObjectFileInfo.cpp
Labels: pr:backport

#7629 [backport][cmake] Do not bind cling's sysroot to a particular version of osx sdk.
  interpreter/cling/lib/Interpreter/CMakeLists.txt
Labels: pr:backport

#6700 [DF] Improve reading collections with RNTuple DS
  tree/dataframe/inc/ROOT/RNTupleDS.hxx
  tree/dataframe/src/RNTupleDS.cxx
  tree/dataframe/test/datasource_ntuple.cxx
  tree/ntuple/v7/inc/ROOT/RField.hxx
  tree/ntuple/v7/inc/ROOT/RNTupleUtil.hxx
  tree/ntuple/v7/src/RField.cxx
  tree/ntuple/v7/test/ntuple_rdf.cxx
Labels: pr:squash on merge

#7608 Fix unwind info relocation with large code model on PowerPC and AArch64 [v6.20]
  interpreter/llvm/src/lib/MC/MCObjectFileInfo.cpp
Labels: pr:backport

#7620 [hist] memory leak with MakeIterator
  hist/hist/src/TLimit.cxx
  hist/unfold/src/TUnfoldBinningXML.cxx
Labels: affects:master, bug

#7628 [backport][cmake] Do not bind cling's sysroot to a particular version of osx sdk.
  interpreter/cling/lib/Interpreter/CMakeLists.txt
Labels: pr:backport

#7647 [jsroot] update 6.24 with many fixes [skip-ci]
  js/changes.md
  js/scripts/JSRoot.base3d.js
  js/scripts/JSRoot.core.js
  js/scripts/JSRoot.geobase.js
  js/scripts/JSRoot.geom.js
  js/scripts/JSRoot.gpad.js
  js/scripts/JSRoot.hierarchy.js
  js/scripts/JSRoot.hist.js
  js/scripts/JSRoot.hist3d.js
  js/scripts/JSRoot.io.js
  js/scripts/JSRoot.jq2d.js
  js/scripts/JSRoot.latex.js
  js/scripts/JSRoot.math.js
  js/scripts/JSRoot.menu.js
  js/scripts/JSRoot.more.js
  js/scripts/JSRoot.openui5.js
  js/scripts/JSRoot.painter.js
  js/scripts/JSRoot.tree.js
  js/scripts/JSRoot.v7gpad.js
  js/scripts/JSRoot.v7hist.js
  js/scripts/JSRoot.v7hist3d.js
  js/scripts/JSRoot.webwindow.js
Labels: affects:6.24, improvement, in:Other

#7648 [jsroot] dev 23/03/2021 [skip-ci]
  js/changes.md
  js/scripts/JSRoot.core.js
  js/scripts/JSRoot.hierarchy.js
  js/scripts/JSRoot.hist.js
  js/scripts/JSRoot.latex.js
  js/scripts/JSRoot.math.js
  js/scripts/JSRoot.more.js
  js/scripts/JSRoot.painter.js
  js/scripts/JSRoot.tree.js
Labels: affects:master, in:Other

#7649 Show RBrowser when TBrowser is invoked in the ROOT
  cmake/modules/RootConfiguration.cmake
  config/rootrc.in
Labels: affects:master, new feature

#7645 [skip-ci] Fix unresolved external symbol errors on Windows
  interpreter/cling/tools/driver/CMakeLists.txt
Labels: in:Cling

#7664 [skip-ci][DF] Add a section about distributed rdf in doxygen page
  tree/dataframe/src/RDataFrame.cxx
Labels: in:Documentation, in:RDataFrame

#7674 [skip-ci][backport][DF] Add a section about distributed rdf in doxygen page
  tree/dataframe/src/RDataFrame.cxx
Labels: pr:backport

#7668 [PyROOT] avoid using wildcard import in pyroot tutorial
  tutorials/pyroot/numberEntry.py
Labels: in:PyROOT

#7694 [rcanvas] fix two issues in GED [skip-ci]
  ui5/canv/controller/Ged.controller.js
Labels: bug, in:GUI

#7679 Correct cycle order in file merging for non-mergeable obj.
  io/io/inc/TFileMerger.h
  io/io/src/TFileMerger.cxx
Labels: affects:master

#7677 [v620][io] Correct cycle order in file merging for non-mergeable obj.
  io/io/src/TFileMerger.cxx
Labels: affects:6.20, in:I/O

#7720 Move useful functionality from argset up to collection base class so …
  roofit/roofitcore/inc/RooAbsCollection.h
  roofit/roofitcore/inc/RooArgSet.h
  roofit/roofitcore/src/RooAbsCollection.cxx
  roofit/roofitcore/src/RooArgSet.cxx
Labels: in:RooFit/RooStats

#7721 Move useful functionality from argset up to collection base class so …
  roofit/roofitcore/inc/RooAbsCollection.h
  roofit/roofitcore/inc/RooArgSet.h
  roofit/roofitcore/src/RooAbsCollection.cxx
  roofit/roofitcore/src/RooArgSet.cxx
Labels: in:RooFit/RooStats

#7716 [v624][io] Correct cycle order in file merging for non-mergeable obj.
  io/io/inc/TFileMerger.h
  io/io/src/TFileMerger.cxx
Labels: affects:6.24, in:I/O

#7717 [v622][io] Correct cycle order in file merging for non-mergeable obj.
  io/io/inc/TFileMerger.h
  io/io/src/TFileMerger.cxx
Labels: affects:6.22, in:I/O

#7691 [jsmva] fix operator precedence [skip-ci]
  etc/notebook/JsMVA/js/DecisionTree.js
  etc/notebook/JsMVA/js/DecisionTree.min.js
Labels: affects:master, bug

#7722 Translated the rf204a_extendedLikelihood.C example script from C++ to Python.
  tutorials/roofit/rf204a_extendedLikelihood.py
Labels: in:RooFit/RooStats

#7705 [DF] Use ImportError for Python2 compatibility
  bindings/experimental/distrdf/python/DistRDF/Backends/Spark/Backend.py
Labels: affects:6.24, affects:master, bug

#7741 [DF] Use ImportError for Python2 compatibility
  bindings/experimental/distrdf/python/DistRDF/Backends/Spark/Backend.py
Labels: pr:backport

#7723 Pythonization for RooAbsReal::plotOn() RooAbsPdf::fitTo() functions.
  bindings/pyroot/pythonizations/python/ROOT/pythonization/_roofit/__init__.py
  bindings/pyroot/pythonizations/python/ROOT/pythonization/_roofit/_roopythonize.py
  bindings/pyroot/pythonizations/test/roofit/rooabsreal_ploton.py
Labels: in:RooFit/RooStats

#7744 [cling] Throw less exceptions on Apple M1:
  interpreter/cling/lib/Interpreter/Exception.cpp
Labels: pr:squash on merge

#7698 [DF] Add first tutorial for distributed rdf
  tutorials/CMakeLists.txt
  tutorials/dataframe/distrdf001_spark_connection.py
Labels: in:PyROOT, in:RDataFrame

#7764 [DF] Add first tutorial for distributed rdf
  tutorials/CMakeLists.txt
  tutorials/dataframe/distrdf001_spark_connection.py
Labels: in:RDataFrame, pr:backport

#7755 Fix the action PushDataCache for TClonesArray.
  io/io/inc/TStreamerInfoActions.h
  io/io/src/TStreamerInfoActions.cxx
  tree/tree/src/TBranchElement.cxx
Labels: affects:master, in:I/O
