Repository root-project/root, pull requests merged in 2022-12, with the labels that each got.

#11824 [webgui] add Net to list of librariy dependency
  gui/webdisplay/CMakeLists.txt
Labels: affects:master, in:Build System, in:WebGui

#11794 RConcurrentHashColl: remove unused (internal) function
  core/thread/inc/ROOT/RConcurrentHashColl.hxx
  core/thread/src/RConcurrentHashColl.cxx
Labels: bug, priority:low

#11834 [RF] Avoid manual memory management in the rs101 tutorial
  tutorials/roostats/rs101_limitexample.C
  tutorials/roostats/rs101_limitexample.py
  tutorials/roostats/rs_numberCountingCombination.C
Labels: bug, in:RooFit/RooStats

#11821 [RF] Make `CutRange()` also consider unselected vars in `RooAbsData::reduce()`
  roofit/roofitcore/src/RooAbsData.cxx
  roofit/roofitcore/src/RooVectorDataStore.cxx
  roofit/roofitcore/test/testRooDataSet.cxx
Labels: bug, in:RooFit/RooStats

#11840 [RF] Fix nWorker setting in RooMinimizer input config
  roofit/roofitcore/src/RooMinimizer.cxx
Labels: in:RooFit/RooStats

#11763 Avoid TPad::fFrame double delete when read from file
  graf2d/gpad/src/TPad.cxx
Labels: bug, affects:master, in:Core Libraries, in:I/O, affects:6.26

#11849 v6-26: Avoid TPad::fFrame double delete when read from file
  tree/treeplayer/src/TTreeReaderArray.cxx
Labels: affects:6.26

#11846 [cmake] Switch CMP0135 to OLD:
  CMakeLists.txt
  cmake/modules/SearchInstalledSoftware.cmake
Labels: pr:backport

#11862 Avoid leaking TBaskets in Bulk I/O operations
  tree/tree/src/TBranch.cxx
Labels: affects:master, priority:critical, in:TTree

#11871 [relnotes][skip-ci] Update release notes for the upcoming v6.28 release
  README/ReleaseNotes/v628/index.md
Labels: in:Documentation

#11889 Fix physical volume names in GDML, which must be globally unique
  geom/gdml/src/TGDMLWrite.cxx
Labels: improvement, affects:master, in:Geometry

#11887 Remove default argument for creating GDML positions.
  geom/gdml/inc/TGDMLWrite.h
  geom/gdml/src/TGDMLWrite.cxx
Labels: bug, affects:master, in:Geometry

#11886 Allow users to ignore material 'dummy', which is not understood by Geant4
  geom/gdml/inc/TGDMLWrite.h
  geom/gdml/src/TGDMLWrite.cxx
Labels: affects:master, in:Geometry

#11896 [RF] Technical improvements to `RooWorkspace`-related helper classes
  roofit/roofitcore/inc/LinkDef.h
  roofit/roofitcore/inc/RooClassFactory.h
  roofit/roofitcore/inc/RooCustomizer.h
  roofit/roofitcore/inc/RooSimWSTool.h
  roofit/roofitcore/src/RooClassFactory.cxx
  roofit/roofitcore/src/RooCustomizer.cxx
  roofit/roofitcore/src/RooSimWSTool.cxx
Labels: in:RooFit/RooStats

#11888 GDML: Fix material properties
  geom/gdml/src/TGDMLParse.cxx
  geom/gdml/src/TGDMLWrite.cxx
Labels: affects:master, in:Geometry

#11906 [RF] Minor interface changes for TestStatistics classes
  roofit/roofitcore/inc/RooAbsPdf.h
  roofit/roofitcore/inc/RooGlobalFunc.h
  roofit/roofitcore/inc/RooMinimizer.h
  roofit/roofitcore/src/RooAbsPdf.cxx
  roofit/roofitcore/src/RooGlobalFunc.cxx
  roofit/roofitcore/src/RooMinimizer.cxx
  roofit/roofitcore/test/TestStatistics/testInterface.cpp
  roofit/roofitcore/test/TestStatistics/testLikelihoodGradientJob.cpp
  roofit/roofitcore/test/TestStatistics/testPlot.cpp
Labels: in:RooFit/RooStats

#11910 [rbrowser] use default draw options for `TH1` and `TProfile`
  gui/browsable/src/TObjectElement.cxx
  ui5/browser/controller/Browser.controller.js
Labels: affects:master, in:WebGui

#11791 [RF] ProcessTimer for logging timings in `RooFit::MultiProcess` and `RooFit::TestStatistics`, and HeatmapAnalyzer for analysing them
  roofit/multiprocess/CMakeLists.txt
  roofit/multiprocess/inc/RooFit/MultiProcess/Config.h
  roofit/multiprocess/inc/RooFit/MultiProcess/HeatmapAnalyzer.h
  roofit/multiprocess/res/RooFit/MultiProcess/ProcessTimer.h
  roofit/multiprocess/src/Config.cxx
  roofit/multiprocess/src/HeatmapAnalyzer.cxx
  roofit/multiprocess/src/ProcessManager.cxx
  roofit/multiprocess/src/ProcessTimer.cxx
  roofit/multiprocess/src/worker.cxx
  roofit/multiprocess/test/CMakeLists.txt
  roofit/multiprocess/test/test_HeatmapAnalyzer.cxx
  roofit/multiprocess/test/test_ProcessTimer.cxx
  roofit/multiprocess/test/test_logs/p_0.json
  roofit/multiprocess/test/test_logs/p_1.json
  roofit/multiprocess/test/test_logs/p_999.json
  roofit/roofitcore/inc/RooAbsPdf.h
  roofit/roofitcore/inc/RooGlobalFunc.h
  roofit/roofitcore/inc/RooMinimizer.h
  roofit/roofitcore/src/RooAbsPdf.cxx
  roofit/roofitcore/src/RooGlobalFunc.cxx
  roofit/roofitcore/src/RooMinimizer.cxx
  roofit/roofitcore/src/TestStatistics/LikelihoodGradientJob.cxx
  roofit/roofitcore/src/TestStatistics/RooSumL.cxx
Labels: new feature, in:RooFit/RooStats

#11911 Update `geom/geodemo.C` and `geom/csgdemo.C` tutorials [skip-ci]
  tutorials/geom/csgdemo.C
  tutorials/geom/geodemo.C
Labels: affects:master, in:Geometry

#4015 [RF] Add new `RooExpPoly` and `RooPower` PDFs
  documentation/doxygen/images/RooExpPoly.png
  documentation/doxygen/images/RooPower.png
  roofit/roofit/CMakeLists.txt
  roofit/roofit/inc/LinkDef1.h
  roofit/roofit/inc/RooExpPoly.h
  roofit/roofit/inc/RooPower.h
  roofit/roofit/src/RooExpPoly.cxx
  roofit/roofit/src/RooPower.cxx
Labels: new feature, in:RooFit/RooStats

#11909 [RF] Make old test statistic classes transient with `ClassDef(0)`
  roofit/roofitcore/inc/RooAbsOptTestStatistic.h
  roofit/roofitcore/inc/RooAbsTestStatistic.h
  roofit/roofitcore/inc/RooChi2Var.h
  roofit/roofitcore/inc/RooDataWeightedAverage.h
  roofit/roofitcore/inc/RooNLLVar.h
  roofit/roofitcore/inc/RooXYChi2Var.h
Labels: in:RooFit/RooStats

#11851 [RF] Add xRooFit to ROOT
  README/ReleaseNotes/v628/RooBrowser.png
  README/ReleaseNotes/v628/index.md
  documentation/doxygen/images/RooBrowser.png
  roofit/CMakeLists.txt
  roofit/xroofit/CMakeLists.txt
  roofit/xroofit/inc/LinkDef.h
  roofit/xroofit/inc/RooBrowser.h
  roofit/xroofit/inc/RooFit/xRooFit/xRooBrowser.h
  roofit/xroofit/inc/RooFit/xRooFit/xRooFit.h
  roofit/xroofit/inc/RooFit/xRooFit/xRooHypoSpace.h
  roofit/xroofit/inc/RooFit/xRooFit/xRooNLLVar.h
  roofit/xroofit/inc/RooFit/xRooFit/xRooNode.h
  roofit/xroofit/src/Asymptotics.cxx
  roofit/xroofit/src/Banner.cxx
  roofit/xroofit/src/coutCapture.h
  roofit/xroofit/src/xRooBrowser.cxx
  roofit/xroofit/src/xRooFit
  roofit/xroofit/src/xRooFit.cxx
  roofit/xroofit/src/xRooFitVersion.h
  roofit/xroofit/src/xRooHypoSpace.cxx
  roofit/xroofit/src/xRooNLLVar.cxx
  roofit/xroofit/src/xRooNode.cxx
  roofit/xroofit/src/xRooNode_interactive.cxx
Labels: new feature, in:RooFit/RooStats

#11917 [RF] Add missing `XROOFIT_NAMESPACE` definition
  roofit/xroofit/inc/RooBrowser.h
Labels: in:RooFit/RooStats

#11918 [RF] Officially deprecate RooMinuit
  roofit/roofitcore/inc/LinkDef.h
  roofit/roofitcore/inc/RooFitLegacy/RooMinuit.h
  roofit/roofitcore/inc/RooMinuit.h
  roofit/roofitcore/src/RooFitLegacy/RooMinuit.cxx
Labels: in:RooFit/RooStats

#11919 [RF] Make RooSentinel and RooMPSentinel private implementation details
  roofit/roofitcore/CMakeLists.txt
  roofit/roofitcore/inc/LinkDef.h
  roofit/roofitcore/inc/RooMPSentinel.h
  roofit/roofitcore/inc/RooRealMPFE.h
  roofit/roofitcore/src/RooFitLegacy/RooMinuit.cxx
  roofit/roofitcore/src/RooMPSentinel.cxx
  roofit/roofitcore/src/RooRealMPFE.cxx
  roofit/roofitcore/src/RooSentinel.h
Labels: in:RooFit/RooStats

#11929 [geo] fix TGeoManagerEditor::LoadLib
  geom/geombuilder/inc/TGeoManagerEditor.h
  geom/geombuilder/src/TGeoManagerEditor.cxx
Labels: affects:master, in:Geometry

#11926 [jsroot] fix TGeo update in TWebCanvas [skip-ci]
  js/build/jsroot.js
  js/changes.md
  js/modules/core.mjs
  js/modules/geom/TGeoPainter.mjs
Labels: affects:master, in:WebGui

#11939 [RF] New `Offset("bin")` command argument for createNLL
  roofit/roofitcore/inc/RooGlobalFunc.h
  roofit/roofitcore/inc/RooNLLVar.h
  roofit/roofitcore/src/BatchModeHelpers.cxx
  roofit/roofitcore/src/RooAbsPdf.cxx
  roofit/roofitcore/src/RooFit/BatchModeHelpers.h
  roofit/roofitcore/src/RooGlobalFunc.cxx
  roofit/roofitcore/src/RooNLLVar.cxx
  roofit/roofitcore/src/RooNLLVarNew.cxx
  roofit/roofitcore/src/RooNLLVarNew.h
Labels: new feature, in:RooFit/RooStats

#11928 [tmvagui] Fix snprintf warning:
  tmva/tmvagui/src/rulevisCorr.cxx
  tmva/tmvagui/src/rulevisHists.cxx
Labels: pr:backport

#11952 [RF] Remove deprecated RooFit parts that are marked for removal in 6.30
  roofit/roofitcore/CMakeLists.txt
  roofit/roofitcore/inc/RooAbsData.h
  roofit/roofitcore/inc/RooFitLegacy/RooMinuit.h
  roofit/roofitcore/inc/RooFitResult.h
  roofit/roofitcore/inc/RooMinuit.h
  roofit/roofitcore/src/RooAbsData.cxx
  roofit/roofitcore/src/RooFitLegacy/RooMinuit.cxx
  roofit/roostats/inc/RooStats/FeldmanCousins.h
  roofit/roostats/inc/RooStats/NeymanConstruction.h
Labels: in:RooFit/RooStats
