Repository root-project/root, pull requests merged in 2022-11, with the labels that each got.

#11625 [TMVA][SOFIE] Fix infer function input tensors order
  tmva/sofie/src/RModel.cxx
  tmva/sofie/test/TestCustomModelsFromONNX.cxx
Labels: in:TMVA

#11527 [ACLiC] For macOS, make sure the syslib exists:
  core/metacling/src/TCling.cxx
Labels: in:Core Libraries

#11666 [ACLiC] For macOS, make sure the syslib exists (v6.26)
  core/metacling/src/TCling.cxx
Labels: pr:backport

#11670 [skip-ci] wrong variable was tested in Makefile
  documentation/doxygen/Makefile
Labels: bug, affects:master, in:Documentation

#11669 [RF] Always clone constraint term in `createNLL`
  roofit/roofitcore/src/BatchModeHelpers.cxx
  roofit/roofitcore/src/ConstraintHelpers.cxx
  roofit/roofitcore/src/RooAbsPdf.cxx
Labels: in:RooFit/RooStats

#11641 [TMVA ][SOFIE] Register operators in the constructor of RModelParser_ONNX
  tmva/sofie_parsers/src/RModelParser_ONNX.cxx
Labels: in:TMVA

#11676 Use `const char *` as return type for `TPave::GetName()` method
  graf2d/graf/inc/TPave.h
Labels: affects:master, in:Graphics

#11674 [ntuple] Make `RNTupleWriter::Fill()` return the number of uncompressed bytes written
  tree/ntuple/v7/inc/ROOT/RNTuple.hxx
Labels: improvement, in:RNTuple

#11684 [v6-26] Fix CMake error with the latest version of Arrow
  cmake/modules/FindArrow.cmake
  cmake/modules/SearchInstalledSoftware.cmake
Labels: pr:backport

#11685 [PyROOT] Enclose tuple unpacking in return statement with parenthesis
  bindings/pyroot/pythonizations/python/ROOT/_pythonization/_rdf_pyz.py
Labels: in:PyROOT

#11687 Add Rint as a dependency of rootcling
  main/CMakeLists.txt
Labels: bug, affects:master, affects:6.22, affects:6.20, affects:6.18, priority:default, in:Build System, affects:6.24, affects:6.26

#11693 [v626][cmake] Xcode 14 warns about `-undefined dynamic_lookup`; simply suppress:
  bindings/jupyroot/CMakeLists.txt
  bindings/pyroot/cppyy/CPyCppyy/CMakeLists.txt
  bindings/pyroot/pythonizations/CMakeLists.txt
  core/metacling/src/CMakeLists.txt
  interpreter/cling/tools/plugins/example/CMakeLists.txt
  montecarlo/pythia6/CMakeLists.txt
Labels: pr:backport

#11700 [cmake] Suppress all warnings compiling builtin-zstd:
  builtins/zstd/CMakeLists.txt
Labels: pr:backport

#11692 Adjust TStyle::SavePrimitve
  core/base/src/TStyle.cxx
Labels: affects:master, in:Graphics

#11683 [ntuple,daos] Add missing attribute to IOD structure mock definition
  tree/ntuple/v7/inc/ROOT/libdaos_mock/daos.h
Labels: in:RNTuple

#11706 [cmake] refine find arrow condition
  cmake/modules/FindArrow.cmake
Labels: affects:master, in:Build System

#11708 [cmake] refine find arrow condition [6.26]
  cmake/modules/FindArrow.cmake
Labels: pr:backport, in:Build System, affects:6.26

#11739 Provide plugin for RTreeViewer
  config/rootrc.in
  core/base/src/TApplication.cxx
  etc/plugins/TVirtualTreeViewer/P010_TTreeViewer.C
  etc/plugins/TVirtualTreeViewer/P020_RTreeViewer.C
  proof/proof/src/TDSet.cxx
  tree/treeplayer/src/TTreePlayer.cxx
  tree/webviewer/inc/ROOT/RTreeViewer.hxx
  tree/webviewer/src/RTreeViewer.cxx
Labels: affects:master, in:GUI, in:WebGui

#11742 [cmake] Tell CMake >= 3.24 to use tared timestamps:
  cmake/modules/SearchInstalledSoftware.cmake
Labels: affects:master, in:Build System

#11753 [ntuple] Add RNTupleUtil standard library
  tree/CMakeLists.txt
  tree/ntupleutil/CMakeLists.txt
  tree/ntupleutil/inc/LinkDef.h
  tree/ntupleutil/v7/inc/ROOT/RNTupleImporter.hxx
  tree/ntupleutil/v7/src/RNTupleImporter.cxx
  tree/ntupleutil/v7/test/CMakeLists.txt
  tree/ntupleutil/v7/test/ntuple_importer.cxx
Labels: in:RNTuple

#11766 Provide json_fwd.hpp for nlohmann 3.9.1 [6.26]
  builtins/nlohmann/CMakeLists.txt
  builtins/nlohmann/json_fwd.hpp
Labels: in:Build System, affects:6.26

#11716 [RF] remove RooGradMinimizerFcn and simplify RooMinimizer configuration
  roofit/roofitcore/CMakeLists.txt
  roofit/roofitcore/src/RooGradMinimizerFcn.cxx
  roofit/roofitcore/src/RooGradMinimizerFcn.h
  roofit/roofitcore/src/RooMinimizer.cxx
  roofit/roofitcore/src/TestStatistics/MinuitFcnGrad.cxx
  roofit/roofitcore/test/CMakeLists.txt
  roofit/roofitcore/test/TestStatistics/testLikelihoodGradientJob.cpp
  roofit/roofitcore/test/testRooGradMinimizerFcn.cxx
Labels: in:RooFit/RooStats

#11696 [RF] Use of proxy norm sets in RooRealIntegral and RooGenProdProj
  roofit/roofitcore/inc/RooRealIntegral.h
  roofit/roofitcore/src/RooGenProdProj.cxx
  roofit/roofitcore/src/RooRealIntegral.cxx
  roofit/roofitcore/test/testRooRealIntegral.cxx
Labels: bug, in:RooFit/RooStats

#11698 [RF] Account for mutation of client list within `sterilizeClientCaches`
  roofit/roofitcore/src/RooAbsPdf.cxx
Labels: bug, in:RooFit/RooStats

#11774 [RF] Improve RooVoigtian documentation
  roofit/roofit/inc/RooVoigtian.h
  roofit/roofit/src/RooVoigtian.cxx
Labels: improvement, in:RooFit/RooStats

#11777 [RF] Don't use RooGenericPdf for pull fitting in RooMCStudy
  roofit/roofitcore/inc/RooAbsMCStudyModule.h
  roofit/roofitcore/inc/RooMCStudy.h
  roofit/roofitcore/src/RooMCStudy.cxx
Labels: improvement, in:RooFit/RooStats

#11764 TTask: don't assume that the list only contains TTask objects
  core/base/src/TTask.cxx
Labels: improvement, affects:master

#11752 [cmake] Tell CMake >= 3.24 to use tared timestamps:
  cmake/modules/SearchInstalledSoftware.cmake
Labels: in:Build System

#11789 [Geom] Fix behaviour of locking default units
  geom/geom/src/TGeoManager.cxx
Labels: bug, in:Geometry

#11788 [Geom] Skip overlap checking if a partner is a tessellated shape.
  geom/geompainter/src/TGeoChecker.cxx
Labels: bug, in:Geometry

#11790 [Geom] Update VecGeom header paths to post version 1.2.
  cmake/modules/SearchInstalledSoftware.cmake
  geom/vecgeom/src/TGeoVGShape.cxx
Labels: bug, in:Geometry

#11556 MakeProject: workaound deficiency in gcc 11.2 warning
  io/io/src/TStreamerInfo.cxx
Labels: affects:master

#11627 [RF] Add PriorityQueue in MultiProcess
  roofit/multiprocess/CMakeLists.txt
  roofit/multiprocess/inc/RooFit/MultiProcess/Config.h
  roofit/multiprocess/inc/RooFit/MultiProcess/types.h
  roofit/multiprocess/res/RooFit/MultiProcess/JobManager.h
  roofit/multiprocess/res/RooFit/MultiProcess/Queue.h
  roofit/multiprocess/src/Config.cxx
  roofit/multiprocess/src/FIFOQueue.cxx
  roofit/multiprocess/src/FIFOQueue.h
  roofit/multiprocess/src/JobManager.cxx
  roofit/multiprocess/src/PriorityQueue.cxx
  roofit/multiprocess/src/PriorityQueue.h
  roofit/multiprocess/src/Queue.cxx
  roofit/multiprocess/test/CMakeLists.txt
  roofit/multiprocess/test/NoopJob.h
  roofit/multiprocess/test/OrderTrackingJob.h
  roofit/multiprocess/test/test_Job.cxx
  roofit/multiprocess/test/test_Queue.cxx
  roofit/roofitcore/src/TestStatistics/LikelihoodGradientJob.cxx
  roofit/roofitcore/src/TestStatistics/LikelihoodJob.cxx
Labels: improvement, in:RooFit/RooStats

#11802 [RF] MultiProcess test_Queue.cxx compile warning fix
  roofit/multiprocess/test/test_Queue.cxx
Labels: in:RooFit/RooStats

#11801 [Geom] GDML parser warns about entities missing a unit definition.
  geom/gdml/inc/TGDMLParse.h
  geom/gdml/src/TGDMLParse.cxx
Labels: improvement, in:Geometry

#11776 Improve ListLibraries
  core/base/inc/TSystem.h
  core/base/src/TSystem.cxx
  core/unix/inc/TUnixSystem.h
Labels: improvement, in:Core Libraries
