Repository root-project/root, pull requests merged in 2022-10, with the labels that each got.

#11285 [tree] Add missing `override` specifiers in tree/dataframe
  tree/dataframe/inc/ROOT/RArrowDS.hxx
  tree/dataframe/inc/ROOT/RCsvDS.hxx
  tree/dataframe/inc/ROOT/RDF/RDefinePerSample.hxx
  tree/dataframe/inc/ROOT/RDF/RFilter.hxx
  tree/dataframe/inc/ROOT/RDF/RFilterBase.hxx
  tree/dataframe/inc/ROOT/RDF/RJittedAction.hxx
  tree/dataframe/inc/ROOT/RDF/RJittedFilter.hxx
  tree/dataframe/inc/ROOT/RDF/RJittedVariation.hxx
  tree/dataframe/inc/ROOT/RDF/RLazyDSImpl.hxx
  tree/dataframe/inc/ROOT/RDF/RLoopManager.hxx
  tree/dataframe/inc/ROOT/RDF/RRange.hxx
  tree/dataframe/inc/ROOT/RDF/RRangeBase.hxx
  tree/dataframe/inc/ROOT/RDF/RTreeColumnReader.hxx
  tree/dataframe/inc/ROOT/RDF/RVariation.hxx
  tree/dataframe/inc/ROOT/RDF/RVariedAction.hxx
  tree/dataframe/inc/ROOT/RDataSource.hxx
  tree/dataframe/inc/ROOT/RRootDS.hxx
  tree/dataframe/inc/ROOT/RTrivialDS.hxx
  tree/dataframe/src/RNTupleDS.cxx
  tree/dataframe/test/RNonCopiableColumnDS.hxx
  tree/dataframe/test/dataframe_definepersample.cxx
  tree/dataframe/test/dataframe_regression.cxx
  tree/dataframe/test/dataframe_samplecallback.cxx
Labels: in:RDataFrame

#11475 [RF] Fix tutorial for `RooStats::SPlot`
  tutorials/roostats/rs301_splot.C
Labels: bug, in:RooFit/RooStats

#11477 [RF] Make no distinction in VectorDataStore between `get` and getNative
  roofit/roofitcore/inc/RooVectorDataStore.h
  roofit/roofitcore/src/RooVectorDataStore.cxx
  roofit/roofitcore/test/CMakeLists.txt
  roofit/roofitcore/test/testTestStatistics.cxx
Labels: bug, in:RooFit/RooStats

#11399 [skip-ci] Small updates to RDF docs
  tree/dataframe/src/RDataFrame.cxx
Labels: in:RDataFrame

#11444 TString sanity check nchar not larger than capacity
  core/base/src/TString.cxx
Labels: bug, in:Core Libraries

#11490 Add missing import to TMVA pythonizations
  bindings/pyroot/pythonizations/python/ROOT/_pythonization/_tmva/__init__.py
Labels: priority:critical

#11468 gcc12's regex header file relies on a std::vector<int> instance, export it
  interpreter/cling/include/cling/std.modulemap
Labels: in:C++ modules

#11398 Respect the user-provided number of entries to be displayed
  tree/dataframe/inc/ROOT/RDF/ActionHelpers.hxx
  tree/dataframe/inc/ROOT/RDF/InterfaceUtils.hxx
  tree/dataframe/inc/ROOT/RDF/RDisplay.hxx
  tree/dataframe/inc/ROOT/RDF/RInterface.hxx
  tree/dataframe/src/RDFDisplay.cxx
  tree/dataframe/test/dataframe_display.cxx
Labels: in:RDataFrame

#11497 Number of rows to display is size_t
  tree/dataframe/inc/ROOT/RDF/ActionHelpers.hxx
  tree/dataframe/inc/ROOT/RDF/InterfaceUtils.hxx
  tree/dataframe/inc/ROOT/RDF/RInterface.hxx
Labels: in:RDataFrame

#11507 [RF] Fix copy-paste error in `RooDataSet::binnedClone`
  roofit/roofitcore/src/RooDataSet.cxx
Labels: new contributor, bug, in:RooFit/RooStats

#11501 Add support for Bulk I/O with SetClusterPrefetch
  tree/tree/inc/TBranch.h
  tree/tree/src/TBranch.cxx
Labels: affects:master, priority:high, in:TTree

#11535 fix display of items in TBrowser that have a checkbox on MAC
  gui/gui/src/TGListTree.cxx
Labels: bug, in:GUI

#11542 [v6.26][backport] Fix display of items in TBrowser that have checkbox against them on MAC (with cocoa)
  gui/gui/src/TGListTree.cxx
Labels: pr:backport

#11536 TPaletteAxis menu update
  hist/histpainter/inc/TPaletteAxis.h
  hist/histpainter/src/TPaletteAxis.cxx
Labels: improvement, in:Graphics

#11543 [v6.24][backport] fix display of items in TBrowser that have checkbox against them on MAC (with cocoa)
  gui/gui/src/TGListTree.cxx
Labels: pr:backport

#10616 [RF] Remove HybridCalculatorOriginal and HypoTestInverterOriginal
  README/ReleaseNotes/v628/index.md
  roofit/roostats/CMakeLists.txt
  roofit/roostats/inc/LinkDef.h
  roofit/roostats/inc/RooStats/HybridCalculatorOriginal.h
  roofit/roostats/inc/RooStats/HypoTestInverterOriginal.h
  roofit/roostats/inc/RooStats/HypoTestInverterResult.h
  roofit/roostats/src/HybridCalculatorOriginal.cxx
  roofit/roostats/src/HypoTestInverterOriginal.cxx
  tutorials/roostats/HybridOriginalDemo.C
  tutorials/roostats/rs801_HypoTestInverterOriginal.C
Labels: in:RooFit/RooStats

#11555 [RF] Don't use redundant `RooPlot::findObject()` in RooFit tutorials
  tutorials/roofit/rf612_recoverFromInvalidParameters.C
  tutorials/roofit/rf612_recoverFromInvalidParameters.py
  tutorials/roofit/rf710_roopoly.py
  tutorials/roofit/rf711_lagrangianmorph.C
  tutorials/roofit/rf711_lagrangianmorph.py
Labels: improvement, in:RooFit/RooStats

#11506 cmake: Replace ever expanding modules_idx_deps cached variable
  CMakeLists.txt
  cmake/modules/RootMacros.cmake
Labels: pr:squash on merge, affects:master, in:Build System, in:Cling

#11551 Fix ROOT-7462 with libstdc++ >= 10
  interpreter/llvm/src/tools/clang/lib/Sema/SemaExpr.cpp
Labels: in:Cling

#11560 Fix ROOT-7462 with libstdc++ >= 10 [v6.26]
  interpreter/llvm/src/tools/clang/lib/Sema/SemaExpr.cpp
Labels: pr:backport

#11564 [sofie] fix compiler override warnings
  tmva/sofie/inc/TMVA/ROperator_BasicBinary.hxx
Labels: affects:master, in:TMVA, pr:emergency🚨

#11559 [RF] Remove `RooSimPdfBuilder` that was deprecated since ROOT 5.20
  README/ReleaseNotes/v628/index.md
  roofit/roofitcore/CMakeLists.txt
  roofit/roofitcore/inc/LinkDef.h
  roofit/roofitcore/inc/RooSimPdfBuilder.h
  roofit/roofitcore/src/RooSimPdfBuilder.cxx
  roofit/roofitcore/test/CMakeLists.txt
  roofit/roofitcore/test/testRooSimPdfBuilder.cxx
Labels: in:RooFit/RooStats

#11584 [RF] Remove error in `RooWorkspace::getSnapshot()` if no snapshot found
  roofit/roofitcore/src/RooWorkspace.cxx
Labels: improvement, in:RooFit/RooStats

#11589 [6.26] [core] Guard gInterpreterMutex in TClingClassInfo::IsEnum
  core/metacling/src/TClingClassInfo.cxx
Labels: pr:backport

#11607 Fix CMake complaint about mis-matching arguments
  cmake/modules/RootBuildOptions.cmake
Labels: in:Build System

#11609 [RF] Veto `.py` tutorial tests of RooStats and HistFactory if ROOT is built without `roofit`
  tutorials/CMakeLists.txt
Labels: bug, in:RooFit/RooStats

#11610 [RF][PyROOT] Move RooFit pythonization tests from roottest to main repo
  bindings/pyroot/pythonizations/test/CMakeLists.txt
  bindings/pyroot/pythonizations/test/roofit/rooabscollection.py
  bindings/pyroot/pythonizations/test/roofit/roodataset.py
  bindings/pyroot/pythonizations/test/roofit/rooglobalfunc.py
Labels: bug, in:PyROOT, in:RooFit/RooStats

#11514 [cxxmodules] Avoid lookup from system headers
  core/metacling/src/TClingCallbacks.cxx
Labels: in:Cling

#11615 [cmake] Update XRootD to v5.5.1
  builtins/xrootd/CMakeLists.txt
Labels: pr:backport

#11281 clarify that TGaxis func is inverted
  graf2d/graf/src/TGaxis.cxx
Labels: in:Graphics

#11324 Typo
  graf2d/graf/src/TGaxis.cxx
Labels: in:Documentation

#11649 [v6.24][backport] Fix datasource_arrow.cxx test
  tree/dataframe/test/datasource_arrow.cxx
Labels: pr:backport
