Repository root-project/root, pull requests merged in 2023-10, with the labels that each got.

#13782 Fix potential crash of the rreader test on Windows
  tmva/tmva/test/rreader.cxx
Labels: in:TMVA

#13781 Add RDefinePerSample to CMakeLists.txt
  tree/dataframe/CMakeLists.txt
Labels: in:RDataFrame

#13614 [cling] Emit const variables only once
  interpreter/cling/test/CodeGeneration/const.C
  interpreter/llvm-project/clang/lib/AST/ASTContext.cpp
  interpreter/llvm-project/llvm-project.tag
  interpreter/llvm-project/llvm/lib/ExecutionEngine/Orc/LLJIT.cpp
Labels: in:Cling

#13789 [6.28] Add RDefinePerSample to CMakeLists.txt
  tree/dataframe/CMakeLists.txt
Labels: pr:backport

#13795 [cling] Emit const variables only once [v6.28]
  interpreter/cling/test/CodeGeneration/const.C
  interpreter/llvm/src/lib/ExecutionEngine/Orc/LLJIT.cpp
  interpreter/llvm/src/tools/clang/lib/AST/ASTContext.cpp
Labels: pr:backport, in:Cling

#13802 [jupyter] correctly handle %jsroot off command
  bindings/jupyroot/python/JupyROOT/helpers/utils.py
Labels: affects:master, in:Notebooks

#13427 [RF] Restore FlexibleInterpVar interpolation for interpCode=4
  roofit/histfactory/src/FlexibleInterpVar.cxx
  roofit/histfactory/src/PiecewiseInterpolation.cxx
  roofit/roofitcore/inc/RooFit/Detail/EvaluateFuncs.h
Labels: in:RooFit/RooStats

#13807 Backport in 6.28 fixes in pymva to avoid timeout in keras tests
  tmva/pymva/src/MethodPyKeras.cxx
  tmva/pymva/src/PyMethodBase.cxx
  tmva/tmva/src/DataSetInfo.cxx
  tmva/tmva/src/MethodBase.cxx
Labels: pr:backport, in:TMVA

#13810 [jsroot] version 7.5.0 5/10/2023 [skip-ci]
  js/build/jsroot.js
  js/changes.md
  js/modules/core.mjs
  js/modules/draw.mjs
Labels: affects:master, in:WebGui

#13642 [ntuple] add RFieldBase::RValue::Release()
  tree/ntuple/v7/inc/ROOT/RField.hxx
Labels: in:RNTuple

#13823 [CMake] Update Vc version to 1.4.4
  cmake/modules/SearchInstalledSoftware.cmake
Labels: affects:master, in:Build System

#13836 [Backport][TMVA] Fix unused variable warnings
  tmva/tmva/inc/TMVA/DNN/Architectures/Cpu/CpuTensor.h
Labels: pr:backport

#13589 [ntuple] fix printing storage details for alias columns
  tree/ntuple/v7/src/RNTupleDescriptorFmt.cxx
  tree/ntuple/v7/test/ntuple_print.cxx
Labels: in:RNTuple

#13841 [cling] Handle length modifiers in IsClassOrFunction
  interpreter/cling/lib/Utils/SourceNormalization.cpp
  interpreter/cling/test/Prompt/DontWrap.C
Labels: in:Cling

#13784 [RF] Fix `xroofit` bugs in breakdown,impact,and error on histograms of RooRealSumPdf
  roofit/xroofit/src/xRooHypoSpace.cxx
  roofit/xroofit/src/xRooNLLVar.cxx
  roofit/xroofit/src/xRooNode.cxx
Labels: in:RooFit/RooStats

#13853 [RF] Use `TAxis::FindBin()` to determine bin offsets for TH1 import
  roofit/roofitcore/inc/RooBinning.h
  roofit/roofitcore/src/RooBinning.cxx
  roofit/roofitcore/src/RooDataHist.cxx
Labels: in:RooFit/RooStats

#7812 [math] Fix inconsistent behaviour of TFormula parameter functions
  hist/hist/inc/TF1.h
  hist/hist/inc/TFormula.h
  hist/hist/src/TF1.cxx
  hist/hist/src/TFormula.cxx
Labels: improvement, in:Math Libraries

#13862 [cmake] Remove `mlp` build option
  .github/workflows/root-ci-config/buildconfig/global.txt
  cmake/modules/RootBuildOptions.cmake
  cmake/modules/SearchInstalledSoftware.cmake
  math/CMakeLists.txt
  tutorials/CMakeLists.txt
Labels: in:Build System

#13859 [clang] Fix crash with constexpr destructor
  interpreter/llvm-project/clang/lib/AST/ExprConstant.cpp
  interpreter/llvm-project/llvm-project.tag
Labels: in:Cling

#13793 Add the `TWebFile::Close(Option_t *option)` method
  net/net/inc/TWebFile.h
  net/net/src/TWebFile.cxx
Labels: pr:backport

#13874 [clang] Fix crash with constexpr destructor [v6.30]
  interpreter/llvm-project/clang/lib/AST/ExprConstant.cpp
  interpreter/llvm-project/llvm-project.tag
Labels: pr:backport, in:Cling

#13881 [RF] Remove unused `JSONTool` entry in the LinkDef file
  roofit/hs3/LinkDef.h
Labels: in:RooFit/RooStats

#13879 [cmake] Don't check `minuit2` option before `ROOT_APPLY_OPTIONS()`
  cmake/modules/RootBuildOptions.cmake
Labels: bug, in:Build System

#13619 [Cling] Simplify std::tuple value printer
  interpreter/cling/include/cling/Interpreter/RuntimePrintValue.h
Labels: in:Cling

#13882 [clang] Fix crash with constexpr destructor [v6.28]
  interpreter/llvm/src/tools/clang/lib/AST/ExprConstant.cpp
Labels: pr:backport, in:Cling

#7539 [cmake] Build only the library of the xrootd client
  builtins/xrootd/CMakeLists.txt
Labels: in:Build System

#5361 [PyROOT] Add test for implicit import from the ROOT namespace
  bindings/pyroot/pythonizations/test/root_module.py
Labels: improvement

#13893 [jsroot] 7.5.1 18/10/2023 [6.30][skip-ci]
  js/build/jsroot.js
  js/changes.md
  js/modules/base/latex.mjs
  js/modules/core.mjs
  js/modules/draw.mjs
  js/modules/gpad/RAxisPainter.mjs
  js/modules/gpad/TAxisPainter.mjs
  js/modules/gui/HierarchyPainter.mjs
  js/modules/hist2d/THistPainter.mjs
Labels: in:WebGui, affects:6.30

#13872 [webcanvas] make default off for the TWebCanvas [6.30]
  cmake/modules/RootConfiguration.cmake
  core/base/src/TROOT.cxx
  gui/gui/src/TRootGuiFactory.cxx
Labels: in:Graphics, affects:6.30

#13887 [Cling][Backport] Simplify tuple value printer
  interpreter/cling/include/cling/Interpreter/RuntimePrintValue.h
Labels: pr:backport, improvement

#13901 [Backport][PyROOT] Value printing: jit once per type
  bindings/pyroot/pythonizations/src/GenericPyz.cxx
  bindings/pyroot/pythonizations/test/pretty_printing.py
Labels: pr:backport

#13898 [Backport] [PyROOT] Speedup inclusion of ROOT module
  bindings/pyroot/pythonizations/python/ROOT/_facade.py
  bindings/pyroot/pythonizations/python/ROOT/_pythonization/_tmva/__init__.py
Labels: pr:backport, in:PyROOT

#13905 [PyROOT] Avoid SyntaxWarning about invalid escape sequence
  bindings/pyroot/pythonizations/python/ROOT/_numbadeclare.py
Labels: in:PyROOT

#13925 [RF] Don't check Minos output code in RooStats LikelihoodInterval
  roofit/roostats/src/LikelihoodInterval.cxx
  test/CMakeLists.txt
Labels: in:RooFit/RooStats

#13926 [PyROOT] Fix distributed RDataFrame tests due to error serialization
  bindings/pyroot/pythonizations/CMakeLists.txt
  bindings/pyroot/pythonizations/python/ROOT/_pythonization/_runtime_error.py
Labels: in:PyROOT

#13920 Update TGraph2D properties before painting [6.30]
  hist/histpainter/inc/TGraph2DPainter.h
  hist/histpainter/src/TGraph2DPainter.cxx
Labels: pr:backport, in:Graphics, affects:6.30

#13934 Paint `TF1` with default "lf" draw option also when "sames" was provided
  hist/hist/src/TF1.cxx
Labels: affects:master, in:Graphics

#13945 [tbrowser] ensure that TCanvas created when web mode is not active [6.28]
  gui/gui/src/TRootBrowser.cxx
Labels: pr:backport, in:GUI, affects:6.28

#13951 Backport mathcore : Fix creating the ParameterSetting when calling SetFCN
  math/mathcore/src/Fitter.cxx
Labels: pr:backport

#13952 Add 6.30 contributions by Vincenzo
  README/ReleaseNotes/v630/index.md
Labels: pr:backport

#13950 [skip-ci][ntuple][NFC] Update importer documentation
  tree/ntupleutil/v7/inc/ROOT/RNTupleImporter.hxx
Labels: in:RNTuple

#13963 [v6-30] Make FindMySQL.cmake more tolerant
  cmake/modules/FindMySQL.cmake
Labels: pr:backport

#13956 v6.30 [matrix] Fix TMatrixTSparse::SetMatrixArray for RowLwb!=0:
  math/matrix/CMakeLists.txt
  math/matrix/src/TMatrixTSparse.cxx
  math/matrix/test/CMakeLists.txt
  math/matrix/test/testMatrixTSparse.cxx
Labels: pr:backport

#13902 [Backport v6-30][Dict] Correct dicts with rootcling+sel xml
  core/dictgen/src/rootcling_impl.cxx
Labels: pr:backport

#13955 [v628][PyROOT] Prevent functions from crashing due to Python 3.12 assert
  bindings/pyroot/cppyy/CPyCppyy/src/CustomPyTypes.cxx
  bindings/pyroot/cppyy/patches/avoiding-python312-assert.patch
Labels: pr:backport, in:PyROOT

#13968 [PyROOT] Fix typo in recent PyROOT commit
  bindings/pyroot/cppyy/CPyCppyy/src/CustomPyTypes.cxx
  bindings/pyroot/cppyy/patches/avoiding-python312-assert.patch
Labels: in:PyROOT

#13969 [PyROOT] Fix typo in recent PyROOT commit
  bindings/pyroot/cppyy/CPyCppyy/src/CustomPyTypes.cxx
  bindings/pyroot/cppyy/patches/avoiding-python312-assert.patch
Labels: pr:backport, in:PyROOT

#13971 v6.30: [cocoa] Fix wrong boundary of cocoa to-bitmap:
  graf2d/cocoa/src/QuartzWindow.mm
Labels: pr:backport

#13980 [jsroot] 7.3.x 31/10/2023 [skip-ci]
  js/build/jsroot.js
  js/changes.md
  js/modules/base/latex.mjs
  js/modules/base/math.mjs
  js/modules/core.mjs
  js/modules/draw.mjs
  js/modules/draw/draw3d.mjs
  js/modules/geom/TGeoPainter.mjs
  js/modules/geom/geobase.mjs
  js/modules/gpad/TFramePainter.mjs
  js/modules/gui/HierarchyPainter.mjs
  js/modules/hist/RH3Painter.mjs
  js/modules/hist/RPavePainter.mjs
  js/modules/hist2d/RH1Painter.mjs
  js/modules/hist2d/RHistPainter.mjs
  js/modules/hist2d/TGraphPainter.mjs
  js/modules/hist2d/TH2Painter.mjs
  js/modules/hist2d/THistPainter.mjs
  js/modules/io.mjs
  js/modules/webwindow.mjs
Labels: in:WebGui, affects:6.28

#13983 [jsroot] 6.3.x 31/10/2023 with critical fixes from v7 [6.26] [skip-ci]
  js/scripts/JSRoot.core.js
  js/scripts/JSRoot.more.js
  js/scripts/JSRoot.v7hist.js
  js/scripts/JSRoot.webwindow.js
Labels: in:WebGui, affects:6.26

#12602 [cmake] Add support for partially enabled modules
  cmake/modules/RootMacros.cmake
Labels: in:Build System, in:C++ modules

#13986 [RF] Yet another fix to bin-by-bin offsetting
  roofit/roofitcore/src/RooNLLVar.cxx
  roofit/roofitcore/src/RooNLLVarNew.cxx
Labels: bug, in:RooFit/RooStats
