Repository root-project/root, pull requests merged in 2023-08, with the labels that each got.

#13134 [rbrowser] Move RBrowserDataCleanup into header and LinkDef.h
  gui/browserv7/inc/LinkDef.h
  gui/browserv7/inc/ROOT/RBrowserData.hxx
  gui/browserv7/src/RBrowserData.cxx
Labels: in:WebGui

#13266 [RF] Generalize RooMultiVarGaussian to be constructed from TMatrixDBase
  roofit/roofitcore/inc/RooMultiVarGaussian.h
  roofit/roofitcore/src/RooMultiVarGaussian.cxx
Labels: improvement, in:RooFit/RooStats

#13334 [RF] Replace ReooRealAnalytic with `createIntegral` plus RooRealBinding
  README/ReleaseNotes/v630/index.md
  roofit/roofitcore/CMakeLists.txt
  roofit/roofitcore/inc/LinkDef.h
  roofit/roofitcore/inc/RooRealAnalytic.h
  roofit/roofitcore/src/RooRealAnalytic.cxx
  roofit/roofitcore/src/RooRealIntegral.cxx
Labels: in:RooFit/RooStats

#13360 [math] Avoid warnings from Vc.h from deprecated enum comparisons
  math/mathcore/inc/Math/Types.h
Labels: in:Math Libraries

#13253 Correct GL drawing for scaled shapes
  core/base/inc/TBuffer3D.h
  core/base/src/TBuffer3D.cxx
  geom/geom/src/TGeoScaledShape.cxx
  graf3d/gl/src/TGLScenePad.cxx
Labels: bug, priority:low, in:Geometry

#13241 Added support for GDML read/write of scaled solids.
  geom/gdml/inc/TGDMLParse.h
  geom/gdml/inc/TGDMLWrite.h
  geom/gdml/src/TGDMLParse.cxx
  geom/gdml/src/TGDMLWrite.cxx
Labels: new feature, in:Geometry

#13356 [cmake] Check that the Protobuf compiler is found
  cmake/modules/SearchInstalledSoftware.cmake
Labels: in:Build System, in:TMVA

#13375 [cmake] Remove faulty GTEST_INCLUDE_DIRS
  cmake/modules/SearchInstalledSoftware.cmake
Labels: in:Build System, pr:emergency🚨, clean build

#13381 [ntuple] Simplify `RPageSourceDaos::LoadClusters()`
  tree/ntuple/v7/src/RPageStorageDaos.cxx
Labels: improvement, in:RNTuple

#13316 [RF] Make plotting of histograms work for all orders of magnitude
  roofit/roofit/inc/RooParametricStepFunction.h
  roofit/roofit/inc/RooStepFunction.h
  roofit/roofit/src/RooParametricStepFunction.cxx
  roofit/roofit/src/RooStepFunction.cxx
  roofit/roofitcore/inc/RooCurve.h
  roofit/roofitcore/src/RooCurve.cxx
  roofit/roofitcore/src/RooHistPdf.cxx
Labels: bug, in:RooFit/RooStats

#13376 [RF] Add documentation to `RooB*Decay` constructors
  roofit/roofit/inc/RooBCPEffDecay.h
  roofit/roofit/inc/RooBCPGenDecay.h
  roofit/roofit/inc/RooBDecay.h
  roofit/roofit/inc/RooBMixDecay.h
  roofit/roofit/src/RooBCPEffDecay.cxx
  roofit/roofit/src/RooBCPGenDecay.cxx
  roofit/roofit/src/RooBDecay.cxx
  roofit/roofit/src/RooBMixDecay.cxx
Labels: in:RooFit/RooStats

#13354 Update script for PDG table
  etc/pdg_table.txt
  etc/pdg_table_update.py
Labels: pr:squash on merge

#13400 [core] Do not provide our own strlcpy if glibc >= 2.38 (v6.28)
  core/foundation/inc/ROOT/RConfig.hxx
Labels: pr:backport

#13411 [qt6web] remove unused member [skip-ci]
  gui/qt6webdisplay/rootqt6.cpp
Labels: affects:master, in:WebGui

#13370 [clang] Backport patch to merge template member parent
  interpreter/llvm-project/clang/lib/Serialization/ASTReaderDecl.cpp
  interpreter/llvm-project/llvm-project.tag
Labels: in:Cling

#13402 Allow geometry transparency at the volume level
  geom/geom/inc/TGeoVolume.h
  geom/geom/src/TGeoVolume.cxx
Labels: new feature, in:Geometry

#13412 Use nullptr in TInterpreter.h
  core/meta/inc/TInterpreter.h
Labels: affects:master, in:Core Libraries

#13442 [core][skip-ci] Fix typos in TVirtualCollectionProxy documentation
  core/cont/inc/TVirtualCollectionProxy.h
Labels: improvement, in:Documentation

#13425 Fix rounding problem in circle drawing in latex parser
  graf2d/graf/src/TLatex.cxx
Labels: affects:master, in:Graphics

#13426 Fix rounding problem in circle drawing in latex parser [6.28]
  graf2d/graf/src/TLatex.cxx
Labels: pr:backport, in:Graphics, affects:6.28

#13455 [cmake] remove chrome workaround for Ubuntu
  cmake/modules/RootConfiguration.cmake
Labels: affects:master, in:WebGui

#13405 [RF] Improve docs of RooAbsReal::getPropagatedError()
  roofit/roofitcore/inc/RooAbsReal.h
  roofit/roofitcore/src/RooAbsReal.cxx
Labels: in:RooFit/RooStats

#13452 [ntuple] RNTupleSerialize: construct `std::span` from pointer + size
  tree/ntuple/v7/src/RNTupleSerialize.cxx
Labels: in:RNTuple

#13456 [ntuple] Fix typo in `RPageSource::PrepareLoadCluster` signature
  tree/ntuple/v7/inc/ROOT/RPageStorage.hxx
  tree/ntuple/v7/src/RPageStorage.cxx
Labels: in:RNTuple

#13463 Delete the object held by gROOT after we reset the globals.
  core/base/src/TROOT.cxx
Labels: in:Core Libraries

#13482 [cling] Skip IncrementalExecutor for CUDADevice
  interpreter/cling/lib/Interpreter/Interpreter.cpp
Labels: in:Cling

#13451 io: Do not turn on automatically MustClean for TDirectory
  core/base/src/TDirectory.cxx
Labels: affects:master, in:I/O

#13487 [ntuple] Move `R__ASSERT` out of the inlined code path
  tree/ntuple/v7/inc/ROOT/RColumn.hxx
  tree/ntuple/v7/src/RColumn.cxx
Labels: improvement, in:RNTuple

#13478 Warn on identical autoload keys from two different libraries
  core/metacling/src/TCling.cxx
Labels: improvement, in:Core Libraries

#13501 [RF] Only keep class declaration of `RooRefCountList`
  roofit/roofitcore/CMakeLists.txt
  roofit/roofitcore/inc/LinkDef.h
  roofit/roofitcore/inc/RooLinkedList.h
  roofit/roofitcore/inc/RooRefCountList.h
  roofit/roofitcore/inc/RooSTLRefCountList.h
  roofit/roofitcore/src/RooRefCountList.cxx
  roofit/roofitcore/src/RooSTLRefCountList.cxx
Labels: in:RooFit/RooStats

#13500 [v6.28][backport][windows] Make `OpenDirectory` and `GetDirEntry` thread safe (#13472)
  core/winnt/inc/TWinNTSystem.h
  core/winnt/src/TWinNTSystem.cxx
Labels: pr:backport

#13504 [cmake] relatedrepo_GetClosestMatch: fix well-known branch regex
  CMakeLists.txt
Labels: bug, in:Build System

#13492 Fix in case positions sizes or colors are the same for all points.
  hist/histpainter/src/TGraphPainter.cxx
Labels: in:Graphics

#13530 [RF] Rename the RooFitDriver to `RooFit::Evaluator` and make it public
  roofit/histfactory/test/testHistFactory.cxx
  roofit/histfactory/test/testParamHistFunc.cxx
  roofit/roofitcore/CMakeLists.txt
  roofit/roofitcore/inc/RooAbsReal.h
  roofit/roofitcore/inc/RooFit/Evaluator.h
  roofit/roofitcore/inc/RooFit/TestStatistics/RooUnbinnedL.h
  roofit/roofitcore/src/Buffers.cxx
  roofit/roofitcore/src/RooAbsArg.cxx
  roofit/roofitcore/src/RooAbsPdf.cxx
  roofit/roofitcore/src/RooAbsReal.cxx
  roofit/roofitcore/src/RooEvaluatorWrapper.cxx
  roofit/roofitcore/src/RooEvaluatorWrapper.h
  roofit/roofitcore/src/RooFit/Detail/Buffers.h
  roofit/roofitcore/src/RooFit/Evaluator.cxx
  roofit/roofitcore/src/RooNLLVarNew.cxx
  roofit/roofitcore/src/TestStatistics/RooUnbinnedL.cxx
  roofit/roofitcore/test/testRooDataHist.cxx
Labels: in:RooFit/RooStats

#13534 [cling][NFC] Cleanup `DeclUnloader`
  interpreter/cling/lib/Interpreter/DeclUnloader.cpp
Labels: in:Cling

#13523 Avoid inclusion of arrow testing stuff
  tree/dataframe/test/datasource_arrow.cxx
Labels: affects:master, in:RDataFrame, in:Testing

#13538 [RF] Avoid double counting norm integrals in RooAddPdf with BatchMode
  roofit/roofitcore/src/RooAddHelpers.cxx
  roofit/roofitcore/src/RooAddModel.cxx
  roofit/roofitcore/src/RooAddPdf.cxx
  roofit/roofitcore/test/testRooAddPdf.cxx
Labels: in:RooFit/RooStats

#13539 Set kMustCleanup bit for all pad primitives when streaming
  graf2d/gpad/src/TPad.cxx
Labels: affects:master, in:Graphics

#13532 [PyROOT][9058] Implement TPython::ExecScript for Python 3
  bindings/tpython/src/TPython.cxx
Labels: affects:master

#13205 [Tutorial] How to create ROOT Dictionary for a custom class is a stand-alone C++ project
  tutorials/tree/dictionary/CMakeLists.txt
  tutorials/tree/dictionary/README.md
  tutorials/tree/dictionary/data2Tree.cxx
  tutorials/tree/dictionary/data2Tree.hxx
  tutorials/tree/dictionary/data2TreeLinkDef.hxx
  tutorials/tree/dictionary/main.cpp
  tutorials/tree/dictionary/readTree.cxx
  tutorials/tree/dictionary/readTreeDF.cxx
  tutorials/tree/dictionary/writeTree.cxx
Labels: improvement, in:Documentation

#13512 [ci] Use Ninja as build system. [skip-ci]
  .github/workflows/root-ci-config/build_root.py
Labels: clean build

#13213 [cxxmodules] Make the ROOT modulemap only a dependency when building ROOT
  cmake/modules/RootMacros.cmake
Labels: in:Build System, in:C++ modules

#13561 Make TNetXNGFile::Close() reentrant [6.28] [skip-ci]
  net/netxng/src/TNetXNGFile.cxx
Labels: pr:backport, in:I/O, affects:6.28

#13549 [ntuple] specifications.md: fully describe a Compression block
  tree/ntuple/v7/doc/specifications.md
Labels: improvement, in:Documentation, in:RNTuple

#13577 [core] Do not provide our own strlcpy if glibc >= 2.38
  core/base/inc/ROOT/RConfig.hxx
Labels: pr:backport
