Repository root-project/root, pull requests merged in 2023-05, with the labels that each got.

#12731 [ntuple] fix importing leaf count arrays with broken title
  tree/ntupleutil/v7/src/RNTupleImporter.cxx
Labels: in:RNTuple

#12560 [graph] copy all attributes to new histogram
  hist/hist/src/TGraph.cxx
Labels: affects:master, in:Graphics

#12754 [RF] Some cleanup of public `roofitcore` classes
  roofit/roofitcore/CMakeLists.txt
  roofit/roofitcore/inc/LinkDef.h
  roofit/roofitcore/inc/RooAddModel.h
  roofit/roofitcore/inc/RooAddPdf.h
  roofit/roofitcore/inc/RooInt.h
  roofit/roofitcore/inc/RooObjCacheManager.h
  roofit/roofitcore/inc/RooTFoamBinding.h
  roofit/roofitcore/src/RooConvIntegrandBinding.cxx
  roofit/roofitcore/src/RooConvIntegrandBinding.h
  roofit/roofitcore/src/RooTFoamBinding.cxx
  roofit/roofitcore/src/RooTFoamBinding.h
Labels: in:RooFit/RooStats

#12763 [math] Fix GCC 13 warning in `math/unuran/test/unuranDistr.cxx`
  math/unuran/test/unuranDistr.cxx
Labels: in:Math Libraries

#12767 [RF] Mark template specialization as inline
  roofit/roofitcore/inc/RooAbsSelfCachedReal.h
Labels: affects:master, in:RooFit/RooStats, pr:emergency🚨

#12782 [cling][v6-28] DefinitionShadower: fix crash with C++20 concepts
  interpreter/cling/lib/Interpreter/DefinitionShadower.cpp
  interpreter/cling/test/CodeUnloading/DeclShadowing.C
Labels: pr:backport, bug, in:Cling, affects:6.28

#12781 [cling] DefinitionShadower: fix crash with C++20 concepts
  interpreter/cling/lib/Interpreter/DefinitionShadower.cpp
  interpreter/cling/test/CodeUnloading/DeclShadowing.C
Labels: bug, affects:master, in:Cling

#12774 Fix seldom crash in `TPad::ShowGuidelines` [6.26]
  graf2d/gpad/src/TPad.cxx
Labels: pr:backport, in:Graphics, affects:6.26

#12789 [webgui] change launch string for headless chrome
  gui/webdisplay/src/RWebDisplayHandle.cxx
Labels: affects:master, in:WebGui

#12794 [v6-28][skip-ci] Resize the canvas when displaying the editor
  gui/gui/src/TRootCanvas.cxx
Labels: pr:backport

#12791 [webgui] change launch string for headless chrome [6.28]
  gui/webdisplay/src/RWebDisplayHandle.cxx
Labels: pr:backport, in:WebGui, affects:6.28

#12793 [cxxmodules] Fix C++14 build with GCC 12
  interpreter/cling/include/cling/std.modulemap
Labels: in:C++ modules

#12803 TString: Enable spaceship operator with libc++ [v6.28]
  core/base/inc/TString.h
Labels: pr:backport

#12795 Always set positive screen gamma in libAfterImage
  graf2d/asimage/src/libAfterImage/import.c
Labels: affects:master, in:Graphics

#12796 Fix warning in asimage about redefinition of TObject::Hash()
  graf2d/asimage/inc/TASImagePlugin.h
  graf2d/asimage/inc/TASPluginGS.h
  graf2d/asimage/src/TASPluginGS.cxx
Labels: affects:master, in:Graphics

#12799 Add support of openssl 3.1 for libRHTTP building [6.28]
  net/http/CMakeLists.txt
Labels: pr:backport, in:WebGui, affects:6.28

#12806 [skip-ci][windows] Fix the webgui ping test on Windows
  gui/webdisplay/src/RWebDisplayHandle.cxx
Labels: affects:master, in:WebGui

#12807 [skip-ci][v6-28][windows] Fix the webgui ping test on Windows
  gui/webdisplay/src/RWebDisplayHandle.cxx
Labels: pr:backport, in:WebGui, affects:6.28

#12810 Fix the build of TBB in Debug mode on Windows
  cmake/modules/SearchInstalledSoftware.cmake
Labels: affects:master, in:Build System

#12805 [DF] Fix MakeNumpyDataFrame in v6.28
  bindings/pyroot/pythonizations/python/ROOT/_facade.py
Labels: pr:backport

#12809 [RF] Make datasets that contain strings cloneable
  roofit/roofitcore/inc/RooStringVar.h
  roofit/roofitcore/src/RooStringVar.cxx
  roofit/roofitcore/test/testRooDataSet.cxx
Labels: bug, in:RooFit/RooStats

#12818 [skip-ci][windows] Disable the failing df013_InspectAnalysis also on 32 bit
  tutorials/CMakeLists.txt
Labels: affects:master

#12816 [DF] Re-introduce diagnostics for Define expr returning void (v6.28)
  tree/dataframe/inc/ROOT/RDF/RInterface.hxx
Labels: pr:backport

#12827 [PyROOT] Replace deprecated np.bool by plain bool
  bindings/pyroot/pythonizations/test/numbadeclare.py
Labels: in:PyROOT

#12830 [ci] Upload build artifacts before testing
  .github/workflows/root-ci-config/build_root.py
Labels: pr:emergency🚨

#12843 Add numba compatible with Python 3.11 to requirements.txt
  requirements.txt
Labels: in:PyROOT

#12853 [cling] DeclUnloader: remove `TagDecl`s after all other decls
  interpreter/cling/lib/Interpreter/DeclUnloader.cpp
Labels: bug, affects:master, in:Cling, affects:6.28

#12854 [cling][v6-28] DeclUnloader: remove `TagDecl`s after all other decls
  interpreter/cling/lib/Interpreter/DeclUnloader.cpp
Labels: pr:backport, in:Cling

#12836 [ntuple] Add more test coverage for RNTuple+RVec
  tree/ntuple/v7/test/rfield_vector.cxx
Labels: in:RNTuple

#12862 [webgui] support multiple connections for embed web window
  geom/webviewer/src/RGeomViewer.cxx
  gui/browserv7/src/RFileDialog.cxx
  gui/webdisplay/inc/ROOT/RWebDisplayArgs.hxx
  gui/webdisplay/inc/ROOT/RWebWindow.hxx
  gui/webdisplay/src/RWebDisplayArgs.cxx
  gui/webdisplay/src/RWebWindow.cxx
Labels: affects:master, in:WebGui

#12824 [ntuple] Make sure that all tasks have finished in `~RPageStorage`
  tree/ntuple/v7/inc/ROOT/RPageStorage.hxx
  tree/ntuple/v7/src/RPageSinkBuf.cxx
  tree/ntuple/v7/src/RPageStorage.cxx
Labels: bug, affects:master

#12845 Fix forward compatibility with v6-30
  core/base/src/TObject.cxx
  io/io/src/TStreamerInfoActions.cxx
  io/io/src/TStreamerInfoReadBuffer.cxx
Labels: priority:critical, in:I/O

#12389 [RF] The testRooAbsL test compares two doubles and fails due to rounding errors
  roofit/roofitcore/test/TestStatistics/testRooAbsL.cxx
Labels: affects:master, in:RooFit/RooStats, in:Testing, affects:6.28

#12849 v628: HistFactory: open channel and combined files only once
  roofit/histfactory/src/MakeModelAndMeasurementsFast.cxx
Labels: in:RooFit/RooStats

#12867 v626 HistFactory: open channel and combined files only once
  roofit/histfactory/src/MakeModelAndMeasurementsFast.cxx
Labels: pr:backport, in:RooFit/RooStats

#12873 [cmake] disable qt5web option when webgui is not enabled [6.28]
  cmake/modules/RootBuildOptions.cmake
Labels: pr:backport, in:Build System, affects:6.28

#12857 [PyROOT] Only forward some tp_flags
  bindings/pyroot/cppyy/CPyCppyy/src/MemoryRegulator.cxx
  bindings/pyroot/cppyy/patches/gc_flags.patch
Labels: in:PyROOT

#12825 [skip-ci] Improve TTree::Draw help
  tree/tree/src/TTree.cxx
Labels: in:TTree

#12879 Clean up some LLVM CMake settings
  interpreter/CMakeLists.txt
  interpreter/cling/tools/plugins/clad/CMakeLists.txt
Labels: in:Build System, in:Cling, clean build

#12860 [RF] Add exceptions to set methods for non-existing objects
  roofit/roofitcore/inc/RooFit/ModelConfig.h
  roofit/roofitcore/src/RooWorkspace.cxx
Labels: in:RooFit/RooStats

#12819 [doc][math] Update Minimizer documentation
  math/mathcore/inc/Math/Minimizer.h
Labels: in:Math Libraries

#12891 [RF] Add missing declarations for JSONInterface template specializations
  roofit/jsoninterface/inc/RooFit/Detail/JSONInterface.h
  roofit/jsoninterface/src/JSONInterface.cxx
Labels: in:RooFit/RooStats

#12877 [RF] Add `ExternalConstraints`, createNLL() and fitTo() to ModelConfig
  roofit/roofitcore/inc/RooFit/ModelConfig.h
  roofit/roofitcore/inc/RooWorkspace.h
  roofit/roofitcore/src/ModelConfig.cxx
  roofit/roofitcore/src/RooWorkspace.cxx
  roofit/roostats/inc/RooStats/AsymptoticCalculator.h
  roofit/roostats/src/AsymptoticCalculator.cxx
Labels: improvement, in:RooFit/RooStats

#12904 [jsroot] 7.3.2 release with several fixes [skip-ci]
  js/build/jsroot.js
  js/changes.md
  js/modules/base/math.mjs
  js/modules/core.mjs
  js/modules/geom/TGeoPainter.mjs
  js/modules/gui/display.mjs
  js/modules/hist2d/TGraphPainter.mjs
  js/modules/tree.mjs
Labels: in:WebGui, affects:6.28

#12906 [jsroot] dev 30/05/2023 [skip-ci]
  js/build/jsroot.js
  js/changes.md
  js/modules/base/base3d.mjs
  js/modules/base/latex.mjs
  js/modules/base/math.mjs
  js/modules/core.mjs
  js/modules/d3.mjs
  js/modules/geom/TGeoPainter.mjs
  js/modules/gpad/TCanvasPainter.mjs
  js/modules/gpad/TPadPainter.mjs
  js/modules/hist2d/TScatterPainter.mjs
  js/modules/io.mjs
  js/modules/three.mjs
  js/modules/tree.mjs
Labels: affects:master, in:WebGui

#12901 Fix std.modulemap for gcc13
  interpreter/cling/include/cling/std.modulemap
Labels: pr:backport

#12913 [ntuple] Fix typo in exception message
  tree/ntuple/v7/src/RField.cxx
  tree/ntuple/v7/test/ntuple_types.cxx
Labels: in:RNTuple

#12903 [ntuple] Move the `WaitForAllTasks()` call to `~RPageSinkBuf`
  tree/ntuple/v7/inc/ROOT/RPageSinkBuf.hxx
  tree/ntuple/v7/src/RPageSinkBuf.cxx
  tree/ntuple/v7/src/RPageStorage.cxx
Labels: bug, affects:master, in:RNTuple

#12838 [RF] RooAbsReal::getPropagatedError: fix for case of negative parameter with zero error
  roofit/roofitcore/src/RooAbsReal.cxx
Labels: in:RooFit/RooStats

#12910 [skip-ci] fix an issue with python 3.12
  build/misc/argparse2help.py
Labels: in:PyROOT

#12921 [RF] Refactor BatchMode likelihood creation code
  roofit/roofitcore/src/BatchModeHelpers.cxx
  roofit/roofitcore/src/RooAbsPdf.cxx
  roofit/roofitcore/src/RooFit/BatchModeHelpers.h
  roofit/roofitcore/src/RooFitDriver.cxx
  roofit/roofitcore/src/RooFitDriver.h
Labels: in:RooFit/RooStats
