Repository root-project/root, pull requests merged in 2023-09, with the labels that each got.

#13416 [cmake] Remove deprecated options cxx11/14/17
  cmake/modules/CheckCompiler.cmake
  cmake/modules/RootBuildOptions.cmake
Labels: in:Build System

#13585 The TRI1/2 TGraph2D options produced artifacts.
  hist/hist/src/TGraph2D.cxx
  hist/histpainter/src/TGraph2DPainter.cxx
Labels: affects:master, in:Graphics

#13587 [jsroot] dev 1/09/2023
  js/build/jsroot.js
  js/modules/draw/TLinePainter.mjs
  js/modules/draw/TPolyMarker3D.mjs
  js/modules/draw/TRatioPlotPainter.mjs
  js/modules/draw/TSplinePainter.mjs
  js/modules/draw/TTree.mjs
  js/modules/draw/TWebPaintingPainter.mjs
  js/modules/draw/v7more.mjs
  js/modules/geom/TGeoPainter.mjs
  js/modules/geom/csg.mjs
  js/modules/geom/geobase.mjs
  js/modules/gpad/RAxisPainter.mjs
  js/modules/gpad/RCanvasPainter.mjs
  js/modules/gpad/RFramePainter.mjs
  js/modules/gpad/RPadPainter.mjs
  js/modules/gpad/TAxisPainter.mjs
  js/modules/gpad/TCanvasPainter.mjs
  js/modules/gpad/TFramePainter.mjs
  js/modules/gpad/TPadPainter.mjs
  js/modules/gui/HierarchyPainter.mjs
  js/modules/gui/display.mjs
  js/modules/gui/menu.mjs
  js/modules/gui/utils.mjs
  js/modules/hist/RH1Painter.mjs
  js/modules/hist/RH2Painter.mjs
  js/modules/hist/RH3Painter.mjs
  js/modules/hist/RPavePainter.mjs
  js/modules/hist/TEfficiencyPainter.mjs
  js/modules/hist/TF1Painter.mjs
  js/modules/hist/TF2Painter.mjs
  js/modules/hist/TGraph2DPainter.mjs
  js/modules/hist/TGraphPainter.mjs
  js/modules/hist/TGraphTimePainter.mjs
  js/modules/hist/TH1Painter.mjs
  js/modules/hist/TH2Painter.mjs
  js/modules/hist/TH3Painter.mjs
  js/modules/hist/THStackPainter.mjs
  js/modules/hist/TPavePainter.mjs
  js/modules/hist/hist3d.mjs
  js/modules/hist2d/RH1Painter.mjs
  js/modules/hist2d/RH2Painter.mjs
  js/modules/hist2d/RHistPainter.mjs
  js/modules/hist2d/TGraphPainter.mjs
  js/modules/hist2d/TH1Painter.mjs
  js/modules/hist2d/TH2Painter.mjs
  js/modules/hist2d/THistPainter.mjs
Labels: affects:master, in:WebGui

#13584 Fix a debug assertion failure on Windows when running stressgraphics
  core/base/src/Stringio.cxx
Labels: in:Core Libraries

#13401 [ntuple] Throw when `RNTupleInspector` encounters inconsistent compression
  tree/ntupleutil/v7/inc/ROOT/RNTupleInspector.hxx
  tree/ntupleutil/v7/src/RNTupleInspector.cxx
Labels: in:RNTuple

#13598 [interpreter] Add builtin_llvm's CMake modules
  interpreter/CMakeLists.txt
Labels: in:Build System, in:Cling

#13608 [tmva][sofie-gnn] Increase tolerance for sofie-gnn tests
  bindings/pyroot/pythonizations/test/sofie_gnn.py
Labels: in:TMVA

#13609 [RF][PyROOT] Fix `RooDataSet.from_numpy()` for contiguous input arrays
  bindings/pyroot/pythonizations/python/ROOT/_pythonization/_roofit/_roodataset.py
  bindings/pyroot/pythonizations/test/roofit/roodataset_numpy.py
Labels: bug, in:PyROOT, in:RooFit/RooStats

#13291 [IO][v6-28] Backport of prevent infinite loop in `TFile::ls` #13217
  io/io/src/TDirectoryFile.cxx
Labels: pr:backport, pr:squash on merge, in:I/O, affects:6.28

#13590 [ntuple] Speed up reading/writing of simple vectors
  tree/ntuple/v7/src/RField.cxx
Labels: in:RNTuple

#13571 [CMake] Make PROOF optional and enabled by default
  CMakeLists.txt
  cmake/modules/RootBuildOptions.cmake
  gui/CMakeLists.txt
  main/CMakeLists.txt
  test/CMakeLists.txt
Labels: improvement, in:Build System

#13617 [build] Format error as string in dependency_versions.py test
  bindings/pyroot/pythonizations/test/dependency_versions.py
Labels: in:Build System

#13628 [RF] Limit maximum number of thread blocks in RooFit CUDA code
  roofit/batchcompute/src/RooBatchCompute.cu
Labels: bug, in:RooFit/RooStats

#13629 [RF] Consistent RooCmdArg names for all `RooFit::Import()` overloads
  roofit/roofitcore/src/RooDataHist.cxx
  roofit/roofitcore/src/RooGlobalFunc.cxx
Labels: in:RooFit/RooStats

#13633 [Math] Respawn genvector tests
  math/genvector/CMakeLists.txt
  math/genvector/test/CMakeLists.txt
  math/genvector/test/rotationApplication.cxx
  math/genvector/test/testBoost.cxx
  math/genvector/test/testVectorIO.cxx
Labels: improvement, in:Math Libraries, in:Testing

#13637 [RF] Give example for multiple categories plot in rf501_simultaneouspdf
  roofit/roofitcore/src/RooGlobalFunc.cxx
  tutorials/roofit/rf501_simultaneouspdf.C
  tutorials/roofit/rf501_simultaneouspdf.py
Labels: in:RooFit/RooStats

#13612 [RF][PyROOT] Avoid boolean operators on numpy arrays in unit test
  bindings/pyroot/pythonizations/test/roofit/roodataset_numpy.py
Labels: in:PyROOT, in:RooFit/RooStats

#13646 [math] Don't `#include "Math/Error.h"` and `"Math/Util.h"` in Minuit2 headers
  math/mathcore/CMakeLists.txt
  math/mathcore/inc/Fit/ParameterSettings.h
  math/mathcore/inc/Math/IOptions.h
  math/mathcore/inc/Math/Minimizer.h
  math/mathcore/src/IOptions.cxx
  math/mathcore/src/Minimizer.cxx
  math/mathcore/src/ParameterSettings.cxx
  math/minuit2/src/Minuit2Minimizer.cxx
  math/minuit2/src/math/CMakeLists.txt
  roofit/roofitcore/inc/RooFit/TestStatistics/LikelihoodWrapper.h
Labels: in:Math Libraries

#13639 [RF] Fix skipping of zero weights in tests statistic caching
  roofit/roofitcore/inc/RooAbsOptTestStatistic.h
  roofit/roofitcore/inc/RooAbsTestStatistic.h
  roofit/roofitcore/src/RooAbsOptTestStatistic.cxx
  roofit/roofitcore/src/RooAbsTestStatistic.cxx
  roofit/roofitcore/src/RooChi2Var.cxx
  roofit/roofitcore/src/RooDataWeightedAverage.cxx
  roofit/roofitcore/src/RooNLLVar.cxx
  roofit/roofitcore/src/RooXYChi2Var.cxx
Labels: bug, in:RooFit/RooStats

#13645 [ipython] fix canvas width/height usage [6.28]
  bindings/jupyroot/python/JupyROOT/helpers/utils.py
Labels: pr:backport, in:Notebooks, affects:6.28

#13671 [jsroot] 7.5.pre 19/09/2023 with grayscale support [skip-ci]
  js/build/jsroot.js
  js/changes.md
  js/modules/base/colors.mjs
  js/modules/draw/TASImagePainter.mjs
  js/modules/draw/v7more.mjs
  js/modules/gpad/RPadPainter.mjs
  js/modules/gpad/TCanvasPainter.mjs
  js/modules/gpad/TFramePainter.mjs
  js/modules/gpad/TPadPainter.mjs
  js/modules/hist/TH2Painter.mjs
  js/modules/hist/TH3Painter.mjs
  js/modules/hist/TPavePainter.mjs
  js/modules/hist2d/TH1Painter.mjs
  js/modules/hist2d/TH2Painter.mjs
  js/modules/hist2d/THistPainter.mjs
  js/modules/hist2d/TScatterPainter.mjs
Labels: affects:master, in:Graphics, in:WebGui

#13670 [webgui] Provide correct TCanvas::Draw and TPad::Draw for web canvas
  graf2d/gpad/src/TCanvas.cxx
  graf2d/gpad/src/TPad.cxx
Labels: affects:master, in:Graphics, in:WebGui

#13606 [PyROOT] Make building with Python 2 optional
  bindings/pyroot/pythonizations/python/ROOT/__init__.py
  cmake/modules/RootBuildOptions.cmake
  cmake/modules/SearchRootCoreDeps.cmake
Labels: in:PyROOT

#13700 Do not evaluate dependent immediate invocations
  interpreter/llvm-project/clang/lib/Sema/SemaExpr.cpp
  interpreter/llvm-project/llvm-project.tag
Labels: in:C++ modules, in:Cling

#13701 [RF] Include `gsl_integration.h` in RooFitMore instead of copy-pasting
  roofit/roofitmore/CMakeLists.txt
  roofit/roofitmore/src/RooGaussKronrodIntegrator1D.cxx
Labels: in:RooFit/RooStats

#13703 [jsroot] dev 21/09/2023 with fixes [skip-ci]
  js/build/jsroot.js
  js/changes.md
  js/modules/base/ObjectPainter.mjs
  js/modules/base/TAttFillHandler.mjs
  js/modules/core.mjs
  js/modules/draw/more.mjs
  js/modules/gpad/RPadPainter.mjs
  js/modules/gpad/TAxisPainter.mjs
  js/modules/gpad/TPadPainter.mjs
  js/modules/hist/TPavePainter.mjs
  js/modules/hist2d/TGraphPainter.mjs
Labels: affects:master, in:Graphics, in:WebGui

#13711 [config] remove install of removed root-help.el
  cmake/modules/RootConfiguration.cmake
Labels: pr:emergency🚨

#13706 [jsroot] 7.5.pre 22/09/2023 with TProfile3D support [skip-ci]
  js/build/jsroot.js
  js/changes.md
  js/modules/base/TAttFillHandler.mjs
  js/modules/core.mjs
  js/modules/draw.mjs
  js/modules/hist/TH3Painter.mjs
  js/modules/hist2d/THistPainter.mjs
Labels: affects:master, in:Graphics, in:WebGui

#13722 [LLVM] Backport commit
  interpreter/llvm/src/tools/clang/lib/Sema/SemaExpr.cpp
Labels: pr:backport, affects:6.28

#13728 [v628][RF][HF] Add missing LinkDefs for systematics classes in HistFactory
  roofit/histfactory/inc/LinkDef.h
Labels: pr:backport, in:RooFit/RooStats

#10492 [bugfix] Update SimplexBuilder.cxx to fix #6775
  math/minuit2/src/SimplexBuilder.cxx
Labels: in:Math Libraries

#13740 [jsroot] 7.5.pre 28/09/2023 with TPaletteAxis fixes [skip-ci]
  js/build/jsroot.js
  js/modules/base/ObjectPainter.mjs
  js/modules/core.mjs
  js/modules/draw.mjs
  js/modules/draw/TGaxisPainter.mjs
  js/modules/gpad/RAxisPainter.mjs
  js/modules/gpad/RPadPainter.mjs
  js/modules/gpad/TAxisPainter.mjs
  js/modules/gpad/TCanvasPainter.mjs
  js/modules/gui/HierarchyPainter.mjs
  js/modules/gui/display.mjs
  js/modules/gui/menu.mjs
  js/modules/hist/TPavePainter.mjs
  js/modules/hist2d/THistPainter.mjs
Labels: affects:master, in:WebGui

#13743 [webgeom] Remove dead code
  geom/webviewer/src/RGeomData.cxx
Labels: pr:backport, affects:6.28

#13717 [RF] Update to latest xRooFit
  roofit/xroofit/CMakeLists.txt
  roofit/xroofit/doc/index.md
  roofit/xroofit/inc/LinkDef.h
  roofit/xroofit/inc/RooBrowser.h
  roofit/xroofit/inc/RooFit/xRooFit/Config.h
  roofit/xroofit/inc/RooFit/xRooFit/xRooBrowser.h
  roofit/xroofit/inc/RooFit/xRooFit/xRooFit.h
  roofit/xroofit/inc/RooFit/xRooFit/xRooHypoSpace.h
  roofit/xroofit/inc/RooFit/xRooFit/xRooNLLVar.h
  roofit/xroofit/inc/RooFit/xRooFit/xRooNode.h
  roofit/xroofit/inc/XRooFit.h
  roofit/xroofit/src/Asymptotics.cxx
  roofit/xroofit/src/coutCapture.h
  roofit/xroofit/src/xRooBrowser.cxx
  roofit/xroofit/src/xRooFit.cxx
  roofit/xroofit/src/xRooHypoSpace.cxx
  roofit/xroofit/src/xRooNLLVar.cxx
  roofit/xroofit/src/xRooNode.cxx
  roofit/xroofit/src/xRooNode_interactive.cxx
Labels: in:RooFit/RooStats

#13750 [CMake] Use `find_package(XRootD)` and not `XROOTD` (case sensitivity)
  cmake/modules/SearchInstalledSoftware.cmake
Labels: bug, in:Build System

#13751 [geom] Don't use `-fabi-version=6` when compiling geom/vecgeom with GCC
  geom/vecgeom/CMakeLists.txt
Labels: bug, in:Geometry

#13753 Revert "[CMake] Use `find_package(XRootD)` and not `XROOTD` (case sen…
  cmake/modules/SearchInstalledSoftware.cmake
Labels: in:Build System

#13764 [Backport][core] Remove some `mm*.c` in core/clib
  core/clib/CMakeLists.txt
  core/clib/src/mmemalign.c
  core/clib/src/mmstats.c
  core/clib/src/mmtrace.c
  core/clib/src/mvalloc.c
Labels: pr:backport, affects:6.28

#13763 [Backport][CMake] Remove N-1 identical link statements
  builtins/lz4/CMakeLists.txt
  builtins/zstd/CMakeLists.txt
Labels: pr:backport, in:Build System
