Repository root-project/root, pull requests merged in 2023-02, with the labels that each got.

#12189 [PyROOT] Use non-deprecated API to initialize Python interpreter
  bindings/pyroot/cppyy/CPyCppyy/src/API.cxx
  bindings/pyroot/cppyy/patches/PyROOT-Use-non-deprecated-API-to-initialize-Python.patch
Labels: in:PyROOT

#12159 [DF][PyROOT] Avoid deprecated numpy.object
  bindings/pyroot/pythonizations/python/ROOT/_pythonization/_rdataframe.py
Labels: in:PyROOT, in:RDataFrame

#12198 [6.28] Avoid deprecated numpy.object
  bindings/pyroot/pythonizations/python/ROOT/_pythonization/_rdataframe.py
Labels: pr:backport, in:PyROOT, in:RDataFrame

#11997 [cling] Add back basic support for JITLink
  interpreter/cling/lib/Interpreter/IncrementalJIT.cpp
Labels: in:Cling

#12200 [rmkdepend] Work around GCC format truncation warning:
  build/rmkdepend/include.c
Labels: pr:squash on merge

#12127 [skip-ci][ntuple] specifications.md: document `RNTupleCardinality`
  tree/ntuple/v7/doc/specifications.md
Labels: in:Documentation, in:RNTuple

#12212 [DF] Removing failing test with shorter friends (v6.28)
  tree/dataframe/test/dataframe_datasetspec.cxx
Labels: pr:backport

#12210 [ntuple] fix-up RNTupleDescriptor::Clone
  tree/ntuple/v7/src/RNTupleDescriptor.cxx
Labels: in:RNTuple

#12216 Add missing include to metacling test
  core/metacling/test/TClingCallFuncTests.cxx
Labels: affects:master, in:Cling

#12125 [RF] Fix documentation for RooBrowser
  roofit/xroofit/inc/RooBrowser.h
Labels: in:RooFit/RooStats

#12221 [RF] Make it possible to switch to `ryml` backend after building ROOT
  .github/workflows/rootci-installers/buildconfig/global.txt
  .github/workflows/rootci-installers/buildconfig/mac12.txt
  .github/workflows/rootci-installers/buildconfig/ubuntu18.txt
  .github/workflows/rootci-installers/buildconfig/ubuntu20.txt
  .github/workflows/rootci-installers/buildconfig/windows.txt
  cmake/modules/RootBuildOptions.cmake
  roofit/hs3/src/HistFactoryJSONTool.cxx
  roofit/jsoninterface/CMakeLists.txt
  roofit/jsoninterface/inc/RooFit/Detail/JSONInterface.h
  roofit/jsoninterface/src/JSONInterface.cxx
Labels: in:RooFit/RooStats

#12102 Change `clang-format` style to have line breaks in c'tor initializer
  .clang-format
Labels: improvement

#12082 [cxxmodules] Enable a few modules for Windows. Now we can run hsimple.C.
  cmake/modules/RootMacros.cmake
  core/base/CMakeLists.txt
  graf3d/gviz3d/CMakeLists.txt
  gui/ged/CMakeLists.txt
  interpreter/cling/include/cling/std_msvc.modulemap
  roofit/RDataFrameHelpers/CMakeLists.txt
  roofit/histfactory/CMakeLists.txt
  roofit/roofit/CMakeLists.txt
  roofit/roofitcore/CMakeLists.txt
  roofit/roostats/CMakeLists.txt
  tmva/tmva/CMakeLists.txt
  tmva/tmvagui/CMakeLists.txt
  tree/dataframe/CMakeLists.txt
  tree/treeplayer/CMakeLists.txt
Labels: in:C++ modules

#12237 [cling] Switch back to large code model for macOS on AArch64
  interpreter/cling/lib/Interpreter/IncrementalJIT.cpp
Labels: in:Cling

#12236 [RF] Support again same-name pdfs in RooSimultaneous with BatchMode
  roofit/roofitcore/src/RooSimultaneous.cxx
  roofit/roofitcore/test/testRooAbsPdf.cxx
Labels: bug, in:RooFit/RooStats

#12172 TStorage: Remove functions marked obsolete since 6.02/00
  README/ReleaseNotes/v630/index.md
  core/base/inc/TStorage.h
  core/base/src/TStorage.cxx
  core/newdelete/src/NewDelete.cxx
Labels: improvement, in:Core Libraries

#12255 Backport the SaveAs MENU fix from master
  hist/hist/inc/TGraph.h
Labels: affects:6.28

#12256 [DF] Error out when TTreeIndex is used in distributed mode
  bindings/experimental/distrdf/python/DistRDF/HeadNode.py
  bindings/experimental/distrdf/test/test_headnode.py
Labels: in:RDataFrame

#12266 [webgeom] Remove dead code
  geom/webviewer/src/RGeomData.cxx
Labels: in:WebGui

#12280 [ntuple] Remove unneeded `RColumnElementBase::Generate<void>` instatiation
  tree/ntuple/v7/src/RColumnElement.cxx
Labels: in:RNTuple

#12288 [v6-28] Disable BZip2 in freetype on Windows
  cmake/modules/SearchInstalledSoftware.cmake
Labels: pr:backport

#12287 [RF] Correctly normalize max possible val in generation with proto data
  roofit/roofit/test/testRooKeysPdf.cxx
  roofit/roofitcore/src/RooGenContext.cxx
Labels: bug, in:RooFit/RooStats

#12313 [rbrowser] fix click in `RBrowser` on "@size" branch [6.28]
  gui/browsable/src/TLeafProvider.hxx
Labels: pr:backport, in:WebGui, affects:6.28

#12284 Support globbing with ?# treename token in TChain::Add
  tree/tree/src/TChain.cxx
  tree/tree/test/TChainParsing.cxx
Labels: in:TTree

#12304 HistFactory improvement: where appropriate, take titles from input objects
  roofit/histfactory/src/HistoToWorkspaceFactoryFast.cxx
Labels: in:RooFit/RooStats

#12318 [skip-ci] Improve example
  tutorials/hist/ratioplot1.C
Labels: improvement, in:Graphics

#12315 [geom] Extended TGeoVGShape with extra solids
  geom/geom/inc/TGeoTessellated.h
  geom/vecgeom/src/TGeoVGShape.cxx
  tutorials/CMakeLists.txt
  tutorials/geom/tessellatedNav.C
Labels: in:Geometry

#12324 Add missing TH1K::RetrieveBinContent
  hist/hist/inc/TH1K.h
Labels: bug, affects:master, in:Math Libraries

#12325 Add missing TH1K::RetrieveBinContent 6.28
  hist/hist/inc/TH1K.h
Labels: pr:backport, bug, in:Math Libraries, affects:6.28

#12330 [RF] Clearly mark `RooFit::CloneData()` as deprecated
  roofit/roofitcore/src/RooAbsPdf.cxx
  roofit/roofitcore/src/RooGlobalFunc.cxx
Labels: in:RooFit/RooStats

#12335 [cling] Set DataLayout from our TargetMachine
  interpreter/cling/lib/Interpreter/IncrementalJIT.cpp
Labels: in:Cling

#12348 [RF] Composition over inheritance in RooAbsMinimizerFcn implementations
  roofit/roofitcore/src/RooMinimizer.cxx
  roofit/roofitcore/src/RooMinimizerFcn.cxx
  roofit/roofitcore/src/RooMinimizerFcn.h
  roofit/roofitcore/src/TestStatistics/MinuitFcnGrad.cxx
  roofit/roofitcore/src/TestStatistics/MinuitFcnGrad.h
Labels: improvement, in:RooFit/RooStats

#12337 [cling] Backport fixes to TargetMachine and DataLayout
  interpreter/cling/lib/Interpreter/IncrementalJIT.cpp
Labels: pr:backport

#12353 [cling] Disable outline-atomics on AArch64
  interpreter/cling/lib/Interpreter/CIFactory.cpp
Labels: in:Cling

#12359 Improve TAttText::Modify
  core/base/src/TAttText.cxx
Labels: improvement, affects:master, in:Graphics

#12369 [tree] Avoid odr-using TTree::kMaxEntries (v6.28)
  tree/tree/src/InternalTreeUtils.cxx
Labels: pr:backport

#12371 [jsroot] fixes from 23/02/2023 [skip-ci]
  js/build/jsroot.js
  js/modules/base/BasePainter.mjs
  js/modules/core.mjs
  js/modules/gpad/TPadPainter.mjs
  js/modules/gui/menu.mjs
Labels: in:WebGui, affects:6.28

#12374 Fix webgui/qt5web cmake file [628] [skip-ci]
  tutorials/webgui/qt5web/CMakeLists.txt
Labels: affects:6.28

#12377 [ntuple,v6-28] RPageSinkBuf: add missing call to ReleasePage()
  tree/ntuple/v7/src/RPageSinkBuf.cxx
Labels: pr:backport, bug, in:RNTuple

#12385 [PyROOT] Only build RooFit and TMVA pythonizations if needed
  bindings/pyroot/pythonizations/CMakeLists.txt
Labels: pr:backport

#12393 [ntuple] improve unit testing of split encodings
  tree/ntuple/v7/test/ntuple_packing.cxx
Labels: in:RNTuple
