Repository root-project/root, pull requests merged in 2023-03, with the labels that each got.

#12411 Fix RVec masking (v6.28)
  math/vecops/inc/ROOT/RVec.hxx
Labels: pr:backport

#12360 [cling] Disable outline-atomics on AArch64 [v6.28]
  interpreter/cling/lib/Interpreter/CIFactory.cpp
Labels: pr:backport

#12440 [ntuple] Avoid warning about possibly uninitialized variable
  tree/ntuple/v7/src/RColumnElement.cxx
Labels: in:RNTuple

#12444 Change `clang-format` style to have line breaks in c'tor initializer
  .clang-format
Labels: pr:backport

#12447 [RF] Rewrite `RooProdPdf.TestGetPartIntList` unit test
  roofit/roofitcore/inc/RooProdPdf.h
  roofit/roofitcore/src/RooProdPdf.cxx
  roofit/roofitcore/test/testRooProdPdf.cxx
Labels: in:RooFit/RooStats

#12364 [CI] Add option to force builds from scratch
  .github/workflows/root-ci.yml
Labels: clean build

#12464 [v6-28][skip-ci][windows] Fix TDatime on Windows
  core/base/src/TDatime.cxx
Labels: pr:backport

#12466 [ntuple] RCollectionClassField: restore missing calls to `PushProxy()`
  tree/ntuple/v7/src/RField.cxx
Labels: bug, in:RNTuple

#12468 [ntuple] Fixes for 32bit / non-x86_64 builds
  tree/dataframe/src/RNTupleDS.cxx
  tree/ntuple/v7/inc/ROOT/RField.hxx
  tree/ntuple/v7/test/ntuple_extended.cxx
Labels: in:RNTuple

#12478 [CI] Fix nightly builds
  .github/workflows/root-ci.yml
Labels: affects:master

#12482 [RF] Enable analytic integration of RooHistPdfs with RooLinearVars
  roofit/roofitcore/inc/RooHistFunc.h
  roofit/roofitcore/inc/RooHistPdf.h
  roofit/roofitcore/src/RooHistFunc.cxx
  roofit/roofitcore/src/RooHistPdf.cxx
  roofit/roofitcore/test/CMakeLists.txt
  roofit/roofitcore/test/testRooHistPdf.cxx
Labels: improvement, in:RooFit/RooStats

#12503 [RF] Use `std::vector` diretly in RooVectorDataStore::RealFullVector
  roofit/roofitcore/inc/LinkDef.h
  roofit/roofitcore/inc/RooVectorDataStore.h
  roofit/roofitcore/src/RooVectorDataStore.cxx
  roofit/roofitcore/test/CMakeLists.txt
  roofit/roofitcore/test/dataSet_with_errors_6_26_10.root
  roofit/roofitcore/test/testRooDataSet.cxx
Labels: in:RooFit/RooStats

#12508 [v628] Allow splitting of TTime objects
  core/base/inc/LinkDef2.h
Labels: pr:backport

#12511 [RF] Add support for differentiating Gaussian integrals using AD.
  roofit/roofit/src/RooGaussian.cxx
  roofit/roofitcore/CMakeLists.txt
  roofit/roofitcore/inc/RooFit/Detail/AnalyticalIntegrals.h
  roofit/roofitcore/test/testRooFuncWrapper.cxx
Labels: in:RooFit/RooStats

#12476 Do not remove -Wp, before -D and -U when recording used compiler flags
  cmake/modules/RootConfiguration.cmake
Labels: priority:critical

#12516 Revert recent C++20 related modulemap commits
  interpreter/cling/include/cling/std.modulemap
Labels: pr:emergency🚨

#12349 Fix issue of multiple declaration of same objects in the saved C macros
  graf2d/gpad/src/TCanvas.cxx
  graf2d/gpad/src/TPad.cxx
Labels: affects:master, in:Graphics

#12538 [webgeom] add indicator for selected node
  geom/webviewer/inc/ROOT/RGeomData.hxx
  geom/webviewer/src/RGeomData.cxx
  ui5/geom/controller/GeomHierarchy.controller.js
  ui5/geom/model/GeomBrowserModel.js
Labels: affects:master, in:Geometry, in:WebGui

#12542 [ntuple] Fix misuse of the `TVirtualCollectionProxy` iterator interface
  tree/ntuple/v7/inc/ROOT/RField.hxx
  tree/ntuple/v7/test/SimpleCollectionProxy.hxx
Labels: bug, in:RNTuple

#12424 [TMVA] Resize method for RTensor
  tmva/tmva/inc/TMVA/RTensor.hxx
  tmva/tmva/test/rtensor.cxx
Labels: in:TMVA

#12529 [RF] Add initial interface and implementation for code-squashing.
  roofit/roofit/inc/RooGaussian.h
  roofit/roofit/src/RooGaussian.cxx
  roofit/roofitcore/CMakeLists.txt
  roofit/roofitcore/inc/RooAbsReal.h
  roofit/roofitcore/inc/RooAddition.h
  roofit/roofitcore/inc/RooConstVar.h
  roofit/roofitcore/inc/RooFit/Detail/CodeSquashContext.h
  roofit/roofitcore/inc/RooFit/Detail/EvaluateFuncs.h
  roofit/roofitcore/inc/RooFuncWrapper.h
  roofit/roofitcore/inc/RooNumber.h
  roofit/roofitcore/inc/RooProduct.h
  roofit/roofitcore/inc/RooRealIntegral.h
  roofit/roofitcore/inc/RooRealVar.h
  roofit/roofitcore/src/RooAbsReal.cxx
  roofit/roofitcore/src/RooAddition.cxx
  roofit/roofitcore/src/RooConstVar.cxx
  roofit/roofitcore/src/RooFuncWrapper.cxx
  roofit/roofitcore/src/RooNormalizedPdf.cxx
  roofit/roofitcore/src/RooNormalizedPdf.h
  roofit/roofitcore/src/RooNumber.cxx
  roofit/roofitcore/src/RooProduct.cxx
  roofit/roofitcore/src/RooRealIntegral.cxx
  roofit/roofitcore/src/RooRealVar.cxx
  roofit/roofitcore/test/testRooFuncWrapper.cxx
Labels: in:RooFit/RooStats

#12473 [ntuple,daos] Cast variable to preclude warning in 32-bit
  tree/ntuple/v7/inc/ROOT/RPageStorageDaos.hxx
Labels: in:RNTuple

#12563 [jsroot] 7.3.1 28/03/2023 [skip-ci] [6.28]
  js/build/jsroot.js
  js/changes.md
  js/modules/core.mjs
  js/modules/geom/TGeoPainter.mjs
  js/modules/hist2d/TH2Painter.mjs
  js/scripts/geoworker.js
Labels: in:WebGui, affects:6.28

#12554 [RF] Minor improvements to RooFit evaluation code generation
  roofit/roofit/inc/RooExponential.h
  roofit/roofit/src/RooExponential.cxx
  roofit/roofit/src/RooGaussian.cxx
  roofit/roofitcore/inc/RooFit/Detail/AnalyticalIntegrals.h
  roofit/roofitcore/inc/RooFit/Detail/CodeSquashContext.h
  roofit/roofitcore/inc/RooFit/Detail/EvaluateFuncs.h
  roofit/roofitcore/inc/RooFuncWrapper.h
  roofit/roofitcore/src/RooAddition.cxx
  roofit/roofitcore/src/RooFuncWrapper.cxx
  roofit/roofitcore/src/RooNormalizedPdf.cxx
  roofit/roofitcore/src/RooProduct.cxx
  roofit/roofitcore/test/testRooFuncWrapper.cxx
Labels: in:RooFit/RooStats

#12556 [RF] Don't add `weightVar` to observables in HistFactory
  roofit/histfactory/src/HistoToWorkspaceFactoryFast.cxx
Labels: in:RooFit/RooStats

#12571 [CI] Use root-user inside containers again
  .github/workflows/root-ci-config/build_root.py
  .github/workflows/root-ci.yml
Labels: clean build

#12587 [ntuple][skip-ci] Update `std::variant` section in specifications.md
  tree/ntuple/v7/doc/specifications.md
Labels: in:RNTuple

#12522 [ci] Print CMake cache vars for incr build. [skip-ci]
  .github/workflows/root-ci-config/build_root.py
Labels: pr:squash on merge
