Repository root-project/root, pull requests merged in 2023-11, with the labels that each got.

#13999 [tmva][sofie] Backport Fix in SOFIE GNN for senders/receivers
  bindings/pyroot/pythonizations/test/sofie_gnn.py
  tmva/sofie/inc/TMVA/RFunction.hxx
  tmva/sofie/inc/TMVA/SOFIE_common.hxx
  tmva/sofie/src/RFunction.cxx
  tmva/sofie/src/RModel_GNN.cxx
  tutorials/tmva/TMVA_SOFIE_GNN.py
Labels: pr:backport

#13987 [v630][RF] Yet another fix to bin-by-bin offsetting
  roofit/roofitcore/src/RooNLLVar.cxx
  roofit/roofitcore/src/RooNLLVarNew.cxx
Labels: pr:backport, bug, in:RooFit/RooStats

#13953 [graf2d] Apply `clang-tidy` suggestions
  graf2d/fitsio/src/TFITS.cxx
  graf2d/gpad/inc/TPad.h
  graf2d/gpad/src/TCanvas.cxx
  graf2d/gpad/src/TPad.cxx
  graf2d/gpadv7/inc/ROOT/RCanvas.hxx
  graf2d/gpadv7/inc/ROOT/RMenuItems.hxx
  graf2d/gpadv7/inc/ROOT/ROnFrameDrawable.hxx
  graf2d/gpadv7/inc/ROOT/RPad.hxx
  graf2d/gpadv7/inc/ROOT/RPadBase.hxx
  graf2d/gpadv7/inc/ROOT/RPadDisplayItem.hxx
  graf2d/gpadv7/inc/ROOT/RPadLength.hxx
  graf2d/gpadv7/inc/ROOT/TObjectDisplayItem.hxx
  graf2d/gpadv7/inc/ROOT/TObjectDrawable.hxx
  graf2d/gpadv7/src/RCanvas.cxx
  graf2d/gpadv7/src/RColor.cxx
  graf2d/gpadv7/src/RPadBase.cxx
  graf2d/gpadv7/src/RPalette.cxx
  graf2d/gpadv7/src/RVirtualCanvasPainter.cxx
  graf2d/graf/src/TBox.cxx
  graf2d/graf/src/TCandle.cxx
  graf2d/graf/src/TDiamond.cxx
  graf2d/graf/src/TEllipse.cxx
  graf2d/graf/src/TGaxis.cxx
  graf2d/graf/src/TLegend.cxx
  graf2d/graf/src/TLine.cxx
  graf2d/graf/src/TPaveText.cxx
  graf2d/graf/src/TPie.cxx
  graf2d/mathtext/inc/fontembed.h
  graf2d/mathtext/inc/mathrender.h
  graf2d/mathtext/src/fontembed.cxx
  graf2d/mathtext/src/fontembedps.cxx
  graf2d/mathtext/src/mathrender.cxx
  graf2d/mathtext/src/mathrenderstyle.cxx
  graf2d/mathtext/src/mathtextparse.cxx
  graf2d/mathtext/src/mathtextview.cxx
  graf2d/postscript/src/TPDF.cxx
  graf2d/win32gdk/inc/TGWin32VirtualXProxy.h
  graf2d/x11/src/GX11Gui.cxx
  graf2d/x11/src/Rotated.cxx
  graf2d/x11/src/TGX11.cxx
Labels: in:Graphics

#13995 Fix cmake/modules/FindZeroMQ.cmake
  cmake/modules/FindZeroMQ.cmake
Labels: in:Build System

#14019 [relnotes] SOFIE changes and implementations for v630
  README/ReleaseNotes/v630/index.md
Labels: in:TMVA

#11826 [mathcore] Delete obscure conditions in class for adaptive quadrature integration in multi-dimensions (AdaptiveIntegratorMultiDim)
  math/mathcore/src/AdaptiveIntegratorMultiDim.cxx
Labels: in:Math Libraries

#14021 [RF] RooTruthModel analytical integrals for general integration ranges
  roofit/roofitcore/inc/RooTruthModel.h
  roofit/roofitcore/src/RooAbsAnaConvPdf.cxx
  roofit/roofitcore/src/RooTruthModel.cxx
  roofit/roofitcore/test/CMakeLists.txt
  roofit/roofitcore/test/testRooTruthModel.cxx
Labels: bug, in:RooFit/RooStats

#14033 Fix drawing of the TPaveText label
  graf2d/graf/src/TPaveText.cxx
Labels: affects:master, in:Graphics

#14011 [tree] Apply suggestions from clang-tidy
  tree/dataframe/inc/ROOT/RDF/InterfaceUtils.hxx
  tree/dataframe/inc/ROOT/RDF/RInterface.hxx
  tree/dataframe/inc/ROOT/RDF/RInterfaceBase.hxx
  tree/dataframe/inc/ROOT/RDataFrame.hxx
  tree/dataframe/src/RArrowDS.cxx
  tree/dataframe/src/RDFHelpers.cxx
  tree/dataframe/src/RDFHistoModels.cxx
  tree/dataframe/src/RDFInterfaceUtils.cxx
  tree/dataframe/src/RDFUtils.cxx
  tree/dataframe/src/RDataFrame.cxx
  tree/dataframe/src/RLoopManager.cxx
  tree/dataframe/src/RSqliteDS.cxx
  tree/dataframe/src/RVariationsDescription.cxx
  tree/dataframe/test/dataframe_datasetspec.cxx
  tree/dataframe/test/dataframe_simple.cxx
  tree/dataframe/test/dataframe_snapshot.cxx
  tree/dataframe/test/dataframe_vary.cxx
  tree/ntuple/v7/inc/ROOT/RColumnElement.hxx
  tree/ntuple/v7/inc/ROOT/RField.hxx
  tree/ntuple/v7/inc/ROOT/RNTuple.hxx
  tree/ntuple/v7/inc/ROOT/RNTupleZip.hxx
  tree/ntuple/v7/src/RClusterPool.cxx
  tree/ntuple/v7/src/RField.cxx
  tree/ntuple/v7/src/RMiniFile.cxx
  tree/ntuple/v7/src/RNTupleDescriptorFmt.cxx
  tree/ntuple/v7/src/RPageSinkBuf.cxx
  tree/ntuple/v7/src/RPageSourceFriends.cxx
  tree/ntuple/v7/src/RPageStorage.cxx
  tree/ntuple/v7/test/ntuple_basics.cxx
  tree/ntuple/v7/test/ntuple_modelext.cxx
  tree/ntupleutil/v7/inc/ROOT/RNTupleImporter.hxx
  tree/ntupleutil/v7/src/RNTupleImporter.cxx
  tree/ntupleutil/v7/src/RNTupleInspector.cxx
  tree/ntupleutil/v7/test/ntuple_inspector.cxx
Labels: in:TTree

#14035 [ntuple] Update comment in ntpl004_dimuon.C
  tutorials/v7/ntuple/ntpl004_dimuon.C
Labels: in:RNTuple

#13313 Changed filters used by RBatchGenerator to a single string
  bindings/pyroot/pythonizations/python/ROOT/_pythonization/_tmva/_batchgenerator.py
  tmva/tmva/inc/TMVA/RBatchGenerator.hxx
  tmva/tmva/inc/TMVA/RChunkLoader.hxx
Labels: in:PyROOT

#13373 [cmake] Bump minimum CMake version
  cmake/scripts/RootUseFile.cmake.in
  graf2d/asimage/src/libAfterImage/CMakeLists.txt
  math/genetic/test/CMakeLists.txt
  math/minuit2/CMakeLists.txt
  math/minuit2/StandAlone.cmake
  math/minuit2/examples/simple/CMakeLists.txt
  math/minuit2/test/CMakeLists.txt
  test/CMakeLists.txt
  test/RootShower/CMakeLists.txt
  test/periodic/CMakeLists.txt
  tutorials/CMakeLists.txt
  tutorials/tree/dictionary/CMakeLists.txt
  tutorials/webgui/qtweb/CMakeLists.txt
Labels: in:Build System

#13299 counterpart of Python's join function in C++
  core/foundation/inc/ROOT/StringUtils.hxx
  core/foundation/test/testStringUtils.cxx
Labels: in:Core Libraries

#14043 [DF] Avoid public dependency of RDataFrame on `nlohmann::json`
  tree/dataframe/CMakeLists.txt
  tree/dataframe/inc/ROOT/RDF/RMetaData.hxx
  tree/dataframe/src/RMetaData.cxx
Labels: in:Build System, in:RDataFrame

#14044 [DF] Avoid unused parameter warning in RDF ActionHelpers
  tree/dataframe/inc/ROOT/RDF/ActionHelpers.hxx
Labels: in:RDataFrame

#12375 Use consistent wording of the comments in the different TMVA classification tests to avoid confusion
  tutorials/tmva/TMVA_CNN_Classification.py
  tutorials/tmva/TMVA_RNN_Classification.C
  tutorials/tmva/TMVA_RNN_Classification.py
Labels: in:TMVA

#9651 [TMVA] fix some inconsistencies and warnings found by doxygen
  tmva/sofie/README.md
  tmva/tmva/inc/TMVA/DNN/Architectures/Cuda.h
  tmva/tmva/inc/TMVA/DNN/Architectures/Reference.h
  tmva/tmva/inc/TMVA/Executor.h
  tmva/tmva/src/DNN/Architectures/Cpu/ActivationFunctions.hxx
  tmva/tmva/src/DNN/Architectures/Cpu/Dropout.hxx
  tmva/tmva/src/DNN/Architectures/Cpu/Initialization.hxx
  tmva/tmva/src/DNN/Architectures/Cpu/OutputFunctions.hxx
  tmva/tmva/src/DNN/Architectures/Cpu/Propagation.hxx
  tmva/tmva/src/DNN/Architectures/Reference/ActivationFunctions.hxx
  tmva/tmva/src/DNN/Architectures/Reference/Dropout.hxx
  tmva/tmva/src/MethodPDERS.cxx
Labels: improvement, in:Documentation, in:TMVA

#14060 [TMVA] Remove workaround from the CINT era
  tmva/tmva/inc/TMVA/Reader.h
  tmva/tmva/src/Reader.cxx
  tutorials/tmva/TMVAClassificationApplication.C
  tutorials/tmva/TMVAClassificationCategoryApplication.C
Labels: in:TMVA

#14063 Change default TColor resolution
  core/base/src/TColor.cxx
Labels: affects:master, in:Graphics

#13748 [hist] Avoid `try-catch` in TH1
  hist/hist/inc/TH1.h
  hist/hist/src/TH1.cxx
Labels: in:Math Libraries

#14071 [RF] Deprecate RooFit legacy iterators
  README/ReleaseNotes/v632/index.md
  roofit/roofitcore/inc/RooAbsArg.h
  roofit/roofitcore/inc/RooAbsCollection.h
  roofit/roofitcore/inc/RooWorkspace.h
  roofit/roofitcore/src/RooWorkspace.cxx
Labels: in:RooFit/RooStats

#14069 [ntuple] Add support for `std::unordered_set` fields
  tree/ntuple/v7/inc/ROOT/RField.hxx
  tree/ntuple/v7/src/RField.cxx
  tree/ntuple/v7/test/CustomStruct.hxx
  tree/ntuple/v7/test/CustomStructLinkDef.h
  tree/ntuple/v7/test/ntuple_types.cxx
Labels: new feature, in:RNTuple

#14072 [ntuple] Move STL dictionary entries to separate file
  tree/ntuple/v7/test/CMakeLists.txt
  tree/ntuple/v7/test/CustomStructLinkDef.h
  tree/ntuple/v7/test/ProxiedSTLContainer.hxx
  tree/ntuple/v7/test/ProxiedSTLContainerLinkDef.h
Labels: in:RNTuple

#14020 [v6-28] Backport Cocoa
  graf2d/cocoa/src/QuartzWindow.mm
  graf2d/cocoa/src/ROOTOpenGLView.mm
  graf2d/cocoa/src/TGCocoa.mm
Labels: pr:backport, in:Graphics

#12705 Don't check CMAKE_GENERATOR use MSVC instead
  cmake/modules/RootMacros.cmake
Labels: in:Build System

#14081 [webgui] use loopback by default [6.28]
  config/rootrc.in
Labels: pr:backport, in:WebGui, affects:6.28

#14079 [webgui] use loopback by default
  config/rootrc.in
Labels: affects:master, in:WebGui

#14087 small improvements in sqlite3_prepare
  sql/sqlite/src/TSQLiteServer.cxx
Labels: affects:master, in:Other

#14090 [NFC][ntuple] Add `std::unordered_set` to specification
  tree/ntuple/v7/doc/specifications.md
Labels: in:RNTuple

#14083 [ntuple] Move includes in test helpers to correct header file
  tree/ntuple/v7/test/CustomStruct.hxx
  tree/ntuple/v7/test/ProxiedSTLContainer.hxx
Labels: in:RNTuple

#14089 [ntuple] Add support for `std::unordered_map` fields
  tree/ntuple/v7/doc/specifications.md
  tree/ntuple/v7/inc/ROOT/RField.hxx
  tree/ntuple/v7/src/RField.cxx
  tree/ntuple/v7/test/CustomStruct.hxx
  tree/ntuple/v7/test/ProxiedSTLContainer.hxx
  tree/ntuple/v7/test/ProxiedSTLContainerLinkDef.h
  tree/ntuple/v7/test/ntuple_types.cxx
Labels: new feature, in:RNTuple

#14095 [jsroot] update for 6.28 branch
  js/build/jsroot.js
  js/changes.md
  js/modules/core.mjs
  js/modules/hist/RH3Painter.mjs
  js/modules/hist/TH3Painter.mjs
  js/modules/hist2d/RH2Painter.mjs
  js/modules/hist2d/TH2Painter.mjs
  js/modules/tree.mjs
  js/scripts/geoworker.js
Labels: in:WebGui, affects:6.28

#14100 [CMake] Always build Minuit2
  cmake/modules/RootBuildOptions.cmake
  cmake/modules/RootConfiguration.cmake
  math/CMakeLists.txt
  math/mathcore/CMakeLists.txt
  math/mathcore/src/MinimizerOptions.cxx
  math/mathcore/test/CMakeLists.txt
  roofit/roostats/test/CMakeLists.txt
  tutorials/CMakeLists.txt
Labels: in:Build System, in:Math Libraries

#14034 Avoid memory blowup of TBufferMerger
  io/io/inc/ROOT/TBufferMerger.hxx
  io/io/src/TBufferMerger.cxx
  io/io/src/TBufferMergerFile.cxx
  io/io/test/TBufferMerger.cxx
Labels: in:I/O

#14092 [tmva] Fix cross entropy calculation for large input values
  tmva/tmva/src/DNN/Architectures/Cpu/LossFunctions.hxx
  tmva/tmva/src/DNN/Architectures/Cuda/Kernels.cuh
Labels: in:TMVA

#14008 [v630] Fix cmake/modules/FindZeroMQ.cmake
  cmake/modules/FindZeroMQ.cmake
Labels: pr:backport, in:Build System

#14080 [webgui] use loopback by default [6.30]
  config/rootrc.in
Labels: pr:backport, in:WebGui, affects:6.30

#14094 [webgui] improve handling of embed widgets [6.30]
  gui/webdisplay/src/RWebWindow.cxx
  gui/webdisplay/src/RWebWindowsManager.cxx
Labels: pr:backport, in:WebGui, affects:6.30

#14117 Fix fatal issues with cpack package names [6.30]
  cmake/modules/RootCPack.cmake
Labels: pr:backport

#14124 [webgui] always use loopback [6.26]
  gui/webdisplay/src/RWebWindowsManager.cxx
Labels: pr:backport, in:WebGui, affects:6.26

#14128 [webgui] use classical browser by default [6.26]
  cmake/modules/RootConfiguration.cmake
Labels: in:WebGui, affects:6.26

#14110 [cling] Handle variable templates in DeclUnloader
  interpreter/cling/lib/Interpreter/DeclUnloader.cpp
  interpreter/cling/lib/Interpreter/DeclUnloader.h
  interpreter/cling/test/ErrorRecovery/IncompleteType.C
Labels: in:Cling

#14115 [interpreter] Fix LLVM target selection
  interpreter/CMakeLists.txt
Labels: in:Cling

#14131 [ntuple] Rename `R*Info` classes to `R*Inspector`
  tree/ntupleutil/v7/inc/ROOT/RNTupleInspector.hxx
  tree/ntupleutil/v7/src/RNTupleInspector.cxx
  tree/ntupleutil/v7/test/ntuple_inspector.cxx
Labels: in:RNTuple

#14129 [ntuple] Throw exception when trying to load out-of-bounds entries
  tree/ntuple/v7/src/RColumn.cxx
  tree/ntuple/v7/src/RPageStorageDaos.cxx
  tree/ntuple/v7/src/RPageStorageFile.cxx
  tree/ntuple/v7/test/ntuple_friends.cxx
  tree/ntuple/v7/test/ntuple_show.cxx
  tree/ntuple/v7/test/ntuple_storage.cxx
  tree/ntuple/v7/test/ntuple_storage_daos.cxx
Labels: in:RNTuple
