Repository root-project/root, pull requests merged in 2023-06, with the labels that each got.

#12937 [webgui] support qt6 version when create embedding qualifier [skip-ci]
  gui/webdisplay/inc/ROOT/RWebDisplayArgs.hxx
  gui/webdisplay/src/RWebDisplayArgs.cxx
Labels: pr:backport, in:WebGui, affects:6.28

#12939 [jsroot] 7.3.x 2/06/2023 [skip-ci]
  js/build/jsroot.js
  js/changes.md
  js/modules/core.mjs
  js/modules/geom/TGeoPainter.mjs
  js/modules/hist2d/RH1Painter.mjs
  js/modules/tree.mjs
Labels: in:WebGui, affects:6.28

#12936 [RF] Improve Copy Constructor of HypoTestResult
  roofit/roostats/src/HypoTestResult.cxx
Labels: improvement, in:RooFit/RooStats

#12951 [windows] Fix the C++ notebooks on Windows (#12912)
  bindings/jupyroot/python/JupyROOT/helpers/cppcompleter.py
  bindings/jupyroot/python/JupyROOT/kernel/utils.py
Labels: pr:backport

#12950 [RF] Correctly reset y-axis limits after `RooCurve::shiftCurveToZero()`
  roofit/roofitcore/inc/RooCurve.h
  roofit/roofitcore/inc/RooPlotable.h
  roofit/roofitcore/src/RooCurve.cxx
Labels: improvement, in:RooFit/RooStats

#12969 [RF][HF] Add missing LinkDefs for systematics classes in HistFactory
  roofit/histfactory/inc/LinkDef.h
Labels: bug, in:RooFit/RooStats

#12974 [CMake] Add `-Wno-deprecated-non-prototype` to build unuran with Clang
  math/unuran/CMakeLists.txt
Labels: in:Build System

#12973 [RF][HF] Remove commented-out `Systematic` class from HistFactory
  roofit/histfactory/inc/LinkDef.h
  roofit/histfactory/inc/RooStats/HistFactory/Systematics.h
Labels: in:RooFit/RooStats

#12911 [PyROOT] Feature to initialise RooWorkspace objects in PyRoot using strings
  bindings/pyroot/pythonizations/python/ROOT/_pythonization/_roofit/_rooworkspace.py
  bindings/pyroot/pythonizations/test/roofit/rooworkspace.py
Labels: in:PyROOT, in:RooFit/RooStats

#12859 Updating RDatasetSpec docs with Cpp MWE
  tree/dataframe/src/RDatasetSpec.cxx
Labels: in:RDataFrame

#12984 [DF] Actually push back values, do not write to uninitialized memory (v6.28)
  tree/dataframe/inc/ROOT/RDF/InterfaceUtils.hxx
Labels: pr:backport

#12979 [ntuple] Rename `struct EmptyBase` and add to CustomStructLinkDef.h
  tree/ntuple/v7/test/CustomStruct.hxx
  tree/ntuple/v7/test/CustomStructLinkDef.h
  tree/ntuple/v7/test/ntuple_modelext.cxx
  tree/ntuple/v7/test/ntuple_types.cxx
Labels: bug, affects:master

#12980 [ntuple] Fix issue in `RPageSinkBuf::CommitClusterImpl()`
  tree/ntuple/v7/inc/ROOT/RPageSinkBuf.hxx
  tree/ntuple/v7/src/RPageSinkBuf.cxx
  tree/ntuple/v7/test/ntuple_storage.cxx
Labels: bug, affects:master

#12976 [skip-ci] doc fix.
  math/physics/src/TRolke.cxx
Labels: in:Documentation, in:Math Libraries

#12983 [v6-28][skip-ci][windows] Install also cfitsio.dll
  cmake/modules/SearchInstalledSoftware.cmake
Labels: pr:backport

#12990 [ntuple] Use references in RPageSinkBuf
  tree/ntuple/v7/inc/ROOT/RPageSinkBuf.hxx
  tree/ntuple/v7/src/RPageSinkBuf.cxx
Labels: in:RNTuple

#13023 [ntuple] Temporarily disable the `RNTuple.SmallClusters` test
  tree/ntuple/v7/test/ntuple_extended.cxx
Labels: in:RNTuple

#13028 [v6.28][cmake][windows] Use standard ${PYTHON_LIBRARIES} on Windows
  bindings/jupyroot/CMakeLists.txt
  bindings/pyroot/cppyy/CPyCppyy/CMakeLists.txt
Labels: pr:backport

#13029 [math] Add missing `<limits>` include to `Delaunay2D.cxx`
  math/mathcore/src/Delaunay2D.cxx
Labels: in:Math Libraries, pr:emergency🚨

#13024 [RF] Avoid RooBinWidthFunction in final likelihood computation graphs
  roofit/roofitcore/inc/RooBinWidthFunction.h
  roofit/roofitcore/inc/RooFit/Detail/NormalizationHelpers.h
  roofit/roofitcore/src/RooAbsPdf.cxx
  roofit/roofitcore/src/RooBinWidthFunction.cxx
  roofit/roofitcore/src/RooNLLVarNew.cxx
  roofit/roofitcore/src/RooSimultaneous.cxx
Labels: in:RooFit/RooStats

#13033 [RF] Update RooAbsCollection.cxx - fix invalid read bug in remove
  roofit/roofitcore/src/RooAbsCollection.cxx
Labels: bug, in:RooFit/RooStats

#12970 [CMake] Add warning for the `minuit2_omp` or `minuit2_mpi` build options
  cmake/modules/RootBuildOptions.cmake
Labels: in:Build System, in:Math Libraries

#13043 [RF] Use `RooFit::OwningPtr<T>` in RooFit data generation functions
  roofit/multiprocess/test/utils.h
  roofit/roofitcore/inc/RooAbsPdf.h
  roofit/roofitcore/inc/RooSimultaneous.h
  roofit/roofitcore/src/RooAbsPdf.cxx
  roofit/roofitcore/src/RooAbsReal.cxx
  roofit/roofitcore/src/RooMCStudy.cxx
  roofit/roofitcore/src/RooSimultaneous.cxx
  roofit/roofitcore/test/TestStatistics/testLikelihoodSerial.cxx
  roofit/roofitcore/test/testGlobalObservables.cxx
  roofit/roofitcore/test/testRooProdPdf.cxx
  roofit/roofitcore/test/testRooSimultaneous.cxx
  roofit/roostats/inc/RooStats/ToyMCSampler.h
  roofit/roostats/src/BayesianCalculator.cxx
  roofit/roostats/src/PdfProposal.cxx
  roofit/roostats/src/ToyMCImportanceSampler.cxx
  roofit/roostats/src/ToyMCSampler.cxx
  roofit/xroofit/src/xRooFit.cxx
  test/stressHistFactory_tests.cxx
  test/stressRooStats_models.h
  test/stressRooStats_tests.h
Labels: in:RooFit/RooStats

#13046 [cxxmodules] Avoid loading more modules while instantiating templates
  core/metacling/src/TClingCallbacks.cxx
Labels: in:C++ modules

#13050 [cxxmodules] Avoid loading more modules while instantiating templates [v6.28]
  core/metacling/src/TClingCallbacks.cxx
Labels: pr:backport

#13061 Fix YML syntax in github templates
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/ISSUE_TEMPLATE/improvement_report.yml
Labels: pr:emergency🚨

#12996 Initial support for building on FreeBSD
  build/unix/compiledata.sh
  cmake/modules/CheckCompiler.cmake
  cmake/modules/SetUpFreeBSD.cmake
  config/root-config.in
  core/CMakeLists.txt
  core/dictgen/src/rootcling_impl.cxx
  core/foundation/inc/ThreadLocalStorage.h
  core/foundation/src/FoundationUtils.cxx
  core/metacling/src/CMakeLists.txt
  core/metacling/src/TCling.cxx
  core/metacling/src/rootclingTCling.cxx
  core/rootcling_stage1/CMakeLists.txt
  core/unix/CMakeLists.txt
  core/unix/src/TUnixSystem.cxx
  etc/Makefile.arch
  interpreter/cling/lib/Interpreter/DynamicLibraryManagerSymbol.cpp
  interpreter/cling/lib/Utils/PlatformPosix.cpp
  io/io/src/TFile.cxx
  net/auth/CMakeLists.txt
  net/rpdutils/CMakeLists.txt
  rootx/CMakeLists.txt
  rootx/src/rootx.cxx
Labels: pr:squash on merge

#13094 Describe what Schema Extension actually has in RNTuple
  tree/ntuple/v7/doc/specifications.md
Labels: in:RNTuple

#13072 TClingUtils: Remove HackForDefaultTemplateArg
  core/clingutils/src/TClingUtils.cxx
  interpreter/llvm-project/clang/include/clang/AST/ASTContext.h
  interpreter/llvm-project/clang/lib/AST/ASTContext.cpp
  interpreter/llvm-project/clang/lib/Sema/HackForDefaultTemplateArg.h
  interpreter/llvm-project/clang/lib/Sema/SemaCXXScopeSpec.cpp
  interpreter/llvm-project/clang/lib/Sema/SemaTemplate.cpp
  interpreter/llvm-project/clang/lib/Sema/SemaTemplateInstantiate.cpp
  interpreter/llvm-project/clang/lib/Sema/TreeTransform.h
  interpreter/llvm-project/llvm-project.tag
Labels: in:Cling

#13097 [webgui] detect available browser when producing image
  gui/webdisplay/src/RWebDisplayHandle.cxx
Labels: affects:master, in:WebGui

#13105 [rbrowser] use TWebCanvas in async mode
  gui/browserv7/src/RBrowserTCanvasWidget.cxx
Labels: affects:master, in:WebGui

#13113 [rbrowser] use TWebCanvas in async mode [6.28]
  gui/browserv7/src/RBrowserTCanvasWidget.cxx
Labels: pr:backport, in:WebGui, affects:6.28

#13116 [webcanvas] fix update optimization
  gui/webgui6/src/TWebCanvas.cxx
Labels: affects:master, in:Graphics, in:WebGui

#13117 [webcanvas] fix update optimization [6.28]
  gui/webgui6/src/TWebCanvas.cxx
Labels: pr:backport, in:Graphics, in:WebGui, affects:6.28

#13119 [treeplayer] fix compiler warnings concerning enum combination
  tree/treeplayer/src/TFormLeafInfo.cxx
  tree/treeplayer/src/TTreeFormula.cxx
Labels: affects:master, in:TTree

#13003 [cmake] Allow bringing up-to-date an existing roottest repository
  .github/workflows/root-ci-config/buildconfig/global.txt
  CMakeLists.txt
Labels: in:Build System

#13114 Remove checks for deprecated _REENTRANT macro
  cmake/modules/SetUpFreeBSD.cmake
  config/root-config.in
  core/base/inc/TVirtualMutex.h
  core/base/inc/TVirtualRWMutex.h
  core/base/src/TDatime.cxx
  core/base/src/TSystem.cxx
  core/base/src/TTimeStamp.cxx
  core/cont/inc/TCollection.h
  core/meta/inc/TInterpreter.h
  core/thread/src/TThread.cxx
  graf2d/x11/src/GX11Gui.cxx
  interpreter/cling/lib/Interpreter/CIFactory.cpp
  net/net/src/TS3HTTPRequest.cxx
  net/rpdutils/src/error.cxx
  rootx/src/rootx.cxx
Labels: in:Core Libraries

#13135 [tmva] fix capture warning from c++20
  tmva/tmva/src/Classification.cxx
Labels: affects:master, in:TMVA

#13141 [eve] Fix TGCompositeFrame flags - c++20 warnings
  graf3d/eve/src/TEveDigitSetEditor.cxx
Labels: affects:master
