Repository root-project/root, pull requests merged in 2024-05, with the labels that each got.

#15389 [skip-ci][ci] Remove Fedora 38 builds
  .github/workflows/root-ci-config/buildconfig/fedora38.txt
  .github/workflows/root-ci.yml
Labels: backport v6-32-00-patches

#15390 [ci] Remove Fedora 38 builds
  .github/workflows/root-ci-config/buildconfig/fedora38.txt
  .github/workflows/root-ci.yml
Labels: backport v6-30-00-patches

#15391 [ci] Remove Fedora 38 builds
  .github/workflows/root-ci-config/buildconfig/fedora38.txt
  .github/workflows/root-ci.yml
Labels: backport v6-28-00-patches

#15264 Reduce the memory footprint of the computation graph
  tree/dataframe/CMakeLists.txt
  tree/dataframe/inc/ROOT/RDF/GraphNode.hxx
  tree/dataframe/inc/ROOT/RDF/RAction.hxx
  tree/dataframe/inc/ROOT/RDF/RColumnRegister.hxx
  tree/dataframe/inc/ROOT/RDF/RDefinePerSample.hxx
  tree/dataframe/inc/ROOT/RDF/RDefineReader.hxx
  tree/dataframe/inc/ROOT/RDF/RFilter.hxx
  tree/dataframe/inc/ROOT/RDF/RInterface.hxx
  tree/dataframe/inc/ROOT/RDF/RInterfaceBase.hxx
  tree/dataframe/inc/ROOT/RDF/RLoopManager.hxx
  tree/dataframe/inc/ROOT/RDF/RRange.hxx
  tree/dataframe/inc/ROOT/RDF/RVariationReader.hxx
  tree/dataframe/inc/ROOT/RDF/RVariedAction.hxx
  tree/dataframe/src/RDFColumnRegister.cxx
  tree/dataframe/src/RDFGraphUtils.cxx
  tree/dataframe/src/RDFInterfaceUtils.cxx
  tree/dataframe/src/RDefineReader.cxx
  tree/dataframe/src/RInterfaceBase.cxx
  tree/dataframe/src/RJittedFilter.cxx
  tree/dataframe/src/RLoopManager.cxx
  tree/dataframe/src/RVariationReader.cxx
  tree/dataframe/test/dataframe_utils.cxx
Labels: in:RDataFrame

#15404 [PyROOT] Merge `libROOTPythonizations` and `libJupyROOT`
  bindings/jupyroot/CMakeLists.txt
  bindings/jupyroot/python/JupyROOT/helpers/handlers.py
  bindings/pyroot/pythonizations/src/IOHandler.cxx
  bindings/pyroot/pythonizations/src/PyROOTModule.cxx
Labels: in:PyROOT

#15411 [reve] backport to v6-32-00-patches t fix rendering of REveBoxSet
  builtins/rendercore/RenderCore-1.2.tar.gz
  builtins/rendercore/RenderCore-1.3.tar.gz
  cmake/modules/SearchInstalledSoftware.cmake
Labels: in:WebGui, affects:6.32

#12202 [RF] LikelihoodJob improved precision
  roofit/multiprocess/src/Job.cxx
  roofit/roofitcore/CMakeLists.txt
  roofit/roofitcore/inc/RooFit/TestStatistics/LikelihoodGradientWrapper.h
  roofit/roofitcore/inc/RooFit/TestStatistics/LikelihoodWrapper.h
  roofit/roofitcore/inc/RooFit/TestStatistics/SharedOffset.h
  roofit/roofitcore/src/TestStatistics/LikelihoodGradientJob.cxx
  roofit/roofitcore/src/TestStatistics/LikelihoodGradientJob.h
  roofit/roofitcore/src/TestStatistics/LikelihoodGradientWrapper.cxx
  roofit/roofitcore/src/TestStatistics/LikelihoodJob.cxx
  roofit/roofitcore/src/TestStatistics/LikelihoodJob.h
  roofit/roofitcore/src/TestStatistics/LikelihoodSerial.cxx
  roofit/roofitcore/src/TestStatistics/LikelihoodSerial.h
  roofit/roofitcore/src/TestStatistics/LikelihoodWrapper.cxx
  roofit/roofitcore/src/TestStatistics/MinuitFcnGrad.cxx
  roofit/roofitcore/src/TestStatistics/MinuitFcnGrad.h
  roofit/roofitcore/src/TestStatistics/SharedOffset.cxx
  roofit/roofitcore/test/TestStatistics/testLikelihoodGradientJob.cxx
  roofit/roofitcore/test/TestStatistics/testLikelihoodJob.cxx
  roofit/roofitcore/test/TestStatistics/testLikelihoodSerial.cxx
Labels: in:RooFit/RooStats

#15402 [PyROOT] Integrate JsMVA into PyROOT
  bindings/CMakeLists.txt
  bindings/jsmva/CMakeLists.txt
  bindings/pyroot/pythonizations/CMakeLists.txt
  bindings/pyroot/pythonizations/python/ROOT/JsMVA/DataLoader.py
  bindings/pyroot/pythonizations/python/ROOT/JsMVA/Factory.py
  bindings/pyroot/pythonizations/python/ROOT/JsMVA/JPyInterface.py
  bindings/pyroot/pythonizations/python/ROOT/JsMVA/JsMVAMagic.py
  bindings/pyroot/pythonizations/python/ROOT/JsMVA/OutputTransformer.py
  bindings/pyroot/pythonizations/python/ROOT/JsMVA/__init__.py
  bindings/pyroot/pythonizations/python/ROOT/__init__.py
Labels: in:PyROOT

#15416 [CMake] Only build `clad` plugin if requested
  interpreter/cling/tools/plugins/CMakeLists.txt
Labels: in:Build System

#15424 [PyROOT] Correct JsMVA module path and always include JsMVA in build
  bindings/pyroot/pythonizations/CMakeLists.txt
  bindings/pyroot/pythonizations/python/ROOT/JsMVA/__init__.py
Labels: in:PyROOT

#15417 [core] Fallback to urandom for increased compatibility
  core/unix/CMakeLists.txt
  core/unix/src/TUnixSystem.cxx
Labels: in:Core Libraries

#15431 [cling] Fix build with assertions
  interpreter/cling/lib/Interpreter/IncrementalParser.cpp
Labels: priority:high, in:Cling

#15432 [TCling] Separate test for GetCppName
  core/clingutils/test/TClingUtilsTests.cxx
Labels: in:Cling

#15428 [ntuple] reduce number of open files in RDF source
  tree/dataframe/src/RNTupleDS.cxx
Labels: in:RDataFrame, in:RNTuple

#15436 [BP][632] Enable Fortran for Win and Linux
  .github/workflows/root-ci-config/buildconfig/global.txt
  .github/workflows/root-ci-config/buildconfig/mac-beta.txt
  .github/workflows/root-ci-config/buildconfig/mac12.txt
  .github/workflows/root-ci-config/buildconfig/mac13.txt
  .github/workflows/root-ci-config/buildconfig/mac14.txt
Labels: pr:backport

#15376 [PyROOT] Don't import `libcppyy` directly in PyROOT
  bindings/pyroot/pythonizations/python/ROOT/_facade.py
  bindings/pyroot/pythonizations/python/ROOT/_pythonization/_cppinstance.py
  bindings/pyroot/pythonizations/python/ROOT/_pythonization/_drawables.py
  bindings/pyroot/pythonizations/python/ROOT/_pythonization/_rdf_pyz.py
  bindings/pyroot/pythonizations/python/ROOT/_pythonization/_roofit/_rooabscollection.py
  bindings/pyroot/pythonizations/python/ROOT/_pythonization/_roofit/_utils.py
  bindings/pyroot/pythonizations/python/ROOT/_pythonization/_tfile.py
  bindings/pyroot/pythonizations/python/ROOT/_pythonization/_tseqcollection.py
  bindings/pyroot/pythonizations/src/PyROOTModule.cxx
  bindings/pyroot/pythonizations/test/tcollection_iterable.py
  bindings/pyroot/pythonizations/test/tcollection_listmethods.py
  bindings/pyroot/pythonizations/test/tcollection_operators.py
  bindings/pyroot/pythonizations/test/tdirectory_attrsyntax.py
  bindings/pyroot/pythonizations/test/tdirectoryfile_attrsyntax_get.py
  bindings/pyroot/pythonizations/test/tfile_attrsyntax_get_writeobject_open.py
  bindings/pyroot/pythonizations/test/titer_iterator.py
  bindings/pyroot/pythonizations/test/tobject_contains.py
  bindings/pyroot/pythonizations/test/tseqcollection_itemaccess.py
  bindings/pyroot/pythonizations/test/tseqcollection_listmethods.py
  bindings/pyroot/pythonizations/test/ttree_branch_attr.py
  bindings/pyroot/pythonizations/test/ttree_iterable.py
  bindings/pyroot/pythonizations/test/ttree_setbranchaddress.py
Labels: in:PyROOT

#15408 TEnum::GetEnum normalize name before search.
  core/meta/src/TEnum.cxx
Labels: affects:master, in:Core Libraries, affects:6.32, backport v6-32-00-patches

#15243 [ntuple] Add option to turn off tail page optimization
  tree/ntuple/v7/inc/ROOT/RColumn.hxx
  tree/ntuple/v7/inc/ROOT/RNTupleWriteOptions.hxx
  tree/ntuple/v7/src/RColumn.cxx
  tree/ntuple/v7/test/ntuple_storage.cxx
Labels: in:RNTuple

#15224 [RF] Fix computation graphs with RooParamHistFunc
  README/ReleaseNotes/v632/index.md
  roofit/roofit/inc/RooParamHistFunc.h
  roofit/roofit/src/RooParamHistFunc.cxx
  roofit/roofit/test/testRooParamHistFunc.cxx
  tutorials/roofit/rf709_BarlowBeeston.C
  tutorials/roofit/rf709_BarlowBeeston.py
Labels: bug, in:RooFit/RooStats

#15439 [TMVA] Enable again all tests on `alma9` and `fedora39`
  .github/workflows/root-ci-config/buildconfig/alma9.txt
  .github/workflows/root-ci-config/buildconfig/fedora39.txt
  tutorials/CMakeLists.txt
Labels: in:TMVA

#15420 [CMake] Look for Python3 again in `SearchInstalledSoftware.cmake`
  CMakeLists.txt
  bindings/experimental/distrdf/CMakeLists.txt
  bindings/jupyroot/CMakeLists.txt
  bindings/pyroot/cppyy/CPyCppyy/CMakeLists.txt
  bindings/pyroot/cppyy/cppyy-backend/CMakeLists.txt
  bindings/pyroot/cppyy/cppyy-backend/cling/python/cppyy_backend/cmake/FindCppyy.cmake
  bindings/pyroot/cppyy/cppyy/CMakeLists.txt
  bindings/pyroot/pythonizations/CMakeLists.txt
  bindings/pyroot/pythonizations/test/CMakeLists.txt
  cmake/modules/FindDask.cmake
  cmake/modules/FindPySpark.cmake
  cmake/modules/RootBuildOptions.cmake
  cmake/modules/RootConfiguration.cmake
  cmake/modules/RootMacros.cmake
  cmake/modules/SearchInstalledSoftware.cmake
  cmake/modules/SearchRootCoreDeps.cmake
  cmake/scripts/ROOTConfig.cmake.in
  documentation/doxygen/Makefile
  documentation/doxygen/filter.cxx
  documentation/doxygen/makeNotebooks.sh
  etc/notebook/kernels/root/kernel.json.in
  interpreter/CMakeLists.txt
  interpreter/cling/CMakeLists.txt
  main/CMakeLists.txt
  tutorials/CMakeLists.txt
Labels: in:Build System, in:PyROOT

#15449 [RF] Implement code generation for `RooCBShape`
  roofit/roofit/inc/RooCBShape.h
  roofit/roofit/src/RooCBShape.cxx
  roofit/roofitcore/inc/RooFit/Detail/AnalyticalIntegrals.h
  roofit/roofitcore/inc/RooFit/Detail/EvaluateFuncs.h
  roofit/roofitcore/test/testRooFuncWrapper.cxx
Labels: in:RooFit/RooStats

#15445 [BP][v6.32] TEnum::GetEnum normalize name before search.
  core/meta/src/TEnum.cxx
Labels: pr:backport

#15283 [tree] raise error instead of crash when trying to access null GetTree
  tree/treeplayer/src/TTreeFormula.cxx
Labels: in:TTree

#15455 [RF] Update xroofit
  roofit/xroofit/inc/RooFit/xRooFit/xRooFit.h
  roofit/xroofit/src/xRooFit.cxx
  roofit/xroofit/src/xRooFitVersion.h
  roofit/xroofit/src/xRooNLLVar.cxx
  roofit/xroofit/src/xRooNode.cxx
Labels: in:RooFit/RooStats

#15287 remove repeatative divisions in TDecompChol::Decompose
  math/matrix/src/TDecompChol.cxx
Labels: in:Math Libraries

#15471 [CMake] Don't check if Python headers are found in `RootBuildOptions`
  cmake/modules/RootBuildOptions.cmake
Labels: priority:high, in:Build System, in:PyROOT

#15218 [cling] remove remnant declaration of removed function
  interpreter/cling/include/cling/Utils/Platform.h
Labels: in:Cling

#15485 [PyROOT] Report the exception type (instead of TypeError) is multiple overloads raise C++ exceptions of the same type
  bindings/pyroot/cppyy/CPyCppyy/src/Utility.cxx
Labels: bug, in:PyROOT

#15493 [tmva] Fix dependency of tutorials
  tutorials/CMakeLists.txt
Labels: in:TMVA

#15492 [ntuple] remove deprecated LinkDef statements
  tree/ntuple/v7/test/CustomStructLinkDef.h
  tree/ntuple/v7/test/ProxiedSTLContainerLinkDef.h
  tree/ntupleutil/inc/LinkDef.h
Labels: in:RNTuple

#15452 [webgui] strict check for HMAC signature
  gui/webdisplay/src/RWebWindow.cxx
Labels: affects:master, in:WebGui

#15453 [webgui] strict check for HMAC signature [6.32]
  gui/webdisplay/src/RWebWindow.cxx
Labels: pr:backport, in:WebGui, affects:6.32

#15488 [CMake] Move connection check for `clad` after RootBuildOptions
  CMakeLists.txt
Labels: in:Build System

#15497 Comply with CMP0148
  interpreter/CMakeLists.txt
  interpreter/cling/CMakeLists.txt
Labels: in:Cling

#15491 [RF] Support RooBernstein in code generation for AD
  roofit/roofit/inc/RooBernstein.h
  roofit/roofit/src/RooBernstein.cxx
  roofit/roofit/src/RooLandau.cxx
  roofit/roofit/test/testRooBernstein.cxx
  roofit/roofitcore/inc/RooFit/Detail/AnalyticalIntegrals.h
  roofit/roofitcore/inc/RooFit/Detail/EvaluateFuncs.h
  roofit/roofitcore/test/testRooFuncWrapper.cxx
Labels: in:RooFit/RooStats

#15475 RField: add vector.reserve() wherever we know the number of elements...
  tree/ntuple/v7/src/RField.cxx
Labels: in:RNTuple

#15505 [ntuple] run clang-format on RMiniFile.cxx
  tree/ntuple/v7/src/RMiniFile.cxx
Labels: in:RNTuple

#15507 [ntuple] Provide default RFieldBase::GenerateColumnsImpl
  tree/ntuple/v7/inc/ROOT/RField.hxx
Labels: in:RNTuple

#15515 [ntuple] Fix warning about hidden virtual function
  tree/ntuple/v7/inc/ROOT/RField.hxx
Labels: in:RNTuple

#15509 [ntuple] Provide method to estimate memory usage of model
  tree/ntuple/v7/inc/ROOT/RNTupleModel.hxx
  tree/ntuple/v7/src/RNTupleModel.cxx
  tree/ntuple/v7/test/CMakeLists.txt
  tree/ntuple/v7/test/ntuple_model.cxx
  tree/ntuple/v7/test/ntuple_model.py
Labels: in:RNTuple

#15518 [gpad] Change TCanvas::SetName() implementation
  graf2d/gpad/src/TCanvas.cxx
Labels: affects:master, in:Graphics

#15508 Builtin CFITSIO: 3.45 -> 4.4.0 to avoid indirect CURL dependency
  builtins/cfitsio/CMakeLists.txt
  builtins/cfitsio/cfitsio-no-find-zlib.diff
  builtins/cfitsio/no-fortran-wrapper.diff
  cmake/modules/FindCFITSIO.cmake
  cmake/modules/SearchInstalledSoftware.cmake
  graf2d/fitsio/CMakeLists.txt
Labels: in:Build System, clean build

#15519 [ntuple] fail gracefully for MakeField<T> on unsplit type
  tree/ntuple/v7/src/RField.cxx
  tree/ntuple/v7/test/rfield_unsplit.cxx
Labels: in:RNTuple

#15477 [df] Delete allocated node before throwing error
  tree/dataframe/src/RDFInterfaceUtils.cxx
Labels: in:RDataFrame

#15490 [RF] Move remaining RooFit tests in `test/` into `roofit/`
  roofit/roofit/test/CMakeLists.txt
  roofit/roofit/test/GaussFunction.h
  roofit/roofit/test/MinimizerTypes.h
  roofit/roofit/test/WrapperRooPdf.h
  roofit/roofit/test/testFitPerf.cxx
  roofit/roofit/test/testRooFit.cxx
  test/CMakeLists.txt
  test/fit/CMakeLists.txt
  test/fit/GaussFunction.h
Labels: in:RooFit/RooStats

#15466 [core] Update davix to 0.8.6 and openssl to 3.0.13
  builtins/davix/CMakeLists.txt
  builtins/openssl/CMakeLists.txt
  builtins/openssl/openssl-darwin64-aarch64-cc.diff
Labels: clean build

#15526 [rntuple] Default initialize data member of RNTupleLocator
  tree/ntuple/v7/inc/ROOT/RNTupleUtil.hxx
Labels: in:RNTuple

#15530 [BP][6.32][core] Upgrade openssl and davix builtin versions
  builtins/davix/CMakeLists.txt
  builtins/openssl/CMakeLists.txt
  builtins/openssl/openssl-darwin64-aarch64-cc.diff
Labels: pr:backport, clean build

#15527 [interpreter] Disable warnings when compiling LLVM / Clang
  interpreter/CMakeLists.txt
Labels: in:Build System

#15532 [RF] Disable RooNaNPacker.PackedNaNPreservedAfterArithmetic on Windows
  roofit/roofitcore/test/testNaNPacker.cxx
Labels: in:RooFit/RooStats

#15543 [RF] Optimize code generated from `PiecewiseInterpolation` for use in AD
  roofit/histfactory/src/PiecewiseInterpolation.cxx
  roofit/roofitcore/inc/RooHistFunc.h
Labels: improvement, in:RooFit/RooStats

#15546 [skip ci][BP][6.32][doc] Clarify current limitation of TMethodCall
  core/meta/src/TMethodCall.cxx
Labels: pr:backport

#15540 [ci] Enable distributed RDataFrame testing on MacOS
  .github/workflows/root-ci-config/buildconfig/mac-beta.txt
  .github/workflows/root-ci-config/buildconfig/mac13.txt
  .github/workflows/root-ci-config/buildconfig/mac14.txt
Labels: in:CI

#14419 [cmd] add recursive version of rootls
  main/python/cmdLineUtils.py
  main/python/rootls.py
Labels: in:PyROOT

#15547 [6.32] Backport of #15540
  .github/workflows/root-ci-config/buildconfig/mac-beta.txt
  .github/workflows/root-ci-config/buildconfig/mac13.txt
  .github/workflows/root-ci-config/buildconfig/mac14.txt
Labels: pr:backport

#15552 [BP][6.32] [cmd] add recursive version of rootls
  main/python/cmdLineUtils.py
  main/python/rootls.py
Labels: pr:backport

#15548 [6.30] Backport of #15540
  .github/workflows/root-ci-config/buildconfig/mac-beta.txt
  .github/workflows/root-ci-config/buildconfig/mac13.txt
  .github/workflows/root-ci-config/buildconfig/mac14.txt
Labels: pr:backport

#15568 [skip ci][ci] Simplify root 626 yml and run 6.26/8 nightlies every other day
  .github/workflows/root-626.yml
  .github/workflows/root-628.yml
Labels: in:CI

#10303 Ignore warnings
  core/testsupport/src/TestSupport.cxx
Labels: affects:master, in:RooFit/RooStats, affects:6.30

#15558 [RF] Rename RooPower and RooExpPoly to avoid clash with classes fom CMS
  README/ReleaseNotes/v632/index.md
  documentation/doxygen/images/RooLegacyExpPoly.png
  documentation/doxygen/images/RooPowerSum.png
  etc/RooFitHS3_wsexportkeys.json
  etc/RooFitHS3_wsfactoryexpressions.json
  roofit/hs3/src/JSONFactories_RooFitCore.cxx
  roofit/hs3/test/testRooFitHS3.cxx
  roofit/roofit/CMakeLists.txt
  roofit/roofit/inc/LinkDef1.h
  roofit/roofit/inc/RooLegacyExpPoly.h
  roofit/roofit/inc/RooPowerSum.h
  roofit/roofit/src/RooLegacyExpPoly.cxx
  roofit/roofit/src/RooPowerSum.cxx
  roofit/roofitcore/test/testTestStatistics.cxx
  tutorials/roofit/rf614_binned_fit_problems.C
  tutorials/roofit/rf614_binned_fit_problems.py
Labels: in:RooFit/RooStats

#13771 Support PCRE2
  bindings/pyroot/pythonizations/test/import_load_libs.py
  cmake/modules/FindPCRE2.cmake
  cmake/modules/SearchInstalledSoftware.cmake
  core/base/CMakeLists.txt
  core/base/src/TPRegexp.cxx
  tutorials/legacy/regexp/regexp.C
Labels: in:Build System, in:Core Libraries

#15502 [RF] Small fixup for using RooFit with new Clad 1.5
  roofit/histfactory/src/FlexibleInterpVar.cxx
  roofit/histfactory/src/PiecewiseInterpolation.cxx
  roofit/roofitcore/inc/RooFit/Detail/MathFuncs.h
Labels: in:RooFit/RooStats

#15587 [v632][RF] Small fixup for using RooFit with new Clad 1.5
  roofit/histfactory/src/FlexibleInterpVar.cxx
  roofit/histfactory/src/PiecewiseInterpolation.cxx
  roofit/roofitcore/inc/RooFit/Detail/MathFuncs.h
Labels: pr:backport

#15593 [hist] Comment unused parameter in TFormula
  hist/hist/src/TFormula.cxx
Labels: pr:backport

#15586 [v632] Support PCRE2
  bindings/pyroot/pythonizations/test/import_load_libs.py
  cmake/modules/FindPCRE2.cmake
  cmake/modules/SearchInstalledSoftware.cmake
  core/base/CMakeLists.txt
  core/base/src/TPRegexp.cxx
  tutorials/legacy/regexp/regexp.C
Labels: pr:backport

#15594 Don't use system giflib on macOS
  cmake/modules/SearchInstalledSoftware.cmake
Labels: clean build

#15595 [v632] Don't use system giflib on macOS
  cmake/modules/SearchInstalledSoftware.cmake
Labels: pr:backport

#15559 Add doc comments to R__ASSERT/CHECK
  core/foundation/inc/TError.h
Labels: in:Core Libraries

#12341 Simplify the platform-dependent part of a couple of add_custom_command
  CMakeLists.txt
Labels: in:Build System

#15598 Add REve notes [6.32] [skip-ci]
  README/ReleaseNotes/v632/index.md
  README/ReleaseNotes/v632/reve-boxset-cones.png
Labels: pr:backport, in:Documentation, affects:6.32

#15602 [CMake] Fix version detection in `FindCUDNN.cmake`
  cmake/modules/FindCUDNN.cmake
Labels: in:Build System

#15580 [ntuple] Make RNTupleFileWriter::Recreate/Append return unique_ptr
  tree/ntuple/v7/inc/ROOT/RMiniFile.hxx
  tree/ntuple/v7/src/RMiniFile.cxx
  tree/ntuple/v7/src/RPageStorageFile.cxx
  tree/ntuple/v7/test/ntuple_minifile.cxx
Labels: in:RNTuple

#15613 [geom] Fix registered identity matrix removal warning
  geom/geom/src/TGeoMatrix.cxx
Labels: affects:master

#15611 [v632][skip-ci] Update release notes
  README/ReleaseNotes/v632/index.md
Labels: pr:backport

#15591 io: Avoid infinite recursion in TFile::Open
  io/io/src/TFile.cxx
Labels: in:I/O

#15620 [tree] Avoid buffer overflow in TBranch
  tree/tree/src/TBranch.cxx
Labels: in:TTree

#15627 [6.30] Backport of #15620
  tree/tree/src/TBranch.cxx
Labels: pr:backport

#15629 [6.28] Backport of #15620
  tree/tree/src/TBranch.cxx
Labels: pr:backport

#15626 [6.32] Backport of #15620
  tree/tree/src/TBranch.cxx
Labels: pr:backport

#15628 [6.32] Backport of #15477
  tree/dataframe/src/RDFInterfaceUtils.cxx
Labels: pr:backport

#15631 [backport][632][tutorials][tmva] Fix a dependency issue with TMVA tutorials
  tutorials/CMakeLists.txt
  tutorials/tmva/TMVA_SOFIE_RDataFrame.py
Labels: pr:backport

#15625 [v628] io: Avoid infinite recursion in TFile::Open
  io/io/src/TFile.cxx
Labels: pr:backport

#15637 [skip-ci] Backport of #15630
  README/ReleaseNotes/v632/index.md
Labels: pr:backport

#15563 build: Allow building Cling using the Clang shared library.
  interpreter/cling/CMakeLists.txt
Labels: in:Cling

#15649 [skip-ci][RN] Update 632 version with closed items
  README/ReleaseNotes/v632/index.md
Labels: backport v6-32-00-patches

#15652 Make string caching in RLoopManager thread-safe
  tree/dataframe/inc/ROOT/RDF/RDefineReader.hxx
  tree/dataframe/inc/ROOT/RDF/RLoopManager.hxx
  tree/dataframe/inc/ROOT/RDF/Utils.hxx
  tree/dataframe/src/RDFColumnRegister.cxx
  tree/dataframe/src/RDFUtils.cxx
  tree/dataframe/src/RDefineReader.cxx
Labels: in:RDataFrame, pr:emergency🚨

#15657 Revert "[ntuple] add ClassDefInline to RKeyBlob"
  tree/ntuple/v7/src/RMiniFile.cxx
Labels: priority:high, in:RNTuple

#15138 [cmake] Set the permissions for etc and other folders that are in the source tree when installing
  CMakeLists.txt
Labels: in:Build System

#15612 [io] Update TKey::Sizeof doc comment
  io/io/src/TKey.cxx
Labels: in:I/O

#15669 [math] Add dictionary for vector<TVector3>
  math/physics/inc/LinkDef.h
Labels: backport-to-v6-32-00-patches

#15232 [TGraphErrors] add AddPointError method
  hist/hist/inc/TGraph2DAsymmErrors.h
  hist/hist/inc/TGraph2DErrors.h
  hist/hist/inc/TGraphAsymmErrors.h
  hist/hist/inc/TGraphBentErrors.h
  hist/hist/inc/TGraphErrors.h
  hist/hist/src/TGraph2DAsymmErrors.cxx
  hist/hist/src/TGraph2DErrors.cxx
  hist/hist/src/TGraphAsymmErrors.cxx
  hist/hist/src/TGraphBentErrors.cxx
  hist/hist/src/TGraphErrors.cxx
Labels: in:Hist

#15679 Fix problem with timeonaxis tutorials
  tutorials/CMakeLists.txt
Labels: affects:master, pr:emergency🚨, backport-to-v6-32-00-patches

#15680 [BP-v632] Fix problem with timeonaxis tutorials
  tutorials/CMakeLists.txt
Labels: pr:backport, pr:emergency🚨, backport-to-v6-32-00-patches

#15676 [skip-ci][ntuple] Fix `RColumn` Doxygen class
  tree/ntuple/v7/inc/ROOT/RColumn.hxx
Labels: in:RNTuple

#15671 [io] TKey: remove dead code
  io/io/src/TKey.cxx
Labels: in:I/O

#15673 [skip-ci][ntuple] add doc about the RNTuple anchor schema
  tree/ntuple/v7/test/RXTuple.cxx
Labels: in:Documentation, in:RNTuple

#15687 [v630] [io] fix crash due to overflow in buffer length variable
  core/base/inc/TBuffer.h
  io/io/inc/TBufferFile.h
  io/io/inc/TBufferJSON.h
  io/io/inc/TBufferText.h
  io/io/src/TBufferFile.cxx
  io/io/src/TBufferJSON.cxx
  io/io/src/TBufferText.cxx
  io/sql/inc/TBufferSQL2.h
  io/sql/src/TBufferSQL2.cxx
  io/xml/inc/TBufferXML.h
  io/xml/src/TBufferXML.cxx
  tree/tree/inc/TBufferSQL.h
  tree/tree/src/TBufferSQL.cxx
Labels: pr:backport, in:I/O, affects:6.30
