Repository root-project/root, pull requests merged in 2024-02, with the labels that each got.

#14516 [ntuple] remove page source based Create overload of inspector
  tree/ntupleutil/v7/inc/ROOT/RNTupleInspector.hxx
  tree/ntupleutil/v7/src/RNTupleInspector.cxx
Labels: in:RNTuple

#14489 [math][fitter] Fix crash when doing a weighted likelihood fit
  math/mathcore/src/Fitter.cxx
  test/stressHistoFit.cxx
Labels: pr:backport

#14488 [math][fitter] Fix crash when doing a weighted likelihood fit
  math/mathcore/src/Fitter.cxx
  test/stressHistoFit.cxx
Labels: pr:backport

#14517 [ntuple] Clone model's RFieldZero only once
  tree/ntuple/v7/src/RNTupleModel.cxx
Labels: in:RNTuple

#14524 [v6-30][python][windows] There is no `python3` on Windows, only `python`
  main/CMakeLists.txt
Labels: pr:backport

#14414 [PyROOT] More use of public CPyCppyy API instead of internals
  bindings/pyroot/cppyy/CPyCppyy/CMakeLists.txt
  bindings/pyroot/pythonizations/python/ROOT/_pythonization/_tclass.py
  bindings/pyroot/pythonizations/src/CPPInstancePyz.cxx
  bindings/pyroot/pythonizations/src/GenericPyz.cxx
  bindings/pyroot/pythonizations/src/PyROOTModule.cxx
  bindings/pyroot/pythonizations/src/PyROOTWrapper.cxx
  bindings/pyroot/pythonizations/src/PyzCppHelpers.cxx
  bindings/pyroot/pythonizations/src/PyzCppHelpers.hxx
  bindings/pyroot/pythonizations/src/PyzPythonHelpers.cxx
  bindings/pyroot/pythonizations/src/RDataFramePyz.cxx
  bindings/pyroot/pythonizations/src/RPyROOTApplication.cxx
  bindings/pyroot/pythonizations/src/RTensorPyz.cxx
  bindings/pyroot/pythonizations/src/RVecPyz.cxx
  bindings/pyroot/pythonizations/src/TClassPyz.cxx
  bindings/pyroot/pythonizations/src/TMemoryRegulator.cxx
  bindings/pyroot/pythonizations/src/TMemoryRegulator.h
  bindings/pyroot/pythonizations/src/TObjectPyz.cxx
  bindings/pyroot/pythonizations/src/TPyDispatcher.cxx
  bindings/pyroot/pythonizations/src/TTreePyz.cxx
Labels: in:PyROOT

#14536 [cmake] ROOTConfig: if not builtin Vdt find it
  cmake/scripts/ROOTConfig.cmake.in
Labels: experiment, pr:emergency🚨

#14530 [ntuple] remove page source from pulic view interface
  gui/browsable/src/RFieldHolder.hxx
  gui/browsable/src/RFieldProvider.hxx
  gui/browsable/src/RNTupleBrowseProvider.cxx
  tree/ntuple/v7/inc/ROOT/RNTuple.hxx
  tree/ntuple/v7/inc/ROOT/RNTupleView.hxx
  tree/ntuple/v7/test/ntuple_view.cxx
Labels: in:RNTuple

#14534 [ntuple] move RNTupleMerger to Internal namespace
  tree/ntuple/v7/inc/ROOT/RNTupleMerger.hxx
  tree/ntuple/v7/src/RNTupleMerger.cxx
  tree/ntuple/v7/test/ntuple_test.hxx
Labels: in:RNTuple

#14410 [NFC][CONTRIBUTING] Extend contribution guidelines
  .git-commit-template
  CONTRIBUTING.md
Labels: in:Documentation

#14502 [ntuple] Implement RPageNullSink
  tree/ntuple/CMakeLists.txt
  tree/ntuple/v7/inc/ROOT/RPageNullSink.hxx
  tree/ntuple/v7/test/ntuple_storage.cxx
Labels: in:RNTuple

#14596 [meta][cppyy] Export `isAggregate` property to TDictionary
  bindings/pyroot/cppyy/cppyy-backend/clingwrapper/src/capi.h
  bindings/pyroot/cppyy/cppyy-backend/clingwrapper/src/clingwrapper.cxx
  bindings/pyroot/cppyy/cppyy-backend/clingwrapper/src/cpp_cppyy.h
  core/meta/inc/TDictionary.h
  core/metacling/src/TClingClassInfo.cxx
Labels: in:Core Libraries

#14604 [ntuple] add skimming tutorial
  tree/ntuple/v7/src/RNTupleModel.cxx
  tutorials/v7/ntuple/ntpl010_skim.C
Labels: in:RNTuple

#14639 [v6-30][roofit][skip-ci] Disable failing tests on Windows (x86)
  tutorials/CMakeLists.txt
Labels: pr:backport, affects:6.30

#14633 Be explicit about reason for error in distributed execution
  bindings/experimental/distrdf/python/DistRDF/Proxy.py
Labels: in:RDataFrame

#14630 Enable RNTupleModel usage in PyROOT
  tree/ntuple/v7/inc/ROOT/RNTupleModel.hxx
  tree/ntuple/v7/src/RNTupleModel.cxx
  tree/ntuple/v7/test/CMakeLists.txt
  tree/ntuple/v7/test/ntuple_model.py
Labels: in:RNTuple

#14640 [ntuple] rename RNTupleViewCollection --> RNTupleCollectionView
  tree/ntuple/v7/inc/ROOT/RNTuple.hxx
  tree/ntuple/v7/inc/ROOT/RNTupleView.hxx
  tree/ntuple/v7/test/ntuple_view.cxx
  tree/ntuple/v7/test/rfield_vector.cxx
  tree/ntupleutil/v7/test/ntuple_importer.cxx
Labels: in:RNTuple

#14652 [ntuple] remove handling of phased-out ':Collection:' type
  tree/ntuple/v7/src/RField.cxx
Labels: in:RNTuple

#14649 [ntuple] add support for bulk reading into adopted buffer
  tree/ntuple/v7/inc/ROOT/RField.hxx
  tree/ntuple/v7/src/RField.cxx
  tree/ntuple/v7/test/ntuple_bulk.cxx
Labels: in:RNTuple

#14608 [skip-ci] document how to remove shadow of TPave, as it is not evident (only explained in the forum)
  graf2d/graf/inc/TPave.h
  graf2d/graf/src/TPaveLabel.cxx
  graf2d/graf/src/TPaveStats.cxx
  graf2d/graf/src/TPaveText.cxx
  graf2d/graf/src/TPavesText.cxx
Labels: improvement

#14661 [PyROOT] Remove JupyROOT welcome message
  bindings/jupyroot/python/JupyROOT/helpers/utils.py
Labels: in:PyROOT

#14667 [cling] Fix disabling optimizations with CLING_DEBUG
  interpreter/cling/lib/Interpreter/CIFactory.cpp
Labels: in:Cling

#14706 [PyROOT] Relax overly pedantic `getattr` pythonization tests
  bindings/pyroot/pythonizations/test/tdirectory_attrsyntax.py
  bindings/pyroot/pythonizations/test/tdirectoryfile_attrsyntax_get.py
  bindings/pyroot/pythonizations/test/tfile_attrsyntax_get_writeobject_open.py
Labels: in:PyROOT

#14705 [ntuple] add REntry::EmplaceNewValue()
  tree/ntuple/v7/inc/ROOT/REntry.hxx
  tree/ntuple/v7/test/ntuple_basics.cxx
Labels: in:RNTuple

#14709 [ntuple] RColumn: Distinguish ConnectPage{Sink,Source}
  tree/ntuple/v7/inc/ROOT/RColumn.hxx
  tree/ntuple/v7/src/RColumn.cxx
  tree/ntuple/v7/src/RField.cxx
  tree/ntuple/v7/test/ntuple_cluster.cxx
Labels: in:RNTuple

#14684 [ntuple] Remove `R__LOAD_LIBRARY` from tutorials
  tutorials/v7/ntuple/ntpl001_staff.C
  tutorials/v7/ntuple/ntpl002_vector.C
  tutorials/v7/ntuple/ntpl003_lhcbOpenData.C
  tutorials/v7/ntuple/ntpl004_dimuon.C
  tutorials/v7/ntuple/ntpl005_introspection.C
  tutorials/v7/ntuple/ntpl006_friends.C
  tutorials/v7/ntuple/ntpl007_mtFill.C
  tutorials/v7/ntuple/ntpl008_import.C
  tutorials/v7/ntuple/ntpl009_parallelWriter.C
Labels: in:RNTuple

#14739 [ntuple] Allow MakeField with a std::string
  tree/ntuple/v7/inc/ROOT/RNTupleModel.hxx
  tree/ntuple/v7/test/ntuple_limits.cxx
Labels: in:RNTuple

#14694 [core] Prevent void return type from Map function
  core/base/inc/ROOT/TExecutorCRTP.hxx
  core/base/inc/ROOT/TSequentialExecutor.hxx
  core/imt/inc/ROOT/TExecutor.hxx
  core/imt/inc/ROOT/TThreadExecutor.hxx
  core/multiproc/inc/ROOT/TProcessExecutor.hxx
Labels: in:Core Libraries

#14737 [ntuple] Use `R__ASSERT` in `RArrayAsRVecField::GenerateColumnsImpl`
  tree/ntuple/v7/inc/ROOT/RField.hxx
Labels: in:RNTuple

#14752 [DF] Fix typo to open TFile without registration
  tree/dataframe/src/RLoopManager.cxx
Labels: in:RDataFrame

#14755 [RF] Explicitly use legacy backend for references in `testRooRealL`
  roofit/roofitcore/test/TestStatistics/testLikelihoodJob.cxx
  roofit/roofitcore/test/TestStatistics/testLikelihoodSerial.cxx
  roofit/roofitcore/test/TestStatistics/testRooRealL.cxx
Labels: in:RooFit/RooStats

#14756 [ntuple] simplify REntry implementation
  tree/ntuple/v7/inc/ROOT/REntry.hxx
Labels: in:RNTuple

#14614 [http] implement `file.root` handler
  net/http/inc/TRootSniffer.h
  net/http/src/TRootSniffer.cxx
  net/httpsniff/inc/TRootSnifferFull.h
  net/httpsniff/src/TRootSnifferFull.cxx
Labels: affects:master

#14759 [RF] Set workspace on imported roofit objects
  roofit/roofitcore/src/RooWorkspace.cxx
Labels: in:RooFit/RooStats

#14762 [RF] Fix for display of canvases in jupyter notebooks
  roofit/xroofit/src/xRooNode.cxx
Labels: in:RooFit/RooStats

#14749 [ntuple] Fix field construction for friends
  tree/ntuple/v7/src/RNTupleDescriptor.cxx
  tree/ntuple/v7/test/ntuple_show.cxx
Labels: in:RNTuple

#14764 [ntuple] move RNTupleImtScheduler to Internal
  tree/ntuple/CMakeLists.txt
  tree/ntuple/v7/inc/ROOT/RNTuple.hxx
  tree/ntuple/v7/inc/ROOT/RNTupleImtTaskScheduler.hxx
  tree/ntuple/v7/src/RNTuple.cxx
Labels: in:RNTuple

#14761 [ntuple] remove ENTupleContainerFormat
  tree/ntuple/v7/inc/ROOT/RMiniFile.hxx
  tree/ntuple/v7/inc/ROOT/RNTupleOptions.hxx
  tree/ntuple/v7/src/RMiniFile.cxx
  tree/ntuple/v7/src/RPageStorageFile.cxx
  tree/ntuple/v7/test/ntuple_compat.cxx
  tree/ntuple/v7/test/ntuple_minifile.cxx
  tree/ntuple/v7/test/ntuple_storage.cxx
  tree/ntuple/v7/test/ntuple_test.hxx
Labels: in:RNTuple

#14618 [matrix] Enable Transpose for rectangular matrices
  math/matrix/inc/TMatrixTSparse.h
  math/matrix/src/TMatrixTSparse.cxx
  math/matrix/test/testMatrixTSparse.cxx
Labels: improvement, in:Math Libraries

#8546 [hist] implement long64 version of TH1I TH2I TH3I hists
  core/rint/test/TTabComTests.cxx
  documentation/primer/histograms.md
  documentation/users-guide/Histograms.md
  hist/doc/Hist.md
  hist/hist/CMakeLists.txt
  hist/hist/inc/LinkDef.h
  hist/hist/inc/TH1.h
  hist/hist/inc/TH1L.h
  hist/hist/inc/TH2.h
  hist/hist/inc/TH2L.h
  hist/hist/inc/TH3.h
  hist/hist/inc/TH3L.h
  hist/hist/inc/THn.h
  hist/hist/inc/THnSparse.h
  hist/hist/src/TH1.cxx
  hist/hist/src/TH2.cxx
  hist/hist/src/TH3.cxx
  hist/hist/src/THn.cxx
  hist/hist/src/THnBase.cxx
  hist/hist/src/THnSparse.cxx
  hist/histv7/inc/ROOT/RHist.hxx
  test/stressHistogram.cxx
Labels: new feature, in:Core Libraries, in:Graphics

#14627 [io] fix crash due to overflow in buffer length variable
  core/base/inc/TBuffer.h
  io/io/inc/TBufferFile.h
  io/io/inc/TBufferJSON.h
  io/io/inc/TBufferText.h
  io/io/src/TBufferFile.cxx
  io/io/src/TBufferJSON.cxx
  io/io/src/TBufferText.cxx
  io/sql/inc/TBufferSQL2.h
  io/sql/src/TBufferSQL2.cxx
  io/xml/inc/TBufferXML.h
  io/xml/src/TBufferXML.cxx
  tree/tree/inc/TBufferSQL.h
  tree/tree/src/TBufferSQL.cxx
Labels: bug, affects:master, in:I/O, experiment, affects:6.28, affects:6.30

#14795 [ntuple] split off RNTupleFillContext header
  tree/ntuple/CMakeLists.txt
  tree/ntuple/v7/inc/ROOT/RNTupleFillContext.hxx
  tree/ntuple/v7/inc/ROOT/RNTupleWriter.hxx
  tree/ntuple/v7/src/RNTupleFillContext.cxx
  tree/ntuple/v7/src/RNTupleWriter.cxx
  tutorials/v7/ntuple/ntpl009_parallelWriter.C
Labels: in:RNTuple

#14797 [ntuple] split off RNTupleCollectionWriter header
  tree/ntuple/CMakeLists.txt
  tree/ntuple/v7/inc/ROOT/REntry.hxx
  tree/ntuple/v7/inc/ROOT/RField.hxx
  tree/ntuple/v7/inc/ROOT/RNTupleCollectionWriter.hxx
  tree/ntuple/v7/inc/ROOT/RNTupleModel.hxx
  tree/ntuple/v7/inc/ROOT/RNTupleWriter.hxx
  tree/ntuple/v7/src/RField.cxx
  tree/ntuple/v7/src/RNTupleModel.cxx
  tree/ntuple/v7/src/RNTupleWriter.cxx
  tree/ntuple/v7/test/ntuple_test.hxx
  tree/ntupleutil/v7/inc/ROOT/RNTupleImporter.hxx
Labels: in:RNTuple

#14799 [ntuple] split RNTupleOptions header
  tree/ntuple/CMakeLists.txt
  tree/ntuple/v7/inc/ROOT/RMiniFile.hxx
  tree/ntuple/v7/inc/ROOT/RNTupleParallelWriter.hxx
  tree/ntuple/v7/inc/ROOT/RNTupleReadOptions.hxx
  tree/ntuple/v7/inc/ROOT/RNTupleReader.hxx
  tree/ntuple/v7/inc/ROOT/RNTupleWriteOptions.hxx
  tree/ntuple/v7/inc/ROOT/RNTupleWriteOptionsDaos.hxx
  tree/ntuple/v7/inc/ROOT/RPageStorage.hxx
  tree/ntuple/v7/src/RNTupleFillContext.cxx
  tree/ntuple/v7/src/RNTupleWriteOptions.cxx
  tree/ntuple/v7/src/RNTupleWriter.cxx
  tree/ntuple/v7/src/RPageSinkBuf.cxx
  tree/ntuple/v7/src/RPageSourceFriends.cxx
  tree/ntuple/v7/src/RPageStorageDaos.cxx
  tree/ntuple/v7/test/ntuple_cluster.cxx
  tree/ntuple/v7/test/ntuple_endian.cxx
  tree/ntuple/v7/test/ntuple_test.hxx
  tree/ntupleutil/v7/inc/ROOT/RNTupleImporter.hxx
  tree/ntupleutil/v7/src/RNTupleImporter.cxx
  tree/ntupleutil/v7/test/ntuple_inspector.cxx
  tree/ntupleutil/v7/test/ntupleutil_test.hxx
  tutorials/v7/ntuple/ntpl005_introspection.C
  tutorials/v7/ntuple/ntpl011_global_temperatures.C
Labels: in:RNTuple

#14798 [ntuple] rename header RNTupleAnchor.hxx --> RNTuple.hxx
  tree/dataframe/src/RLoopManager.cxx
  tree/ntuple/CMakeLists.txt
  tree/ntuple/v7/inc/ROOT/RMiniFile.hxx
  tree/ntuple/v7/inc/ROOT/RNTuple.hxx
  tree/ntuple/v7/inc/ROOT/RPageStorageDaos.hxx
  tree/ntuple/v7/src/RNTuple.cxx
  tree/ntuple/v7/src/RNTupleMerger.cxx
  tree/ntuple/v7/src/RNTupleReader.cxx
  tree/ntupleutil/v7/test/ntupleutil_test.hxx
Labels: in:RNTuple

#14785 [NFC][cling] Use StringRef::{starts,ends}_with
  interpreter/cling/lib/Interpreter/AutoloadCallback.cpp
  interpreter/cling/lib/Interpreter/BackendPasses.cpp
  interpreter/cling/lib/Interpreter/ClangInternalState.cpp
  interpreter/cling/lib/Interpreter/ClingCodeCompleteConsumer.cpp
  interpreter/cling/lib/Interpreter/DeclUnloader.cpp
  interpreter/cling/lib/Interpreter/DefinitionShadower.cpp
  interpreter/cling/lib/Interpreter/DynamicLibraryManager.cpp
  interpreter/cling/lib/Interpreter/ExternalInterpreterSource.cpp
  interpreter/cling/lib/Interpreter/ForwardDeclPrinter.cpp
  interpreter/cling/lib/Interpreter/Interpreter.cpp
  interpreter/cling/lib/Interpreter/LookupHelper.cpp
  interpreter/cling/lib/Interpreter/NullDerefProtectionTransformer.cpp
  interpreter/cling/lib/MetaProcessor/InputValidator.cpp
  interpreter/cling/lib/MetaProcessor/MetaParser.cpp
  interpreter/cling/lib/Utils/AST.cpp
  interpreter/cling/lib/Utils/Paths.cpp
  interpreter/cling/lib/Utils/PlatformWin.cpp
  interpreter/cling/lib/Utils/SourceNormalization.cpp
Labels: in:Cling

#14784 [cmake] properly use nlohmann in ctest
  tree/dataframe/test/CMakeLists.txt
Labels: affects:master, in:Build System

#14810 [v6-30][win] Fix failing `std::this_thread::sleep_for` (#14786)
  core/metacling/src/CMakeLists.txt
Labels: pr:backport, affects:6.30

#14803 [DF] Change test to avoid double free on Fedora39
  tree/dataframe/test/dataframe_vecops.cxx
Labels: in:Testing

#14805 [cmake] properly use nlohmann in ctest [6.30]
  tree/dataframe/test/CMakeLists.txt
Labels: pr:backport, in:Build System, in:Testing, affects:6.30

#14804 [jsroot] 7.5.x from 14.02.2024
  js/build/jsroot.js
  js/changes.md
  js/modules/base/BasePainter.mjs
  js/modules/base/ObjectPainter.mjs
  js/modules/base/latex.mjs
  js/modules/core.mjs
  js/modules/draw/TGraphPolarPainter.mjs
  js/modules/draw/TTree.mjs
  js/modules/gpad/RPadPainter.mjs
  js/modules/gpad/TAxisPainter.mjs
  js/modules/gpad/TPadPainter.mjs
  js/modules/gui.mjs
  js/modules/gui/HierarchyPainter.mjs
  js/modules/gui/display.mjs
  js/modules/gui/menu.mjs
  js/modules/hist/RH3Painter.mjs
  js/modules/hist/TF1Painter.mjs
  js/modules/hist/TH3Painter.mjs
  js/modules/hist/THStackPainter.mjs
  js/modules/hist/TPavePainter.mjs
  js/modules/hist/hist3d.mjs
  js/modules/hist2d/RH2Painter.mjs
  js/modules/hist2d/TH1Painter.mjs
  js/modules/hist2d/TH2Painter.mjs
  js/modules/io.mjs
  js/modules/tree.mjs
  js/scripts/JSRoot.core.js
  js/scripts/geoworker.js
Labels: in:WebGui, affects:6.30

#14826 [cmake] do not test chrome version on windows
  cmake/modules/RootConfiguration.cmake
Labels: affects:master, in:Build System, pr:emergency🚨

#14827 [cmake] do not test chrome version on windows [6.30]
  cmake/modules/RootConfiguration.cmake
Labels: pr:backport, in:Build System, pr:emergency🚨, affects:6.30

#14831 [ntuple] Add options to disable usage of IMT
  tree/ntuple/v7/inc/ROOT/RNTupleReadOptions.hxx
  tree/ntuple/v7/inc/ROOT/RNTupleWriteOptions.hxx
  tree/ntuple/v7/src/RNTupleReader.cxx
  tree/ntuple/v7/src/RNTupleWriter.cxx
Labels: in:RNTuple

#14833 Enable I/O for RCutFlowReport
  tree/dataframe/inc/LinkDef.h
  tree/dataframe/inc/ROOT/RDF/RCutFlowReport.hxx
  tree/dataframe/test/dataframe_report.cxx
Labels: in:RDataFrame

#14505 [skip-CI][NFC][ntuple] describe code architecture
  tree/ntuple/v7/doc/architecture.md
Labels: in:RNTuple

#14847 [ntuple] Make `RPageSource::UnsealPage` public
  tree/ntuple/v7/inc/ROOT/RPageStorage.hxx
  tree/ntuple/v7/src/RPageStorage.cxx
Labels: in:RNTuple

#14850 [jsroot] dev 28/02/2024 with TRatioPlot fixes
  js/build/jsroot.js
  js/changes.md
  js/modules/base/BasePainter.mjs
  js/modules/base/ObjectPainter.mjs
  js/modules/base/base3d.mjs
  js/modules/core.mjs
  js/modules/draw/TLinePainter.mjs
  js/modules/draw/TRatioPlotPainter.mjs
  js/modules/draw/TTree.mjs
  js/modules/gpad/RFramePainter.mjs
  js/modules/gpad/TAxisPainter.mjs
  js/modules/gpad/TFramePainter.mjs
  js/modules/gpad/TPadPainter.mjs
  js/modules/gui.mjs
  js/modules/gui/HierarchyPainter.mjs
  js/modules/gui/menu.mjs
  js/modules/hist/TPavePainter.mjs
  js/modules/hist2d/TH1Painter.mjs
  js/modules/hist2d/THistPainter.mjs
  js/modules/io.mjs
Labels: affects:master, in:WebGui

#14858 [skip-ci][v6-30][windows] disable mtbb201_parallelHistoFill.C
  tutorials/CMakeLists.txt
Labels: pr:backport, affects:6.30
