Repository root-project/root, pull requests merged in 2024-11, with the labels that each got.

#16800 [CMake] Disable TPython without development package
  cmake/modules/SearchInstalledSoftware.cmake
Labels: in:Build System

#16802 builtin_davix: Drop `PATCH_COMMAND`
  builtins/davix/CMakeLists.txt
Labels: in:Build System

#16437 [Minuit2] Add interface to pass initial values/cov matrix
  math/mathcore/inc/Math/Minimizer.h
  math/mathcore/src/Minimizer.cxx
  math/minuit2/inc/Minuit2/Minuit2Minimizer.h
  math/minuit2/inc/Minuit2/MnUserParameterState.h
  math/minuit2/inc/Minuit2/MnUserTransformation.h
  math/minuit2/inc/Minuit2/SinParameterTransformation.h
  math/minuit2/inc/Minuit2/SqrtLowParameterTransformation.h
  math/minuit2/inc/Minuit2/SqrtUpParameterTransformation.h
  math/minuit2/src/Minuit2Minimizer.cxx
  math/minuit2/src/MnFunctionCross.cxx
  math/minuit2/src/MnSeedGenerator.cxx
  math/minuit2/src/MnUserParameterState.cxx
  math/minuit2/src/MnUserTransformation.cxx
  math/minuit2/src/SinParameterTransformation.cxx
  math/minuit2/src/SqrtLowParameterTransformation.cxx
  math/minuit2/src/SqrtUpParameterTransformation.cxx
  math/minuit2/test/CMakeLists.txt
  math/minuit2/test/testCovariance.cxx
  roofit/roofitcore/inc/RooMinimizer.h
  roofit/roofitcore/src/RooMinimizer.cxx
Labels: in:Math Libraries

#16812 [rootssh] export ROOT_WEBDISPLAY=server [skip-ci]
  config/rootssh
Labels: affects:master, in:WebGui

#16816 [CPyCppyy] Remove implicit conversion of any ctypes ptr type to `void*`
  bindings/pyroot/cppyy/CPyCppyy/src/Converters.cxx
  bindings/pyroot/cppyy/patches/CPyCppyy-Always-convert-returned-std-string.patch
  bindings/pyroot/cppyy/patches/CPyCppyy-Remove-implicit-conversion-of-any-ctypes-ptr.patch
  bindings/pyroot/cppyy/sync-upstream
Labels: in:Python Interface

#16824 [v634][CPyCppyy] Remove implicit conversion of any ctypes ptr type to `void*`
  bindings/pyroot/cppyy/CPyCppyy/src/Converters.cxx
  bindings/pyroot/cppyy/patches/CPyCppyy-Always-convert-returned-std-string.patch
  bindings/pyroot/cppyy/patches/CPyCppyy-Remove-implicit-conversion-of-any-ctypes-ptr.patch
  bindings/pyroot/cppyy/sync-upstream
Labels: pr:backport, in:Python Interface

#16745 [skip-ci][NFC][ntuple] document default RNTupleWriteOptions
  tree/ntuple/v7/doc/BinaryFormatSpecification.md
Labels: in:RNTuple

#16821 [RF] Remove the deprecated RooFit code to be removed in ROOT 6.36
  README/ReleaseNotes/v636/index.md
  roofit/histfactory/inc/RooStats/HistFactory/MakeModelAndMeasurementsFast.h
  roofit/histfactory/inc/RooStats/HistFactory/Measurement.h
  roofit/histfactory/src/ConfigParser.cxx
  roofit/histfactory/src/MakeModelAndMeasurementsFast.cxx
  roofit/roofitcore/inc/RooAbsArg.h
  roofit/roofitcore/inc/RooPlot.h
  roofit/roofitcore/inc/RooTemplateProxy.h
  roofit/roofitcore/src/RooAbsArg.cxx
  roofit/roofitcore/src/RooPlot.cxx
  roofit/roostats/inc/RooStats/MarkovChain.h
  roofit/roostats/src/MarkovChain.cxx
Labels: in:RooFit/RooStats

#16828 [skip-ci][v6.34][NFC][ntuple] document default RNTupleWriteOptions
  tree/ntuple/v7/doc/BinaryFormatSpecification.md
Labels: pr:backport, in:RNTuple

#16842 [BP][hist] remove default parameter in TH1::GetQuantiles, as is the case with TF1::GetQuantiles
  hist/hist/src/TH1.cxx
Labels: pr:backport

#16455 [webgui] Make default single connection
  config/rootrc.in
  documentation/users-guide/WebDisplay.md
  gui/webdisplay/inc/ROOT/RWebWindowsManager.hxx
  gui/webdisplay/src/RWebWindow.cxx
  gui/webdisplay/src/RWebWindowsManager.cxx
  tutorials/webgui/ping/ping.cxx
Labels: affects:master, in:WebGui

#16813 [skip-ci] [ntuple] Add naming rules to the specification
  tree/ntuple/v7/doc/BinaryFormatSpecification.md
Labels: in:RNTuple

#16846 [v6-34][win] Add Python version in CPack binary name
  cmake/modules/RootCPack.cmake
Labels: pr:backport

#16862 [v630][hist] prevent nullptr access with copy from default constructor
  hist/hist/src/TH2Poly.cxx
Labels: bug, experiment, in:Hist

#16863 [v632][hist] prevent nullptr access with copy from default constructor
  hist/hist/src/TH2Poly.cxx
Labels: bug, experiment, in:Hist

#16825 [ntuple] forbid creating a RNTupleWriter with an XML TFile
  tree/ntuple/v7/src/RMiniFile.cxx
  tree/ntuple/v7/src/RNTupleWriter.cxx
  tree/ntuple/v7/test/ntuple_basics.cxx
Labels: in:RNTuple

#16854 [6.34] [ntuple] Add naming rules to the specification
  tree/ntuple/v7/doc/BinaryFormatSpecification.md
Labels: pr:backport, in:RNTuple

#16833 [v634][ntuple] Check field range validity only on access
  tree/ntuple/v7/inc/ROOT/RNTupleView.hxx
  tree/ntuple/v7/src/RNTupleView.cxx
  tree/ntuple/v7/test/ntuple_view.cxx
Labels: pr:backport, in:RNTuple

#16857 [ntuple] Add zip timer to `RPageSinkBuf`
  tree/ntuple/v7/inc/ROOT/RPageSinkBuf.hxx
  tree/ntuple/v7/src/RPageSinkBuf.cxx
Labels: in:RNTuple

#16861 [CPyCppyy] Fix regression in passing buffers through `void *`
  bindings/pyroot/cppyy/CPyCppyy/src/CPyCppyy.h
  bindings/pyroot/cppyy/CPyCppyy/src/Converters.cxx
  bindings/pyroot/cppyy/CPyCppyy/src/LowLevelViews.cxx
  bindings/pyroot/cppyy/CPyCppyy/src/PyStrings.cxx
  bindings/pyroot/cppyy/CPyCppyy/src/PyStrings.h
  bindings/pyroot/cppyy/CPyCppyy/src/Pythonize.cxx
  bindings/pyroot/cppyy/cppyy/test/test_regression.py
  bindings/pyroot/cppyy/patches/CPyCppyy-Remove-implicit-conversion-of-any-ctypes-ptr.patch
  bindings/pyroot/cppyy/sync-upstream
Labels: in:Python Interface

#16873 [pyroot] fix clang warning due to changes in PyObject
  bindings/pyroot/cppyy/CPyCppyy/src/CPyCppyyModule.cxx
Labels: in:Python Interface

#16875 [BP 6.34][skip-ci][rn] Update information about contributors, deprecations and builtins
  README/ReleaseNotes/v634/index.md
Labels: pr:backport

#16850 [ntuple] Enforce RNTuple naming rules
  tree/ntuple/v7/inc/ROOT/RFieldBase.hxx
  tree/ntuple/v7/inc/ROOT/RNTupleUtil.hxx
  tree/ntuple/v7/src/RField.cxx
  tree/ntuple/v7/src/RNTupleDescriptor.cxx
  tree/ntuple/v7/src/RNTupleModel.cxx
  tree/ntuple/v7/src/RNTupleUtil.cxx
  tree/ntuple/v7/src/RPageStorage.cxx
  tree/ntuple/v7/test/ntuple_basics.cxx
  tree/ntuple/v7/test/ntuple_model.cxx
  tree/ntuple/v7/test/rfield_basics.cxx
Labels: in:RNTuple

#16886 [6.32][core] Fix bug in the root version macros
  cmake/modules/SetROOTVersion.cmake
  core/foundation/inc/ROOT/RVersion.hxx
Labels: pr:backport

#16887 [NFC][ntuple] add v6.34 release notes
  README/ReleaseNotes/v634/index.md
Labels: in:RNTuple

#16894 [v6.34][NFC][ntuple] add v6.34 release notes (#16887)
  README/ReleaseNotes/v634/index.md
Labels: pr:backport, in:RNTuple

#16888 Exclude JSROOT modules from clang-format check
  .ci/format_script.sh
Labels: affects:master, in:CI

#16902 Add relase note for web-canvas, JSROOT, rootssh [skip-ci]
  README/ReleaseNotes/v634/index.md
Labels: affects:master

#16903 Add relase note for web-canvas, JSROOT, rootssh [6.34] [skip-ci]
  README/ReleaseNotes/v634/index.md
Labels: pr:backport, affects:6.34

#16896 [6.34]Disable stress graphics chrome
  test/CMakeLists.txt
Labels: pr:backport

#16882 [RF] Implement code generation for RooMultiVarGaussian
  roofit/roofitcore/inc/RooFit/Detail/MathFuncs.h
  roofit/roofitcore/inc/RooMultiVarGaussian.h
  roofit/roofitcore/src/RooMultiVarGaussian.cxx
Labels: in:RooFit/RooStats

#16900 [ntuple] Fixup `RNTupleIndex` error messages
  tree/ntuple/v7/inc/ROOT/RNTupleIndex.hxx
  tree/ntuple/v7/src/RNTupleIndex.cxx
  tree/ntuple/v7/test/ntuple_index.cxx
Labels: in:RNTuple

#16932 [PyROOT] Retain C++ memory ownership for TStyle
  bindings/pyroot/pythonizations/CMakeLists.txt
  bindings/pyroot/pythonizations/python/ROOT/_pythonization/_tstyle.py
  bindings/pyroot/pythonizations/test/memory.py
Labels: bug, in:Python Interface

#16933 [v634][PyROOT] Retain C++ memory ownership for TStyle
  bindings/pyroot/pythonizations/CMakeLists.txt
  bindings/pyroot/pythonizations/python/ROOT/_pythonization/_tstyle.py
  bindings/pyroot/pythonizations/test/memory.py
Labels: pr:backport, bug, in:Python Interface

#16935 [v634] Fix buffer overflow when opening the Fit Panel
  gui/gui/src/TGNumberEntry.cxx
Labels: pr:backport, bug

#16934 [v632] Fix buffer overflow when opening the Fit Panel
  gui/gui/src/TGNumberEntry.cxx
Labels: pr:backport, bug

#16943 [ci] Remove ubu20 from master
  .github/workflows/root-ci-config/buildconfig/ubuntu20.txt
  .github/workflows/root-ci.yml
Labels: in:CI

#16930 build: The builtin TBB sets a debug suffix for its library on linux too
  bindings/pyroot/pythonizations/test/import_load_libs.py
  cmake/modules/SearchInstalledSoftware.cmake
Labels: bug, in:Build System

#16349 [RF] Added new printout RooCmdArg to recreate constructor call
  bindings/pyroot/pythonizations/test/CMakeLists.txt
  bindings/pyroot/pythonizations/test/roofit/roocmdarg.py
  roofit/roofitcore/inc/RooCmdArg.h
  roofit/roofitcore/src/RooCmdArg.cxx
Labels: new feature, in:RooFit/RooStats

#16923 [ntuple] Reduce includes of RColumnElement.hxx
  tree/ntuple/v7/inc/ROOT/RNTupleUtil.hxx
  tree/ntuple/v7/src/RColumnElement.hxx
  tree/ntuple/v7/src/RNTupleSerialize.cxx
  tree/ntuple/v7/test/ntuple_compat.cxx
Labels: in:RNTuple

#16953 [RF] Add old getter for covariance matrix
  roofit/roofitcore/inc/RooMinimizer.h
  roofit/roofitcore/src/RooMinimizer.cxx
Labels: in:RooFit/RooStats

#13809 [RF][HF] Clearly mark interpolation code 3 as unknown
  roofit/histfactory/inc/RooStats/HistFactory/FlexibleInterpVar.h
  roofit/histfactory/inc/RooStats/HistFactory/PiecewiseInterpolation.h
  roofit/histfactory/src/FlexibleInterpVar.cxx
  roofit/histfactory/src/HistoToWorkspaceFactoryFast.cxx
  roofit/histfactory/src/PiecewiseInterpolation.cxx
  roofit/roofitcore/inc/RooFit/Detail/MathFuncs.h
Labels: improvement, in:RooFit/RooStats

#16962 [6.34][df] Check for empty file list in constructor
  tree/dataframe/src/RLoopManager.cxx
  tree/dataframe/test/dataframe_regression.cxx
Labels: pr:backport

#16963 [6.34][PyROOT] Retain C++ ownership for TColor
  bindings/pyroot/pythonizations/CMakeLists.txt
  bindings/pyroot/pythonizations/python/ROOT/_pythonization/_tcolor.py
  bindings/pyroot/pythonizations/test/memory.py
Labels: pr:backport

#16956 [ntuple] Simplify `RNTuple::Streamer()`
  tree/ntuple/v7/src/RNTuple.cxx
Labels: in:RNTuple

#16977 [webcanvas] make default off for the TWebCanvas [6.34]
  cmake/modules/RootConfiguration.cmake
  core/base/src/TROOT.cxx
  gui/gui/src/TRootGuiFactory.cxx
Labels: affects:6.34

#16983 [6.34][core] print -> symbol when dumping pointer in showMembers
  core/meta/src/TClass.cxx
Labels: pr:backport

#17005 [skip-ci] Complete parameter documentation
  gui/gui/src/TGPicture.cxx
Labels: new contributor, improvement

#17010 [6.34] [io] warn user about the trailing blanks being stripped from keyname upon writing
  io/io/src/TDirectoryFile.cxx
Labels: pr:backport

#17006 [ntuple] Micro-optimize `RVectorField::AppendImpl`
  tree/ntuple/v7/src/RFieldSequenceContainer.cxx
Labels: in:RNTuple

#17007 Several fixes in TAxis
  hist/hist/src/TAxis.cxx
Labels: in:Graphics

#16991 [RF] Add analytic integral for RooRealSumPdf (Codegen backend)
  roofit/codegen/inc/RooFit/CodegenImpl.h
  roofit/codegen/src/CodegenImpl.cxx
  roofit/roofitcore/inc/RooRealSumPdf.h
  roofit/roofitcore/src/RooRealSumPdf.cxx
  roofit/roofitcore/test/testRooFuncWrapper.cxx
Labels: new contributor, in:RooFit/RooStats

#17013 [ntuple] fix out-of-bounds in Real32Quant test
  tree/ntuple/v7/test/ntuple_packing.cxx
Labels: in:RNTuple

#17012 [ntuple] add missing include in RFieldMeta
  tree/ntuple/v7/src/RFieldMeta.cxx
Labels: in:RNTuple

#17017 [6.34][skip-ci][rn] Update set of closed items for 6.34.00
  README/ReleaseNotes/v634/index.md
Labels: pr:backport

#17028 [skip-ci] Add `python` anchor tag to PyROOT docs
  bindings/pyroot/pythonizations/python/ROOT/_pythonization/_rvec.py
  bindings/pyroot/pythonizations/python/ROOT/_pythonization/_tarray.py
  bindings/pyroot/pythonizations/python/ROOT/_pythonization/_tcontext.py
  bindings/pyroot/pythonizations/python/ROOT/_pythonization/_tdirectory.py
  bindings/pyroot/pythonizations/python/ROOT/_pythonization/_tdirectoryfile.py
  bindings/pyroot/pythonizations/python/ROOT/_pythonization/_tf1.py
  bindings/pyroot/pythonizations/python/ROOT/_pythonization/_tfile.py
  bindings/pyroot/pythonizations/python/ROOT/_pythonization/_ttree.py
Labels: in:Documentation, 2nd Hackathon

#17014 [ntuple] Allow configuration of initial page size
  tree/ntuple/v7/inc/ROOT/RColumn.hxx
  tree/ntuple/v7/inc/ROOT/RNTupleWriteOptions.hxx
  tree/ntuple/v7/src/RColumn.cxx
  tree/ntuple/v7/src/RNTupleModel.cxx
  tree/ntuple/v7/src/RNTupleWriteOptions.cxx
  tree/ntuple/v7/test/ntuple_basics.cxx
  tree/ntuple/v7/test/ntuple_extended.cxx
  tree/ntuple/v7/test/ntuple_limits.cxx
  tree/ntuple/v7/test/ntuple_model.cxx
  tree/ntuple/v7/test/ntuple_model.py
  tree/ntuple/v7/test/ntuple_storage.cxx
  tree/ntupleutil/v7/test/ntuple_inspector.cxx
Labels: in:RNTuple

#17032 [skip-ci][tree] Revamp TTree documentation
  bindings/pyroot/pythonizations/python/ROOT/_pythonization/_ttree.py
  tree/tree/src/TTree.cxx
Labels: 2nd Hackathon

#17033 [RF] Use TRandom3 explicitly in RooFit
  tutorials/roofit/rf102_dataimport.C
  tutorials/roofit/rf102_dataimport.py
  tutorials/roofit/rf303_conditional.C
  tutorials/roofit/rf303_conditional.py
  tutorials/roofit/rf401_importttreethx.C
  tutorials/roofit/rf401_importttreethx.py
  tutorials/roofit/rf609_xychi2fit.C
  tutorials/roofit/rf609_xychi2fit.py
Labels: in:RooFit/RooStats, 2nd Hackathon

#17047 [6.34][core] Adjust kp6Violet to the correct Petroff value, #7a21dd
  core/base/src/TColor.cxx
Labels: pr:backport

#17042 [RF] Skip normalization over nEvents in RooSimultaneous if necessary
  roofit/roofitcore/src/RooSimultaneous.cxx
  roofit/roofitcore/test/testRooSimultaneous.cxx
Labels: bug, in:RooFit/RooStats

#17035 [skip-ci] Add th1 pyroot fit documentation
  bindings/pyroot/pythonizations/python/ROOT/_pythonization/_th1.py
Labels: 2nd Hackathon

#17036 Move PROOF Tutorials under Legacy Tutorials
  tutorials/CMakeLists.txt
  tutorials/doc/v528/index.html
  tutorials/doc/v528/mass_spectrum.gif
  tutorials/doc/v530/index.html
  tutorials/doc/v532/index.html
  tutorials/doc/v534/index.html
  tutorials/doc/v600/index.md
  tutorials/doc/v602/index.md
  tutorials/index.md
  tutorials/legacy/PhaseSpace.C
  tutorials/legacy/proof/EmptyInclude.h
  tutorials/legacy/proof/ProcFileElements.C
  tutorials/legacy/proof/ProcFileElements.h
  tutorials/legacy/proof/ProofAux.C
  tutorials/legacy/proof/ProofAux.h
  tutorials/legacy/proof/ProofEvent.C
  tutorials/legacy/proof/ProofEvent.h
  tutorials/legacy/proof/ProofEventProc.C
  tutorials/legacy/proof/ProofEventProc.h
  tutorials/legacy/proof/ProofFriends.C
  tutorials/legacy/proof/ProofFriends.h
  tutorials/legacy/proof/ProofNtuple.C
  tutorials/legacy/proof/ProofNtuple.h
  tutorials/legacy/proof/ProofPythia.C
  tutorials/legacy/proof/ProofPythia.h
  tutorials/legacy/proof/ProofSimple.C
  tutorials/legacy/proof/ProofSimple.h
  tutorials/legacy/proof/ProofSimpleFile.C
  tutorials/legacy/proof/ProofSimpleFile.h
  tutorials/legacy/proof/ProofStdVect.C
  tutorials/legacy/proof/ProofStdVect.h
  tutorials/legacy/proof/ProofTests.C
  tutorials/legacy/proof/ProofTests.h
  tutorials/legacy/proof/event.md5sum
  tutorials/legacy/proof/event.par
  tutorials/legacy/proof/finalizeProof.C
  tutorials/legacy/proof/getProof.C
  tutorials/legacy/proof/index.md
  tutorials/legacy/proof/ntprndm.root
  tutorials/legacy/proof/packtest1.md5sum
  tutorials/legacy/proof/packtest1.par
  tutorials/legacy/proof/packtest2.md5sum
  tutorials/legacy/proof/packtest2.par
  tutorials/legacy/proof/packtest3.md5sum
  tutorials/legacy/proof/packtest3.par
  tutorials/legacy/proof/pythia8.par
  tutorials/legacy/proof/runProof.C
Labels: in:Documentation, 2nd Hackathon

#17050 Delete container tutorial
  tutorials/cont/cnt001_basictseq.C
  tutorials/index.md
Labels: in:Documentation, 2nd Hackathon

#17024 [windows] Fix several tree tutorials
  test/CMakeLists.txt
  tutorials/tree/copytree.C
  tutorials/tree/copytree2.C
  tutorials/tree/copytree3.C
Labels: 2nd Hackathon

#17023 [skip-ci] add awkward to-from rdataframe documentation
  bindings/pyroot/pythonizations/python/ROOT/_pythonization/_rdataframe.py
Labels: in:Documentation, 2nd Hackathon

#17039 Add pyroot documentation for TScatter
  bindings/pyroot/pythonizations/CMakeLists.txt
  bindings/pyroot/pythonizations/python/ROOT/_pythonization/_tscatter.py
Labels: new contributor, in:Documentation, 2nd Hackathon

#17070 [Python] Don't import print function from `__future__` in tutorials
  tmva/sofie/test/Conv1dModelGenerator.py
  tmva/sofie/test/Conv2dModelGenerator.py
  tmva/sofie/test/Conv3dModelGenerator.py
  tmva/sofie/test/ConvTrans2dModelGenerator.py
  tmva/sofie/test/LinearModelGenerator.py
  tmva/sofie/test/RecurrentModelGenerator.py
  tutorials/histfactory/makeQuickModel.py
  tutorials/pyroot/graph.py
  tutorials/pyroot/gui_ex.py
  tutorials/pyroot/parse_CSV_file_with_TTree_ReadStream.py
  tutorials/roofit/rf109_chi2residpull.py
  tutorials/roofit/rf110_normintegration.py
  tutorials/roofit/rf203_ranges.py
  tutorials/roofit/rf308_normintegration2d.py
  tutorials/roofit/rf402_datahandling.py
  tutorials/roofit/rf403_weightedevts.py
  tutorials/roofit/rf404_categories.py
  tutorials/roofit/rf505_asciicfg.py
  tutorials/roofit/rf508_listsetmanip.py
  tutorials/roofit/rf602_chi2fit.py
  tutorials/roofit/rf604_constraints.py
  tutorials/roofit/rf607_fitresult.py
  tutorials/roofit/rf901_numintconfig.py
Labels: in:Python Interface, 2nd Hackathon

#17061 [skip-ci][tutorials][ntuple] Add comments to ntuple tutorilas category
  tutorials/v7/ntuple/index.md
  tutorials/v7/ntuple/ntpl011_global_temperatures.C
Labels: 2nd Hackathon

#17054 [ntuple] fix compiler warning in streamer field test
  tree/ntuple/v7/test/rfield_streamer.cxx
Labels: in:RNTuple

#16967 [core] Fix early return in AutoloadLibraryGenerator
  core/metacling/src/TClingCallbacks.cxx
Labels: in:Cling

#17064 [gitignore] ignore more stuff in documentation/doxygen
  .gitignore
Labels: 2nd Hackathon

#17059 Support ipython tab completion when getting item TFile and RooWorkspace
  bindings/pyroot/pythonizations/python/ROOT/_pythonization/_roofit/_rooworkspace.py
  bindings/pyroot/pythonizations/python/ROOT/_pythonization/_tdirectory.py
Labels: in:Python Interface, 2nd Hackathon

#17073 [ntuple] Fix error message for projected subfield
  tree/ntuple/v7/src/RNTupleModel.cxx
Labels: in:RNTuple

#17078 [core] Fix compiler warning about missing return
  core/metacling/src/TClingCallFunc.cxx
Labels: in:Core Libraries, 2nd Hackathon

#17055 Allow passing numpy array to TH1::Fill()
  bindings/pyroot/pythonizations/python/ROOT/_pythonization/_th1.py
  bindings/pyroot/pythonizations/test/CMakeLists.txt
  bindings/pyroot/pythonizations/test/th1_fillN.py
  tutorials/dataframe/df017_vecOpsHEP.py
  tutorials/fit/fitConvolution.py
  tutorials/hist/twoscales.py
  tutorials/math/tStudent.py
  tutorials/roofit/rf102_dataimport.py
  tutorials/roofit/rf401_importttreethx.py
Labels: in:Hist, 2nd Hackathon

#17082 [skip-ci] Add dedicated page for python specific user documentation
  bindings/pyroot/pythonizations/doc/index.md
  bindings/pyroot/pythonizations/python/ROOT/_pythonization/__init__.py
  documentation/doxygen/Doxyfile
  documentation/doxygen/filter.cxx
  documentation/doxygen/makeinput.sh
Labels: in:Documentation, 2nd Hackathon

#17096 add PyROOT THistPainter documentation for keeping the TBrowser open
  bindings/pyroot/pythonizations/CMakeLists.txt
  bindings/pyroot/pythonizations/python/ROOT/_pythonization/_thistpainter.py
Labels: 2nd Hackathon

#17099 unify 'pythonization' spelling
  bindings/pyroot/pythonizations/python/ROOT/_pythonization/_tdirectory.py
  bindings/pyroot/pythonizations/python/ROOT/_pythonization/_tdirectoryfile.py
  bindings/pyroot/pythonizations/python/ROOT/_pythonization/_ttree.py
  bindings/pyroot/pythonizations/test/CMakeLists.txt
  bindings/pyroot/pythonizations/test/tclass_dynamiccast.py
  bindings/pyroot/pythonizations/test/tf_pycallables.py
  bindings/pyroot/pythonizations/test/tobject_comparisonops.py
  bindings/pyroot/pythonizations/test/tobject_contains.py
Labels: 2nd Hackathon

#17107 [skip-ci] Add documentation with short example with TF1.SetParameters from numpy array
  bindings/pyroot/pythonizations/python/ROOT/_pythonization/_tf1.py
Labels: 2nd Hackathon

#17084 Move a couple of tree tutorials in legacy/tree
  tutorials/CMakeLists.txt
  tutorials/legacy/tree/tree.C
  tutorials/legacy/tree/tvdemo.C
Labels: in:Tutorials, 2nd Hackathon

#17119 Disable test-webgui-ping for Mac
  gui/webdisplay/test/CMakeLists.txt
Labels: affects:master, in:Testing, pr:emergency🚨

#17126 Rename forgotten circular tree tutorial
  tutorials/tree/tree114_circular.C
Labels: 2nd Hackathon

#17138 [skip-ci] [python] Fix syntax warning in docstring
  bindings/pyroot/pythonizations/python/ROOT/_pythonization/__init__.py
Labels: in:Documentation

#17143 [skip-ci] Add a note in reference about the coordinate system negation pitfalls
  math/genvector/doc/index.md
Labels: in:Documentation

#17140 [webgui] use posix_spawn to start chrome in headless for ping
  gui/webdisplay/src/RWebDisplayHandle.cxx
Labels: affects:master, in:WebGui

#17121 Disable test-webgui-ping for Mac [6.34] [skip-ci]
  gui/webdisplay/test/CMakeLists.txt
Labels: pr:emergency🚨, affects:6.34

#13011 [core] Prevent buffer underrun in SplitAclicMode (thanks, SonarCloud)
  core/base/src/TSystem.cxx
Labels: in:Core Libraries

#10781 chore: Set permissions for GitHub actions
  .github/workflows/code_analysis.yml
Labels: in:Build System

#17123 [ntuple] Support bulk-reading with views
  tree/ntuple/v7/inc/ROOT/RNTupleView.hxx
  tree/ntuple/v7/test/ntuple_view.cxx
Labels: in:RNTuple

#17150 [v634][Minuit2] Remove deleted header file reference
  math/minuit2/src/CMakeLists.txt
Labels: pr:backport, in:Math Libraries

#17146 [df] Ensure proper graph dependencies for local info in distributed mode
  bindings/experimental/distrdf/python/DistRDF/HeadNode.py
  bindings/experimental/distrdf/python/DistRDF/Node.py
  bindings/experimental/distrdf/python/DistRDF/Proxy.py
  bindings/experimental/distrdf/test/test_callable_generator.py
  bindings/experimental/distrdf/test/test_proxy.py
Labels: in:RDataFrame

#17144 [skip-ci] Remove Windows from the CI for 6-30
  .github/workflows/root-ci.yml
Labels: in:CI

#16969 [core] Fold AutoloadLibraryMU into AutoloadLibraryGenerator
  core/metacling/src/TClingCallbacks.cxx
Labels: in:Cling

#17120 [core] Correct and extend `TClingCallFunc` tests
  core/metacling/test/TClingCallFuncTests.cxx
Labels: in:Core Libraries

#15100 [TMath] Add Gradient and Laplacian methods for arrays
  math/mathcore/inc/TMath.h
  math/mathcore/test/testTMath.cxx
Labels: in:Math Libraries
