Repository root-project/root, pull requests merged in 2024-06, with the labels that each got.

#15677 [jsroot] version 7.7.1 [6.32]
  js/build/jsroot.js
  js/changes.md
  js/modules/core.mjs
  js/modules/geom/bundle.mjs
  js/modules/hist/TF1Painter.mjs
  js/modules/hist/TF2Painter.mjs
  js/modules/hist/TF3Painter.mjs
  js/modules/hist2d/TH1Painter.mjs
Labels: in:WebGui, affects:6.32

#15697 [CMake] Forward `OPENSSL_ROOT_DIR` to builtin xrootd
  builtins/xrootd/CMakeLists.txt
Labels: in:Build System

#15695 [RF] Fix segfault with RooBernstein instances read back from files
  roofit/roofit/src/RooBernstein.cxx
Labels: in:RooFit/RooStats

#15693 [hist] Don't define default `w=1.0` parameter in `TProfile2D::Fill()`
  hist/hist/inc/TProfile2D.h
Labels: bug, in:Hist

#15702 [RF] Fix vectorized evaluation for RooRealSumpdf with `_doFloor`
  roofit/roofitcore/src/RooRealSumPdf.cxx
Labels: bug, in:RooFit/RooStats

#15710 [BP 632][ci] Remove ubu2310 build
  .github/workflows/root-ci-config/buildconfig/ubuntu2310.txt
  .github/workflows/root-ci.yml
Labels: pr:backport

#15711 [BP630][ci] Remove ubu2310 build
  .github/workflows/root-ci-config/buildconfig/ubuntu2310.txt
  .github/workflows/root-ci.yml
Labels: pr:backport

#15700 [skip-ci][ntuple] update RNTuple anchor doc
  tree/ntuple/v7/doc/specifications.md
Labels: in:Documentation, in:RNTuple

#15654 [ntuple] Improve inspector error for compression setting mismatch
  tree/ntupleutil/v7/src/RNTupleInspector.cxx
Labels: in:RNTuple

#15720 [ntuple] minor improvement to ROptionalField
  tree/ntuple/v7/src/RField.cxx
Labels: in:RNTuple

#15678 [core] Link clad to clang only if target available
  core/metacling/src/CMakeLists.txt
Labels: in:Core Libraries

#15715 [ntuple] additional testing for std::optional
  tree/ntuple/v7/test/ntuple_types.cxx
Labels: in:RNTuple

#15729 [ntuple] fix merging of unsplit fields
  tree/ntuple/v7/inc/ROOT/RPageStorage.hxx
  tree/ntuple/v7/src/RNTupleMerger.cxx
  tree/ntuple/v7/test/rfield_unsplit.cxx
Labels: in:RNTuple

#15724 [ntuple] Call UnzipCluster on all clusters
  tree/ntuple/v7/src/RClusterPool.cxx
Labels: in:RNTuple

#15739 [RF] Set size of offsets vector in LikelihoodJob correctly
  roofit/roofitcore/src/TestStatistics/LikelihoodJob.cxx
Labels: in:RooFit/RooStats

#15437 [Clang] Implement CWG2518 - static_assert(false)
  interpreter/llvm-project/clang/docs/ReleaseNotes.rst
  interpreter/llvm-project/clang/lib/Sema/SemaDeclCXX.cpp
  interpreter/llvm-project/clang/www/cxx_dr_status.html
  interpreter/llvm-project/llvm-project.tag
Labels: in:Cling

#15698 [ntuple] Add `kUnknownCompressionSettings`
  tree/ntuple/v7/inc/ROOT/RNTupleDescriptor.hxx
  tree/ntuple/v7/inc/ROOT/RNTupleUtil.hxx
Labels: in:RNTuple

#15745 [df] Make RInterfaceBase::GetNFiles resilient to different TTree conf…
  tree/dataframe/src/RInterfaceBase.cxx
  tree/dataframe/test/dataframe_interface.cxx
Labels: in:RDataFrame

#15753 [Clang] Implement CWG2518 - static_assert(false) [v6.32]
  interpreter/llvm-project/clang/docs/ReleaseNotes.rst
  interpreter/llvm-project/clang/lib/Sema/SemaDeclCXX.cpp
  interpreter/llvm-project/clang/www/cxx_dr_status.html
  interpreter/llvm-project/llvm-project.tag
Labels: pr:backport, in:Cling

#15764 Improve df101_h1Analysis.C macro
  tutorials/dataframe/df101_h1Analysis.C
Labels: affects:master, in:Graphics

#15765 Introduce TF1::HasSave method
  hist/hist/inc/TF1.h
Labels: affects:master, in:Hist

#15712 [BP 628][ci] Remove ubu2310 build
  .github/workflows/root-ci-config/buildconfig/ubuntu2310.txt
  .github/workflows/root-ci.yml
Labels: pr:backport

#15618 [ntuple] Add tests for forward compatibility
  tree/ntuple/v7/src/RMiniFile.cxx
  tree/ntuple/v7/test/CMakeLists.txt
  tree/ntuple/v7/test/RXTuple.cxx
  tree/ntuple/v7/test/RXTuple.hxx
  tree/ntuple/v7/test/RXTupleLinkDef.h
  tree/ntuple/v7/test/ntuple_compat.cxx
Labels: in:RNTuple

#15699 [ntuple] Fix column range construction for extended fields
  tree/ntuple/v7/src/RNTupleDescriptor.cxx
  tree/ntuple/v7/test/ntuple_modelext.cxx
Labels: bug, in:RNTuple

#15759 [ntuple] Ignore unkown compression settings in the `RNTupleInspector` construction
  tree/ntupleutil/v7/src/RNTupleInspector.cxx
  tree/ntupleutil/v7/test/ntuple_inspector.cxx
Labels: bug, in:RNTuple

#15770 [ci] Add Debian 12.5 builds
  .github/workflows/root-ci-config/buildconfig/debian125.txt
  .github/workflows/root-ci.yml
Labels: in:CI

#15773 [RF] Use `std::min` and `std::max` in MathFuncs
  roofit/roofitcore/inc/RooFit/Detail/MathFuncs.h
Labels: in:RooFit/RooStats

#15784 [ntuple] add RIO Dependencies for RXTuple
  tree/ntuple/v7/test/CMakeLists.txt
Labels: in:RNTuple

#15795 [RF] Fix conditional RooProdPdfs in RooSimultaneous with new backend
  roofit/roofitcore/src/RooSimultaneous.cxx
  roofit/roofitcore/test/testRooSimultaneous.cxx
Labels: bug, in:RooFit/RooStats

#15800 [ci] Correctly parse Debian version
  cmake/modules/RootCPack.cmake
Labels: in:CI

#15801 [ci] Display time per group
  .github/workflows/root-ci-config/build_utils.py
Labels: in:CI

#15806 [skip-ci] clang-format ntuple_storage.cxx
  tree/ntuple/v7/test/ntuple_storage.cxx
Labels: in:RNTuple

#15772 [skip-ci][ntuple] Clarify `RColumnRange::kFirstElementIndex` doc
  tree/ntuple/v7/inc/ROOT/RNTupleDescriptor.hxx
Labels: in:RNTuple

#15804 [http] Allow to use any of openssl 3.x with civetweb
  net/http/CMakeLists.txt
Labels: affects:master, in:WebGui

#15807 [PyROOT] Implement TTree SetBranchAddress pythonization in Python
  bindings/pyroot/pythonizations/python/ROOT/_pythonization/_ttree.py
  bindings/pyroot/pythonizations/src/PyROOTModule.cxx
  bindings/pyroot/pythonizations/src/PyROOTPythonize.h
  bindings/pyroot/pythonizations/src/TTreePyz.cxx
Labels: bug, in:PyROOT

#15816 [math] Use correct type when invoking the GSLIntegrator
  math/mathcore/src/Integrator.cxx
Labels: in:Math Libraries

#15794 [skip-ci][RDF] clang-format some RDF tests
  tree/dataframe/inc/ROOT/RSnapshotOptions.hxx
  tree/dataframe/test/dataframe_cache.cxx
  tree/dataframe/test/dataframe_simple.cxx
  tree/dataframe/test/dataframe_snapshot.cxx
Labels: in:RDataFrame

#15820 [rdf] add RIO dependency for dataframe_splitcoll_arrayview
  tree/dataframe/test/CMakeLists.txt
Labels: in:RDataFrame

#15768 [ntuple] minor improvement in RDaos
  tree/ntuple/v7/src/RDaos.cxx
Labels: in:RNTuple

#15825 [webgui] ensure main thread id set when TWebCanvas is created
  gui/webgui6/src/TWebCanvas.cxx
Labels: affects:master, in:WebGui, backport-to-v6-32-00-patches

#15788 [PyROOT] Register custom converters and executors via CPyCppyy API
  bindings/pyroot/cppyy/CPyCppyy/include/CPyCppyy/API.h
  bindings/pyroot/cppyy/CPyCppyy/src/Converters.cxx
  bindings/pyroot/cppyy/CPyCppyy/src/Converters.h
  bindings/pyroot/cppyy/CPyCppyy/src/Executors.cxx
  bindings/pyroot/cppyy/CPyCppyy/src/Executors.h
  bindings/pyroot/cppyy/patches/CPyCppyy-Add-converters-and-executors-for-ROOT-types.patch
  bindings/pyroot/pythonizations/python/ROOT/_facade.py
  bindings/pyroot/pythonizations/src/PyROOTModule.cxx
Labels: in:PyROOT

#15828 [BP 630] [math] Use correct type when invoking the GSLIntegrator
  math/mathcore/src/Integrator.cxx
Labels: pr:backport

#15829 [BP 632] [math] Use correct type when invoking the GSLIntegrator
  math/mathcore/src/Integrator.cxx
Labels: pr:backport

#15834 [gpad] Always set `kMustCleanup` bit when object add to pad
  core/base/src/TObject.cxx
  graf2d/gpad/src/TPad.cxx
Labels: affects:master, in:Graphics

#15830 [webgui] ensure main thread id set when TWebCanvas is created [6.32]
  gui/webgui6/src/TWebCanvas.cxx
Labels: pr:backport, in:WebGui, affects:6.32

#15835 [ntuple] read header and footer in vector read
  tree/ntuple/v7/src/RPageStorageFile.cxx
Labels: in:RNTuple

#15844 [RF] Don't call `resetDataToken()` on RooRealVars in Evaluator d'tor
  roofit/roofitcore/src/RooFit/Evaluator.cxx
Labels: bug, in:RooFit/RooStats

#15845 [RF] Enable RooCrystalBall test for AD
  roofit/roofitcore/test/testRooFuncWrapper.cxx
Labels: in:RooFit/RooStats

#15839 [ci] Add back the march=native build
  .github/workflows/root-ci-config/build_root.py
  .github/workflows/root-ci-config/build_utils.py
  .github/workflows/root-ci.yml
Labels: in:CI

#15815 [core] deprecate R__zip
  core/zip/inc/RZip.h
Labels: in:Core Libraries

#15796 [ntuple] fix unbuffered compression of large pages
  tree/ntuple/v7/inc/ROOT/RPageStorage.hxx
  tree/ntuple/v7/src/RPageStorage.cxx
  tree/ntuple/v7/test/ntuple_extended.cxx
Labels: in:RNTuple

#15722 [ntuple] add test for std::set<std::array<...>>
  tree/ntuple/v7/test/ProxiedSTLContainerLinkDef.h
  tree/ntuple/v7/test/ntuple_types.cxx
Labels: in:RNTuple

#15840 [cmake] Add asan options to ACLiC
  CMakeLists.txt
  cmake/modules/RootConfiguration.cmake
Labels: in:Build System

#15848 [ntuple] Change `VisitIntField` to `VisitInt32Field`
  gui/browsable/src/RFieldProvider.hxx
  tree/ntuple/v7/inc/ROOT/RFieldVisitor.hxx
  tree/ntuple/v7/src/RField.cxx
  tree/ntuple/v7/src/RFieldVisitor.cxx
Labels: in:RNTuple

#15849 [ntuple] remove parameter from simple SealPage overload
  tree/ntuple/v7/inc/ROOT/RPageStorage.hxx
  tree/ntuple/v7/src/RPageStorage.cxx
  tree/ntuple/v7/src/RPageStorageDaos.cxx
  tree/ntuple/v7/src/RPageStorageFile.cxx
  tree/ntuple/v7/test/ntuple_endian.cxx
Labels: in:RNTuple

#15854 [ORC] Preserve order of constructors with same priority
  interpreter/llvm-project/llvm-project.tag
  interpreter/llvm-project/llvm/lib/ExecutionEngine/Orc/LLJIT.cpp
Labels: in:Cling

#15860 [v6-32][win32] Fix error with VS v17.10
  core/metacling/src/CMakeLists.txt
Labels: pr:backport

#15857 [ORC] Preserve order of constructors with same priority [v6.32]
  interpreter/llvm-project/llvm-project.tag
  interpreter/llvm-project/llvm/lib/ExecutionEngine/Orc/LLJIT.cpp
Labels: pr:backport, in:Cling

#15650 [RF] Improve binBoundaries method of ParamHistFunc
  roofit/histfactory/src/ParamHistFunc.cxx
Labels: improvement, in:RooFit/RooStats

#15864 [ntuple] add debug output to RVectorField
  tree/ntuple/v7/src/RField.cxx
Labels: in:RNTuple, experiment

#15867 [webgui] let enable usage of currentdir
  gui/webdisplay/inc/ROOT/RWebWindow.hxx
  gui/webdisplay/src/RWebWindow.cxx
  gui/webdisplay/src/RWebWindowsManager.cxx
Labels: affects:master, in:WebGui

#15858 [ORC] Preserve order of constructors with same priority [v6.30]
  interpreter/llvm-project/llvm-project.tag
  interpreter/llvm-project/llvm/lib/ExecutionEngine/Orc/LLJIT.cpp
Labels: pr:backport, in:Cling

#15859 [ORC] Preserve order of constructors with same priority [v6.28]
  interpreter/llvm/src/lib/ExecutionEngine/Orc/LLJIT.cpp
Labels: pr:backport, in:Cling

#15869 [ntuple] Fix clang compile warning due to typeid in RField
  tree/ntuple/v7/src/RField.cxx
Labels: in:RNTuple

#15852 [core] silence warning for deprecated fn in Compression.cxx
  core/zip/inc/Compression.h
  core/zip/src/Compression.cxx
Labels: in:Core Libraries

#15868 [webgui] let enable usage of currentdir [6.32]
  gui/webdisplay/inc/ROOT/RWebWindow.hxx
  gui/webdisplay/src/RWebWindow.cxx
  gui/webdisplay/src/RWebWindowsManager.cxx
Labels: pr:backport, in:WebGui, affects:6.32

#15865 [ntuple] add test for vector of strings
  tree/ntuple/v7/test/rfield_vector.cxx
Labels: in:RNTuple

#15879 [ntuple] avoid some memory allocations in RPageStorageFile
  tree/ntuple/v7/src/RPageStorageFile.cxx
Labels: in:RNTuple

#15884 [ntuple] turn RSealedPage into class with getters/setters
  tree/ntuple/v7/inc/ROOT/RPageNullSink.hxx
  tree/ntuple/v7/inc/ROOT/RPageStorage.hxx
  tree/ntuple/v7/src/RNTupleMerger.cxx
  tree/ntuple/v7/src/RPageStorage.cxx
  tree/ntuple/v7/src/RPageStorageDaos.cxx
  tree/ntuple/v7/src/RPageStorageFile.cxx
  tree/ntuple/v7/test/ntuple_endian.cxx
  tree/ntuple/v7/test/ntuple_merger.cxx
  tree/ntuple/v7/test/ntuple_packing.cxx
Labels: in:RNTuple

#15885 [jsroot] 7.7.2 19/06/2024 [6.32]
  js/build/jsroot.js
  js/changes.md
  js/modules/core.mjs
  js/modules/gpad/TAxisPainter.mjs
  js/modules/gpad/TFramePainter.mjs
  js/modules/gui/menu.mjs
  js/modules/hist/TPavePainter.mjs
  js/modules/hist2d/TGraphPainter.mjs
  js/modules/hist2d/TH2Painter.mjs
  js/modules/hist2d/THistPainter.mjs
  js/modules/hist2d/TScatterPainter.mjs
Labels: in:WebGui, affects:6.32

#15889 [cmake] Fix some typos
  CMakeLists.txt
  cmake/modules/SetROOTVersion.cmake
Labels: in:Build System

#15898 [ntuple] don't bubble up exceptions from RNTuple::Merge
  tree/ntuple/v7/src/RNTupleMerger.cxx
Labels: in:RNTuple

#15225 [skip-ci] Remove link to rawgit as it will shut down
  interpreter/cling/docs/ReleaseNotes.md
Labels: in:Cling

#15923 Fix variable name in tutorials/graphs/scatter.C
  tutorials/graphs/scatter.C
Labels: pr:emergency🚨

#15870 Use dataframe/df105_WBosonAnalysis.json in rcanvas
  tutorials/CMakeLists.txt
  tutorials/rcanvas/df105.json
  tutorials/rcanvas/df105.py
Labels: affects:master

#15909 [ntuple] split loading and processing meta-data
  tree/ntuple/v7/inc/ROOT/RPageSourceFriends.hxx
  tree/ntuple/v7/inc/ROOT/RPageStorage.hxx
  tree/ntuple/v7/inc/ROOT/RPageStorageDaos.hxx
  tree/ntuple/v7/inc/ROOT/RPageStorageFile.hxx
  tree/ntuple/v7/src/RPageStorage.cxx
  tree/ntuple/v7/src/RPageStorageFile.cxx
  tree/ntuple/v7/test/ntuple_cluster.cxx
  tree/ntuple/v7/test/ntuple_endian.cxx
Labels: in:RNTuple

#15935 [ci] Disable fortran on march=native build
  .github/workflows/root-ci.yml
Labels: in:CI

#15934 [ci] Add MacOS version to build artifacts path
  .github/workflows/root-ci-config/build_root.py
Labels: in:CI

#15890 [ntuple] minor cleanups to some RNTuple classes
  tree/ntuple/v7/inc/ROOT/RField.hxx
  tree/ntuple/v7/inc/ROOT/RNTupleDescriptor.hxx
  tree/ntuple/v7/inc/ROOT/RNTupleMetrics.hxx
  tree/ntuple/v7/inc/ROOT/RNTupleModel.hxx
  tree/ntuple/v7/inc/ROOT/RNTupleReader.hxx
  tree/ntuple/v7/src/RNTupleDescriptorFmt.cxx
  tree/ntuple/v7/src/RNTupleReader.cxx
Labels: in:RNTuple

#15946 [RF] Make ROOT compile again also with `-DROOFIT_MEMORY_SAFE_INTERFACES`
  roofit/roofitcore/src/TestStatistics/ConstantTermsOptimizer.cxx
  roofit/roofitcore/test/TestStatistics/testRooAbsL.cxx
Labels: in:RooFit/RooStats
