Repository root-project/root, pull requests merged in 2024-12, with the labels that each got.

#17161 [PyROOT] Whitelist `libgcc_s` library in imported library test
  bindings/pyroot/pythonizations/test/import_load_libs.py
Labels: in:Python Interface

#17081 [RDF] Refactor RDisplay::AsString and Print
  tree/dataframe/inc/ROOT/RDF/RDisplay.hxx
  tree/dataframe/src/RDFDisplay.cxx
  tree/dataframe/test/dataframe_display.cxx
  tree/dataframe/test/dataframe_vary.cxx
  tree/dataframe/test/datasource_csv.cxx
Labels: in:RDataFrame, 2nd Hackathon

#17147 [TMVA] Fix warning on x86
  tmva/sofie/inc/TMVA/ROperator_Reshape.hxx
Labels: in:TMVA

#17129 Do not use tilted `TGaxis` in tutorials
  documentation/users-guide/Graphics.md
  tutorials/graphics/gaxis.C
  tutorials/hist/reverseaxis.C
Labels: affects:master, in:Graphics, in:Tutorials

#17159 Fix wrong interaction between VariationsFor,Vary,GetMergeableValue
  tree/dataframe/inc/ROOT/RDF/RMergeableValue.hxx
  tree/dataframe/inc/ROOT/RDF/RResultMap.hxx
Labels: in:RDataFrame

#17167 [6.34] Fix wrong interaction between VariationsFor,Vary,GetMergeableValue
  tree/dataframe/inc/ROOT/RDF/RMergeableValue.hxx
  tree/dataframe/inc/ROOT/RDF/RResultMap.hxx
Labels: in:RDataFrame

#17177 [tutorials] Fix paths in multicore tutorials
  tutorials/multicore/mp103_processSelector.C
  tutorials/multicore/mp104_processH1.C
  tutorials/multicore/mp105_processEntryList.C
Labels: pr:emergency🚨, in:Tutorials

#17174 [6.32] Fix wrong interaction between VariationsFor,Vary,GetMergeableValue
  tree/dataframe/inc/ROOT/RDF/RMergeableValue.hxx
  tree/dataframe/inc/ROOT/RDF/RResultMap.hxx
Labels: pr:backport

#17154 [tutorials] Move net tutorials to legacy folder
  tutorials/CMakeLists.txt
  tutorials/index.md
  tutorials/legacy/index.md
  tutorials/legacy/net/TUriTest.C
  tutorials/legacy/net/TestAuth.C
  tutorials/legacy/net/authclient.C
  tutorials/legacy/net/authserv.C
  tutorials/legacy/net/fastMergeServer.C
  tutorials/legacy/net/hclient.C
  tutorials/legacy/net/hcons.C
  tutorials/legacy/net/hprod.C
  tutorials/legacy/net/hserv.C
  tutorials/legacy/net/hserv2.C
  tutorials/legacy/net/parallelMergeClient.C
  tutorials/legacy/net/parallelMergeServer.C
  tutorials/legacy/net/parallelMergeTest.C
  tutorials/legacy/net/parallelMergeTest.sh
  tutorials/legacy/net/pclient.C
  tutorials/legacy/net/pserv.C
  tutorials/legacy/net/spy.C
  tutorials/legacy/net/spyserv.C
  tutorials/legacy/net/testTUDPSocket.C
  tutorials/legacy/net/treeClient.C
  tutorials/legacy/net/udpserver.c
Labels: in:Tutorials, 2nd Hackathon

#17184 [skip-ci] Update dataframe tutorials path
  tutorials/analysis/dataframe/df105_WBosonAnalysis.py
  tutorials/analysis/dataframe/df106_HiggsToFourLeptons.C
  tutorials/analysis/dataframe/df106_HiggsToFourLeptons.py
  tutorials/analysis/dataframe/df107_SingleTopAnalysis.py
Labels: in:Tutorials

#17164 [RF] Clarify ownership of underlying TTree for RooDataSet
  roofit/roofitcore/src/RooDataSet.cxx
Labels: in:RooFit/RooStats

#17094 [RF] Forbid calling `getVal()` with r-value references to norm set
  bindings/pyroot/pythonizations/python/ROOT/_pythonization/_roofit/_rooabsreal.py
  roofit/histfactory/test/testHistFactory.cxx
  roofit/roofit/test/testRooPoisson.cxx
  roofit/roofitcore/inc/RooAbsReal.h
  roofit/roofitcore/src/RooAbsReal.cxx
  roofit/roofitcore/test/testRooAbsPdf.cxx
  roofit/roofitcore/test/testRooDataHist.cxx
  roofit/roofitcore/test/testRooProdPdf.cxx
  roofit/roofitcore/test/testRooWrapperPdf.cxx
Labels: in:RooFit/RooStats, 2nd Hackathon

#17083 [RF] Deprecate RooDataSet constructors other than universal constructor
  README/ReleaseNotes/v636/index.md
  core/foundation/inc/ROOT/RConfig.hxx
  roofit/roofitcore/inc/RooDataSet.h
  roofit/roofitcore/test/stressRooFit_tests.h
  roofit/roofitcore/test/testSumW2Error.cxx
  tutorials/roofit/rf403_weightedevts.C
  tutorials/roofit/rf403_weightedevts.py
Labels: in:RooFit/RooStats

#17186 [ci] Try cloning 6 times and sleep in between attempts
  .github/workflows/root-ci-config/build_root.py
Labels: in:CI

#17171 [df] Add support for Alias() in DistRDF
  bindings/experimental/distrdf/python/DistRDF/Operation.py
  tree/dataframe/src/RDataFrame.cxx
Labels: clean build

#17178 Upgrade builtin XRootD to version 5.7.2
  builtins/xrootd/CMakeLists.txt
Labels: clean build

#16858 New interpCode=6 for PiecewiseInterpolation: Multiplicative Polynominal Interpolation with Linear Extrapolation
  roofit/histfactory/src/PiecewiseInterpolation.cxx
  roofit/histfactory/test/CMakeLists.txt
  roofit/histfactory/test/testPiecewiseInterpolation.cxx
  roofit/roofitcore/inc/RooFit/Detail/MathFuncs.h
Labels: new feature, in:RooFit/RooStats

#17188 [skip-ci][tutorials] Delete extra items
  tutorials/analysis/unfold/TSVDUnfoldExample.C
  tutorials/index.md
Labels: in:Tutorials

#17197 [PyROOT] Don't assume ownership of TTree created by `CloneTree()`
  bindings/pyroot/pythonizations/python/ROOT/_pythonization/_ttree.py
  bindings/pyroot/pythonizations/test/memory.py
Labels: bug, in:Python Interface, experiment

#17204 [6.34] builtins: update Davix to add patch for gcc14 in rapidjson
  builtins/davix/CMakeLists.txt
Labels: pr:backport

#17196 [ntuple] Optimize `RArrayField`
  tree/ntuple/v7/src/RFieldSequenceContainer.cxx
Labels: in:RNTuple

#17210 [ntuple] fix compiler warning
  tree/ntuple/v7/inc/ROOT/RColumn.hxx
Labels: in:RNTuple

#17218 [ci] Disable the GPU builds until the DNS problem is solved
  .github/workflows/root-ci.yml
Labels: in:CI

#12059 New constructors for TAxis, THnSparse and friends.
  hist/hist/inc/TAxis.h
  hist/hist/inc/THnBase.h
  hist/hist/inc/THnSparse.h
  hist/hist/src/TAxis.cxx
  hist/hist/src/THnBase.cxx
  hist/hist/src/THnSparse.cxx
Labels: new contributor, improvement, in:Hist

#14993 [RF] Don't support `proof` anymore in RooFit and RooStats
  roofit/roofitcore/CMakeLists.txt
  roofit/roofitcore/inc/LinkDef.h
  roofit/roofitcore/inc/RooProofDriverSelector.h
  roofit/roofitcore/inc/RooStudyManager.h
  roofit/roofitcore/src/RooProofDriverSelector.cxx
  roofit/roofitcore/src/RooStudyManager.cxx
  roofit/roostats/CMakeLists.txt
  roofit/roostats/inc/LinkDef.h
  roofit/roostats/inc/RooStats/HypoTestInverter.h
  roofit/roostats/inc/RooStats/ProofConfig.h
  roofit/roostats/inc/RooStats/ToyMCSampler.h
  roofit/roostats/inc/RooStats/ToyMCStudy.h
  roofit/roostats/src/HypoTestInverter.cxx
  roofit/roostats/src/ToyMCSampler.cxx
  roofit/roostats/src/ToyMCStudy.cxx
  tutorials/roostats/HybridInstructional.C
  tutorials/roostats/HybridStandardForm.C
  tutorials/roostats/IntervalExamples.C
  tutorials/roostats/OneSidedFrequentistUpperLimitWithBands.C
  tutorials/roostats/StandardFeldmanCousinsDemo.C
  tutorials/roostats/StandardFrequentistDiscovery.C
  tutorials/roostats/StandardHypoTestDemo.C
  tutorials/roostats/StandardHypoTestInvDemo.C
  tutorials/roostats/StandardTestStatDistributionDemo.C
  tutorials/roostats/TwoSidedFrequentistUpperLimitWithBands.C
Labels: in:RooFit/RooStats

#17228 Many fixes in `TFileDrawMap`
  tree/treeplayer/inc/TFileDrawMap.h
  tree/treeplayer/src/TFileDrawMap.cxx
Labels: affects:master, in:Graphics

#17230 [tut] make sure python tutorials write into separate files
  tutorials/hist/hist001_TH1_fillrandom.py
  tutorials/hist/hist002_TH1_fillrandom_userfunc.py
Labels: in:Tutorials

#17229 Give ownership to C++ for objects with directory registration logic
  bindings/pyroot/pythonizations/CMakeLists.txt
  bindings/pyroot/pythonizations/python/ROOT/_pythonization/_tefficiency.py
  bindings/pyroot/pythonizations/python/ROOT/_pythonization/_tentrylist.py
  bindings/pyroot/pythonizations/python/ROOT/_pythonization/_teventlist.py
  bindings/pyroot/pythonizations/python/ROOT/_pythonization/_tgraph2d.py
  bindings/pyroot/pythonizations/python/ROOT/_pythonization/_th1.py
  bindings/pyroot/pythonizations/python/ROOT/_pythonization/_th2.py
  bindings/pyroot/pythonizations/python/ROOT/_pythonization/_th3.py
  bindings/pyroot/pythonizations/python/ROOT/_pythonization/_ttree.py
  bindings/pyroot/pythonizations/test/memory.py
Labels: in:Python Interface

#17237 Implement rule of five in RDataSource and derived
  tree/dataframe/inc/ROOT/RArrowDS.hxx
  tree/dataframe/inc/ROOT/RCsvDS.hxx
  tree/dataframe/inc/ROOT/RDF/RLazyDSImpl.hxx
  tree/dataframe/inc/ROOT/RDataSource.hxx
  tree/dataframe/inc/ROOT/RNTupleDS.hxx
  tree/dataframe/inc/ROOT/RRootDS.hxx
  tree/dataframe/inc/ROOT/RSqliteDS.hxx
  tree/dataframe/inc/ROOT/RTrivialDS.hxx
  tree/dataframe/inc/ROOT/RVecDS.hxx
  tree/dataframe/src/RTrivialDS.cxx
  tree/dataframe/test/RArraysDS.hxx
  tree/dataframe/test/RNonCopiableColumnDS.hxx
  tree/dataframe/test/RStreamingDS.hxx
Labels: in:RDataFrame

#17245 [df] Early return if empty string in InterpreterCalc
  tree/dataframe/inc/ROOT/RDF/Utils.hxx
  tree/dataframe/src/RDFUtils.cxx
Labels: in:RDataFrame

#17252 [ntuple] some fixes to Real32Quant
  tree/ntuple/v7/inc/ROOT/RField/RFieldFundamental.hxx
  tree/ntuple/v7/src/RColumnElement.hxx
  tree/ntuple/v7/test/ntuple_packing.cxx
Labels: in:RNTuple

#17224 [ci] Overwrite files when unzipping test results
  .github/workflows/test-result-comment.yml
Labels: in:CI

#17235 [ntuple] set proper UUID in simple mini file writer
  tree/ntuple/v7/src/RMiniFile.cxx
  tree/ntuple/v7/test/ntuple_minifile.cxx
Labels: in:RNTuple

#17261 [v6.34][ntuple] Fix race in cluster pool
  tree/ntuple/v7/inc/ROOT/RClusterPool.hxx
  tree/ntuple/v7/src/RClusterPool.cxx
Labels: pr:backport, in:RNTuple

#17254 RooSimultaneous: fix bug with category fraction calculation.
  roofit/roofitcore/src/RooSimultaneous.cxx
  roofit/roofitcore/test/testRooSimultaneous.cxx
Labels: bug, in:RooFit/RooStats

#17250 [python] Factor memory utility functions in one module
  bindings/pyroot/pythonizations/CMakeLists.txt
  bindings/pyroot/pythonizations/python/ROOT/_pythonization/_memory_utils.py
  bindings/pyroot/pythonizations/python/ROOT/_pythonization/_tentrylist.py
  bindings/pyroot/pythonizations/python/ROOT/_pythonization/_teventlist.py
  bindings/pyroot/pythonizations/python/ROOT/_pythonization/_tgraph2d.py
  bindings/pyroot/pythonizations/python/ROOT/_pythonization/_th1.py
  bindings/pyroot/pythonizations/python/ROOT/_pythonization/_th2.py
  bindings/pyroot/pythonizations/python/ROOT/_pythonization/_th3.py
  bindings/pyroot/pythonizations/python/ROOT/_pythonization/_ttree.py
Labels: in:Python Interface

#17236 [io] Set empty TKey default title
  io/io/src/TKey.cxx
  io/io/test/TFileTests.cxx
Labels: in:I/O

#17268 [6.34][python] Factor memory utility functions in one module
  bindings/pyroot/pythonizations/CMakeLists.txt
  bindings/pyroot/pythonizations/python/ROOT/_pythonization/_memory_utils.py
  bindings/pyroot/pythonizations/python/ROOT/_pythonization/_tentrylist.py
  bindings/pyroot/pythonizations/python/ROOT/_pythonization/_teventlist.py
  bindings/pyroot/pythonizations/python/ROOT/_pythonization/_tgraph2d.py
  bindings/pyroot/pythonizations/python/ROOT/_pythonization/_th1.py
  bindings/pyroot/pythonizations/python/ROOT/_pythonization/_th2.py
  bindings/pyroot/pythonizations/python/ROOT/_pythonization/_th3.py
  bindings/pyroot/pythonizations/python/ROOT/_pythonization/_ttree.py
Labels: pr:backport

#17251 [ntuple] Support bulk-reading with views [v6.34]
  tree/ntuple/v7/inc/ROOT/RNTupleView.hxx
  tree/ntuple/v7/test/ntuple_view.cxx
Labels: pr:backport

#17253 Add C++23 support
  graf3d/eve7/inc/ROOT/REveCaloData.hxx
  graf3d/eve7/src/REveCaloData.cxx
  interpreter/cling/lib/Interpreter/CIFactory.cpp
  interpreter/cling/lib/Interpreter/IncrementalCUDADeviceCompiler.cpp
  interpreter/cling/tools/Jupyter/kernel/clingkernel.py
  roofit/histfactory/inc/RooStats/HistFactory/HistRef.h
  roofit/roofitcore/inc/RooFit/Detail/NormalizationHelpers.h
Labels: new contributor

#15371 [RF] RooStats tutorials translated into Python
  README/ReleaseNotes/v636/index.md
  tutorials/CMakeLists.txt
  tutorials/roostats/CreateExampleFile.py
  tutorials/roostats/FourBinInstructional.C
  tutorials/roostats/FourBinInstructional.py
  tutorials/roostats/HybridInstructional.C
  tutorials/roostats/HybridInstructional.py
  tutorials/roostats/HybridStandardForm.py
  tutorials/roostats/ModelInspector.C
  tutorials/roostats/ModelInspector.py
  tutorials/roostats/OneSidedFrequentistUpperLimitWithBands.C
  tutorials/roostats/OneSidedFrequentistUpperLimitWithBands.py
  tutorials/roostats/StandardBayesianMCMCDemo.C
  tutorials/roostats/StandardBayesianMCMCDemo.py
  tutorials/roostats/StandardBayesianNumericalDemo.C
  tutorials/roostats/StandardBayesianNumericalDemo.py
  tutorials/roostats/StandardFeldmanCousinsDemo.C
  tutorials/roostats/StandardFeldmanCousinsDemo.py
  tutorials/roostats/StandardFrequentistDiscovery.C
  tutorials/roostats/StandardFrequentistDiscovery.py
  tutorials/roostats/StandardHistFactoryPlotsWithCategories.C
  tutorials/roostats/StandardHistFactoryPlotsWithCategories.py
  tutorials/roostats/StandardHypoTestDemo.py
  tutorials/roostats/StandardHypoTestInvDemo.C
  tutorials/roostats/StandardHypoTestInvDemo.py
  tutorials/roostats/StandardTestStatDistributionDemo.C
  tutorials/roostats/StandardTestStatDistributionDemo.py
  tutorials/roostats/TwoSidedFrequentistUpperLimitWithBands.py
  tutorials/roostats/rs102_hypotestwithshapes.C
  tutorials/roostats/rs102_hypotestwithshapes.py
  tutorials/roostats/rs301_splot.py
  tutorials/roostats/rs302_JeffreysPriorDemo.C
  tutorials/roostats/rs302_JeffreysPriorDemo.py
  tutorials/roostats/rs401d_FeldmanCousins.C
  tutorials/roostats/rs401d_FeldmanCousins.py
  tutorials/roostats/rs701_BayesianCalculator.py
  tutorials/roostats/rs_numberCountingCombination.py
Labels: in:RooFit/RooStats

#17279 [rntuple] Fix assertion failure in RNtuple
  tree/ntuple/v7/src/RColumnElement.hxx
Labels: in:RNTuple

#17271 [ntuple] Refactor and add more `RNTupleJoinProcessor` tests
  tree/ntuple/v7/test/ntuple_processor_join.cxx
Labels: in:RNTuple

#17280 Fix Ranges.get_clusters_and_entries in DistRDF.HeadNode.py
  bindings/experimental/distrdf/python/DistRDF/HeadNode.py
Labels: in:RDataFrame

#17270 [ntuple] Refactor `RNTupleJoinProcessor::LoadEntry`
  tree/ntuple/v7/src/RNTupleProcessor.cxx
Labels: in:RNTuple

#17285 [ntuple] Add evolution tests for added, renamed, removed intermediate classes
  tree/ntuple/v7/test/ntuple_evolution.cxx
Labels: in:RNTuple

#17293 [RF] Manually create hist2workspace documentation
  roofit/CMakeLists.txt
  roofit/histfactory/CMakeLists.txt
  roofit/histfactory/src/hist2workspace-argparse.py
  roofit/histfactory/src/hist2workspace.cxx
  roofit/man/man1/hist2workspace.1
Labels: in:RooFit/RooStats

#17289 [ntuple] allow passing RCreateModelOptions to RNTupleReader::Open
  tree/ntuple/v7/inc/ROOT/RNTupleReader.hxx
  tree/ntuple/v7/src/RNTupleReader.cxx
Labels: in:RNTuple

#17301 [tree] Avoid rebuilding the TChainIndex in every MT task
  tree/tree/src/InternalTreeUtils.cxx
Labels: in:RDataFrame, in:TTree

#17284 [Python] Sync with cppyy 3.5.0
  bindings/pyroot/cppyy/CPyCppyy/setup.py
  bindings/pyroot/cppyy/CPyCppyy/src/CPPInstance.h
  bindings/pyroot/cppyy/CPyCppyy/src/CPPMethod.cxx
  bindings/pyroot/cppyy/CPyCppyy/src/CPPOverload.cxx
  bindings/pyroot/cppyy/CPyCppyy/src/Converters.cxx
  bindings/pyroot/cppyy/CPyCppyy/src/DeclareConverters.h
  bindings/pyroot/cppyy/CPyCppyy/src/DeclareExecutors.h
  bindings/pyroot/cppyy/CPyCppyy/src/Executors.cxx
  bindings/pyroot/cppyy/CPyCppyy/src/LowLevelViews.cxx
  bindings/pyroot/cppyy/CPyCppyy/src/MemoryRegulator.cxx
  bindings/pyroot/cppyy/CPyCppyy/src/ProxyWrappers.cxx
  bindings/pyroot/cppyy/CPyCppyy/src/Pythonize.cxx
  bindings/pyroot/cppyy/CPyCppyy/src/Utility.cxx
  bindings/pyroot/cppyy/cppyy/LICENSE.txt
  bindings/pyroot/cppyy/cppyy/doc/source/changelog.rst
  bindings/pyroot/cppyy/cppyy/installer/cppyy_monkey_patch.py
  bindings/pyroot/cppyy/cppyy/python/cppyy/__init__.py
  bindings/pyroot/cppyy/cppyy/python/cppyy/__pyinstaller/hook-cppyy.py
  bindings/pyroot/cppyy/cppyy/python/cppyy/_cpython_cppyy.py
  bindings/pyroot/cppyy/cppyy/python/cppyy/_pypy_cppyy.py
  bindings/pyroot/cppyy/cppyy/python/cppyy/_pythonization.py
  bindings/pyroot/cppyy/cppyy/python/cppyy/_typemap.py
  bindings/pyroot/cppyy/cppyy/python/cppyy/_version.py
  bindings/pyroot/cppyy/cppyy/python/cppyy/interactive.py
  bindings/pyroot/cppyy/cppyy/python/cppyy/ll.py
  bindings/pyroot/cppyy/cppyy/python/cppyy/numba_ext.py
  bindings/pyroot/cppyy/cppyy/setup.py
  bindings/pyroot/cppyy/cppyy/test/test_cpp11features.py
  bindings/pyroot/cppyy/cppyy/test/test_leakcheck.py
  bindings/pyroot/cppyy/cppyy/test/test_numba.py
  bindings/pyroot/cppyy/cppyy/test/test_stltypes.py
  bindings/pyroot/cppyy/cppyy/test/test_templates.py
  bindings/pyroot/cppyy/patches/CPyCppyy-Avoid-nullptr-dereferencing.patch
  bindings/pyroot/cppyy/patches/CPyCppyy-Perform-function-style-casts.patch
  bindings/pyroot/cppyy/patches/CPyCppyy-Support-conversion-from-str-to-char.patch
  bindings/pyroot/cppyy/patches/CPyCppyy-Use-PyMapping_GetOptionalItemString-where-necessary.patch
  bindings/pyroot/cppyy/patches/cppyy-Don-t-enable-cling-autoloading.patch
  bindings/pyroot/cppyy/patches/cppyy-No-CppyyLegacy-namespace.patch
  bindings/pyroot/cppyy/patches/cppyy-Remove-Windows-workaround.patch
  bindings/pyroot/cppyy/sync-upstream
Labels: in:Python Interface

#17313 [ntuple][python] Generalise getting and setting values of an REntry
  bindings/pyroot/pythonizations/python/ROOT/_pythonization/_rntuple.py
  tree/ntuple/v7/inc/ROOT/RNTupleUtil.hxx
  tree/ntuple/v7/test/ntuple_basics.py
Labels: in:Python Interface, in:RNTuple

#17323 [RF] Remove unused sel rule for RooStats::ToyMCPayload
  roofit/roostats/inc/LinkDef.h
Labels: in:RooFit/RooStats

#17322 [cmake] Remove race in RS demo tutorials input creation
  tutorials/CMakeLists.txt
Labels: in:RooFit/RooStats

#17312 [DF] add validation for number of column names imposed to CSV source
  tree/dataframe/inc/ROOT/RCsvDS.hxx
  tree/dataframe/src/RCsvDS.cxx
  tree/dataframe/test/datasource_csv.cxx
  tree/dataframe/test/datasource_csv.py
Labels: in:RDataFrame

#17292 [RF] Fix parameter ordering bug in RooFormulaArgStreamer
  roofit/hs3/src/JSONFactories_RooFitCore.cxx
Labels: new contributor, bug, in:RooFit/RooStats

#17328 Modernise multicore tutorials
  tutorials/CMakeLists.txt
  tutorials/analysis/mp_parallelHistoFill.C
  tutorials/analysis/mp_processSelector.C
  tutorials/analysis/mt_fillHistos.C
  tutorials/analysis/mt_parallelHistoFill.C
  tutorials/analysis/mtbb_fillHistos.C
  tutorials/analysis/mtbb_parallelHistoFill.C
  tutorials/io/tree/imt_parBranchProcessing.C
  tutorials/io/tree/imt_parTreeProcessing.C
  tutorials/io/tree/mp_fillNtuples.C
  tutorials/io/tree/mp_readNtuplesFillHistosAndFit.C
  tutorials/io/tree/mt_fillNtupleFromMultipleThreads.C
  tutorials/io/tree/mt_fillNtuples.C
  tutorials/io/tree/mt_readNtuplesFillHistosAndFit.C
  tutorials/io/tree/mtbb_fillNtuples.C
  tutorials/legacy/multicore/mp104_processH1.C
  tutorials/legacy/multicore/mp_H1_lambdas.C
  tutorials/legacy/multicore/mt301_TTaskGroupSimple.C
  tutorials/multicore/mp001_fillHistos.C
  tutorials/multicore/mp105_processEntryList.C
  tutorials/multicore/mt304_fillHistos.C
Labels: 2nd Hackathon

#17333 [RS] Increase test coverage (slightly) and streamline dependencies
  tutorials/CMakeLists.txt
Labels: in:RooFit/RooStats, in:Tutorials

#17329 [ntuple] Fix unused variable warning in `ntuple_processor.cxx` test
  tree/ntuple/v7/test/ntuple_processor.cxx
Labels: in:RNTuple

#16285 [CMake] Only replace `find_package` if required
  cmake/modules/SearchInstalledSoftware.cmake
Labels: in:Build System, clean build

#17335 Revert "[CMake] Only replace `find_package` if required"
  cmake/modules/SearchInstalledSoftware.cmake
Labels: pr:emergency🚨, clean build, in:CI

#17343 [ci] Do not print docker instructions if on macOS
  .github/workflows/root-ci-config/build_root.py
  .github/workflows/root-ci-config/build_utils.py
Labels: in:CI
