Repository root-project/root, pull requests merged in 2025-04, with the labels that each got.

#18203 [ntuple] Move RNTupleWriter out of Experimental
  bindings/pyroot/pythonizations/python/ROOT/_pythonization/_rntuple.py
  tree/dataframe/inc/ROOT/RDF/ActionHelpers.hxx
  tree/dataframe/test/dataframe_snapshot_ntuple.cxx
  tree/dataframe/test/dataframe_unified_constructor.cxx
  tree/dataframe/test/datasource_ntuple.cxx
  tree/ntuple/v7/inc/ROOT/RNTupleFillContext.hxx
  tree/ntuple/v7/inc/ROOT/RNTupleFillStatus.hxx
  tree/ntuple/v7/inc/ROOT/RNTupleModel.hxx
  tree/ntuple/v7/inc/ROOT/RNTupleWriter.hxx
  tree/ntuple/v7/src/RNTupleModel.cxx
  tree/ntuple/v7/src/RNTupleWriter.cxx
  tree/ntuple/v7/test/ntuple_basics.py
  tree/ntuple/v7/test/ntuple_cluster.cxx
  tree/ntuple/v7/test/ntuple_compat.cxx
  tree/ntuple/v7/test/ntuple_storage.cxx
  tree/ntuple/v7/test/ntuple_test.hxx
  tree/ntupleutil/v7/src/RNTupleImporter.cxx
  tree/ntupleutil/v7/test/ntuple_exporter.cxx
  tree/ntupleutil/v7/test/ntuple_inspector.cxx
  tutorials/io/ntuple/ntpl001_staff.C
  tutorials/io/ntuple/ntpl002_vector.C
  tutorials/io/ntuple/ntpl005_introspection.C
  tutorials/io/ntuple/ntpl007_mtFill.C
  tutorials/io/ntuple/ntpl010_skim.C
  tutorials/io/ntuple/ntpl012_processor_chain.C
  tutorials/io/ntuple/ntpl014_framework.C
  tutorials/io/ntuple/ntpl015_processor_join.C
Labels: in:RNTuple

#18092 [DF] Retrieve RDatasetSpec for RDF built from JSON
  tree/dataframe/inc/ROOT/RDF/Utils.hxx
  tree/dataframe/src/RDFUtils.cxx
  tree/dataframe/src/RDataFrame.cxx
Labels: clean build

#18219 [ntuple] Add tests and a warning for projected Real32(Quant|Trunc)
  tree/ntuple/v7/src/RNTupleModel.cxx
  tree/ntuple/v7/test/ntuple_project.cxx
Labels: in:RNTuple

#18226 [hist] reset kAxisRange bit when fully unzooming
  graf2d/gpad/src/TPad.cxx
  hist/hist/src/TAxis.cxx
  hist/histpainter/src/THistPainter.cxx
Labels: affects:master, in:Graphics

#18225 [ntuple] Move RNTupleReader out of Experimental
  gui/browsable/src/RFieldHolder.hxx
  gui/browsable/src/RFieldProvider.hxx
  gui/browsable/src/RNTupleBrowseProvider.cxx
  tree/dataframe/test/dataframe_snapshot_ntuple.cxx
  tree/ntuple/v7/inc/ROOT/REntry.hxx
  tree/ntuple/v7/inc/ROOT/RNTupleReader.hxx
  tree/ntuple/v7/inc/ROOT/RNTupleView.hxx
  tree/ntuple/v7/src/RNTupleReader.cxx
  tree/ntuple/v7/test/ntuple_cluster.cxx
  tree/ntuple/v7/test/ntuple_multi_column.cxx
  tree/ntuple/v7/test/ntuple_print.cxx
  tree/ntuple/v7/test/ntuple_show.cxx
  tree/ntuple/v7/test/ntuple_test.hxx
  tree/ntupleutil/v7/test/ntuple_importer.cxx
  tutorials/io/ntuple/ntpl001_staff.C
  tutorials/io/ntuple/ntpl002_vector.C
  tutorials/io/ntuple/ntpl005_introspection.C
  tutorials/io/ntuple/ntpl007_mtFill.C
  tutorials/io/ntuple/ntpl008_import.C
  tutorials/io/ntuple/ntpl009_parallelWriter.C
  tutorials/io/ntuple/ntpl010_skim.C
  tutorials/io/ntuple/ntpl014_framework.C
Labels: in:RNTuple

#18247 [v632][CMake] Don't force builtin libpng/gif/tiff/jpeg on macOS
  cmake/modules/SearchInstalledSoftware.cmake
  graf2d/asimage/CMakeLists.txt
Labels: pr:backport, in:Build System, clean build

#18246 [v634][CMake] Don't force builtin libpng/gif/tiff/jpeg on macOS
  cmake/modules/SearchInstalledSoftware.cmake
  graf2d/asimage/CMakeLists.txt
Labels: pr:backport, in:Build System, clean build

#18249 Properly format the preprocessor if clause
  graf2d/asimage/src/libAfterImage/libpng/pngpriv.h
Labels: clean build

#18267 [v632][CPyCppyy] Drop `__array__` from std::vector pythonizations
  bindings/pyroot/cppyy/CPyCppyy/src/Pythonize.cxx
  bindings/pyroot/cppyy/patches/CPyCppyy-Disable_std-vector-numpy-array-pythonization.patch
  bindings/pyroot/cppyy/sync-upstream
Labels: pr:backport, in:Python Interface

#18244 [core] improve TDirectory::DecodeNameCycle
  core/base/inc/TDirectory.h
  core/base/src/TDirectory.cxx
Labels: in:Core Libraries

#18271 [cling][JIT] Adapt compiler-rt changes for LLVM16
  interpreter/cling/lib/Interpreter/IncrementalJIT.cpp
Labels: clean build

#18269 [cppyy] Disable warnings for invalid function casts
  bindings/pyroot/cppyy/CPyCppyy/CMakeLists.txt
Labels: in:Python Interface

#18274 [BP][6.34][cppyy] Disable warnings for invalid function casts
  bindings/pyroot/cppyy/CPyCppyy/CMakeLists.txt
Labels: pr:backport

#18275 [BP][6.32][cppyy] Disable warnings for invalid function casts
  bindings/pyroot/cppyy/CPyCppyy/CMakeLists.txt
Labels: pr:backport

#18181 Remove fragile test
  bindings/pyroot/pythonizations/test/memory.py
Labels: in:Python Interface, in:Testing

#18279 [BP][6.34][tree] Don't dereference a nullptr in TTreeReaderValue test.
  tree/treeplayer/test/leafs.cxx
Labels: pr:backport

#18278 [BP][6.32][tree] Don't dereference a nullptr in TTreeReaderValue test.
  tree/treeplayer/test/leafs.cxx
Labels: pr:backport

#18266 [json] Check dictionary for std::map object in streaming
  io/io/src/TBufferJSON.cxx
Labels: affects:master, in:I/O

#18277 [CMake] Improve handling of RPATH options
  cmake/modules/RootBuildOptions.cmake
Labels: in:Build System, clean build

#18284 [cppyy] Do not use non-C++ GCC warning
  bindings/pyroot/cppyy/CPyCppyy/CMakeLists.txt
Labels: in:Python Interface

#18287 [6.32] [cppyy] Do not use non-C++ GCC warning
  bindings/pyroot/cppyy/CPyCppyy/CMakeLists.txt
Labels: pr:backport, in:Python Interface

#18110 [ntuple] update RNTupleModel's documentation
  tree/ntuple/v7/inc/ROOT/RNTupleModel.hxx
Labels: in:Documentation, in:RNTuple

#18270 [df] Move RNTupleDS out of experimental
  tree/dataframe/inc/ROOT/RDF/ActionHelpers.hxx
  tree/dataframe/inc/ROOT/RNTupleDS.hxx
  tree/dataframe/src/RLoopManager.cxx
  tree/dataframe/src/RNTupleDS.cxx
  tree/dataframe/test/datasource_ntuple.cxx
  tutorials/io/ntuple/ntpl004_dimuon.C
Labels: in:RDataFrame, in:RNTuple

#18187 [ntuple] Merger: fix improper output column id assignment in incremental merging
  tree/ntuple/v7/src/RNTupleMerger.cxx
  tree/ntuple/v7/test/ntuple_merger.cxx
Labels: in:RNTuple

#18272 [CMake] Manage libAfterImage builtins explicitly
  .github/workflows/root-ci-config/buildconfig/mac13.txt
  .github/workflows/root-ci-config/buildconfig/mac14.txt
  .github/workflows/root-ci-config/buildconfig/windows10.txt
  README/ReleaseNotes/v636/index.md
  cmake/modules/RootBuildOptions.cmake
  cmake/modules/SearchInstalledSoftware.cmake
Labels: in:Build System, clean build

#18253 [ntuple] more informative error message on failed open RMiniFile
  tree/ntuple/v7/src/RMiniFile.cxx
  tree/ntuple/v7/test/ntuple_minifile.cxx
Labels: in:RNTuple

#18289 [Json] check dictionary of std::map [6.34]
  io/io/src/TBufferJSON.cxx
Labels: pr:backport, in:I/O, affects:6.34

#18290 [Json] check dictionary for std::map [6.32]
  io/io/src/TBufferJSON.cxx
Labels: pr:backport, in:I/O, affects:6.32

#18305 [skip-ci] Minor documentation improvement for --web=server
  gui/webdisplay/src/RWebDisplayArgs.cxx
  gui/webdisplay/src/RWebWindowsManager.cxx
Labels: affects:master, in:Documentation, in:WebGui

#18178 Make basket size option a serializable type
  tree/dataframe/inc/ROOT/RDF/ActionHelpers.hxx
  tree/dataframe/inc/ROOT/RSnapshotOptions.hxx
Labels: in:RDataFrame

#18280 [RF] Use smart pointers in `RooStats::MCMCInterval`
  roofit/roostats/inc/RooStats/MCMCInterval.h
  roofit/roostats/src/MCMCInterval.cxx
Labels: in:RooFit/RooStats

#18276 [RF] Fix likelihood fits with constant probabliliy
  roofit/batchcompute/src/RooBatchCompute.cu
  roofit/batchcompute/src/RooBatchCompute.cxx
  roofit/roofitcore/inc/RooFit/Detail/RooNLLVarNew.h
  roofit/roofitcore/src/BatchModeDataHelpers.cxx
  roofit/roofitcore/src/RooNLLVarNew.cxx
  roofit/roofitcore/test/stressRooFit.cxx
  roofit/roofitcore/test/testTestStatistics.cxx
Labels: bug, in:RooFit/RooStats

#18282 [RF] Consistent collection proxy names between constructors
  roofit/roofit/src/RooBernstein.cxx
  roofit/roofit/src/RooChebychev.cxx
  roofit/roofit/src/RooTFnBinding.cxx
  roofit/roofitcore/inc/RooCollectionProxy.h
  roofit/roofitcore/src/RooPolyFunc.cxx
  roofit/roofitcore/src/RooProfileLL.cxx
  roofit/roofitcore/src/RooProjectedPdf.cxx
Labels: improvement, in:RooFit/RooStats

#18324 [TMVA][SOFIE] Fix RModel move constructor and assignment
  tmva/sofie/inc/TMVA/RModel.hxx
  tmva/sofie/inc/TMVA/RModel_Base.hxx
  tmva/sofie/src/RModel.cxx
Labels: in:TMVA

#18336 [gui,graf][nfc] apply clang-tidy fixit modernize-use-override
  graf2d/x11ttf/src/TGX11TTF.cxx
  gui/browsable/src/RGroup.cxx
  gui/browsable/src/RNTupleBrowseProvider.cxx
  gui/browsable/src/RSysFile.cxx
  gui/browsable/src/TBranchBrowseProvider.cxx
  gui/browsable/src/TDirectoryElement.cxx
  gui/browsable/src/TObjectElement.cxx
  gui/browserv7/src/RBrowser.cxx
  gui/browserv7/src/RBrowserGeomWidget.cxx
  gui/browserv7/src/RBrowserTCanvasWidget.cxx
  gui/browserv7/src/RBrowserTreeWidget.cxx
  gui/canvaspainter/src/RCanvasPainter.cxx
Labels: affects:master, clean build

#18291 [ntuple] Move RNTupleSerializer out of Experimental
  tree/ntuple/v7/inc/ROOT/RField.hxx
  tree/ntuple/v7/inc/ROOT/RMiniFile.hxx
  tree/ntuple/v7/inc/ROOT/RNTupleDescriptor.hxx
  tree/ntuple/v7/inc/ROOT/RNTupleSerialize.hxx
  tree/ntuple/v7/inc/ROOT/RPageStorage.hxx
  tree/ntuple/v7/inc/ROOT/RPageStorageDaos.hxx
  tree/ntuple/v7/inc/ROOT/RPageStorageFile.hxx
  tree/ntuple/v7/src/RFieldMeta.cxx
  tree/ntuple/v7/src/RMiniFile.cxx
  tree/ntuple/v7/src/RNTupleDescriptor.cxx
  tree/ntuple/v7/src/RNTupleMerger.cxx
  tree/ntuple/v7/src/RNTupleSerialize.cxx
  tree/ntuple/v7/src/RPageStorage.cxx
  tree/ntuple/v7/src/RPageStorageDaos.cxx
  tree/ntuple/v7/src/RPageStorageFile.cxx
  tree/ntuple/v7/test/ntuple_endian.cxx
  tree/ntuple/v7/test/ntuple_test.hxx
Labels: in:RNTuple

#18356 [webgui] Fix build on Windows
  gui/webdisplay/src/RWebDisplayHandle.cxx
Labels: pr:emergency🚨

#18309 [ntuple] Merger: properly compress generated zero pages
  tree/ntuple/v7/inc/ROOT/RNTupleMerger.hxx
  tree/ntuple/v7/src/RNTupleMerger.cxx
  tree/ntuple/v7/test/ntuple_merger.cxx
Labels: in:RNTuple

#18349 [TMVA][SOFIE] Implement wrapper for `BLAS::sgemm_` call
  tmva/sofie/inc/TMVA/ROperator_Gemm.hxx
  tmva/sofie/inc/TMVA/SOFIE_common.hxx
Labels: in:TMVA

#18299 [TMVA][SOFIE] Make it possible to build SOFIE without TFile support
  tmva/sofie/CMakeLists.txt
  tmva/sofie/src/RModel.cxx
  tmva/sofie/test/CMakeLists.txt
Labels: in:TMVA

#18300 [skip-ci] Update release notes with RNTuple out of Experimental
  README/ReleaseNotes/v636/index.md
Labels: in:RNTuple

#18320 tree: Fix address for nested split obj with io rule.
  tree/tree/inc/TBranch.h
  tree/tree/inc/TBranchElement.h
  tree/tree/src/TBranchElement.cxx
Labels: bug, in:I/O, in:TTree

#18268 zlib: Remove fdopen #defines.
  builtins/zlib/zutil.h
Labels: in:Core Libraries

#18375 [v634][Python] Backports for NumPy compatibility
  bindings/pyroot/pythonizations/python/ROOT/_pythonization/_rvec.py
  bindings/pyroot/pythonizations/test/rvec_asrvec.py
  bindings/pyroot/pythonizations/test/ttree_setbranchaddress.py
Labels: pr:backport, in:Python Interface

#18384 [ci] Remove duplicate env variables
  .github/workflows/root-ci.yml
Labels: in:CI

#18385 [ci] Enable ROOT asserts
  .github/workflows/root-ci.yml
Labels: in:CI

#18379 [tmva][sofie] Remove explicit function definitions that can be implicit
  tmva/sofie/inc/TMVA/RModel.hxx
  tmva/sofie/inc/TMVA/RModel_Base.hxx
  tmva/sofie/inc/TMVA/RModel_GNN.hxx
  tmva/sofie/inc/TMVA/RModel_GraphIndependent.hxx
  tmva/sofie/inc/TMVA/SOFIE_common.hxx
  tmva/sofie/src/RModel.cxx
  tmva/sofie/src/RModel_GNN.cxx
  tmva/sofie/src/RModel_GraphIndependent.cxx
Labels: in:TMVA

#18302 [TMVA][SOFIE] Use `uint8_t` instead of `bool` in return types
  tmva/sofie/inc/TMVA/SOFIE_common.hxx
  tmva/sofie/src/RModel.cxx
  tmva/sofie/test/TestCustomModelsFromONNX.cxx
Labels: in:TMVA

#18362 [ntuple] Move RMiniFileReader/RNTupleFileWriter out of Experimental
  tree/ntuple/v7/inc/ROOT/RMiniFile.hxx
  tree/ntuple/v7/inc/ROOT/RNTuple.hxx
  tree/ntuple/v7/inc/ROOT/RPageStorageFile.hxx
  tree/ntuple/v7/src/RMiniFile.cxx
  tree/ntuple/v7/src/RNTuple.cxx
  tree/ntuple/v7/src/RPageStorageFile.cxx
  tree/ntuple/v7/test/ntuple_test.hxx
Labels: in:RNTuple

#18397 [skip-ci][ntuple] Update documentation in Doxygen group
  tree/ntuple/v7/doc/README.md
Labels: in:Documentation, in:RNTuple

#18388 [ntuple] Remove deprecated typedefs
  tree/ntuple/v7/inc/ROOT/RCreateFieldOptions.hxx
  tree/ntuple/v7/inc/ROOT/REntry.hxx
  tree/ntuple/v7/inc/ROOT/RField.hxx
  tree/ntuple/v7/inc/ROOT/RField/RFieldFundamental.hxx
  tree/ntuple/v7/inc/ROOT/RField/RFieldProxiedCollection.hxx
  tree/ntuple/v7/inc/ROOT/RField/RFieldRecord.hxx
  tree/ntuple/v7/inc/ROOT/RField/RFieldSTLMisc.hxx
  tree/ntuple/v7/inc/ROOT/RField/RFieldSequenceContainer.hxx
  tree/ntuple/v7/inc/ROOT/RFieldBase.hxx
  tree/ntuple/v7/inc/ROOT/RNTupleDescriptor.hxx
  tree/ntuple/v7/inc/ROOT/RNTupleFillStatus.hxx
  tree/ntuple/v7/inc/ROOT/RNTupleModel.hxx
  tree/ntuple/v7/inc/ROOT/RNTupleRange.hxx
  tree/ntuple/v7/inc/ROOT/RNTupleReadOptions.hxx
  tree/ntuple/v7/inc/ROOT/RNTupleReader.hxx
  tree/ntuple/v7/inc/ROOT/RNTupleUtil.hxx
  tree/ntuple/v7/inc/ROOT/RNTupleView.hxx
  tree/ntuple/v7/inc/ROOT/RNTupleWriteOptions.hxx
  tree/ntuple/v7/inc/ROOT/RNTupleWriter.hxx
  tree/ntuple/v7/test/ntuple_basics.py
  tutorials/io/ntuple/ntpl011_global_temperatures.C
Labels: in:RNTuple

#18394 [ntuple] Remove experimental notice from tutorials
  tutorials/io/ntuple/ntpl001_staff.C
  tutorials/io/ntuple/ntpl002_vector.C
  tutorials/io/ntuple/ntpl004_dimuon.C
  tutorials/io/ntuple/ntpl005_introspection.C
  tutorials/io/ntuple/ntpl007_mtFill.C
  tutorials/io/ntuple/ntpl008_import.C
  tutorials/io/ntuple/ntpl009_parallelWriter.C
  tutorials/io/ntuple/ntpl010_skim.C
  tutorials/io/ntuple/ntpl011_global_temperatures.C
  tutorials/io/ntuple/ntpl012_processor_chain.C
  tutorials/io/ntuple/ntpl013_staged.C
  tutorials/io/ntuple/ntpl014_framework.C
  tutorials/io/ntuple/ntpl015_processor_join.C
Labels: in:RNTuple, in:Tutorials

#18399 [tmva][sofie] Add overload for inference code that takes output params
  tmva/sofie/inc/TMVA/SOFIE_common.hxx
  tmva/sofie/src/RModel.cxx
Labels: in:TMVA

#18408 [skip-ci][ci] Doc: create 6.32 doxy once per day, create 6.36 doxy
  .github/workflows/root-636.yml
  .github/workflows/root-docs-632.yml
Labels: in:Documentation, in:CI

#18409 [ci] Reduce the amount of builds of 6.34
  .github/workflows/root-ci.yml
Labels: in:CI

#18393 [graphics] set TMathText color in TLatex
  graf2d/graf/src/TLatex.cxx
Labels: affects:master, in:Graphics

#18423 [python] Improve CPyCppyy heuristic for Clone methods
  bindings/pyroot/cppyy/CPyCppyy/src/CPPOverload.cxx
Labels: in:Python Interface

#18124 Split long-running test
  tree/ntuple/test/CMakeLists.txt
  tree/ntuple/test/ntuple_extended.cxx
  tree/ntuple/test/ntuple_largefile1.cxx
  tree/ntuple/test/ntuple_largefile2.cxx
  tree/ntuple/test/ntuple_randomaccess.cxx
Labels: in:RNTuple

#18430 [python] UHI Refactoring: Slicing Logic, Equality Operator, and Negative Indexing
  bindings/pyroot/pythonizations/python/ROOT/_pythonization/_uhi.py
Labels: improvement, in:Python Interface

#18436 [ntuple][RDF] remove more Experimental/ROOT7 leftovers from RDF and RNTuple
  bindings/pyroot/pythonizations/CMakeLists.txt
  bindings/pyroot/pythonizations/python/ROOT/_pythonization/_rntuple.py
  bindings/pyroot/pythonizations/test/root_module.py
  tree/dataframe/inc/ROOT/RDF/ActionHelpers.hxx
  tree/dataframe/inc/ROOT/RDF/InterfaceUtils.hxx
  tree/dataframe/inc/ROOT/RDF/RInterface.hxx
  tree/dataframe/src/RDataFrame.cxx
  tutorials/CMakeLists.txt
Labels: in:RDataFrame, in:RNTuple

#18440 [base] Move RFloat16.hxx out of ROOT7
  core/base/CMakeLists.txt
  core/base/inc/ROOT/RFloat16.hxx
Labels: in:Core Libraries

#18438 [ntuple] add test for merging projected fields with diff sources
  tree/ntuple/test/ntuple_merger.cxx
Labels: in:RNTuple

#18445 [skip-ci][ntuple] Remove mention of `ntuple->Scan()`
  tutorials/io/ntuple/ntpl001_staff.C
  tutorials/io/ntuple/ntpl002_vector.C
Labels: in:RNTuple, in:Tutorials

#18444 [BP 632][ci] Do not run mac-beta builds on workflow dispatch triggers
  .github/workflows/root-ci.yml
Labels: pr:backport

#18457 Release notes for jsroot and graphics [skip-ci]
  README/ReleaseNotes/v636/index.md
Labels: in:Documentation

#18470 [Python] Fix RDF attribute of ROOT facade in case of `dataframe=OFF`
  bindings/pyroot/pythonizations/python/ROOT/_facade.py
Labels: in:Python Interface

#18378 Don't export `CLING_STANDARD_PCH=none` in setup scripts
  config/thisroot.bat
  config/thisroot.csh
  config/thisroot.fish
  config/thisroot.ps1
  config/thisroot.sh
Labels: in:Python Interface

#18367 [webgui] detect firefox in /snap/bin
  cmake/modules/RootConfiguration.cmake
  gui/webdisplay/inc/ROOT/RWebDisplayHandle.hxx
  gui/webdisplay/src/RWebDisplayHandle.cxx
Labels: affects:master, in:WebGui

#18478 [hist] Mark input `x` of the declared TFormula function as `const`
  hist/hist/src/TFormula.cxx
Labels: in:Math Libraries

#18153 [tutorials] Get rid of experimental category
  gui/browserv7/inc/ROOT/RBrowser.hxx
  gui/browserv7/inc/ROOT/RBrowserData.hxx
  gui/browserv7/inc/ROOT/RBrowserReply.hxx
  gui/browserv7/inc/ROOT/RBrowserRequest.hxx
  gui/browserv7/inc/ROOT/RFileDialog.hxx
  gui/browserv7/inc/ROOT/RWebBrowserImp.hxx
  tutorials/CMakeLists.txt
  tutorials/experimental/index.md
  tutorials/visualisation/index.md
  tutorials/visualisation/rcanvas/comic.woff2
  tutorials/visualisation/rcanvas/df104.py
  tutorials/visualisation/rcanvas/df105.py
  tutorials/visualisation/rcanvas/raxis.cxx
  tutorials/visualisation/rcanvas/rbox.cxx
  tutorials/visualisation/rcanvas/rbox.py
  tutorials/visualisation/rcanvas/rcanvas_mt.cxx
  tutorials/visualisation/rcanvas/rcanvas_update.cxx
  tutorials/visualisation/rcanvas/rframe.cxx
  tutorials/visualisation/rcanvas/rline.cxx
  tutorials/visualisation/rcanvas/rline_style.cxx
  tutorials/visualisation/rcanvas/rline_width.cxx
  tutorials/visualisation/rcanvas/rmarker.cxx
  tutorials/visualisation/rcanvas/rpad.cxx
  tutorials/visualisation/rcanvas/rpave.cxx
  tutorials/visualisation/rcanvas/rstyle.cxx
  tutorials/visualisation/rcanvas/rtext_align.cxx
  tutorials/visualisation/rcanvas/rtext_angle.cxx
  tutorials/visualisation/rcanvas/rtext_font.cxx
  tutorials/visualisation/rcanvas/symlog.cxx
  tutorials/visualisation/rcanvas/th1_twoscales.cxx
  tutorials/visualisation/rcanvas/tobject.cxx
  tutorials/visualisation/webgui/browserv7/browser.cxx
  tutorials/visualisation/webgui/browserv7/filedialog.cxx
  tutorials/visualisation/webgui/fitpanelv7/fitpanel6.cxx
Labels: in:Tutorials

#18491 [cmake] do not check none-existing variables
  CMakeLists.txt
Labels: affects:master, in:Build System

#18497 [cmake] Use consistent uppercase in `if(NOT WIN32)`
  CMakeLists.txt
Labels: in:Build System

#18493 [gpad] Fix illegal access to vector.at(-1) [6.36]
  graf2d/gpad/src/TPad.cxx
Labels: pr:backport, affects:6.36

#18465 [core] Add missing includes
  core/cont/inc/TCollectionProxyInfo.h
  math/mathcore/inc/Math/DistSampler.h
  math/mathcore/inc/Math/Functor.h
  tree/ntuple/inc/ROOT/RNTupleMetrics.hxx
Labels: clean build

#18496 [cmake] do not check none-existing variables [6.36]
  CMakeLists.txt
Labels: pr:backport, in:Build System, affects:6.36

#18485 [BP 636][io] fix small memleak in streamerInfoActions
  io/io/src/TStreamerInfoActions.cxx
Labels: pr:backport

#18510 [gpad] avoid potential float precision lost in PaintHatches
  graf2d/gpad/src/TPad.cxx
Labels: affects:master, in:Graphics

#18529 [rn] mention JSROOT 7.9.0 for jupyter [skip-ci] [6.36]
  README/ReleaseNotes/v636/index.md
Labels: in:Documentation, affects:6.36

#18480 [math][GenVector] Add access operator for Rotation3D
  math/genvector/inc/Math/GenVector/Rotation3D.h
Labels: in:Math Libraries

#18383 [clad] Bump clad to v1.10.
  interpreter/cling/tools/plugins/clad/CMakeLists.txt
Labels: clean build

#18522 [cling] The LookupHelper routines need the ROOT lock.
  core/clingutils/src/TClingUtils.cxx
  interpreter/cling/include/cling/Interpreter/InterpreterAccessRAII.h
Labels: in:Cling, clean build

#18543 [RF] Use the actual proxy list as input for RooFormula::doEval()
  roofit/roofitcore/src/RooFormula.cxx
  roofit/roofitcore/src/RooFormula.h
  roofit/roofitcore/src/RooFormulaVar.cxx
  roofit/roofitcore/src/RooGenericPdf.cxx
Labels: bug, in:RooFit/RooStats

#18550 [v636][cling] The LookupHelper routines need the ROOT lock
  core/clingutils/src/TClingUtils.cxx
  interpreter/cling/include/cling/Interpreter/InterpreterAccessRAII.h
Labels: pr:backport, in:Cling

#18559 [v636] [RF] Use the actual proxy list as input for RooFormula::doEval()
  roofit/roofitcore/src/RooFormula.cxx
  roofit/roofitcore/src/RooFormula.h
  roofit/roofitcore/src/RooFormulaVar.cxx
  roofit/roofitcore/src/RooGenericPdf.cxx
Labels: pr:backport, bug, in:RooFit/RooStats

#18561 [cmake] Add rootcling dependencies for Windows
  cmake/modules/RootMacros.cmake
Labels: in:Build System

#18564 [cmake] Do not delete the roottest dir during configuration
  CMakeLists.txt
Labels: in:Build System
