Repository root-project/root, pull requests merged in 2025-07, with the labels that each got.

#19222 [Python] Avoid hack in setting `__reduce__` attribute of CPPInstance
  bindings/pyroot/cppyy/CPyCppyy/src/CPPInstance.cxx
  bindings/pyroot/cppyy/CPyCppyy/src/CPPInstance.h
  bindings/pyroot/pythonizations/python/ROOT/_pythonization/_cppinstance.py
  bindings/pyroot/pythonizations/src/CPPInstancePyz.cxx
  bindings/pyroot/pythonizations/src/PyROOTModule.cxx
Labels: in:Python Interface, clean build

#19296 [skip-ci] ci: Checkout explicit branch in root-docs
  .github/workflows/root-docs-ci.yml
Labels: in:CI

#19297 [skip-ci] ci: Checkout explicit branch in root-docs [v6.36]
  .github/workflows/root-docs-ci.yml
Labels: pr:backport, in:CI

#19302 [skip-ci][ntuple] Fix outdated code example in RNTupleInspector.hxx
  tree/ntupleutil/v7/inc/ROOT/RNTupleInspector.hxx
Labels: in:RNTuple

#18871 [tree] Delegate SetBranchAddress to friends if necessary
  tree/tree/inc/TChain.h
  tree/tree/inc/TChainElement.h
  tree/tree/inc/TTree.h
  tree/tree/src/TChain.cxx
  tree/tree/src/TTree.cxx
  tree/treeplayer/test/CMakeLists.txt
  tree/treeplayer/test/gh16804.cxx
Labels: in:TTree, test coverage

#19301 [Python][UHI] Fix floating point comparisons of effective entries
  bindings/pyroot/pythonizations/test/uhi_indexing.py
  bindings/pyroot/pythonizations/test/uhi_plotting.py
Labels: in:Python Interface

#19315 [Python][UHI] Add implementation of __iter__ to fix list(h)
  bindings/pyroot/pythonizations/python/ROOT/_pythonization/_uhi.py
  bindings/pyroot/pythonizations/test/uhi_indexing.py
Labels: in:Python Interface

#19305 [main] replace rootls.py with new C++ version
  README/ReleaseNotes/v638/index.md
  main/CMakeLists.txt
  main/python/cmdLineUtils.py
  main/python/rootls.py
  roottest/main/CMakeLists.txt
  roottest/main/LongRootls.ref
  roottest/main/LongRootls2.ref
  roottest/main/LongRootls3.ref
  roottest/main/LongRootls4.ref
  roottest/main/MakeNameCyclesRootmvInput.C
  roottest/main/MultipleNameCyclesRootls.ref
  roottest/main/NameCyclesRootmvCheckOutput.ref
  roottest/main/ROOT_8197.C
  roottest/main/ROOT_8197.ref
  roottest/main/RecursiveRootls.ref
  roottest/main/SimplePattern.ref
  roottest/main/SimplePattern2.ref
  roottest/main/SimplePattern3.ref
  roottest/main/SimpleRootcp.ref
  roottest/main/SimpleRootcp2.ref
  roottest/main/SimpleRootcp3.ref
  roottest/main/SimpleRootcp4.ref
  roottest/main/SimpleRootcp5.ref
  roottest/main/SimpleRootls.ref
  roottest/main/SimpleRootls2.ref
  roottest/main/SimpleRootls3.ref
  roottest/main/SimpleRootls4.ref
  roottest/main/SimpleRootmkdir.ref
  roottest/main/SimpleRootmkdir2.ref
  roottest/main/SimpleRootmkdir3.ref
  roottest/main/SimpleRootmv.ref
  roottest/main/SimpleRootmv2.ref
  roottest/main/SimpleRootmv3.ref
  roottest/main/SimpleRootmv4.ref
  roottest/main/SimpleRootmv5.ref
  roottest/main/SimpleRootrm.ref
  roottest/main/SimpleRootrm2.ref
  roottest/main/SimpleRootrm3.ref
  roottest/main/TreeRootls.ref
  roottest/main/WebRootls.ref
  roottest/main/WebRootls2.ref
  roottest/main/multipleNameCycles.root
  roottest/main/simpleTree.root
  roottest/main/subdirs.root
  roottest/main/test.root
  roottest/main/testPatternToFileNameAndPathSplitList.py
  roottest/python/cmdLineUtils/CMakeLists.txt
Labels: clean build

#19318 Properly calculate offset of unsplittable base class of STL collection element type
  roottest/root/tree/gh-18782/CMakeLists.txt
  roottest/root/tree/gh-18782/MyParticle.cxx
  roottest/root/tree/gh-18782/MyParticle.hxx
  roottest/root/tree/gh-18782/MyParticleLinkDef.hxx
  roottest/root/tree/gh-18782/runtest.cxx
  tree/tree/src/TBranchElement.cxx
Labels: in:TTree

#19328 [CMake] Add `check_connection` flag to disable connection check
  cmake/modules/RootBuildOptions.cmake
  cmake/modules/SearchInstalledSoftware.cmake
Labels: in:Build System, clean build

#19332 [core] add macros in TestSupport to match partial dialogs
  core/testsupport/inc/ROOT/TestSupport.hxx
Labels: in:Core Libraries, in:Testing

#17784 [ntuple] use raw strings in ntuple_show for ease of reading
  tree/ntuple/test/ntuple_show.cxx
Labels: in:RNTuple

#19348 [CMake] Correct linking to VDT.
  cmake/modules/SearchInstalledSoftware.cmake
  math/vecops/CMakeLists.txt
  roofit/batchcompute/CMakeLists.txt
  tmva/tmva/CMakeLists.txt
Labels: clean build

#19316 [RF] Avoid using out-of-range values in RooDerivative
  roofit/roofitcore/src/RooDerivative.cxx
  tutorials/roofit/roofit/rf111_derivatives.C
  tutorials/roofit/roofit/rf111_derivatives.py
Labels: in:RooFit/RooStats

#19258 [RF] Implement checking param range
  roofit/roofit/src/RooBifurGauss.cxx
  roofit/roofit/src/RooBreitWigner.cxx
  roofit/roofit/src/RooChiSquarePdf.cxx
  roofit/roofit/src/RooPoisson.cxx
Labels: new contributor, in:RooFit/RooStats

#19337 [ntuple] Remove `/bigobj` flag for `RField.cxx`
  tree/ntuple/CMakeLists.txt
Labels: in:Build System, in:RNTuple

#19319 [ntuple] Fields tree as dot
  tree/ntupleutil/v7/inc/ROOT/RNTupleInspector.hxx
  tree/ntupleutil/v7/src/RNTupleInspector.cxx
  tree/ntupleutil/v7/test/ntuple_inspector.cxx
Labels: in:RNTuple

#19363 [hist] Ignore buffer in `TH1::Sumw2`
  hist/hist/src/TH1.cxx
  hist/hist/test/test_TH1.cxx
Labels: in:Hist

#19295 [skip-ci][hist] Document architecture for initial set of classes
  hist/histv7/doc/CodeArchitecture.md
Labels: in:Hist

#19312 Mitigate TChain with no files and SetBranchAddress call
  tree/tree/src/TChain.cxx
  tree/treeplayer/test/gh16804.cxx
Labels: in:TTree

#19386 [io] Register TKey after successful Streamer()
  io/io/src/TKey.cxx
  roottest/root/io/customStreamer/CMakeLists.txt
  roottest/root/io/customStreamer/StreamerThrow.C
  roottest/root/io/customStreamer/StreamerThrow.ref
  roottest/root/io/customStreamer/StreamerThrowClass.h
  roottest/root/io/customStreamer/StreamerThrowClass_LinkDef.h
Labels: in:I/O

#19406 [632][hist] Skip empty bins when add/filling sparse hist
  hist/hist/src/THnBase.cxx
  hist/hist/test/THn.cxx
Labels: pr:backport

#19405 [636][hist] Skip empty bins when add/filling sparse hist
  hist/hist/src/THnBase.cxx
  hist/hist/test/THn.cxx
Labels: pr:backport

#19415 [cling] Remove legacy GH workflow descrition
  interpreter/cling/.github/workflows/ci.yml
Labels: in:Cling, in:CI, skip ci

#19411 [ntuple] Fix wrong assert in Real32Quant
  tree/ntuple/src/RColumnElement.hxx
Labels: in:RNTuple

#19421 [CI] Fix PR label string for skip code analysis
  .github/workflows/code_analysis.yml
Labels: skip ci, skip code analysis

#19427 [skip-ci][imt] Remove documentation on ROOT namespace
  core/imt/inc/ROOT/RTaskArena.hxx
Labels: in:Documentation

#19420 [ntuple] Fix RBitsetField memory corruption on Windows
  tree/ntuple/inc/ROOT/RField/RFieldSTLMisc.hxx
  tree/ntuple/src/RField.cxx
Labels: in:RNTuple

#19426 [hist] Throw on streaming `Experimental` classes
  hist/histv7/inc/LinkDef.h
  hist/histv7/inc/ROOT/RRegularAxis.hxx
  hist/histv7/inc/ROOT/RVariableBinAxis.hxx
  hist/histv7/standalone.cmake
  hist/histv7/test/CMakeLists.txt
  hist/histv7/test/hist_io.cxx
Labels: in:Hist

#19439 [skip-ci][eve7] Remove documentation on ROOT namespace
  graf3d/eve7/inc/ROOT/REveVSDStructs.hxx
Labels: in:Documentation

#19469 Patch builtin Clad version to add missing include
  interpreter/cling/tools/plugins/clad/CMakeLists.txt
  interpreter/cling/tools/plugins/clad/patches/Add-missing-exception-include.patch
Labels: pr:emergency🚨, clean build

#19322 Improve logic to refresh branch addresses of TChain friends
  tree/tree/inc/TChain.h
  tree/tree/inc/TFriendElement.h
  tree/tree/src/TChain.cxx
  tree/treeplayer/test/CMakeLists.txt
  tree/treeplayer/test/gh16805.cxx
Labels: in:TTree

#19477 [636][hist] clip color to minimum if below with COLZ TH2
  hist/histpainter/src/THistPainter.cxx
Labels: pr:backport

#19465 [Python] Restructure Python libraries to not require system links
  bindings/pyroot/cppyy/CPyCppyy/CMakeLists.txt
  bindings/pyroot/cppyy/CPyCppyy/src/CPyCppyyModule.cxx
  bindings/pyroot/cppyy/CPyCppyy/src/CPyCppyyModule.h
  bindings/pyroot/cppyy/CPyCppyy/src/CPyCppyyPyModule.cxx
  bindings/pyroot/pythonizations/CMakeLists.txt
  bindings/pyroot/pythonizations/test/import_load_libs.py
  bindings/tpython/CMakeLists.txt
Labels: improvement, in:Python Interface, clean build

#19481 [CMake] Remove `ROOTTEST_DIR` variable
  cmake/modules/RootMacros.cmake
  roottest/CMakeLists.txt
  roottest/root/tree/fastcloningeventtree/CMakeLists.txt
Labels: in:Build System, clean build

#19482 [roottest] Fix warnings in AliAOD tests
  roottest/root/io/evolution/pragma_read/v1/AliAODForwardMult.cxx
  roottest/root/io/evolution/pragma_read/v2/AliAODForwardHeader.cxx
Labels: in:Testing
