Repository root-project/root, pull requests merged in 2025-05, with the labels that each got.

#18537 meta: Prevent memory hoarding for `GetClass("int")`
  core/meta/src/TClass.cxx
Labels: bug, in:Core Libraries

#18544 [v6-36][cmake] More fixes for CMake 4.0
  builtins/cfitsio/CMakeLists.txt
  builtins/pcre/CMakeLists.txt
  builtins/pcre/pcre-8.43.tar.bz2
  cmake/modules/SearchInstalledSoftware.cmake
Labels: pr:backport, affects:6.36

#18547 [v6-32][cmake] Fixes for CMake 4.0
  builtins/cfitsio/CMakeLists.txt
  builtins/davix/CMakeLists.txt
  builtins/pcre/CMakeLists.txt
  builtins/pcre/pcre-8.43.tar.bz2
  builtins/zeromq/libzmq/CMakeLists.txt
  cmake/modules/SearchInstalledSoftware.cmake
Labels: pr:backport, affects:6.32

#18578 [v632] meta: Prevent memory hoarding for `GetClass("int")`
  core/meta/src/TClass.cxx
Labels: pr:backport, in:Core Libraries

#18577 [v634] meta: Prevent memory hoarding for `GetClass("int")`
  core/meta/src/TClass.cxx
Labels: pr:backport, in:Core Libraries

#18576 [v636] meta: Prevent memory hoarding for `GetClass("int")`
  core/meta/src/TClass.cxx
Labels: pr:backport, in:Core Libraries

#18567 [CMake] Fix build with LLVM_LIBDIR_SUFFIX
  core/clingutils/CMakeLists.txt
  interpreter/CMakeLists.txt
Labels: in:Build System

#18569 [graf2d] Fix C++23 warnings about spaces in literal operator
  graf2d/gpadv7/inc/ROOT/RPadLength.hxx
Labels: in:Graphics

#18450 [meta] Return exec id of TRef, TRefArray and derived data members
  core/base/test/CMakeLists.txt
  core/base/test/TRefTests.cxx
  core/meta/src/TStreamerElement.cxx
Labels: in:Core Libraries

#18582 [v636][HF] Prevent histograms from registering in the list of cleanups.
  roofit/histfactory/inc/RooStats/HistFactory/Systematics.h
  roofit/histfactory/src/Channel.cxx
  roofit/histfactory/src/HistRef.cxx
Labels: pr:backport

#18589 [ci] Add back `pythia8=ON` to alma9 and Fedoras
  .github/workflows/root-ci-config/buildconfig/alma9.txt
  .github/workflows/root-ci-config/buildconfig/fedora41.txt
  .github/workflows/root-ci-config/buildconfig/fedora42.txt
Labels: clean build, in:CI

#18593 [ci] Set `builtin_nlohmannjson=OFF` also for AlmaLinux and Fedora
  .github/workflows/root-ci-config/buildconfig/alma9-clang.txt
  .github/workflows/root-ci-config/buildconfig/alma9.txt
  .github/workflows/root-ci-config/buildconfig/fedora41.txt
  .github/workflows/root-ci-config/buildconfig/fedora42.txt
Labels: clean build, in:CI

#18575 [BP 6.36][geom] Fix vecgeom interface
  geom/vecgeom/inc/TGeoVGShape.h
  geom/vecgeom/src/TGeoVGShape.cxx
Labels: pr:backport

#18460 [CMake] Get Clang directory from CLANG_INSTALL_PREFIX
  core/clingutils/CMakeLists.txt
  interpreter/CMakeLists.txt
Labels: in:Build System

#18603 [skip-ci][ntuple] Reorder column flags paragraphs
  tree/ntuple/doc/BinaryFormatSpecification.md
Labels: in:RNTuple

#18604 [Python] Don't call `TClass::GetClass()` on branch type in TTreePyz
  bindings/pyroot/pythonizations/src/TTreePyz.cxx
Labels: bug, in:Python Interface

#18435 [gui] Some fixes to TGNumberEntry
  gui/gui/src/TGNumberEntry.cxx
Labels: in:GUI

#18605 [webgui] let configure window queue length
  gui/webdisplay/src/RWebWindow.cxx
  gui/webdisplay/src/RWebWindowsManager.cxx
Labels: affects:master, in:WebGui

#18609 [ntuple] RNTupleMerger: use RLogger instead of TError-style logging
  tree/ntuple/src/RNTupleMerger.cxx
  tree/ntuple/test/ntuple_merger.cxx
Labels: in:RNTuple

#18464 [clang] Forward TPL of NestedNameSpecifier
  interpreter/llvm-project/clang/lib/AST/NestedNameSpecifier.cpp
  interpreter/llvm-project/llvm-project.tag
  roottest/root/meta/naming/CMakeLists.txt
  roottest/root/meta/naming/issue-18363/CMakeLists.txt
  roottest/root/meta/naming/issue-18363/Objects.h
  roottest/root/meta/naming/issue-18363/selection.xml
  roottest/root/meta/naming/issue-18363/templateNameTest.C
  roottest/root/meta/naming/issue-18363/templateNameTest.ref
Labels: pr:squash on merge, in:Cling

#18626 [io] Remove from url parameters parsed by TXNetFile
  io/io/src/TFile.cxx
Labels: in:I/O

#18627 [BP 6.36][io] Remove from url parameters parsed by TXNetFile
  io/io/src/TFile.cxx
Labels: pr:backport, in:I/O

#18628 [BP 6.34][io] Remove from url parameters parsed by TXNetFile
  io/io/src/TFile.cxx
Labels: pr:backport, in:I/O

#18635 [v636] Add RNTuple-related release notes
  README/ReleaseNotes/v636/index.md
Labels: pr:backport

#18644 [clang] Forward TPL of NestedNameSpecifier [v6.36]
  interpreter/llvm-project/clang/lib/AST/NestedNameSpecifier.cpp
  interpreter/llvm-project/llvm-project.tag
Labels: pr:backport, in:Cling

#18619 [ntuple] Fix setting of trivial traits for `RStreamerField`
  tree/ntuple/src/RFieldMeta.cxx
  tree/ntuple/test/StreamerField.hxx
  tree/ntuple/test/StreamerFieldLinkDef.h
  tree/ntuple/test/rfield_streamer.cxx
Labels: priority:high, in:RNTuple, experiment

#18620 [ntuple] Correctly construct values in staging area
  tree/ntuple/inc/ROOT/RField.hxx
  tree/ntuple/src/RFieldMeta.cxx
  tree/ntuple/test/CustomStruct.hxx
  tree/ntuple/test/CustomStructLinkDef.h
  tree/ntuple/test/rfield_class.cxx
Labels: priority:high, in:RNTuple, experiment

#18646 [tmva][sofie] Avoid `std::vector<bool>` for tensor types
  tmva/sofie/inc/TMVA/ROperator_Comparision.hxx
  tmva/sofie/inc/TMVA/ROperator_Where.hxx
  tmva/sofie/inc/TMVA/SOFIE_common.hxx
  tmva/sofie/src/RModel.cxx
  tmva/sofie/src/SOFIE_common.cxx
Labels: improvement, in:TMVA

#14717 [PyROOT][DF] `AsNumpy` automatically converts to numpy arrays
  bindings/pyroot/pythonizations/python/ROOT/_pythonization/_rdataframe.py
  bindings/pyroot/pythonizations/test/rdataframe_asnumpy.py
Labels: in:Python Interface

#18652 [ci] Try to fix retry logic
  .github/workflows/root-ci-config/build_utils.py
Labels: in:CI

#18662 [webcanvas] make default off for the TWebCanvas [6.36]
  cmake/modules/RootConfiguration.cmake
  core/base/src/TROOT.cxx
  gui/gui/src/TRootGuiFactory.cxx
Labels: in:WebGui, affects:6.36

#18655 [ntuple] Use bespoke log channel in RNTupleMerger (ROOT.NTuple.Merge)
  tree/ntuple/src/RNTupleMerger.cxx
  tree/ntuple/test/ntuple_merger.cxx
Labels: in:RNTuple

#18657 [clang] Forward TPL of NestedNameSpecifier [v6.32]
  interpreter/llvm-project/clang/lib/AST/NestedNameSpecifier.cpp
  interpreter/llvm-project/llvm-project.tag
Labels: pr:backport, in:Cling

#18632 Move some functionality away from RLoopManager
  tree/dataframe/inc/ROOT/RDF/RInterface.hxx
  tree/dataframe/inc/ROOT/RDF/RLoopManager.hxx
  tree/dataframe/inc/ROOT/RTTreeDS.hxx
  tree/dataframe/src/RLoopManager.cxx
  tree/dataframe/src/RTTreeDS.cxx
  tree/dataframe/test/dataframe_interface.cxx
  tree/dataframe/test/dataframe_snapshot_emptyoutput.cxx
Labels: in:RDataFrame

#18664 [webgui] improve rootssh [skip-ci]
  config/rootssh
Labels: affects:master, in:WebGui

#18601 [core] Allow using RError with non-default-constructible types
  core/foundation/inc/ROOT/RError.hxx
Labels: in:Core Libraries, clean build

#18642 [interpreter] Disable `LLVM_UNREACHABLE_OPTIMIZE`
  interpreter/CMakeLists.txt
Labels: in:Build System

#18675 [ntuple] Remove unused private `REntry` methods
  tree/ntuple/inc/ROOT/REntry.hxx
Labels: in:RNTuple

#18515 [runtime_cxxmodules] Fix '_FilesystemClock' build warning with macos 15.4 and mac-beta
  core/base/inc/Riostream.h
Labels: clean build

#18687 [skip-ci] Drop PyROOT from the README
  README.md
Labels: in:Documentation

#18668 [ntuple] Fix handling of composed auxiliary processors
  tree/ntuple/src/RNTupleProcessor.cxx
  tree/ntuple/test/ntuple_processor.cxx
Labels: in:RNTuple

#18670 [df] Support DefinePerSample for RNTuple
  tree/dataframe/inc/ROOT/RDataSource.hxx
  tree/dataframe/inc/ROOT/RNTupleDS.hxx
  tree/dataframe/inc/ROOT/RTTreeDS.hxx
  tree/dataframe/src/RDFUtils.cxx
  tree/dataframe/src/RDataSource.cxx
  tree/dataframe/src/RLoopManager.cxx
  tree/dataframe/src/RNTupleDS.cxx
  tree/dataframe/src/RTTreeDS.cxx
  tree/dataframe/test/dataframe_definepersample.cxx
Labels: in:RDataFrame, in:RNTuple

#18701 [skip-ci][tutorials] Remove Experimental category
  tutorials/index.md
Labels: in:Tutorials

#18690 [RF] Use `std::erf` and `std::erfc` in RooFit math functions
  roofit/roofitcore/inc/RooFit/Detail/MathFuncs.h
Labels: in:RooFit/RooStats

#18703 [v6-34][tmva] Fix compilation errors on Windows
  tmva/tmva/src/MethodDNN.cxx
Labels: pr:backport

#18689 [macOS] Include <chrono> to fix `_FilesystemClock` build warning
  core/base/inc/Riostream.h
Labels: pr:backport

#18704 [CMake][RF] Correctly declare dependencies in RooFitHS3 and xRooFit
  roofit/hs3/CMakeLists.txt
  roofit/xroofit/CMakeLists.txt
Labels: in:Build System

#18707 [v6-32][tmva] Fix compilation errors on Windows
  tmva/tmva/src/MethodDNN.cxx
Labels: pr:backport

#18659 [Math][GenVector] Replace `M_PI*` with `TMath` function calls
  math/genvector/inc/Math/GenVector/Cylindrical3D.h
  math/genvector/inc/Math/GenVector/CylindricalEta3D.h
  math/genvector/inc/Math/GenVector/EulerAngles.h
  math/genvector/inc/Math/GenVector/Polar2D.h
  math/genvector/inc/Math/GenVector/Polar3D.h
  math/genvector/inc/Math/GenVector/PtEtaPhiM4D.h
  math/genvector/inc/Math/GenVector/RotationX.h
  math/genvector/inc/Math/GenVector/RotationY.h
  math/genvector/inc/Math/GenVector/RotationZ.h
  math/genvector/inc/Math/GenVector/RotationZYX.h
  math/genvector/inc/Math/GenVector/VectorUtil.h
  math/genvector/src/3DConversions.cxx
  math/genvector/src/RotationZYX.cxx
  math/genvector/src/VectorUtil.cxx
Labels: in:Math Libraries

#18720 [636][ci] Enable C++23 for macOS Beta and 15
  .github/workflows/root-ci.yml
Labels: pr:backport

#18726 [roottest] fix leak when using TSystem::ConcatFileName
  roottest/root/io/newstl/TestHelpers.C
  roottest/root/io/newstl/test.C
  roottest/root/tree/cloning/runtreeCloneTest2.C
Labels: affects:master, in:Testing

#18706 [skip-ci][v636] Backport of RelNotes - distRDF and Tutorials
  README/ReleaseNotes/v636/index.md
Labels: pr:backport, in:Documentation

#18740 [v6-36][cmake] Check if cplusplus is 23 by default
  cmake/modules/CheckCompiler.cmake
Labels: pr:backport, affects:6.36

#18741 [Tutorials] Add Python dependencies for df101 and rf617.
  tutorials/CMakeLists.txt
Labels: pr:backport

#18746 [webgui][ui5] replace title by tooltip in CheckBox [6.36][skip-ci]
  ui5/canv/view/Hist.fragment.xml
Labels: pr:backport, in:WebGui, affects:6.36

#18730 [RF] Fix memory leak of ConcatFileName return value in RooWorkspace
  roofit/roofitcore/src/RooWorkspace.cxx
Labels: in:RooFit/RooStats

#18759 v634, core: Add semantic ROOT::EnableImplicitMT (#18694)
  core/base/inc/TROOT.h
  core/base/src/TROOT.cxx
  core/imt/inc/ROOT/RTaskArena.hxx
  core/imt/src/ROpaqueTaskArena.hxx
  core/imt/src/RTaskArena.cxx
  core/imt/src/TImplicitMT.cxx
  core/imt/test/CMakeLists.txt
  core/imt/test/testEnableImt.cxx
Labels: pr:backport, in:Core Libraries

#18758 v636, core: Add semantic ROOT::EnableImplicitMT
  core/base/inc/TROOT.h
  core/base/src/TROOT.cxx
  core/imt/inc/ROOT/RTaskArena.hxx
  core/imt/src/ROpaqueTaskArena.hxx
  core/imt/src/RTaskArena.cxx
  core/imt/src/TImplicitMT.cxx
  core/imt/test/CMakeLists.txt
  core/imt/test/testEnableImt.cxx
Labels: pr:backport, in:Core Libraries

#18760 v632, core: Add semantic ROOT::EnableImplicitMT (#18694)
  core/base/inc/TROOT.h
  core/base/src/TROOT.cxx
  core/imt/inc/ROOT/RTaskArena.hxx
  core/imt/src/ROpaqueTaskArena.hxx
  core/imt/src/RTaskArena.cxx
  core/imt/src/TImplicitMT.cxx
  core/imt/test/CMakeLists.txt
  core/imt/test/testEnableImt.cxx
Labels: pr:backport, in:Core Libraries

#18750 [RF] Disable loading architecture-specific RooBatchCompute by default
  roofit/batchcompute/res/RooBatchCompute.h
  roofit/batchcompute/src/Initialisation.cxx
  roofit/roofitcore/inc/RooGlobalFunc.h
  roofit/roofitcore/src/RooGlobalFunc.cxx
Labels: improvement, in:RooFit/RooStats

#18695 [skip-ci][ntuple] Add notes about disabled type checks
  tree/ntuple/inc/ROOT/REntry.hxx
  tree/ntuple/inc/ROOT/RNTupleReader.hxx
Labels: in:RNTuple

#18767 [skip-ci][ntuple] Add notes about disabled type checks [v6.36]
  tree/ntuple/inc/ROOT/REntry.hxx
  tree/ntuple/inc/ROOT/RNTupleReader.hxx
Labels: pr:backport, in:RNTuple

#18629 [ntuple] Cast min/max to the actual type when quantizing/unquantizing in Real32Quant
  tree/ntuple/inc/ROOT/RField/RFieldFundamental.hxx
  tree/ntuple/src/RColumnElement.hxx
  tree/ntuple/test/ntuple_packing.cxx
Labels: in:RNTuple

#18784 [v626][ci] Enable `dataframe` on alma9
  .github/workflows/root-ci-config/buildconfig/alma9.txt
Labels: in:CI

#18787 [v634][meta] Correct TClass::LoadClassInfo.
  core/meta/src/TClass.cxx
Labels: pr:backport, in:Core Libraries

#18786 [v636] [meta] Correct TClass::LoadClassInfo.
  core/meta/src/TClass.cxx
Labels: pr:backport, in:Core Libraries

#18790 [v626][ci] Enable `tmva` on alma9
  .github/workflows/root-ci-config/buildconfig/alma9.txt
Labels: in:CI

#18798 [build] Temporarily disable distributed RDF tests on MacOS14
  .github/workflows/root-ci-config/buildconfig/mac14.txt
Labels: in:Build System

#18783 [6.36][ntuple] Fix some inconsistencies in Real32Quant
  tree/ntuple/inc/ROOT/RField/RFieldFundamental.hxx
  tree/ntuple/src/RColumnElement.hxx
  tree/ntuple/test/ntuple_packing.cxx
Labels: in:RNTuple

#18749 [ntuple] Adapt hashing to 32-bit
  tree/ntuple/inc/ROOT/RNTupleJoinTable.hxx
Labels: in:RNTuple, clean build

#18769 [ntuple] Rename `RBulk` to `RBulkValues`
  tree/ntuple/doc/Architecture.md
  tree/ntuple/inc/ROOT/RFieldBase.hxx
  tree/ntuple/inc/ROOT/RNTupleModel.hxx
  tree/ntuple/inc/ROOT/RNTupleView.hxx
  tree/ntuple/src/RFieldBase.cxx
  tree/ntuple/src/RNTupleModel.cxx
  tree/ntuple/test/ntuple_bulk.cxx
  tree/ntuple/test/ntuple_multi_column.cxx
Labels: in:RNTuple

#18806 [clang-format] change standard to c++17 [skip-ci]
  .clang-format
Labels: affects:master

#18797 [df] Remove unused constructor in RNTupleDS
  tree/dataframe/inc/ROOT/RNTupleDS.hxx
  tree/dataframe/src/RNTupleDS.cxx
Labels: in:RDataFrame

#18803 [v636][ntuple] Rename `RBulk` to `RBulkValues`
  tree/ntuple/doc/Architecture.md
  tree/ntuple/inc/ROOT/RFieldBase.hxx
  tree/ntuple/inc/ROOT/RNTupleModel.hxx
  tree/ntuple/inc/ROOT/RNTupleView.hxx
  tree/ntuple/src/RFieldBase.cxx
  tree/ntuple/src/RNTupleModel.cxx
  tree/ntuple/test/ntuple_bulk.cxx
  tree/ntuple/test/ntuple_multi_column.cxx
Labels: pr:backport, in:RNTuple

#18807 [6.36] [df] Remove unused constructor in RNTupleDS
  tree/dataframe/inc/ROOT/RNTupleDS.hxx
  tree/dataframe/src/RNTupleDS.cxx
Labels: in:RDataFrame

#18551 cling: Deduplicate lock code. Keep semantic distinction.
  interpreter/cling/lib/Interpreter/EnterUserCodeRAII.h
  interpreter/cling/lib/Interpreter/LookupHelper.cpp
Labels: in:Cling

#18804 [core] improve R__unzip error messages
  core/zip/src/RZip.cxx
Labels: in:Core Libraries

#18802 [skip-ci] Add 6.36 release notes
  README/ReleaseNotes/v636/index.md
Labels: in:RDataFrame

#18812 [df] Another workaround for attempt to delete stack memory
  tree/dataframe/test/dataframe_friends.cxx
Labels: in:RDataFrame

#18823 [6.36][df] Another workaround for attempt to delete stack memory
  tree/dataframe/test/dataframe_friends.cxx
Labels: pr:backport, in:RDataFrame

#18831 [v634] [cling] Add ROOT lock to LookupHelper::findType
  interpreter/cling/lib/Interpreter/EnterUserCodeRAII.h
  interpreter/cling/lib/Interpreter/LookupHelper.cpp
Labels: pr:backport

#18814 [636] cling: Deduplicate lock code. Keep semantic distinction.
  interpreter/cling/lib/Interpreter/EnterUserCodeRAII.h
  interpreter/cling/lib/Interpreter/LookupHelper.cpp
Labels: pr:backport

#18828 [geom] Update Planck's constant to CODATA2022
  geom/geom/inc/TGeoPhysicalConstants.h
Labels: in:Geometry

#18835 🚨 [test] Remove compilation warning during ACLiC
  roottest/root/io/TFile/execNestedCollectionStreamerInfo.cxx
Labels: pr:emergency🚨

#18849 [skip-ci][df] Remove duplicate entry in release notes
  README/ReleaseNotes/v636/index.md
Labels: in:RDataFrame

#18862 [ci] Enable soversion option for all builds
  .github/workflows/root-ci-config/buildconfig/global.txt
Labels: in:CI

#18867 [cppyy] Use ROOT dictionary generation macro in cppyy tests
  bindings/pyroot/cppyy/cppyy/test/CMakeLists.txt
  bindings/pyroot/cppyy/cppyy/test/test_aclassloader.py
  bindings/pyroot/cppyy/cppyy/test/test_advancedcpp.py
  bindings/pyroot/cppyy/cppyy/test/test_conversions.py
  bindings/pyroot/cppyy/cppyy/test/test_cpp11features.py
  bindings/pyroot/cppyy/cppyy/test/test_crossinheritance.py
  bindings/pyroot/cppyy/cppyy/test/test_datatypes.py
  bindings/pyroot/cppyy/cppyy/test/test_doc_features.py
  bindings/pyroot/cppyy/cppyy/test/test_fragile.py
  bindings/pyroot/cppyy/cppyy/test/test_lowlevel.py
  bindings/pyroot/cppyy/cppyy/test/test_operators.py
  bindings/pyroot/cppyy/cppyy/test/test_overloads.py
  bindings/pyroot/cppyy/cppyy/test/test_pythonify.py
  bindings/pyroot/cppyy/cppyy/test/test_pythonization.py
  bindings/pyroot/cppyy/cppyy/test/test_stltypes.py
  bindings/pyroot/cppyy/cppyy/test/test_streams.py
  bindings/pyroot/cppyy/cppyy/test/test_templates.py
Labels: in:Build System, in:Python Interface, in:Testing, clean build

#18860 [coverage] Update reporting scope
  .github/workflows/root-ci-config/build_root.py
Labels: test coverage

#18858 [df] Add missing dict dependency for datasource_tree
  tree/dataframe/test/CMakeLists.txt
Labels: in:Build System

#18713 [roottest] use cmake for io/abstractclasses
  roottest/root/io/abstractclass/.rootrc
  roottest/root/io/abstractclass/CMakeLists.txt
  roottest/root/io/abstractclass/Makefile
  roottest/root/io/abstractclass/data.root
  roottest/root/io/abstractclass/load_vector.C
  roottest/root/io/abstractclass/read_test.C
  roottest/root/io/abstractclass/write_test.C
Labels: affects:master, in:I/O, in:Testing

#18880 [skip-ci] [tree] Update docs of TTree::GetEntriesFriend
  tree/tree/src/TTree.cxx
Labels: in:Documentation, in:TTree

#18883 [webgui] fix RWebWindow methods for embed widgets
  gui/webdisplay/src/RWebWindow.cxx
Labels: pr:backport, in:WebGui, affects:6.36

#18795 [roottest] Fixes to tree/cloning/CMakeLists.txt
  roottest/root/tree/cloning/CMakeLists.txt
  roottest/root/tree/cloning/generate-eventfile.sh
  test/MainEvent.cxx
Labels: clean build

#18898 [ci] Make alma10 regular build
  .github/workflows/root-ci.yml
Labels: in:CI

#5081 [TTree] Add compression algorithm test for TFile/TTree
  tree/tree/test/CMakeLists.txt
  tree/tree/test/TTreeCompression.cxx
Labels: new contributor, in:Testing, in:TTree

#18915 [v636][ci] Use builtin compression libraries for special alma9 builds
  .github/workflows/root-ci.yml
Labels: pr:backport, in:CI

#18917 [v632][ci] Make alma10 regular build
  .github/workflows/root-ci.yml
Labels: pr:backport, in:CI

#18612 [ntuple] Save a memcpy when reading a compressed Anchor in RMiniFile
  tree/ntuple/src/RMiniFile.cxx
Labels: in:RNTuple

#15310 [PyROOT] Move CPython extensions in subdirectories
  bindings/jupyroot/python/JupyROOT/helpers/handlers.py
  bindings/pyroot/pythonizations/CMakeLists.txt
  bindings/pyroot/pythonizations/python/ROOT/__init__.py
  bindings/pyroot/pythonizations/python/ROOT/_application.py
  bindings/pyroot/pythonizations/python/ROOT/_facade.py
  bindings/pyroot/pythonizations/python/ROOT/_pythonization/_cppinstance.py
  bindings/pyroot/pythonizations/python/ROOT/_pythonization/_generic.py
  bindings/pyroot/pythonizations/python/ROOT/_pythonization/_rdf_namespace.py
  bindings/pyroot/pythonizations/python/ROOT/_pythonization/_tclass.py
  bindings/pyroot/pythonizations/python/ROOT/_pythonization/_tobject.py
  bindings/pyroot/pythonizations/python/ROOT/_pythonization/_ttree.py
Labels: improvement, in:Python Interface, clean build
