Repository root-project/root, pull requests merged in 2025-03, with the labels that each got.

#17852 [Minuit2] Modernize linear algebra code
  math/minuit2/CMakeLists.txt
  math/minuit2/inc/Minuit2/ABObj.h
  math/minuit2/inc/Minuit2/ABProd.h
  math/minuit2/inc/Minuit2/ABSum.h
  math/minuit2/inc/Minuit2/ABTypes.h
  math/minuit2/inc/Minuit2/LASymMatrix.h
  math/minuit2/inc/Minuit2/LAVector.h
  math/minuit2/inc/Minuit2/LaInverse.h
  math/minuit2/inc/Minuit2/LaOuterProduct.h
  math/minuit2/inc/Minuit2/LaProd.h
  math/minuit2/inc/Minuit2/LaSum.h
  math/minuit2/inc/Minuit2/MatrixInverse.h
  math/minuit2/inc/Minuit2/MinimumError.h
  math/minuit2/inc/Minuit2/MinimumParameters.h
  math/minuit2/inc/Minuit2/MnMatrix.h
  math/minuit2/inc/Minuit2/MnPrint.h
  math/minuit2/inc/Minuit2/StackAllocator.h
  math/minuit2/inc/Minuit2/VectorOuterProduct.h
  math/minuit2/src/BFGSErrorUpdator.cxx
  math/minuit2/src/CMakeLists.txt
  math/minuit2/src/DavidonErrorUpdator.cxx
  math/minuit2/src/FumiliBuilder.cxx
  math/minuit2/src/FumiliErrorUpdator.cxx
  math/minuit2/src/LaEigenValues.cxx
  math/minuit2/src/LaInnerProduct.cxx
  math/minuit2/src/LaInverse.cxx
  math/minuit2/src/LaOuterProduct.cxx
  math/minuit2/src/LaSumOfElements.cxx
  math/minuit2/src/LaVtMVSimilarity.cxx
  math/minuit2/src/MnEigen.cxx
  math/minuit2/src/MnLineSearch.cxx
  math/minuit2/src/MnMatrix.cxx
  math/minuit2/src/MnPosDef.cxx
  math/minuit2/src/MnPrint.cxx
  math/minuit2/src/VariableMetricBuilder.cxx
  math/minuit2/src/VariableMetricEDMEstimator.cxx
  math/minuit2/src/mndasum.cxx
  math/minuit2/src/mndaxpy.cxx
  math/minuit2/src/mnddot.cxx
  math/minuit2/src/mndscal.cxx
  math/minuit2/src/mndspmv.cxx
  math/minuit2/src/mndspr.cxx
  math/minuit2/src/mnlsame.cxx
  math/minuit2/src/mnteigen.cxx
  math/minuit2/src/mnvert.cxx
  math/minuit2/src/mnxerbla.cxx
Labels: in:Math Libraries

#17861 [io] TFileMergerTest: add missing TBranch include
  io/io/test/TFileMergerTests.cxx
Labels: in:I/O

#17880 [CMake] Only build Clad on a single core if the workaround if needed
  interpreter/cling/tools/plugins/clad/CMakeLists.txt
Labels: improvement, in:Build System

#17879 [skip-ci][ntuple] Fix doc comment of RNTupleMergeOptions
  tree/ntuple/v7/inc/ROOT/RNTupleMerger.hxx
Labels: in:RNTuple

#17887 [ntuple] Fix GCC shadow warning
  tree/ntuple/v7/src/RFieldUtils.cxx
Labels: in:RNTuple

#17888 [CMake] Compare to the right CMake version for `-j 1` workaround
  interpreter/cling/tools/plugins/clad/CMakeLists.txt
Labels: in:Build System, clean build

#17683 [geompainter] correctly handle drawing on the pad [6.34]
  geom/geom/src/TGeoManager.cxx
Labels: pr:backport, in:Geometry, in:Graphics, affects:6.34

#17877 [ntuple] move RNTupleZip out of Experimental
  tree/ntuple/v7/inc/ROOT/RNTupleZip.hxx
  tree/ntuple/v7/inc/ROOT/RPageStorage.hxx
  tree/ntuple/v7/src/RMiniFile.cxx
  tree/ntuple/v7/src/RPageStorage.cxx
  tree/ntuple/v7/src/RPageStorageDaos.cxx
  tree/ntuple/v7/src/RPageStorageFile.cxx
  tree/ntuple/v7/test/ntuple_test.hxx
Labels: in:RNTuple

#17849 [Minuit2] Delete unused MnRefCountedPointer and MnReferenceCounter
  math/minuit2/inc/Minuit2/MnRefCountedPointer.h
  math/minuit2/inc/Minuit2/MnReferenceCounter.h
Labels: in:Math Libraries

#17893 [RF] numerical stabilities in rooCB
  roofit/roofit/src/RooCrystalBall.cxx
Labels: in:RooFit/RooStats

#17902 [ntuple] Use actual unaligned ntuples in test for chained joins
  tree/ntuple/v7/test/ntuple_processor.cxx
Labels: in:RNTuple

#17905 [NFC] Do not rely on string representation in test
  bindings/pyroot/pythonizations/test/string_view.py
Labels: in:Python Interface, in:RDataFrame

#17908 Simplify nslots in RDataSource
  tree/dataframe/inc/ROOT/RArrowDS.hxx
  tree/dataframe/inc/ROOT/RCsvDS.hxx
  tree/dataframe/inc/ROOT/RDF/RLazyDSImpl.hxx
  tree/dataframe/inc/ROOT/RDataSource.hxx
  tree/dataframe/inc/ROOT/RNTupleDS.hxx
  tree/dataframe/inc/ROOT/RRootDS.hxx
  tree/dataframe/inc/ROOT/RSqliteDS.hxx
  tree/dataframe/inc/ROOT/RTrivialDS.hxx
  tree/dataframe/inc/ROOT/RVecDS.hxx
  tree/dataframe/src/RSqliteDS.cxx
  tree/dataframe/test/RStreamingDS.hxx
Labels: in:RDataFrame

#17917 [skip-ci][ci] Copy the release notes also to EOS
  .github/workflows/root-rn-ci.yml
Labels: in:CI

#17915 [ntuple] Initialize variable in ntuple_zip test
  tree/ntuple/v7/test/ntuple_zip.cxx
Labels: in:RNTuple

#17921 [Python] Reduce time before asyncronous run in JupyROOT unit test
  bindings/jupyroot/python/JupyROOT/helpers/handlers.py
Labels: in:Python Interface

#17914 [ntuple] Move Internal RNTupleUtils out of Experimental
  tree/ntuple/v7/inc/ROOT/RNTupleUtil.hxx
  tree/ntuple/v7/inc/ROOT/RNTupleView.hxx
  tree/ntuple/v7/src/RColumnElement.hxx
  tree/ntuple/v7/src/RFieldBase.cxx
  tree/ntuple/v7/src/RFieldMeta.cxx
  tree/ntuple/v7/src/RMiniFile.cxx
  tree/ntuple/v7/src/RNTupleDescriptor.cxx
  tree/ntuple/v7/src/RNTupleMerger.cxx
  tree/ntuple/v7/src/RNTupleModel.cxx
  tree/ntuple/v7/src/RNTupleSerialize.cxx
  tree/ntuple/v7/src/RNTupleUtil.cxx
  tree/ntuple/v7/src/RPageSinkBuf.cxx
  tree/ntuple/v7/src/RPageStorage.cxx
  tree/ntuple/v7/src/RPageStorageDaos.cxx
  tree/ntuple/v7/src/RPageStorageFile.cxx
  tree/ntuple/v7/test/ntuple_compat.cxx
  tree/ntuple/v7/test/ntuple_test.hxx
Labels: in:RNTuple

#17912 [ntuple] update tutorials to avoid deprecation warnings
  tutorials/io/ntuple/ntpl005_introspection.C
  tutorials/io/ntuple/ntpl009_parallelWriter.C
  tutorials/io/ntuple/ntpl013_staged.C
  tutorials/io/ntuple/ntpl014_framework.C
Labels: in:RNTuple

#17903 Enable untyped reading of TTree data
  tree/dataframe/inc/ROOT/RDF/RTreeColumnReader.hxx
  tree/treeplayer/inc/TBranchProxy.h
  tree/treeplayer/inc/TTreeReaderArray.h
  tree/treeplayer/inc/TTreeReaderUtils.h
  tree/treeplayer/inc/TTreeReaderValue.h
  tree/treeplayer/src/TBranchProxy.cxx
  tree/treeplayer/src/TTreeReaderArray.cxx
Labels: in:RDataFrame

#17928 [ntuple] rename kTestFutureType -> kTestFutureColumnType
  tree/ntuple/v7/inc/ROOT/RNTupleUtil.hxx
  tree/ntuple/v7/src/RColumnElement.cxx
  tree/ntuple/v7/src/RColumnElement.hxx
  tree/ntuple/v7/src/RNTupleSerialize.cxx
  tree/ntuple/v7/test/ntuple_compat.cxx
Labels: in:RNTuple

#17938 Properly store colors in palette, attributes in TParallelCoord
  hist/histpainter/src/TPaletteAxis.cxx
  tree/treeviewer/src/TParallelCoord.cxx
  tree/treeviewer/src/TParallelCoordVar.cxx
Labels: affects:master, in:Graphics

#17957 [Minuit2] Add missing operator to add algebraic vector objects
  math/minuit2/inc/Minuit2/MnMatrix.h
Labels: in:Math Libraries

#17942 [Minuit2] Rule of five for Minuit2 linear algebra classes
  math/minuit2/inc/Minuit2/MnMatrix.h
Labels: in:Math Libraries

#17927 Improve semantics of data member
  tree/dataframe/inc/ROOT/RDF/RDefaultValueFor.hxx
  tree/dataframe/inc/ROOT/RDF/RFilterWithMissingValues.hxx
  tree/dataframe/inc/ROOT/RDF/RLoopManager.hxx
  tree/dataframe/src/RDFInterfaceUtils.cxx
  tree/treeplayer/inc/ROOT/TTreeProcessorMT.hxx
  tree/treeplayer/inc/TTreeReader.h
  tree/treeplayer/src/TTreeProcessorMT.cxx
  tree/treeplayer/src/TTreeReader.cxx
  tree/treeplayer/src/TTreeReaderArray.cxx
  tree/treeplayer/src/TTreeReaderValue.cxx
Labels: in:RDataFrame

#17931 Remove typed TTree column readers
  tree/dataframe/CMakeLists.txt
  tree/dataframe/inc/ROOT/RDF/ColumnReaderUtils.hxx
  tree/dataframe/inc/ROOT/RDF/RDefaultValueFor.hxx
  tree/dataframe/inc/ROOT/RDF/RFilterWithMissingValues.hxx
  tree/dataframe/inc/ROOT/RDF/RTreeColumnReader.hxx
  tree/dataframe/src/RDFColumnReaderUtils.cxx
  tree/dataframe/src/RTreeColumnReader.cxx
  tree/dataframe/test/dataframe_regression.cxx
  tree/dataframe/test/dataframe_snapshot.cxx
Labels: in:RDataFrame

#17949 [ntuple] cast uint64_t to size_t to avoid warnings on windows 32 bit
  tree/ntuple/v7/src/RPageStorageFile.cxx
Labels: in:RNTuple

#17794 [ntuple] Move RPage/RPagePool/RPageAllocator out of Experimental
  tree/ntuple/v7/inc/ROOT/RColumn.hxx
  tree/ntuple/v7/inc/ROOT/RNTupleMerger.hxx
  tree/ntuple/v7/inc/ROOT/RPage.hxx
  tree/ntuple/v7/inc/ROOT/RPageAllocator.hxx
  tree/ntuple/v7/inc/ROOT/RPageNullSink.hxx
  tree/ntuple/v7/inc/ROOT/RPagePool.hxx
  tree/ntuple/v7/inc/ROOT/RPageSinkBuf.hxx
  tree/ntuple/v7/inc/ROOT/RPageStorage.hxx
  tree/ntuple/v7/inc/ROOT/RPageStorageDaos.hxx
  tree/ntuple/v7/inc/ROOT/RPageStorageFile.hxx
  tree/ntuple/v7/src/RNTupleDescriptor.cxx
  tree/ntuple/v7/src/RNTupleMerger.cxx
  tree/ntuple/v7/src/RNTupleParallelWriter.cxx
  tree/ntuple/v7/src/RPage.cxx
  tree/ntuple/v7/src/RPageAllocator.cxx
  tree/ntuple/v7/src/RPagePool.cxx
  tree/ntuple/v7/src/RPageSinkBuf.cxx
  tree/ntuple/v7/src/RPageStorage.cxx
  tree/ntuple/v7/src/RPageStorageDaos.cxx
  tree/ntuple/v7/src/RPageStorageFile.cxx
  tree/ntuple/v7/test/ntuple_cluster.cxx
  tree/ntuple/v7/test/ntuple_endian.cxx
  tree/ntuple/v7/test/ntuple_test.hxx
Labels: in:RNTuple

#17963 [ntuple] Remove some PreserveFile() in ntuple_merger.cxx
  tree/ntuple/v7/test/ntuple_merger.cxx
Labels: in:RNTuple

#17965 [ci] Add Ubuntu 25.04 and Fedora 42 configurations
  .github/workflows/root-ci-config/buildconfig/fedora42.txt
  .github/workflows/root-ci-config/buildconfig/ubuntu2504.txt
  .github/workflows/root-ci.yml
Labels: in:CI

#17980 [v632][cmake] Build Clad with one core only when needed
  interpreter/cling/tools/plugins/clad/CMakeLists.txt
Labels: pr:backport, in:Build System, clean build

#17981 [v634][cmake] Build Clad with one core only when needed
  interpreter/cling/tools/plugins/clad/CMakeLists.txt
Labels: pr:backport, in:Build System, clean build

#17982 [v632] Fix numba tests with Python 3.13+
  bindings/pyroot/pythonizations/python/ROOT/_numbadeclare.py
Labels: pr:backport, in:Python Interface

#17983 [v634] Fix numba tests with Python 3.13+
  bindings/pyroot/pythonizations/python/ROOT/_numbadeclare.py
Labels: pr:backport, in:Python Interface

#17971 Save custom TH1 contour only is such was configured
  hist/hist/src/TH1.cxx
Labels: affects:master, in:Graphics

#17975 Improve exception safety of RDataSource range processing
  tree/dataframe/inc/ROOT/RDF/RLoopManager.hxx
  tree/dataframe/src/RLoopManager.cxx
Labels: in:RDataFrame

#17966 [ntuple] Move RColumn(Index|Switch) out of Experimental
  tree/dataframe/src/RNTupleDS.cxx
  tree/ntuple/v7/inc/ROOT/RColumn.hxx
  tree/ntuple/v7/inc/ROOT/RField.hxx
  tree/ntuple/v7/inc/ROOT/RField/RFieldProxiedCollection.hxx
  tree/ntuple/v7/inc/ROOT/RField/RFieldSTLMisc.hxx
  tree/ntuple/v7/inc/ROOT/RField/RFieldSequenceContainer.hxx
  tree/ntuple/v7/inc/ROOT/RNTupleUtil.hxx
  tree/ntuple/v7/src/RColumnElement.cxx
  tree/ntuple/v7/src/RColumnElement.hxx
  tree/ntuple/v7/src/RField.cxx
  tree/ntuple/v7/src/RFieldMeta.cxx
  tree/ntuple/v7/src/RFieldSequenceContainer.cxx
  tree/ntuple/v7/src/RNTupleMerger.cxx
  tree/ntuple/v7/test/ntuple_endian.cxx
  tree/ntuple/v7/test/ntuple_packing.cxx
  tree/ntuple/v7/test/ntuple_test.hxx
Labels: in:RNTuple

#17988 Fix an error in the ctor from a file
  hist/hist/src/TGraphAsymmErrors.cxx
Labels: affects:master, in:Graphics

#17933 [RF] Remove RooFitResult methods that use `gMinuit`
  roofit/roofitcore/CMakeLists.txt
  roofit/roofitcore/inc/RooFitResult.h
  roofit/roofitcore/src/RooFitResult.cxx
Labels: in:RooFit/RooStats

#17968 [pyroot] Move JupyROOT files at build time.
  bindings/jupyroot/CMakeLists.txt
Labels: clean build

#17926 [RF] Add timing printouts to RooFit likelihood creation
  roofit/roofitcore/res/RooFitImplHelpers.h
  roofit/roofitcore/src/FitHelpers.cxx
  roofit/roofitcore/src/RooFitImplHelpers.cxx
  roofit/roofitcore/src/RooFuncWrapper.cxx
Labels: in:RooFit/RooStats

#18006 [cmake] Use cfitsio sources from the lcg website
  builtins/cfitsio/CMakeLists.txt
Labels: in:Build System

#17979 [CMake] Correctly consider `fail-on-missing` for `tmva-cpu`
  cmake/modules/SearchInstalledSoftware.cmake
Labels: in:Build System, in:TMVA

#17987 [ntuple] Move RColumn out of Experimental
  tree/ntuple/v7/inc/ROOT/RColumn.hxx
  tree/ntuple/v7/inc/ROOT/RField/RFieldFundamental.hxx
  tree/ntuple/v7/inc/ROOT/RFieldBase.hxx
  tree/ntuple/v7/inc/ROOT/RPageNullSink.hxx
  tree/ntuple/v7/inc/ROOT/RPageSinkBuf.hxx
  tree/ntuple/v7/inc/ROOT/RPageStorage.hxx
  tree/ntuple/v7/src/RColumn.cxx
  tree/ntuple/v7/src/RNTupleParallelWriter.cxx
  tree/ntuple/v7/src/RPageSinkBuf.cxx
  tree/ntuple/v7/src/RPageStorage.cxx
  tree/ntuple/v7/test/ntuple_cluster.cxx
  tree/ntuple/v7/test/ntuple_endian.cxx
  tree/ntuple/v7/test/ntuple_storage.cxx
Labels: in:RNTuple

#18022 [CMake] Use `clangCppInterOp` directly as input for Cling target
  core/metacling/src/CMakeLists.txt
Labels: in:Build System, clean build

#17967 Add option for generic Python tests
  bindings/pyroot/pythonizations/test/CMakeLists.txt
  cmake/modules/RootMacros.cmake
Labels: in:Build System

#12745 Simplify CallFunc. NFC
  core/metacling/src/TClingCallFunc.cxx
Labels: in:Core Libraries

#18026 [CMake] Fix building Clad with `builtin_llvm=OFF`
  interpreter/cling/tools/plugins/clad/CMakeLists.txt
Labels: in:Build System, clean build

#18024 [ntuple] Move RPageInfo(Extended) up one level of nesting
  tree/ntuple/v7/inc/ROOT/RNTupleDescriptor.hxx
  tree/ntuple/v7/inc/ROOT/RPageStorage.hxx
  tree/ntuple/v7/src/RNTupleDescriptor.cxx
  tree/ntuple/v7/src/RPageStorage.cxx
  tree/ntuple/v7/src/RPageStorageDaos.cxx
  tree/ntuple/v7/src/RPageStorageFile.cxx
  tree/ntuple/v7/test/ntuple_serialize.cxx
Labels: in:RNTuple

#18034 [df] Avoid creating readers for unavailable columns
  tree/dataframe/inc/ROOT/RDF/RInterface.hxx
Labels: in:RDataFrame

#18035 [Python] Sync `cppyy` and `CPyCppyy` with current master branches
  bindings/pyroot/cppyy/CPyCppyy/pyproject.toml
  bindings/pyroot/cppyy/CPyCppyy/src/CPPClassMethod.cxx
  bindings/pyroot/cppyy/CPyCppyy/src/CPPClassMethod.h
  bindings/pyroot/cppyy/CPyCppyy/src/CPPEnum.cxx
  bindings/pyroot/cppyy/CPyCppyy/src/CPPFunction.cxx
  bindings/pyroot/cppyy/CPyCppyy/src/CPPFunction.h
  bindings/pyroot/cppyy/CPyCppyy/src/CPPMethod.cxx
  bindings/pyroot/cppyy/CPyCppyy/src/Converters.cxx
  bindings/pyroot/cppyy/CPyCppyy/src/DeclareConverters.h
  bindings/pyroot/cppyy/CPyCppyy/src/DeclareExecutors.h
  bindings/pyroot/cppyy/CPyCppyy/src/Executors.cxx
  bindings/pyroot/cppyy/CPyCppyy/src/LowLevelViews.cxx
  bindings/pyroot/cppyy/CPyCppyy/src/LowLevelViews.h
  bindings/pyroot/cppyy/CPyCppyy/src/TemplateProxy.cxx
  bindings/pyroot/cppyy/CPyCppyy/src/Utility.cxx
  bindings/pyroot/cppyy/cppyy/README.rst
  bindings/pyroot/cppyy/cppyy/doc/source/changelog.rst
  bindings/pyroot/cppyy/cppyy/doc/source/cppyy_features_header.rst
  bindings/pyroot/cppyy/cppyy/test/test_cpp11features.py
  bindings/pyroot/cppyy/cppyy/test/test_crossinheritance.py
  bindings/pyroot/cppyy/cppyy/test/test_fragile.py
  bindings/pyroot/cppyy/cppyy/test/test_pythonify.py
  bindings/pyroot/cppyy/cppyy/test/test_regression.py
  bindings/pyroot/cppyy/cppyy/test/test_stltypes.py
  bindings/pyroot/cppyy/sync-upstream
Labels: in:Python Interface

#18033 Provide default implementation of virtual method
  tree/dataframe/inc/ROOT/RDataSource.hxx
  tree/dataframe/inc/ROOT/RVecDS.hxx
  tree/dataframe/test/RArraysDS.hxx
  tree/dataframe/test/RNonCopiableColumnDS.hxx
  tree/dataframe/test/RStreamingDS.hxx
Labels: in:RDataFrame

#18031 [ntuple] Move RFieldVisitor out of Experimental
  gui/browsable/src/RFieldProvider.hxx
  tree/ntuple/v7/inc/ROOT/RField.hxx
  tree/ntuple/v7/inc/ROOT/RField/RFieldFundamental.hxx
  tree/ntuple/v7/inc/ROOT/RField/RFieldProxiedCollection.hxx
  tree/ntuple/v7/inc/ROOT/RField/RFieldRecord.hxx
  tree/ntuple/v7/inc/ROOT/RField/RFieldSTLMisc.hxx
  tree/ntuple/v7/inc/ROOT/RField/RFieldSequenceContainer.hxx
  tree/ntuple/v7/inc/ROOT/RFieldBase.hxx
  tree/ntuple/v7/inc/ROOT/RFieldVisitor.hxx
  tree/ntuple/v7/src/RField.cxx
  tree/ntuple/v7/src/RFieldBase.cxx
  tree/ntuple/v7/src/RFieldMeta.cxx
  tree/ntuple/v7/src/RFieldSequenceContainer.cxx
  tree/ntuple/v7/src/RFieldVisitor.cxx
  tree/ntuple/v7/src/RNTupleReader.cxx
  tree/ntuple/v7/test/ntuple_test.hxx
Labels: in:RNTuple

#18019 [RF] Avoid setting out-of-range value in NaNPacker tests
  roofit/roofitcore/test/TestStatistics/testLikelihoodGradientJob.cxx
  roofit/roofitcore/test/testNaNPacker.cxx
Labels: in:RooFit/RooStats

#18020 [RF][RS] Fix StandardHistFactoryPlotsWithCategories tutorial
  tutorials/roofit/roostats/StandardHistFactoryPlotsWithCategories.C
  tutorials/roofit/roostats/StandardHistFactoryPlotsWithCategories.py
Labels: in:RooFit/RooStats

#18050 [v634][CMake] Fix building Clad with `builtin_llvm=OFF`
  interpreter/cling/tools/plugins/clad/CMakeLists.txt
Labels: pr:backport, in:Build System

#18046 [webgui] exclude old headless mode for newest chrome browser
  gui/webdisplay/src/RWebDisplayHandle.cxx
Labels: affects:master, in:WebGui

#18047 [webgui] exclude old headless mode for newest chrome browser [6.34]
  gui/webdisplay/src/RWebDisplayHandle.cxx
Labels: pr:backport, in:WebGui, affects:6.34

#18056 [v634][RF] Move some private implementation details to `RooFit::Detail`
  roofit/roofitcore/CMakeLists.txt
  roofit/roofitcore/inc/LinkDef.h
  roofit/roofitcore/inc/RooFit/Detail/NormalizationHelpers.h
  roofit/roofitcore/inc/RooFit/Detail/RooNLLVarNew.h
  roofit/roofitcore/inc/RooFit/Detail/RooNormalizedPdf.h
  roofit/roofitcore/inc/RooProdPdf.h
  roofit/roofitcore/src/BatchModeDataHelpers.cxx
  roofit/roofitcore/src/FitHelpers.cxx
  roofit/roofitcore/src/RooAbsAnaConvPdf.cxx
  roofit/roofitcore/src/RooAbsCachedPdf.cxx
  roofit/roofitcore/src/RooAbsPdf.cxx
  roofit/roofitcore/src/RooAddition.cxx
  roofit/roofitcore/src/RooNLLVarNew.cxx
  roofit/roofitcore/src/RooNormalizedPdf.cxx
  roofit/roofitcore/src/RooProdPdf.cxx
  roofit/roofitcore/src/RooRealSumPdf.cxx
Labels: pr:backport, in:RooFit/RooStats

#18058 [ci][6.26] Remove Ubuntu 20 from the battery of platforms
  .github/workflows/root-ci.yml
Labels: in:CI

#18059 [ci][6.28] Remove Ubuntu 20 from the battery of platforms
  .github/workflows/root-ci.yml
Labels: in:CI

#18060 [ci][6.30] Remove Ubuntu 20 from the battery of platforms
  .github/workflows/root-ci.yml
Labels: in:CI

#18061 [ci][6.32] Remove Ubuntu 20 from the battery of platforms
  .github/workflows/root-ci.yml
Labels: in:CI

#18042 [CMake] Raise minimum CMake version for Cling to 3.10
  interpreter/cling/CMakeLists.txt
  interpreter/cling/tools/demo/CMakeLists.txt
Labels: in:Build System

#18068 [test] Fetch the geometries from EOS and not from the website
  test/stressGeometry.cxx
Labels: in:Testing

#18076 [test][BP 6.30] Fetch the geometries from EOS and not from the website
  test/stressGeometry.cxx
Labels: pr:backport, in:Testing

#18074 [CMake] Don't force builtin libpng/gif/tiff/jpeg on macOS
  cmake/modules/SearchInstalledSoftware.cmake
  graf2d/asimage/CMakeLists.txt
Labels: in:Build System, clean build

#18065 [TMVA] Only consider GSL BLAS for `tmva-cpu`
  .github/workflows/root-ci-config/buildconfig/alma9-clang.txt
  .github/workflows/root-ci-config/buildconfig/alma9.txt
  .github/workflows/root-ci-config/buildconfig/fedora42.txt
  .github/workflows/root-ci-config/buildconfig/mac14.txt
  .github/workflows/root-ci-config/buildconfig/mac15.txt
  .github/workflows/root-ci-config/buildconfig/ubuntu2410.txt
  .github/workflows/root-ci-config/buildconfig/ubuntu2504.txt
  cmake/modules/RootBuildOptions.cmake
  cmake/modules/SearchInstalledSoftware.cmake
  tmva/sofie/test/CMakeLists.txt
  tmva/tmva/CMakeLists.txt
  tmva/tmva/src/DNN/Architectures/Cpu/Blas.h
Labels: in:TMVA, clean build

#17767 Simplify TClingCallFunc code based on InterOp's JitCall
  core/metacling/src/TClingCallFunc.cxx
Labels: in:Core Libraries

#18086 [v634][TMVA] Only consider GSL BLAS for `tmva-cpu`
  .github/workflows/root-ci-config/buildconfig/alma9-clang.txt
  .github/workflows/root-ci-config/buildconfig/mac14.txt
  .github/workflows/root-ci-config/buildconfig/mac15.txt
  .github/workflows/root-ci-config/buildconfig/ubuntu2410.txt
  cmake/modules/RootBuildOptions.cmake
  cmake/modules/SearchInstalledSoftware.cmake
  tmva/sofie/test/CMakeLists.txt
  tmva/tmva/CMakeLists.txt
  tmva/tmva/src/DNN/Architectures/Cpu/Blas.h
Labels: pr:backport, in:Build System, clean build

#17994 Fix spurrious auto parsing when looking up a TClass
  core/meta/src/TClass.cxx
Labels: in:Core Libraries

#18100 [v634][hist] fix bug in SmoothArray
  hist/hist/src/TH1.cxx
Labels: pr:backport

#18102 [BP 632] Fix spurrious auto parsing when looking up a TClass
  core/meta/src/TClass.cxx
Labels: pr:backport

#18101 [BP 634] Fix spurrious auto parsing when looking up a TClass
  core/meta/src/TClass.cxx
Labels: pr:backport

#18105 [skip-ci][ci] Remove Fedora40 builds
  .github/workflows/root-ci-config/buildconfig/fedora40.txt
  .github/workflows/root-ci.yml
Labels: in:CI

#18104 Fix macro locations in demos.C
  tutorials/demos.C
Labels: in:Tutorials

#18136 [ntuple] Fix unnecessary join table builds
  tree/ntuple/v7/src/RNTupleProcessor.cxx
Labels: bug, in:RNTuple

#18134 [RF] prevent crash in analyticalIntegralWN
  roofit/roofitcore/inc/RooAICRegistry.h
  roofit/roofitcore/src/RooAICRegistry.cxx
  roofit/roofitcore/src/RooAbsCachedPdf.cxx
Labels: bug, in:RooFit/RooStats

#18131 [metacling] Use GetSizeOfType from CppInterOp
  core/metacling/src/TClingDataMemberInfo.cxx
  core/metacling/src/TClingTypeInfo.cxx
Labels: in:Core Libraries

#18143 [skip-ci][tutorial] Math docs
  hist/hist/src/TFormula.cxx
  math/doc/index.md
  math/mathcore/inc/Math/Minimizer.h
  math/minuit2/doc/Minuit2.md
  tutorials/math/ChebyshevPol.C
  tutorials/math/GammaFun.C
  tutorials/math/Legendre.C
  tutorials/math/LegendreAssoc.C
  tutorials/math/NumericalMinimization.C
  tutorials/math/chi2test.C
  tutorials/math/exampleFunction.py
  tutorials/math/exampleFunctor.C
  tutorials/math/exampleMultiRoot.C
  tutorials/math/exampleTKDE.C
  tutorials/math/goftest.C
  tutorials/math/hlquantiles.C
  tutorials/math/index.md
  tutorials/math/kdTreeBinning.C
  tutorials/math/limit.C
  tutorials/math/mathcoreGenVector.C
  tutorials/math/mathcoreSpecFunc.C
  tutorials/math/mathcoreVectorCollection.C
  tutorials/math/mathcoreVectorFloatIO.C
  tutorials/math/mathcoreVectorIO.C
  tutorials/math/mathmoreIntegration.C
  tutorials/math/mathmoreIntegrationMultidim.C
  tutorials/math/multidimSampling.C
  tutorials/math/permute.C
  tutorials/math/principal.C
  tutorials/math/principal.py
  tutorials/math/qa2.C
  tutorials/math/quantiles.C
  tutorials/math/quasirandom.C
  tutorials/math/testrandom.C
Labels: in:Tutorials

#18115 [skip-ci][ntuple] update REntry's documentation
  tree/ntuple/v7/inc/ROOT/REntry.hxx
Labels: in:Documentation, in:RNTuple

#18157 [skip-ci][tutorials] Add doxygen macro addtogroup
  tutorials/math/index.md
Labels: in:Tutorials

#18114 [skip-ci][ntuple] Update RNTupleView documentation
  tree/ntuple/v7/inc/ROOT/RNTupleView.hxx
Labels: in:Documentation, in:RNTuple

#18152 [tutorials] Rename `ntuple` to `reader` and `writer`
  tutorials/io/ntuple/ntpl001_staff.C
  tutorials/io/ntuple/ntpl002_vector.C
  tutorials/io/ntuple/ntpl005_introspection.C
  tutorials/io/ntuple/ntpl007_mtFill.C
  tutorials/io/ntuple/ntpl011_global_temperatures.C
  tutorials/io/ntuple/ntpl015_processor_join.C
Labels: in:RNTuple, in:Tutorials

#18108 [skip-ci][ntuple] update RNTupleReader's documentation
  tree/ntuple/v7/inc/ROOT/RNTupleReader.hxx
Labels: in:Documentation, in:RNTuple

#18113 [ntuple] Revise documentation in RNTupleDescriptor.hxx
  tree/ntuple/v7/inc/ROOT/RNTupleDescriptor.hxx
Labels: in:Documentation, in:RNTuple

#18163 [CPyCppyy] Preserve Python errors when executing C++ function
  bindings/pyroot/cppyy/CPyCppyy/src/CPPMethod.cxx
Labels: in:Python Interface

#17986 [ntuple] Ensure type name given by RField<T> is renormalized
  tree/ntuple/v7/inc/ROOT/RField.hxx
  tree/ntuple/v7/inc/ROOT/RField/RFieldProxiedCollection.hxx
  tree/ntuple/v7/inc/ROOT/RFieldUtils.hxx
  tree/ntuple/v7/src/RFieldUtils.cxx
  tree/ntuple/v7/test/CustomStructLinkDef.h
  tree/ntuple/v7/test/ntuple_type_name.cxx
Labels: in:RNTuple

#18175 [ntuple] Move REntry out of Experimental
  bindings/pyroot/pythonizations/python/ROOT/_pythonization/_rntuple.py
  tree/dataframe/inc/ROOT/RDF/ActionHelpers.hxx
  tree/ntuple/v7/inc/ROOT/REntry.hxx
  tree/ntuple/v7/inc/ROOT/RField.hxx
  tree/ntuple/v7/inc/ROOT/RNTupleFillContext.hxx
  tree/ntuple/v7/inc/ROOT/RNTupleModel.hxx
  tree/ntuple/v7/inc/ROOT/RNTupleProcessor.hxx
  tree/ntuple/v7/inc/ROOT/RNTupleReader.hxx
  tree/ntuple/v7/inc/ROOT/RNTupleWriter.hxx
  tree/ntuple/v7/src/RNTupleModel.cxx
  tree/ntuple/v7/src/RNTupleProcessor.cxx
  tree/ntuple/v7/src/RNTupleReader.cxx
  tree/ntuple/v7/test/ntuple_basics.cxx
  tree/ntupleutil/v7/inc/ROOT/RNTupleImporter.hxx
Labels: in:RNTuple

#18177 [skip-ci][RF] fix broken URL in doc index
  roofit/doc/index.md
Labels: in:Documentation, in:RooFit/RooStats

#18171 [ci] Format only changed lines with ruff
  .github/workflows/code_analysis.yml
Labels: improvement, in:CI

#18179 [CPyCppyy] Use macros from the C Python API for better compatibility
  bindings/pyroot/cppyy/CPyCppyy/src/API.cxx
  bindings/pyroot/cppyy/CPyCppyy/src/CPPOverload.h
  bindings/pyroot/cppyy/CPyCppyy/src/CPyCppyyModule.cxx
  bindings/pyroot/cppyy/CPyCppyy/src/Converters.cxx
  bindings/pyroot/cppyy/CPyCppyy/src/MemoryRegulator.cxx
  bindings/pyroot/cppyy/CPyCppyy/src/Pythonize.cxx
Labels: in:Python Interface

#18069 [ntuple] Use newer `boost_combine` implementation in `RNTupleJoinTable`
  tree/ntuple/v7/inc/ROOT/RNTupleJoinTable.hxx
Labels: in:RNTuple

#18174 [RF] Avoid a double-loop over computation graph in RooRealIntegral ctor
  roofit/roofitcore/src/RooRealIntegral.cxx
Labels: improvement, in:RooFit/RooStats

#18150 [skip-ci][tutorials] Organise RNTuple tutorials section
  tutorials/io/ntuple/index.md
Labels: in:Documentation, in:RNTuple, in:Tutorials

#18180 [ntuple] Move RNTupleView out of Experimental
  gui/browsable/src/RFieldProvider.hxx
  tree/ntuple/v7/inc/ROOT/RField.hxx
  tree/ntuple/v7/inc/ROOT/RNTupleReader.hxx
  tree/ntuple/v7/inc/ROOT/RNTupleView.hxx
  tree/ntuple/v7/src/RNTupleView.cxx
  tree/ntuple/v7/test/ntuple_test.hxx
  tree/ntuple/v7/test/ntuple_view.cxx
Labels: in:RNTuple

#18192 [Python] Fix RDF Pythonization tests with `builtin_llvm=OFF`
  bindings/pyroot/pythonizations/test/rdf_define_pyz.py
  bindings/pyroot/pythonizations/test/rdf_filter_pyz.py
Labels: in:Python Interface
