Repository root-project/root, pull requests merged in 2025-09, with the labels that each got.

#19779 Revert "[CMake] Never force `RUN_SERIAL` in roottest when using Ninja"
  cmake/modules/RootMacros.cmake
Labels: priority:critical, in:Build System

#19771 [RF] proper error handling and return value when file-write
  roofit/roofitcore/src/RooWorkspace.cxx
Labels: in:RooFit/RooStats

#19785 [RF][Docs] Remove a \see in the RooDataHist/Set documentation.
  roofit/roofitcore/src/RooDataHist.cxx
  roofit/roofitcore/src/RooDataSet.cxx
Labels: in:Documentation, skip ci

#19788 [6.36] Backport of #19749
  cmake/scripts/std_modulemap_darwin_fix.py
Labels: pr:backport

#19793 [skip-ci][hist] Improve Doxygen documentation
  hist/histv7/inc/ROOT/RAxes.hxx
  hist/histv7/inc/ROOT/RBinIndex.hxx
  hist/histv7/inc/ROOT/RBinIndexRange.hxx
  hist/histv7/inc/ROOT/RLinearizedIndex.hxx
  hist/histv7/inc/ROOT/RRegularAxis.hxx
  hist/histv7/inc/ROOT/RVariableBinAxis.hxx
Labels: in:Documentation, in:Hist

#19743 [tmva][sofie] Softmax contiguous memory fast path
  tmva/sofie/inc/TMVA/ROperator_Softmax.hxx
Labels: in:TMVA

#19821 [RF] avoid WS name collision between derivatives of different order
  roofit/roofitcore/src/RooAbsReal.cxx
Labels: in:RooFit/RooStats

#19752 [6.36] Backport of #19318
  tree/tree/src/TBranchElement.cxx
Labels: pr:backport, clean build

#19731 [gui] Add RTreeMap
  gui/treemap/CMakeLists.txt
  gui/treemap/inc/LinkDef.h
  gui/treemap/inc/ROOT/RTreeMapBase.hxx
  gui/treemap/inc/ROOT/RTreeMapPainter.hxx
  gui/treemap/src/RTreeMapBase.cxx
  gui/treemap/src/RTreeMapImporter.cxx
  gui/treemap/src/RTreeMapPainter.cxx
Labels: in:GUI

#19824 Fix the (TH1*, THStack*) ctor
  graf2d/gpad/src/TRatioPlot.cxx
Labels: affects:master, in:Graphics

#19816 [RF] Don't recreate hash tables in `RooLinkedList::Add()`
  roofit/roofitcore/src/RooLinkedList.cxx
Labels: in:RooFit/RooStats

#19839 [632][tree] Allow skipping longdoubles when building tree index
  tree/tree/inc/TTree.h
  tree/tree/inc/TVirtualTreePlayer.h
  tree/tree/src/TTree.cxx
  tree/treeplayer/inc/TChainIndex.h
  tree/treeplayer/inc/TTreeIndex.h
  tree/treeplayer/inc/TTreePlayer.h
  tree/treeplayer/src/TChainIndex.cxx
  tree/treeplayer/src/TTreeIndex.cxx
  tree/treeplayer/src/TTreePlayer.cxx
Labels: pr:backport, experiment

#19861 [ntuplebrowse] Add treemap visualization in classic ntuplebrowser
  config/mimes.unix.in
  config/mimes.win32.in
  tree/ntuplebrowse/CMakeLists.txt
  tree/ntuplebrowse/src/RNTupleClassicBrowse.cxx
  tree/ntuplebrowse/test/ntuple_browse.cxx
Labels: in:GUI, in:RNTuple

#19876 [ntuple] Fix bulk read of artificial fields
  tree/ntuple/src/RFieldBase.cxx
  tree/ntuple/test/ntuple_evolution_shape.cxx
Labels: in:RNTuple

#19844 [ntuple] fix automatic schema evolution of variant
  tree/ntuple/inc/ROOT/RField/RFieldSTLMisc.hxx
  tree/ntuple/src/RFieldMeta.cxx
  tree/ntuple/test/ntuple_evolution_type.cxx
Labels: in:RNTuple

#19885 [docs] Merge documentation of MathMore and MathCore.
  math/mathcore/doc/index.md
  math/mathcore/inc/Math/Integrator.h
  math/mathcore/inc/Math/Math.h
  math/mathcore/inc/Math/PdfFuncMathCore.h
  math/mathcore/inc/Math/SpecFuncMathCore.h
  math/mathmore/doc/index.md
  math/mathmore/inc/Math/QuasiRandom.h
Labels: skip ci

#19780 [CMake] Don't wrap command in `ROOTTEST_COMPILE_MACRO` in CMake target
  cmake/modules/RootMacros.cmake
  roottest/scripts/build.C
Labels: in:Build System, clean build

#19880 [roottest] add missing dependency to io-references-lostRef test
  roottest/root/io/references/CMakeLists.txt
Labels: affects:master, in:Testing

#19789 [CMake] Fixup copy-paste error in previous commit
  cmake/modules/RootMacros.cmake
Labels: in:Build System, clean build

#19891 [RDF][Docs] Explain that RDF uses Kahan sums for the mean.
  tree/dataframe/inc/ROOT/RDF/RInterface.hxx
Labels: skip ci

#19837 [RF] Add and refactor printContents() for RooAbsData
  roofit/roofitcore/inc/RooAbsData.h
  roofit/roofitcore/inc/RooDataHist.h
  roofit/roofitcore/inc/RooDataSet.h
  roofit/roofitcore/src/RooDataHist.cxx
  roofit/roofitcore/src/RooDataSet.cxx
Labels: in:RooFit/RooStats

#19884 [v6.36][ntuple] fix bulk read of artificial fields
  tree/ntuple/src/RFieldBase.cxx
  tree/ntuple/test/ntuple_evolution.cxx
Labels: pr:backport, in:RNTuple

#19901 [webgui] update stressGraphics_web.ref
  test/stressGraphics_web.ref
Labels: affects:master, in:WebGui

#19903 [webgui] update stressGraphics_web.ref [6.36]
  test/stressGraphics_web.ref
Labels: pr:backport, in:WebGui, affects:6.36

#19905 [CMake] Make dictionary generation command depend on C++ standard
  cmake/modules/RootMacros.cmake
Labels: bug, in:Build System

#19381 [cmake] disable Gui if minimal=on
  CMakeLists.txt
  main/CMakeLists.txt
  test/CMakeLists.txt
  tmva/CMakeLists.txt
  tree/CMakeLists.txt
  tutorials/CMakeLists.txt
Labels: clean build

#19924 [ntuple] fix bool-backed enums
  tree/ntuple/src/RFieldMeta.cxx
  tree/ntuple/test/CustomStruct.hxx
  tree/ntuple/test/CustomStructLinkDef.h
  tree/ntuple/test/ntuple_types.cxx
Labels: in:RNTuple

#19665 [CMake] Don't cache `CPPINTEROP_INCLUDE_DIRS` and `CLING_INCLUDE_DIRS`
  CMakeLists.txt
  core/metacling/src/CMakeLists.txt
  interpreter/CMakeLists.txt
Labels: in:Build System, clean build

#19928 [v636][ntuple] Backport fixes to backing type handling of enum and collection proxy
  tree/ntuple/src/RFieldMeta.cxx
  tree/ntuple/test/CustomStruct.hxx
  tree/ntuple/test/CustomStructLinkDef.h
  tree/ntuple/test/ntuple_types.cxx
Labels: pr:backport, in:RNTuple

#19929 [ntuple] remove GetCollectionInfo() from collection fields
  tree/ntuple/inc/ROOT/RField/RFieldProxiedCollection.hxx
  tree/ntuple/inc/ROOT/RField/RFieldSequenceContainer.hxx
  tree/ntuple/src/RFieldSequenceContainer.cxx
  tree/ntuple/test/ntuple_emulated.cxx
Labels: in:RNTuple

#19953 [core] Fix libCling linking with `-Bsymbolic`
  core/metacling/src/CMakeLists.txt
  interpreter/CMakeLists.txt
Labels: in:Build System

#19804 [CMake] Simplify writing of modulemap.
  CMakeLists.txt
  cmake/modules/RootMacros.cmake
  cmake/unix/module.modulemap
Labels: clean build

#19967 [jupyter] optimize jsroot loading
  bindings/jupyroot/python/JupyROOT/helpers/utils.py
Labels: affects:master, in:WebGui

#19980 [ntuple] Test type normalization with collection proxy
  tree/ntuple/test/SimpleCollectionProxy.hxx
  tree/ntuple/test/ntuple_type_name.cxx
Labels: in:RNTuple

#19998 [ntuple] test automatic schema evolution between enums
  tree/ntuple/test/CustomStruct.hxx
  tree/ntuple/test/CustomStructLinkDef.h
  tree/ntuple/test/ntuple_evolution_type.cxx
Labels: in:RNTuple
