Repository root-project/root, pull requests merged in 2025-06, with the labels that each got.

#18920 [gui] Remove unused code
  gui/gui/src/TRootContextMenu.cxx
Labels: in:Graphics

#18938 [metacling] Add missing lock to TCling::Evaluate.
  core/metacling/src/TCling.cxx
Labels: affects:6.32, affects:6.34, affects:6.36

#18942 [634][metacling] Add missing lock to TCling::Evaluate.
  core/metacling/src/TCling.cxx
Labels: pr:backport

#18919 [6.36][io] TFileMerger: fail by default on invalid keys
  README/ReleaseNotes/v636/index.md
  io/io/inc/TFileMerger.h
  io/io/src/TFileMerger.cxx
  main/src/hadd.cxx
Labels: clean build

#18943 [632][metacling] Add missing lock to TCling::Evaluate.
  core/metacling/src/TCling.cxx
Labels: pr:backport

#18945 [634][meta] Remove redundant check
  core/clingutils/src/TClingUtils.cxx
Labels: pr:backport

#18946 [632][meta] Remove redundant check
  core/clingutils/src/TClingUtils.cxx
Labels: pr:backport

#18944 [636][meta] Remove redundant check
  core/clingutils/src/TClingUtils.cxx
Labels: pr:backport

#18959 [ntuple] Add `RNTupleProcessor::PrintStructure`
  tree/ntuple/inc/ROOT/RNTupleProcessor.hxx
  tree/ntuple/src/RNTupleProcessor.cxx
  tree/ntuple/test/ntuple_processor.cxx
  tree/ntuple/test/ntuple_processor_chain.cxx
  tree/ntuple/test/ntuple_processor_join.cxx
Labels: in:RNTuple

#18958 [io] Fix ZIP64 extra entry field parsing in TZIPFile
  io/io/src/TZIPFile.cxx
Labels: in:I/O

#18968 [636][meta] Correctly treat data member types containing functions
  core/foundation/src/TClassEdit.cxx
  core/foundation/test/testClassEdit.cxx
Labels: pr:backport

#18997 [Python] Use relative install path for pythonization library
  bindings/pyroot/pythonizations/CMakeLists.txt
Labels: in:Build System, clean build

#19003 [v6-36] Fix for CMAKE_SOURCE_DIR with special characters . and +
  CMakeLists.txt
Labels: pr:backport

#18885 [ntuple] Merger: properly handle untyped records
  tree/ntuple/inc/ROOT/RNTupleUtil.hxx
  tree/ntuple/src/RNTupleMerger.cxx
  tree/ntuple/test/ntuple_merger.cxx
Labels: in:RNTuple

#19016 [roottest] Use `PYTHON_DEPS` argument also in Roottest macro
  roottest/cmake/modules/RoottestMacros.cmake
  roottest/python/JupyROOT/CMakeLists.txt
Labels: in:Testing

#19015 [Python] Check for identity and not equality where appropriate
  bindings/pyroot/pythonizations/test/tdirectory_attrsyntax.py
  bindings/pyroot/pythonizations/test/tdirectoryfile_attrsyntax_get.py
  bindings/pyroot/pythonizations/test/tfile_attrsyntax_get_writeobject_open.py
  roottest/python/memory/PyROOT_memorytests.py
Labels: bug, in:Python Interface, in:Testing

#19019 [roottest] remove files from source dir after macro compilation [win]
  roottest/cmake/modules/RoottestMacros.cmake
Labels: affects:master, in:Build System, in:Testing

#19024 [v636][Minuit2] Correctly copy ROOT's `std::span` headers for standalone build
  math/minuit2/StandAlone.cmake
Labels: pr:backport, in:RooFit/RooStats

#19028 [roottest] Disable tests that require NumPy if NumPy is not available
  roottest/python/basic/CMakeLists.txt
  roottest/python/basic/PyROOT_datatypetest.py
  roottest/python/basic/PyROOT_datatypetest_numpy.py
Labels: in:Testing

#19047 [tutorials] check gPad in gl tutorials
  tutorials/visualisation/gl/glViewerExercise.C
  tutorials/visualisation/gl/viewer3DLocal.C
  tutorials/visualisation/gl/viewer3DMaster.C
Labels: affects:master, in:Tutorials

#19055 [reve] fix windows compiler warning
  graf3d/eve7/src/REveGeoTopNode.cxx
Labels: affects:master, in:WebGui

#19063 [v6-36][cmake][win][skip-ci] fix duplicate symbol error
  core/metacling/src/CMakeLists.txt
Labels: pr:backport

#19007 [ntuple] Add RMiniFile::GetNTupleProperAtOffset
  tree/ntuple/inc/ROOT/RMiniFile.hxx
  tree/ntuple/src/RMiniFile.cxx
Labels: in:RNTuple

#19059 [core] Add #include <iterator> to StringUtils.hxx
  core/foundation/inc/ROOT/StringUtils.hxx
Labels: in:Core Libraries

#19053 Globally enable sized deallocation functions
  cmake/modules/SetUpFreeBSD.cmake
  cmake/modules/SetUpLinux.cmake
  cmake/modules/SetUpMacOS.cmake
  config/root-config.in
  core/base/inc/TObject.h
  core/base/inc/TStorage.h
  core/base/src/TObject.cxx
  core/base/src/TStorage.cxx
  core/foundation/inc/ROOT/RConfig.hxx
  core/metacling/src/TCling.cxx
  core/newdelete/src/NewDelete.cxx
  interpreter/cling/lib/Interpreter/CIFactory.cpp
  roottest/root/meta/CMakeLists.txt
  roottest/root/meta/MemberComments_macos.ref
Labels: in:Core Libraries, clean build

#19070 [Math] Move gradient methods to IBaseFunction classes
  math/mathcore/inc/Fit/Chi2FCN.h
  math/mathcore/inc/Fit/LogLikelihoodFCN.h
  math/mathcore/inc/Fit/PoissonLikelihoodFCN.h
  math/mathcore/inc/Math/IFunction.h
  math/mathmore/src/GSLNLSMinimizer.cxx
  roofit/roofit/test/GaussFunction.h
  roottest/root/meta/execTypedefList.C
  roottest/root/meta/typelist.v5.txt
  roottest/root/meta/typelist_win32.v5.txt
Labels: in:Math Libraries

#19084 [df] Move RNTuple-related tests out of ROOT 7
  tree/dataframe/test/CMakeLists.txt
Labels: in:RDataFrame, in:RNTuple

#19094 [v6-34][cmake][win] Fix datamodelevolution linker error
  cmake/scripts/compiledata.win32.in
  core/metacling/src/CMakeLists.txt
  main/CMakeLists.txt
Labels: pr:backport

#19095 [6.36] Allow catching entry beyond end from TTreeReaderValueBase
  tree/treeplayer/inc/TTreeReaderValue.h
  tree/treeplayer/src/TTreeReaderValue.cxx
  tree/treeplayer/test/basic.cxx
Labels: pr:backport

#19098 [df] Remove dependency from RNTupleUtil in test
  tree/dataframe/test/CMakeLists.txt
  tree/dataframe/test/dataframe_snapshot_ntuple.cxx
Labels: in:RDataFrame, in:RNTuple

#19108 [CMake] Add proper check for `libstdc++fs`
  cmake/modules/SearchInstalledSoftware.cmake
  main/CMakeLists.txt
  tree/ntupleutil/v7/test/CMakeLists.txt
  tree/treeviewer/CMakeLists.txt
Labels: in:Build System

#19088 [roottest] move reflex test from `io/evolution` to subdir
  roottest/root/io/evolution/CMakeLists.txt
  roottest/root/io/evolution/equivalent/CMakeLists.txt
  roottest/root/io/evolution/equivalent/execioReadRuleEquivalentCode.C
  roottest/root/io/evolution/equivalent/execioReadRuleEquivalentCode.ref
  roottest/root/io/evolution/equivalent/ioReadRuleEquivalentCode.h
  roottest/root/io/evolution/equivalent/ioReadRuleEquivalentCode.root
  roottest/root/io/evolution/equivalent/ioReadRuleEquivalentCode_selection.xml
Labels: affects:master, in:Build System, in:Testing

#19115 [Python][UHI] Fix entry count after slicing operations
  bindings/pyroot/pythonizations/test/uhi_indexing.py
  hist/hist/inc/TH1.h
Labels: improvement, in:Python Interface, clean build

#19119 [cppyy] disable C++11 tests on mac-beta
  bindings/pyroot/cppyy/cppyy/test/CMakeLists.txt
Labels: clean build

#19138 [webcanvas] set default attributes for created TCanvas [6.36]
  gui/webgui6/src/TWebCanvas.cxx
Labels: pr:backport, in:WebGui, affects:6.36

#19141 [cling] Handle unloading unnamed `VarDecl`s in catch statements
  interpreter/cling/lib/Interpreter/DeclUnloader.cpp
  interpreter/cling/test/CodeUnloading/Exception.C
Labels: in:Cling

#19164 [reve] Correct selection in REveGeoTopNode
  ui5/eve7/lib/GlViewerRCore.js
Labels: affects:master, in:WebGui

#19165 [CMake] Also print version of found Python module
  cmake/modules/RootMacros.cmake
Labels: in:Build System

#19150 Untyped snapshot for RNTuple
  tree/dataframe/inc/ROOT/RDF/ActionHelpers.hxx
  tree/dataframe/inc/ROOT/RDF/InterfaceUtils.hxx
  tree/dataframe/inc/ROOT/RDF/RInterface.hxx
  tree/dataframe/inc/ROOT/RDF/Utils.hxx
  tree/dataframe/inc/ROOT/RNTupleDS.hxx
  tree/dataframe/src/RDFActionHelpers.cxx
  tree/dataframe/src/RNTupleDS.cxx
  tree/dataframe/test/CMakeLists.txt
Labels: in:RDataFrame

#19132 Add auto_ptr schema evolution test
  roottest/root/io/autoptr/CMakeLists.txt
  roottest/root/io/autoptr/TestAutoPtr_v2.hxx
  roottest/root/io/autoptr/TestAutoPtr_v2_LinkDef.h
  roottest/root/io/autoptr/TestAutoPtr_v3.hxx
  roottest/root/io/autoptr/TestAutoPtr_v3_LinkDef.h
  roottest/root/io/autoptr/evolve_autoptr.cxx
  roottest/root/io/autoptr/write_autoptr.cxx
Labels: in:I/O

#19112 [cmake] Simplify CMake for TreeFormulaReferencesGeneration
  roottest/root/treeformula/references/CMakeLists.txt
Labels: pr:squash on merge, clean build

#19193 Use new GetColumnReaders API in RCsvDS
  tree/dataframe/inc/ROOT/RCsvDS.hxx
  tree/dataframe/src/RCsvDS.cxx
  tree/dataframe/test/datasource_csv.cxx
Labels: in:RDataFrame

#19212 [skip-ci][ntuple] Use more common Markdown headings
  tree/ntuple/doc/Architecture.md
  tree/ntuple/doc/README.md
  tree/ntuple/doc/tuning.md
Labels: in:RNTuple

#19198 [ntuple] Merger: fix bugs in GenerateZeroPagesForColumns
  tree/ntuple/src/RNTupleMerger.cxx
  tree/ntuple/test/ntuple_merger.cxx
Labels: in:RNTuple

#19203 [Hist] Generalize TF1 constructor using C++17
  hist/hist/inc/TF1.h
Labels: bug, in:Hist

#19211 [CMake] Make it possible to not create `thisroot` setup scripts
  cmake/modules/RootBuildOptions.cmake
  cmake/modules/RootConfiguration.cmake
Labels: in:Build System

#19226 [CMake] Fix typo in Windows installation step
  cmake/modules/RootConfiguration.cmake
Labels: pr:emergency🚨
